### ISSUE TITLE
changing gfx plugin causes crash

### ISSUE THREAD

**Issue by topkex** [project64/project64#1005]
when i change from glide64 to any other plugin it crashes/closes.

change to glide64 > click ok > then choose another plugin > click ok (apply does not cause crash)

i sometimes get a "buffer overrun dected!"

**Comment by vgturtle127** [comment]
What version of Project64 are you on and also what operating system?

**Comment by topkex** [comment]
2.2.0.3 and emucr-20160213, Windows 7 and Windows 10 same error

**Comment by topkex** [comment]
#152 also describes this error, maybe a memory leak

**Comment by vgturtle127** [comment]
@topkex That description doesn't seem like a memory leak to me.

Have you tried uninstalling the 2.2 build and using a newer EmuCR build only?

**Comment by oddMLan** [comment]
**Could reproduce**
The closes itself for me with no error message whatsoever.
Note: only happens when you haven't loaded up any ROM.

Just open Project64, press Ctrl+T to open the settings and change the plugins as @topkex instructed.
Doing this with a ROM loaded works ok, even if you stop emulation by pressing F12.

**Comment by Frank-74** [comment]
@topkex 
I fixed this.  https://github.com/project64/project64/pull/1148
https://github.com/project64/project64/issues/1147
