### ISSUE TITLE
[Feature request] Add Vulkan to Project 64

### ISSUE THREAD

**Issue by twarnercool2** [project64/project64#1009]
https://www.khronos.org/vulkan/

Since Vulkcan is out, I was wondering if you guys can add support to Project 64?

**Comment by oddMLan** [comment]
https://github.com/SaschaWillems/Vulkan/blob/master/texture/texture.cpp

**Comment by vgturtle127** [comment]
@twarnercool2 This would be for plugins, not the emulator itself.

Same with DirectX 12, and all other graphics API's, really.

So we can't add support to the emulator directly. I'm not sure any plugins would be ripe for a new graphics API...

Another issue is that the plugins have to be re-written in order to handle the new API. It is supposed to be easy, but it never is. So basically, you have to create a whole new plugin. At that point, people tend to lose interest or just want to use what they already have.

Not saying it won't happen, but I doubt Nintendo 64 emulators besides CEN64 and Soft64 will get support for Vulkan. Mupen64Plus might have it's graphics plugins updated to Vulkan, but I only suspect that because it heavily uses OpenGL already, and also Vulkan is supposed to run on nearly everything.

Anyway, (https://github.com/gonetz/GLideN64/issues/871) has already been opened, but Gonetz hasn't responded yet. I doubt he will want to port everything over, but maybe he already has something in the works.

The Mupen64Plus team is very busy, but I suppose you could ask them too.

**Comment by SigmaVirus** [comment]
I doubt we'll see any plugins built using DX12 or Vulkan for the N64 emulation scene anytime soon actually.
And if someone is making plugins using these API's then they will be written from scratch.

I also doubt GLideN64 will be using Vulkan anytime soon as it's to young and haven't ironed out all issues yet.
GLideN64 have to mature and be more stable first before bringing in Vulkan to the picture.

As for adding Vulkan to Project64, it doesn't work like that I'm afraid. Project64 is a plugin based emulator and needs a GFX plugin to work.

**Comment by vgturtle127** [comment]
@SigmaVirus Although, a plugin written from scratch with Vulkan and DirectX 12 does sound really nice. :wink: 

I think GLideN64 definitely needs time to mature before a new API is introduced, and I think that even newer or older versions of OpenGL may be issues with GLideN64, since there is a lot of Android and Linux work going into it as well. Who knows!

**Comment by SigmaVirus** [comment]
Well the thing is I'm 30 years old today, not getting younger I'm afraid and I was around 15 when I started playing/toying around with N64 emulation and back then it was pretty much a complete mess and the PC hardware that was being used sucked.

To me, things haven't really started to happen/move until last year when Project64 became open sourced and GLideN64 were released and open sourced and as of today I really like what I see.

Given how fast the time goes and the years pass by, I'll probably be 35+ something when N64 emulation is really really good (I hope)
It's good now, but it can be even better.

My point is, if someone were to made a plugin with DX12 or Vulkan being used from scratch today I think I'd lose interest altogether for the N64 emulation scene when you look at it's background and what it's been through all these years.

At this point I'll just use what I have and be glad with it, because I really don't know how long my interest for games and emulation is gonna last.
I used my first emulator (Nesticle) back in -99 and followed quite a few projects through the years.

I think as of today, many of the consoles that I'm emulating is running great and it's been a hell of a fun ride.

Maybe I don't lose interest and stick around for years to come or maybe I'll just move on.
Only time will tell.

**Comment by LegendOfDragoon** [comment]
>To me, things haven't really started to happen/move until last year when Project64 became open sourced 

Project64 has been open source for years.

**Comment by vgturtle127** [comment]
@LegendOfDragoon Has it really been that long already? That's crazy! :stuck_out_tongue_winking_eye:

**Comment by SigmaVirus** [comment]
I thought it was closed source until he released 2.2 was released last year in April, because Zilmar said this in the description:

_"Celebrating 10 year anniversary of 1.6, releasing 2.2.

Download:
http://www.pj64-emu.com/downloads/project64/binaries/

Source, issue tracker at:
https://github.com/project64

lots of bug fixes, make nrage the default controller plugin now, etc"_

But it being open sourced for years, yeah that's news for me.

**Comment by vgturtle127** [comment]
@SigmaVirus Well, before that there were releases of the 1.4 version, and Zilmar's RSP plugin.

**Comment by SigmaVirus** [comment]
Oh yeah, I'm starting to remember something like that when you mention the 1.4 version.
But could you really go so far to say Project64 in general was open sourced already back then?

I mean where were the source for 1.5, 1.6, 1.7, 2.0 and 2.1 before this Github repository existed?
I sure couldn't find it and as far as I know this repository only goes back to 1.7 something?

Please correct me if I'm wrong guys because nothing of this makes sense to me.

Until 2.2, Project64 were as good as closed sourced to me and the only way to get alpha/beta stuff was to be a project supporter, meaning donating 20 or so dollars.

**Comment by LegendOfDragoon** [comment]
Project64 2.0 (along with source) was released in april 2013. 1.6's source was leaked sometime in 2012, iirc.

**Comment by vgturtle127** [comment]
@LegendOfDragoon 1.6 source was leaked? I don't remember ever hearing about that. Huh. Interesting.

**Comment by retrobenny** [comment]
Necro-bumping this issue to mention that Dolphin Emulator can run faster on Vulkan than it can on OpenGL in some cases.
Part of it being how much better the coding has been said to be in comparison to other back-ends.

Maybe a Vulkan setup for PJ64 can help me get enough performance to use "pure" Interpreter on more games to make it easier to hunt for codes in the ASM/Execution Code sections.
My best performance seemed to be with the Jabo 1.6.1 plugin with "Legacy Pixel Pipeline" on and "Only by Frame" buffer clears,GoldenEye 007 hits 57VI/s-60VI/s facing the wall at the dam while lagging at 30VI/s-44VI/s for real when facing the direction of progressing.

All PJ64 would need for these kind of address changes to function immediately on Recompiler is a fix like Mupen's "flush dirty cache pages" method that works superbly.
I was hoping Zilmar would have  gotten into it and try to get a fix going,but have yet to stumble on any hints of such a fix being added.
Technically a fix because it makes Recompiler as responsive as Pure Interpreter or an actual console,but doesn't heavily impact performance like when using Interpreter.

**Comment by LegendOfDragoon** [comment]
>1.6 source was leaked?

Yes.

>Maybe a Vulkan setup for PJ64 can help me get enough performance to use "pure" Interpreter on more games to make it easier to hunt for codes in the ASM/Execution Code sections.

Sounds futile. Nobody even makes plugins that can compete with Rice Video in performance. Anyway, it's better to solve the real problem, which is the recompielr. Just fix that and then you won't have to use interpreter.

**Comment by retrobenny** [comment]
Thanks,it still would help performance on GLideN64 to have heavily optimized Vulkan support for that boost on lower-end PCs that are dragged in the dirt by up-scaling.

**Comment by LegendOfDragoon** [comment]
>Thanks,it still would help performance on GLideN64 to have heavily optimized Vulkan support for that boost on lower-end PCs that are dragged in the dirt by up-scaling.

Sounds like an oxymoron. Can't run Vulkan on low end hardware. Unless you mean Android devices? That's even assuming those devices which are capable of supporting Vulkan are still too weak for N64 emulation (I'm doubtful). Although if I was coding for android, I'd probably prefer Vulkan.

My IGP doesn't support Vulkan yet can run essentially any N64 game full speed. Just use Rice Video if you need extra performance. The choice of API is not the biggest problem with GLideN64.

**Comment by project64** [comment]
if I get angle working nice .. it has a some start to having vulkan as a backend .. if I get it for free great .. other wise opengl es is my target.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
