### ISSUE TITLE
Merging to MESS? They have N64 support. Why not join forces?

### ISSUE THREAD

**Issue by timofonic** [project64/project64#1013]
Hello.

As many of you know...
@mamedev's is the new umbrella project at GitHub and both MAME and MESS codebases got merged. Despite both projects share code and infraestructure. different build flags rerlease the MAME and MESS binaries.

https://github.com/mamedev/mame

They are upgrading many parts and even putting LUA. It seems it will be used for GUI stuff and future addons.

I think there's a need of a emulation metaproject that becomes a strong umbrella, plus quite known and widely ported to as much as possible platforms. This would provide resources, visibility and even financing similar approaches such as GSoC or bounties.

I would love MAME and MESS become one project finally and not need to build them separately, having a GUI for lots of emulators and even adding "State of the Art" advanced ROM management too. That's my personal desire, others could have their arguments to consider it not optimal.

Kind regards.

**Comment by vgturtle127** [comment]
@timofonic Not to disappoint you, but the licenses won't allow that. Unfortunately, the GPL isn't compatible with any other license except a few *rare* cases. Furthermore, the old MAME license has many restrictions that we would not want to impose on Project64.

On top of that, Project64 and MAME/MESS have very different goals in terms of emulation of the Nintendo 64. MAME/MESS is for system documentation and emulating something on MAME/MESS is usually very different than other emulators.

Not only that, but Project64 and MAME/MESS have different architectures and emulation styles. Project64 utilizes high-level emulation and a plugin system while MESS uses low-level emulation and all the components are drivers, I believe (I could be wrong, don't quote me on that).

Project64 also uses many game-specific hacks, and has common emulator features that a MAME/MESS user might not have usually. MAME/MESS also doesn't have a whole lot of TAS/development features that Project64 has.

We have worked a lot on Project64 (and I have invested much of my time in the project, even if it isn't outwardly apparent since I haven't yet posted any of my research and documentation), and I would hate to see such a historic emulator be put to rest. Project64 is important, and the most compatible emulator currently, so for the foreseeable future I will be contributing to it.

We can't merge the projects in any sort of way you are thinking. Our work and documentation may help  the MAME/MESS developers to create a better N64 driver, though. I am hopeful Nintendo 64 emulation will get much better after some much needed elbow-grease.

**Comment by LegendOfDragoon** [comment]
>Project64 also uses many game-specific hacks

Such as?

**Comment by vgturtle127** [comment]
@LegendOfDragoon Well, I consider the RDB mostly game-specific hacks.

**Comment by LegendOfDragoon** [comment]
>Well, I consider the RDB mostly game-specific hacks.

Sounds like you're making a vague assumption...

**Comment by vgturtle127** [comment]
@LegendOfDragoon I guess so, I would assume using game specific values for emulation settings would be considered a game specific hack. That's just how I always viewed it. It's like Dolphin ini files, really.

**Comment by oddMLan** [comment]
Three words: not gonna happen.
/thread

**Comment by JunielKatarn** [comment]
Does sound like a good idea, but I also think it will never happen. I would close this issue.

**Comment by vgturtle127** [comment]
@project64 Could you close this?
