### ISSUE TITLE
Perfect Dark freezes in LLE

### ISSUE THREAD

**Issue by LegendOfDragoon** [project64/project64#1022]
Shortly after booting Perfect Dark in LLE, it gets stuck in an infinite loop.

```
0x1B8    MFC0 S7, DP CMD DMA current
0x1BC    SUB  S4, S3, S7
0x1C0    BGEZ S4, 0x1D4
0x1C4    ADD  S4, S3, S2
0x1C8    SUB  S4, S4, S7
0x1CC    BGEZ S4, 0x1B8
0x1D0    NOP
```

**Comment by vgturtle127** [comment]
@LegendOfDragoon You mean when booting Perfect Dark with LLE graphics mode it does this? And it doesn't matter whether or not you are using CPU interpreter/recompiler or what RSP plugin you are using?

**Comment by LegendOfDragoon** [comment]
Meant to say LLE graphics. Doesn't seem to matter whether interpreter or not.

**Comment by cxd4** [comment]
Working fine here on Linux, with Mupen64. :smile_cat:

**Comment by vgturtle127** [comment]
@LegendOfDragoon OK, just wanted to clarify. :smile: 

So this happens with every graphics plugin, but not plugins in HLE mode? If that is the case, wouldn't it be a plugin-specific bug? Like a bug exclusive to plugins? I'm just confused how this would related to Project64, the only bug I can think of would be if the CPU isn't being emulated properly when LLE mode is active or something. Hm. :confused:

**Comment by LegendOfDragoon** [comment]
>I'm just confused how this would related to Project64, the only bug I can think of would be if the CPU isn't being emulated properly when LLE mode is active or something.

Because any problem with Project64 or any of the bundled plugins are valid bug reports.

>It is almost like the LLE being turned on is the problem, not any plugin issue.

Problem is either RSP or core. I'm not exactly sure which, but my guess would be core.

**Comment by vgturtle127** [comment]
> Because any problem with Project64 or any of the bundled plugins are valid bug reports.

Oh, I know. I wasn't saying this wasn't valid, I was just saying I didn't understand what exactly was causing the issue, mainly since it didn't matter what most of the plugins and settings were (besides the LLE graphics part).

> RSP or core

Yeah, that's what I was thinking. My guess would have been core as well, since the problem seems to rear it's head shortly after boot (which in my experience is usually either the core or a plugin issue). Very rarely is it an issue with the RSP, especially with cxd4's plugin.

RSP could be the issue, but ZIlmar's and cxd4's RSP are pretty accurate plugins, so I rarely have issues. Or at least, they are pretending well enough that I rarely have issues.

**Comment by purplemarshmallow** [comment]
Perfect Dark works for me in LLE without problems
I tested the (E) version

**Comment by LegendOfDragoon** [comment]
Well, it appears that part of the problem is the mfc0 exit code.

>Perfect Dark works for me in LLE without problems
I tested the (E) version

Lol I guess PAL version works differently. Very interesting tbh. I wonder if it's because the timing is different in PAL or if the game code is different. I tried J version and it also froze.

**Comment by vgturtle127** [comment]
@LegendOfDragoon Man, this is a bit weird. It worked fine for me for a few runs, then it stopped working at all. :fearful:

**Comment by purplemarshmallow** [comment]
I noticed I had FAT disabed. With FAT enabled I can't boot the PAL version

**Comment by LegendOfDragoon** [comment]
I find it interesting that Shunyuan's soft graphic plugin does not freeze. Maybe putting a RSP inside of a graphics plugin can lead to finding a solution.

>I noticed I had FAT disabed. With FAT enabled I can't boot the PAL version

That's odd.

**Comment by vgturtle127** [comment]
@LegendOfDragoon Oh, I didn't know RSP emulation was included with Shunyuan's plugin! Interesting, I will have to add that to my notes.

**Comment by LegendOfDragoon** [comment]
>Oh, I didn't know RSP emulation was included with Shunyuan's plugin! Interesting, I will have to add that to my notes.

He put an outdated version of cxd4's RSP inside of this outdated angrylion fork and calls it "HLE". Apparently the reason he made it "HLE" was for multi-threading.

Seems like a hassle, but I just might have to try putting a RSP inside of Angrylion's and debug it.

>@LegendOfDragoon Man, this is a bit weird. It worked fine for me for a few runs, then it stopped working at all. :fearful:

What plugins were you using and did you have Fixed Audio Timing enabled?

**Comment by vgturtle127** [comment]
@LegendOfDragoon An RSP inside the Angrylion plugin? Sounds interesting, I would definitely like to see some tests with that.

Well, I was using GLideN64, Azimer's, and cxd4's RSP. Then I switched to a bunch of different graphics plugins to test, then it quit working.

I forgot to check for FAT, and I don't remember whether it was enabled or not.

I did a re-install of the latest compiled emulator and newer plugin builds and it seemed to iron out the weird crashing at launch issue. I have a feeling it was with the build of GLideN64 I was using, since some other games crashed when I switched to an older build that I had been using.

**Comment by cxd4** [comment]
Of course, the only thing he had to do for multi-threading was modify the Project64 core, which was open-source, as none of the 4 plugin types let you control the threading for each of the other 3.

Instead of simply modifying Project64, he just took one particular plugin type (in this case, graphics) and told it to do all of the work of a second arbitrary plugin type (RSP) and multi-threaded it because YOLO.

**Comment by vgturtle127** [comment]
@cxd4 To be fair, if he had said YOLO, I think everybody would have let him by with a free pass. lol

**Comment by cxd4** [comment]
That was my lawyerism for explaining away what he did.  No, he never said that.

**Comment by vgturtle127** [comment]
@cxd4 No, but he should've, all things considered. :sunglasses:

**Comment by cxd4** [comment]
For the same reason he should have converged the combined source code contents of 1964, Project64 and Mupen64's .c/.cpp files all into one single .c file and attempted to compile it.

**Comment by vgturtle127** [comment]
@cxd4 THE BEST EMULATOR

**Comment by loganmc10** [comment]
In mupen64plus, this freeze was caused by the RSP task starting with SP_STATUS_YIELD set.

It happens because of the "DP freeze hack":

https://github.com/project64/project64/blob/master/Source/Project64-core/N64System/N64Class.cpp#L1985-L1989

That will delay the RSP task until the FREEZE bit is unset:

https://github.com/project64/project64/blob/e0f2af6338c27e2074cc6ce3e62d2777fbe33b84/Source/Project64-core/N64System/Mips/MemoryVirtualMem.cpp#L1795-L1804

But when it runs there, SP_STATUS_YIELD is set in LLE. Clearing SP_STATUS_YIELD before running the RSP task fixes the freeze in mupen64plus, I assume it will be the same here

**Comment by LegendOfDragoon** [comment]
I opted to just clear the DP_FREEZE bit before pre-emptively exiting the task the first time. This works in 1964 and PJ64, but apparently doesn't work in ParaLLEl.

Nice find though @loganmc10 . Maybe that can lead to finding out a better solution.

**Comment by project64** [comment]
I made a commit (https://github.com/project64/project64/commit/c428d71e7594121ea9423a45b2a723bd92465a48) to only do the frozen dlist on hle only

**Comment by loganmc10** [comment]
Don't games like Blast Corps and DK run way too fast without that, even in LLE? Maybe I'm remembering wrong

**Comment by project64** [comment]
even if that is true, this should not be the fix for it. It needs a real fix if that is the issue

**Comment by Frank-74** [comment]
DK64 does run way too fast now in LLE, it crashes within a few seconds, with same break point as Armorines.

2017/08/31 02:34:55.453 03568,Error,User Interface,CNotificationImp::DisplayError,Break point found at
N64System\Recompiler\x86\x86RecompilerOps.cpp
10000

**Comment by project64** [comment]
I think DPC_FREEZE might need more work, but it is not in the core emu it should be, either in RSP or most likely gfx plugin is the correct place

**Comment by LegendOfDragoon** [comment]
I guess I can close this, since it's technically not an issue anymore
