### ISSUE TITLE
rsp_conf.bin will be written into roms folder

### ISSUE THREAD

**Issue by Papermanzero** [project64/project64#1048]
If a rom is started project64 or the RSP plugin writes an rsp_conf.bin file into the roms folder.

**Comment by cxd4** [comment]
I have no legitimate control over the directory that `rsp_conf.bin` is written in to.

The RSP plugin by me (not the one Project64 comes with, which ordinarily is what you would be using) is just kept portable, so it always writes to:
```c
fopen("./rsp_conf.bin", "wb");
```

If you instead find this file in your ROMs directory configured to Project64 and not the current working directory that the emulator executable was launched from, then you have found a problem with Project64 manipulating what is supposed to be the current working directory using one of its non-portable constructs.

**Comment by project64** [comment]
using current dir is very error prone. I always try to use a full path ... getting the path of a module on linux not sure. But you can easily deal with windows tho to make sure it is in the right dir.

**Comment by cxd4** [comment]
I will not ever use Linux-specific code, just standard C.

As detecting the full path of a module is not a part of the C standard library, emulators should not be designed to make plugins find the current working directory.

>using current dir is very error prone.

I imagine I am uneducated on some reasons on why this is, since I don't know.

But if one of the reasons for it being error-prone is because of WIN32-specific code tweaking the current working directory into becoming something else, then the solution should just be fixing/removing the WIN32-specific code and not making plugins use WIN32-specific code.

**Comment by project64** [comment]
mostly error prone that any code I execute can change it and is valid for them to change it, I want to control the code, if some other random code can change the behavior and make it act wrong then that opens my code for errors. I just seen to many times not using full path causing problems, that I will always try to use full path.

**Comment by cxd4** [comment]
Issue with me using the full path, is that I don't know how to do it.
Not without guessing where they have Project64 installed (`C:\Program Files (x86)\Project64 ?.?\` or `/usr/X11R6/bin/project64/` or `/usr/bin/X11/project64/` or `/home/guest/project64/` or ???).

It's not standard code, and there is no standard feature to detect what it is either--for good reasons I am sure...as common as Win/Macintosh/Linux may all be for being able to detect current paths, there is nothing fundamental to CS itself which dictates this feature always even exist on every file system.

Therefore, it stands to reason that most plugin authors (and for that matter, most plugin-free / module-free software authors) will tend to just know what the current directory is _supposed_ to mean.

>that any code I execute can change it and is valid for them to change it,

I am interested in an example of this, if--as you say--*any* code you execute can change it validly.

So if there is an example of any standards-compliant code you would use that causes the current working directory to change then that would be interesting.  If it's just more platform-specific code then as I said far be it from the truth that there can't be any alterations/workarounds to replace the circumstances attached to that.  Maybe opening up a File Explorer window shell within Project64 for File/Open ROM causes the current directory to change?  Well there are still workarounds, as those explorer directories I think should really be kept separate ideally; made a backup of the starting directory path if need be.

**Comment by Papermanzero** [comment]
By the way similar issue concerning the path:
**https://github.com/project64/project64/issues/1044**
In any scenario, the URI detection is not well implemented.

**Comment by cxd4** [comment]
>In any scenario, the URI detection is not well implemented.

Will not be implementing URI detection.  I'd sooner agree to the plugin specs providing a struct member in the plugin info struct saying what the full path of the proper current directory is, and even then I would have asserted these arguments long back to when the plugin specs were first being formed in an open-source kind of collaboration between more than one person.

>The developer for the plugins has to rely on the definitions of the emulator.

I don't see how.  I'm relying on the standard Unix current directory path of "./rsp_conf.bin" and have never had any issues here, or even with Project64 the last time I booted up a Windows partition to try it.  If only now you see this happen with a recent build of Project64, then it's a recent change to Project64 that manipulates the current working directory which is not right.

**Comment by Papermanzero** [comment]
Well.. the core issue is (but this is my personal opinion), that the specification for the plugins is not further developed.
If you define APIs between a core program and plugins, you also need to readjust the specification from time to time, because you cannot cover everything at once. I don't even no, if the zilmar specification got an update in the recent years (or if ever an update was done).

I would create an API towards the emulator for the configuration storage. Currently every plugin handles the folder structure by its own, which leaded to this issues. However if the plugin can call a function to save it's config with the possible necessary folders then the emulator would take over the complete file handling. Consequently the same must be applied for loading a config.
However this cannot avoid, that the plugin developer still defines folder/file structures by its own. Nevertheless it would make the life easier for the plugin developers because they don't have to take care about different OSs, their file system etc.

Btw. PSEmu Pro has the same issue. It's initial release was in the end of the 90s and since then, nobody enhanced or corrected some aspects of the spec to make the development more efficient. In my opinion the most disadvantage of plugin based emulators.

**Comment by cxd4** [comment]
Absolutely, the specification for plugins should have been further developed.

The only point pertinent to that which I didn't find in your explanation is about _when_ it needs to be addressed, and the answer to that to my understanding is _as early as conceivable_.  Somebody has to come up with the idea.  It's better to come up with the idea ASAP than it is to implement it into the specs 10 years later, where most emulators by then have no plausible binary-compatible version of the spec that can support this revision.  You then have 4 or 5 different versions of each plugin type spec to support.

>In my opinion the most disadvantage of plugin based emulators.

Likely so, but it wouldn't exist if and where plugin-based emulators took more early initiative.

>In this particular scenario, I dunno what PJ64 did, but it seems "./rsp_conf.bin" is used in different manners by the emulator (Maybe the last path which is called. As a consequence it is the roms folder when a rom was opened before?).

What `"./rsp_conf.bin"` means is current directory folder --> rsp_conf.bin.

What it doesn't mean is the last path which was called.  Even back in MS-DOS, the single dot `.` referred to the current folder you're in.  Nothing is allowed to change that until you leave the folder or go somewhere else.

That is just the way it has always worked for me, even outside of C programming.  The only exception I've seen is with Windows XP or older, you have to use a backslash instead of a forward slash:  `"[...]\rsp_conf.bin"`, but this requirement doesn't override the C standard.

But the current directory of Linux programs/emulators I've compiled has always been the location of `"./filehere.ext"`, and the current directory of Project64.exe on Windows has **always** been the same as the location of `"./rsp_conf.bin"` whenever I tested my plugin on it.  I don't know what exactly has changed recently for this to no longer apply, but it's surely nothing compliant to the C standard.

**Comment by Papermanzero** [comment]
I can only speak from my experience. Some technical standards or middleware solutions are continuously enhanced. You have some kind of "core team" which is talking regularly about enhancements or new features, so that a new release of the specification can be done. 

For sure it is desireable to have everything as soon as possible, but it's not possible. Continuous Integration means also to continuously improve, this affects specifications as well. If the specifications were not updated for years, it's never to late to start with it. However the team, who writes and releases a specification, has to ensure that the new version is backwards compatible to its previous version, so that already launched apps, plugins, etc are still usable. The team has to announce in time, that a certain API will be changed rapidly or discontinued, so that all developers have to chance to update their work. 
This is also how the app development on mobiles work.  

Your description about the syntax of Linux URI calls is completely right.
But as said, I guess the "current directory" can also mean the "current directory pointer" in which the emulator is referencing. Means, if PJ64 is currently pointing to the roms folder (for whatever reason), the call "./rsp_conf.bin" creates the bin in the roms folder/directory.

I didn't dig into the source code, so I dunno how the emulator is handling files. But if zilmar is using absolute paths and you are using relative paths, it easily can come to conflicts. 
As said, I would define an API for config save/load.

**Comment by cxd4** [comment]
If someone wants to add an API for config save/load directories into the plugin system then fine.  I just don't see any cause for me to do it because it would complicate more than simplify.

We can add all the extensions, changes and upgrade to the plugin specs that we can think of, but at this point in time it really is a little late for that.  You would implement this in Project64 2.3+ but what about the other plugins that are no longer active, and what about Project64 1.7, Project64 1.6 or older, 1964 etc.?  You would have to recompile all of them too; otherwise this create a new version of the plugin specs thing is just going to inconvenience all the testers who need other emulators/plugins to cross-reference.

**Comment by project64** [comment]
@Papermanzero project64 will update the usage but the focus would be just for it's own plugins and will try to not break any compatibility with other plugins in doing so. For example the first party plugins use project64 system settings mechanism.

Project64 does not directly change the directory, the only place I could fine was the creation of a new directory to check if it could be changed in to, then the current dir previous is restored. Now the windows UI for selecting a directory may change the current dir. Could be another plugin for all I know. I just found it can lead to errors like this when I use current path instead of full path

**Comment by Frank-74** [comment]
While testing S.C.A.R.S earlier, I installed the static interpreter plugin, and renamed the config so it works from project64 Configure RSP.

On clicking Configure RSP from within Project64, the config console program, created the rsp_conf.bin in the plugins folder, next to rsp.dll.

**Comment by Frank-74** [comment]
I deleted rsp_conf.bin, opened spconfig, set '000' for all LLE.  rsp_conf.bin created next to spconfig.exe.

Open Project64, run SCARS, which is already set to LLE graphics, and to use Static Interpreter.  SCARS runs as if HLE is on.  Close Project64, new rsp_conf.bin in Save folder has been written with setting '10'.

Note that I never opened any settings, after opening PJ64, just open and run game.

**Comment by LegendOfDragoon** [comment]
Was this fixed?

**Comment by project64** [comment]
sort of, maybe enough... the plugin does not use full path, just the current working dir which is really the problem.  Granted the plugin spec maybe should have where the base dir is.  The part that has been fixed is that when you choose a directory using the windows API like choosing rom dir, then that changed the working dir. Now in pj64 when I call that function I revert what the current working dir was before that call. 

So while it is still wrong in the plugin it should not be writing to the rom dir

**Comment by project64** [comment]
probaly fixed enough to close it, not like there is anything more pj64 can do. If need be I can reopen it.

**Comment by cxd4** [comment]
It always can be wrong in the plugin because I could `cd` to whatever before invoking `Project64`.

So
```shell
cd ~/project64-git/
../Project64/Project64 # to launch the emu
```
Stuff like GlideN64.log, rsp_conf.bin etc. written to project64-git/Config instead of Project64/Config.

Another example:
```shell
cd /home/
~/Project64-2.x/Project64
```
Again, config files written to /home/Config instead of ~/Project64/Config.

I see no fundamental reason to interpret this behavior as a bug.  Just don't do it as the user.

**Comment by cxd4** [comment]
If anything it's a feature that allows the user to keep their config files archived where they want.

Features can always be abused by the user to cause errors, but they're not bugs of your own fault if you recover from them.
