### ISSUE TITLE
Removing gamefaq

### ISSUE THREAD

**Issue by project64** [project64/project64#108]
The gamefaq has been removed from menu and from what is being installed. 
I was considering removing all the (see GameFAQ) from the rdb since it is no longer there

so we now have comments like: 
[video](see GameFAQ)

that would just leave
[video]

what do you think should they be striped the (see GameFAQ)?

**Comment by Fanatic-64** [comment]
Your link is broken.

And IMO if the GameFAQ is gone, we should replace the (see GameFAQ) comments with a brief description of the issue (e.g. [video] Issues: pause, level, blur, sky, coronas, shadows, effects - That's the shortest I could come up with for Conker). Although thinking about it, should the comments still be specifically for Jabo's plugins?

**Comment by project64** [comment]
hmmm was not meant to be a link, github changed it.

well jabos is the default, so it probably should be, maybe in the comment that

**Comment by death-droid** [comment]
Hmm to be honest, unless we have a video plugin that is tied directly in with Project64. I don't see much point in having the video issues shown, as they tend to not be core related problems.

**Comment by cxd4** [comment]
Understandable.  I guess bot many people like the idea of documenting plugin issues with "first-party" plugins only to somebody else, but actually are third-party to their own possibilities.

Even if Jabo's plugin was open-source, by the time any other plugin came along that was completely different, all of the plugin notes would be useless anyway because several other graphics plugins would have nothing to do with it.  The only relevant notes left would be the core notes.

**Comment by dsx-** [comment]
i put a lot of time into updating the entire GameFAQ last year, which you can see at http://dsxcorner.com/emulation/PJgameFAQ.chm so it now documents many of the current issues with Jabo's graphics plugins, as well as details about many core issues, but if you don't want to include the gamefaq anymore that's fine i guess

maybe the comments can be something like:

[video] third party plugin recommended

**Comment by project64** [comment]
I do not mind looking at how to put it on to the website if that is what we want, or you got good information there. Just removing it out of the installable emu

**Comment by oddMLan** [comment]
>I do not mind looking at how to put it on to the website if that is what we want, or you got good information there. Just removing it out of the installable emu

Agreed.

**Comment by vgturtle127** [comment]
Having a web based version makes a lot more sense, it is easily updated online, while a version that sits on your hard drive would have to be manually updated and synced with the online version, which can be confusing and frustrating for new users. So this is a great idea, and DSX can have all of his hard work used to it's full potential. Which is good, because I actually have been working on trying to find a better way to document issues with emulators and their plugins, BIOS files, specific games, etc. I will probably do a Wiki. Anyway, nice job DSX, this is way better than the current testing method I had of just trying every game with every setting and writing it all down. :smile:

**Comment by vgturtle127** [comment]
Also, is there a chance we could switch from CHM files to something more easily editable on Git? Like text files, HTML files (since CHM files are basically HTML anyway), or or Markdown or something?

**Comment by project64** [comment]
once 2.2 is out I want to go back to the website cleanup/redo it .. so it would be good going in to that knowing how we want to document/manage that .. like should I have information in a git repository that I can use to build the pages, or do we do a wiki where people can edit directly.

**Comment by vgturtle127** [comment]
Well, a Wiki on the website would be good, it could be similar to Dolphin's Wiki:

https://wiki.dolphin-emu.org/index.php?title=Main_Page

I would also be fine with having a version on GitHub, anything other than a binary CHM file at this point would be awesome, otherwise I feel like re-writing the GameFAQ makes little sense if we are going to change formats.

Once you guys figure out a format, I'd gladly fill in as much info as I can. I have a lot of plugins and project64 source copied locally ready to go. Also, you have a lot of binaries in your repo that I think should be added to the .gitignore list so you don't break anything. Or you could remove them from the repository and only include them in binary releases.

**Comment by cxd4** [comment]
There may be a way to grant access permissions on GitHub for people to contribute to the Wiki without also giving them collaborator status.  I can't remember, but somebody did that trick with me for a chess site once.  (That was just so that I could fix their crappy English.)

**Comment by vgturtle127** [comment]
"so I could fix their crappy English"

LOL. I do pull requests on projects that correct grammar and punctuation all the time! Glad somebody else does it and I'm not just crazy.

**Comment by cxd4** [comment]
Yeah most people don't really give a crap.  They spell/have even worse grammar than English teachers do in the US.

Not really a current hobby of mine though, just something I was hired by some French guy to do.

**Comment by vgturtle127** [comment]
Well, hey. At least people are being honest about their limitations. I always prefer that over anything else.

Are we going to switch formats, BTW? I would like to get to this ASAP if possible. I still have to get my dev machine setup, but that shouldn't take long.

**Comment by project64** [comment]
well if you have something ideas, we can look at starting it right away. I do not plan to do any real work on the web site till after 2.2 is released

**Comment by vgturtle127** [comment]
I would think a Wiki would be best, but I don't know if that is possible on your web host/setup/whatever. That would be the easiest for others to contribute as well. Once the work on that could start, we should talk about that.

Another thing we could do is use DevDocs (https://github.com/Thibaut/devdocs). Just a thought, and it works in browsers offline.

I'm trying to think of other solutions, but really I can't. Can anybody else think of anything?

**Comment by oddMLan** [comment]
I think this can be closed, since the FAQs have been since removed and the RDB comments revamped #908
