### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by bsmiles32** [project64/project64#1080]
Recent work on this project has integrated a substantial amount of my work without respecting the license I chose for it. More specifically all the HLE RSP code and most of the transfer pak code have been copy pasted without attributing proper credit.

Proof:
Original work for the HLE RSP : https://github.com/mupen64plus/mupen64plus-rsp-hle/tree/master/src
Similar code without proper copyright : https://github.com/project64/project64/tree/master/Source/Android/PluginRSP

Original work for the transfer pak code : https://github.com/mupen64plus/mupen64plus-core/pull/98/files
Similar code without porper copyright : https://github.com/project64/project64/blob/master/Source/Project64-core/N64System/Mips/GBCart.cpp

Therefore I demand that proper copyright be readded on the incriminated files.

Bobby Smiles

**Comment by cxd4** [comment]
@project64 IIRC you mentioned you got the audio sources from @weinerschnitzel's [plugin-spec-fork](https://github.com/weinerschnitzel/mupen64plus-rsp-hle/tree/master/src) of the M64P audio "plugin", which did still credit Bobby in the copyright.

@death-droid Just pinging in case you might have any details about this, as according to [this commit](https://github.com/project64/project64/commit/ff5fcf6d337bc14db4e44e4b47042d4a4e328711) in which you had added those files.

Sorry that this happened for whatever it's worth.  I'm not really acquainted well at all with license details and copyright requirements or their entailments, (I do remember proposing to port the existing PJ64 RSP interpreter sources to Android instead of throwing in another plugin.) but I hope that this type of issue can be adequately resolved on both sides.

**Comment by bsmiles32** [comment]
To clarify my stance, I'm not against the reuse of my work (otherwise it wouldn't GPL to begin with), it is just that removing copyright notices is not fair.

For the HLE RSP plugin, I think that importing it in this repo and modifying it this way will complicate further cooperation (see what happens with the libretro fork). If you want to go that route, I don't mind, just keep the copyright notice. Otherwise, for easier cooperation, you could :
- fork the mupen64plus-rsp-hle repo
- keep all files verbatim except the compilation scripts
- remove src/plugin.c from the compilation
- implement a project64 specific src/pj64_plugin.c{,pp} and add it instead of the src/plugin.c where you implement the plugin exported functions compatible with pj64 interface.
This way you can enjoy a pj64 compatible plugin which will be easy to synchronize between projects.
When I refactored the HLE RSP plugin I really tried hard to make it easy to reuse in other projects despite being at the time a M64P plugin only. I hope you'll find it valuable.

**Comment by cxd4** [comment]
Yes I've heard about your efforts to keep your plugins compatible with both pre- and post-M64P specs.

> * fork the mupen64plus-rsp-hle repo

This personally would have been my choice.

My stance has always been that plugins should be kept out of the Project64 repository, as none of them can really be (legally?) credited to being a part of Project64's design team or efforts except for the Project64 RSP plugin.  Separate repositories would also keep the actual Project64 source control much cleaner and less polluted, not to mention take advantage of the fact that we have a plugin system--for whatever pros and cons that entails.  I'm guessing that a part of why zilmar prefers the "all-in-one" repository approach may be related to the Android port profiting money from what is considered to be a part of Project64.

But I did not see the license/header bits when pj64 uploaded your HLE sources.  Did not really pay attention because I was not really interested in the idea of your plugin being forked as a part of Project64 and polluting the repository with more plugin sources (no offense intended to e.g. yours or anyone else's plugins).

That being said, a separate repository sounds to me like a good solution during the interim that zilmar can, in later releases, port the RSP recompiler to ARM with Android, instead of exponentiating the size of the repository with more plugin options.

**Comment by project64** [comment]
@bsmiles32 thank you for the work you have done and I am sorry for not doing it correctly when importing the code. If I understand correctly I just need to add:
```
Copyright (C) 2014 Bobby Smiles
```
to those files, is that correct, or something else I need to do? 

I do have everything still gpl2 as I believe that is your license and am sharing all the changes I do/have made. So I think that is the only thing I did wrong? I am trying my best to be respectful to you, the work you have done and respecting the license you chose.

I think the only place I have used Copyright (C) xxx zilmar was when I first released the RSP plugin cause I was copying how other people did there headers, beyond that I do not notice that so sorry. 

with the way I have forked the code with importing it in to the repo and modifying it will complicate further cooperation, I agree with that.  I did try separating the code before and using git sub modules I just ran in to issues and dropped trying to do that, I dislike another developer having to keep multiple repositories up to date, instead of a single repository. But that is a discussion I am happy to have and if there is a better way then I would love to hear and use it. 

I probably did break mupen's plugin spec usage as well. 

I never did actually use the mupen64plus-rsp-hle repo directly, tho I do know the code I used is based on it. I referred to:
https://github.com/mupen64plus-ae/mupen64plus-ae/tree/master/jni/mupen64plus-rsp-hle
https://github.com/weinerschnitzel/mupen64plus-rsp-hle

Some of the changes I made was getting it to use the pj64 specs, changing it from c to c++, like using classes to represent the data instead of structs, Use the project64 property sheets for settings, Some code formatting, etc.

I am not sure you would want these changes merged back any way.

**Comment by bsmiles32** [comment]
Thanks for your answer. Your code is indeed gpl2 so no problem with that. Just keep copyright notices verbatim. Other changes are fine for your project but out of scope for m64p. As you noted they will complicate further cooperation but that's another issue.

**Comment by project64** [comment]
@bsmiles32 just want to make sure i get this right, for example:
https://github.com/mupen64plus/mupen64plus-rsp-hle/blob/master/src/hle.c

i have to make sure I have line 4, 5, 6, right?

**Comment by cxd4** [comment]
I'm guessing he wants it to be
```
/****************************************************************************
*                                                                           *
* Project64 - A Nintendo 64 emulator.                                       *
* http://www.pj64-emu.com/                                                  *
* Copyright (C) 2016 Project64. All rights reserved.                        *
 *   Copyright (C) 2012 Bobby Smiles                                       *
 *   Copyright (C) 2009 Richard Goedeken                                   *
 *   Copyright (C) 2002 Hacktarux                                          *
*                                                                           *
* License:                                                                  *
* GNU/GPLv2 http://www.gnu.org/licenses/gpl-2.0.html                        *
*                                                                           *
****************************************************************************/
```
Or so my dbz fusion dance knowledge tells me of fusing m64p (Krillin) with pj64 (Majin Buu).

That pj64 stuff + URL doesn't really seem relevant to go in the license bits anyway tho.  Not like we don't all know what the URL for the site is, but I could say the same thing about M64P putting it in anyway.

**Comment by project64** [comment]
does https://github.com/project64/project64/commit/f598588b622f95975a53e42c473a2f0d1a3db66b answer this issue?

**Comment by bsmiles32** [comment]
@project64 Your commit is indeed a step in the right direction. There is however still 2 issues (as far as I understand) : 
- The original code is GPLv2 or "any later version" not GPL2v2 "only"
- Transfer pak + GBCart copy/pasted code is still not compliant with the original license

Thanks for your cooperation

**Comment by project64** [comment]
I believe that gpl2 is auto compatible with any latter version which is why I never had it. But I could be wrong so I added it to the files you cared about. So does now https://github.com/project64/project64/commit/21920f984b31e0814414b098744795958a142a46 cover the rest of the issues?

**Comment by project64** [comment]
@bsmiles32  can I close this now?

**Comment by bsmiles32** [comment]
Sorry for the delay.

There is still the transfer pak file that is heavily copy/pasted from my work:
https://github.com/project64/project64/blob/master/Source/Project64-core/N64System/Mips/Transferpak.cpp
vs
https://github.com/mupen64plus/mupen64plus-core/pull/98/files

After that you can close this issue.
Thanks for cooperating.

**Comment by project64** [comment]
ok https://github.com/project64/project64/commit/c999a177a80e2c31e99baa60dd69077c1680c438 updates that file

**Comment by cxd4** [comment]
10/80 would re-license again

**Comment by vgturtle127** [comment]
@bsmiles32 @project64 So is this fixed, or is everything OK now?

**Comment by cxd4** [comment]
Well he said _"After that you can close this issue."_ so I guess bsmiles thinks it's fixed.

Though it might have been fine if he closed it instead of project64 since he seems to know more about catching licensing issues than project64 does.

**Comment by bsmiles32** [comment]
Sorry for the delay. Yes, I consider this issue fixed and will close it.

**Comment by vgturtle127** [comment]
@bsmiles32 Thanks, buddy.
