### ISSUE TITLE
Android build : When Project 64 release on Google play ?

### ISSUE THREAD

**Issue by zminhquanz** [project64/project64#1124]
When it release official version ?

**Comment by project64** [comment]
when it is ready 

Still got some clean up to do and get the recompiler working to a payable level

**Comment by zminhquanz** [comment]
i hope it's better than mupen64ae android port

**Comment by project64** [comment]
it may or may not be on the initial version, but give it some time to mature and it should be as a good as the PC version

**Comment by retrobenny** [comment]
I hope the speeds can hit the point of good or greater than N64oid's recompiler but without the freezing,that and Rice made it uber fast,then again RetroArch's core is also capable of uber fast speeds even decent with rewind enabled,but N64oid is even fast on old and low-end hardware,making it badass for speed. Good luck on releasing it soon enough.
**I now have the balance to get the Pro version if you make one.**

**Comment by Rafaelele** [comment]
Really looking forward to the Android release. How's progress on it (percentage wise)?

**Comment by retrobenny** [comment]
I would like to at least see a video soon to know how its getting along,even if it runs slowly.

Also,now that the fps limit on Mupen64Plus AE has been lifted in a build on the Paulscode shoutbox,you can test the true performance beyond 60fps to see just how fast it will go on each device,meaning you can theoretically benchmark it properly and fully fast forward on 30fps and 60fps games past the long intros and unskippable cutscenes.

**Comment by project64** [comment]
the interpter works, there is some things in the UI I still need to fix, but been working on get a basic recompiler working. It is not to far away (I hope) from a first public beta. It will not be great on the first instance but it should be good enough to play game.s

**Comment by zminhquanz** [comment]
when the public Project64 release on Google Play

**Comment by cxd4** [comment]
You need to change that avatar.

**Comment by retrobenny** [comment]
Since I have yet to get a response,I tried running a buildbot apk on my Shield TV Pro and it doesn't work yet.
Two crashes:
Trying to add N64 games with several in a folder (includes other files/filetypes) triggers a crash while adding a single game Super Mario 64 (U) in a folder by itself works fine.
Starting the game causes it to have a fatal crash error before it can even boot the game,the controls appear on the screen briefly before the crash.

I will test the latest posted buildbot apk soon in case of helpful changes.

Also,I sent information regarding DK64,and how it runs on the Wii U VC with interesting details of some config settings that might lead to fixed bone placement.

**Comment by oddMLan** [comment]
>Also,I sent information regarding DK64,and how it runs on the Wii U VC with interesting details of some config settings that might lead to fixed bone placement.

hm, where can we find more about that?

**Comment by project64** [comment]
thanks @retrobenny,

yes there is a bug in the path code that makes in cause a stack overflow when scanning sub directories. Will commit a fix for that in a day or two. 

It crashes when you run a game cause it is trying to use the recompiler that does not exist. I got a basic recompiler done that should be good enough for the initial version, should be checked in the next few days. 

If you turn it to interpter it will probably run just slow.

**Comment by retrobenny** [comment]
First,it turns out slowdown based lag still happens via 4 orange bombs+camera,but movement speeds aren't boosted like the original despite being 1:1 of the game file.

Here's the **DK64 Wii U VC** config parameters...

UseTimer = 1 (said to be the one that makes it never lag and even run at 60fps)

AIUseTimer = 0 (unsure about effect,but newer PJ64 has an AI value)

;TicksPerFrame = 788000 (off by 1k of a value I found in RDRAM when address used for lagfix is at its default of 020D)

RSPMultiCore = 1 (very interesting,insisting what is implied)

Getting someone to debug on their modded Wii U with their legitimately installed DK64 copy could help in figuring out how to replicate what the VC does from scratch so as not to upset anything worse than the grey area.
Or maybe if Cemu will ever run DK64,it too could possibly be debugged from there if features can ever be added for debugging to try and find the results.
The message I sent specifically to zilmar on PJ64 Forums may have a bit more depth to it.

**Comment by retrobenny** [comment]
Checked the log file and it is looking for the .so files in storage/emulated/0/Android/data (where the files aren't even at/it fails to reach them) instead of the /sdcard/data/data (root directory) destination where apps generally store their .so files.

I also looked for the RSP setting so I could change it to Interpreter,but I couldn't find it in the cfg files.

**Comment by project64** [comment]
if it on a real device, if you mount it then logs should be in "Project64/logs"

For interpter, go to about screen, click on "Project64 for Android" 6 times you should get a message appear at the bottom, go to rom list and long click a rom, go to settings and you should have an Option there for CPU core style.

**Comment by zminhquanz** [comment]
I have a question : on Android builds , could it support x86 Intel processor ?

**Comment by project64** [comment]
Yes, it does, uses the same recompiler

**Comment by zminhquanz** [comment]
i hear somebody have downloaded APK on buildbot , but it's not found

**Comment by zminhquanz** [comment]
@retrobenny so , where did you downloaded this APK file ?

**Comment by retrobenny** [comment]
Oooooh,developer secrets,sneaky...thanks!

Gotta be eligible for alpha forum access via certain member stat/s to get to the buildbot downloads,also the non-forum beta versions can't be downloaded because that section is real badly broken,it would of made it simpler for grabbing specific versions if there is optimal builds of 1.7 and 2.x that work better for certain things.

**Comment by retrobenny** [comment]
Running this on a **Shield TV Pro** non-rooted,expect good performance to be a given for the most part.
Interpeter runs quite fast on Super Mario 64,the shadows are odd,visual positions are misplaced,and the Glide64 shaking texture issue wreaks havoc.
Can't test much because I can't jump and move at the same time,preventing me from entering levels,but audio is really good.
I got stuck in a crash loop after adding another game into the same directory I put SM64 in,every time I open the app now,it crashes out immediately,probably should have enabled all of the logs to full strength.

The most important fix first I would say is the game listing crashes so testing can go by much more smoothly,then eventually getting button mapping set up akin to the Windows input plugins hopefully or at least like Mupen Android's input mapping for now.

**Comment by project64** [comment]
if you end emulation and it locks, click resume.

If you long click and do resume with native saves does it crash?

**Comment by project64** [comment]
ok added a potential fox for the listing the rom crash (https://github.com/project64/project64/commit/7eccf17c90dfd007edeebf2dd803c55173ff52c0) matching apk (http://forum.pj64-emu.com/showthread.php?p=65988#post65988)

**Comment by retrobenny** [comment]
Clicking resume on ending it didn't help and trying to resume with native saves exits the menu instead of booting the game along with restart as well,making games unloadable after the first play of them.

Banjo-Kazooie is really glitched out with texture placement to the point of obscuring most of the screen while DK64 seems visually perfect aside from general issues with texture sizing bugs and possibly a core issue with Diddy's tail and one part of Tiny's hair bone animations being stiff,then the Cranky barrels show more glitches with vine animations being broken and barrels growing massive before being destroyed.

I think I deserve props for beating all but the orange bomb training challenge,as I can't hit multiple touch buttons on a TV device quickly enough for most actions except jumping then attacking,but that's about it.
Its a chore to control it without the proper input conditions that I can't use with a TV device.

The sad part is a tablet I have has recently started acting up with its UI,making me have to brute force my WiFi connection info just to connect it because nothing appears in the list and Mupen has issues contracted from that failure,plus I dropped it recently after that problem already existed,so its even worse.

**Comment by Frank-74** [comment]
@retrobenny 
Can't you use a controller?  Mine works via a mini usb to usb adapter in Mupen64AE.
I'll test the Project64 android version on my tablet soon.

**Comment by project64** [comment]
@Frank-74 I have not done anything for controllers yet, yes it should not be hard, but I am just trying to get to the first beta release, then add more features/fix anything wrong. Lots of small updates then trying to get it perfect first go

**Comment by project64** [comment]
@retrobenny the default settings for glide64 might need to be tweaked for android. I am using the same as the PC, but I do not know graphics well so not sure what they should be and more work is needed there.

How do you find the UI in general, I think I am getting close to the first public beta release. I know it will not be perfect, but knowing where the biggest issues are before release is really great, thank you

**Comment by retrobenny** [comment]
I haven't seen a single Glide64 without some major issue on Android,Mupen AE's has polygon sections missing and RetroArch's has performance and pause buffer scaling issues.

I like how the list text resembles the way it looks on Windows with the colors,but I think you should have an option to show filenames so that things like SM64 hacks show up with clean names instead of "pound sign"340"pound sign" if I remember correctly what they were listed as.
The UI itself looks good,though I think a night theme would be nice for viewing on a TV.
Can't say much else about it since the features are not yet hooked in,but hopefully the cheat UI can be implemented soon as in a while from now and eventually the many options already found on Windows for advanced users to change like the already included Advanced Block Linking.

Forgot to say in case,I am retroben from PJ64 forums,the name being used forced me to make an alteration for my name on here,but the icon is a dead give-away.

**Comment by project64** [comment]
I did work out who you were :)

It is the windows version made to be moved to other systems, yes the "#340#" is in my list to make sure I fix post release.  I am sure I could spend another year on it and still not be happy with it, just trying to get the minimal viable version ready and build on it. Like the core does have all the cheats code in it, just need to add the ui for it. The "#340#" is to do with multi language which is not in yet.

there is a whole issue here about me using ANGLE, post release I will likely be spending a lot of time on the gfx plugin, cleaning it up and trying to get it better, not sure how much I can fix pre-release. In general I am happy that it is close, tho I do like the crashing you are getting.

I would like to see a release that I can do continual small upgrades to make it really good, things like LLE version will probably be windows only tho. If people actually buy it I will end up buy lots of difference device just to test with, at the moment I have limited devices.

**Comment by retrobenny** [comment]
Mupen64Plus AE recently got CXD4 LLE via GLideN64 but it is super slow and it may end up with Angrylion too for various interesting test scenarios and the possible faster speeds.

That RetroArch Vulkan LLE plugin,what is your thoughts on that matter?
I can't get it to run either that or Angrylion on Android,but Shield TV has good Vulkan drivers for cutting edge performance boosts.

**Comment by project64** [comment]
I am not interested in LLE for android, I am interested in it for compatibility and for testing. 

the crash you were seeing, was that for all games or one game in particular, if you reset the game does it work, I want to see if I can reproduce the crash

**Comment by retrobenny** [comment]
Out of curiosity,what about Vulkan in general? Dolphiin Emu recently got it added with Android working rather well but not without initial rendering glitches for some games they'll likely fix sooner or later when publicly released.

The end emulation crash has happened on all three of the games I tested so far no game has gone crashless upon exiting.
To be more clear,it **hangs first** on end emulation with Android's option to wait or close it,and closing it makes the crash message appear afterward,haven't tried hitting wait but waiting may cause the device itself to eventually reset from a kernel panic with Shield TV's history of random resets in normal situations.

**Comment by retrobenny** [comment]
I got a verbose log hitting 9MB in size,should I upload it for you to check out despite this massive file?

**Comment by project64** [comment]
it is ok, I will do some more testing, it could be something I already fixed as I have changed some of the code releated to end emulation and not sure it is it the public version yet

**Comment by retrobenny** [comment]
Damn log got overwritten and I hit several complications before I could recreate the scenario new file is around 8MB and zip size is much smaller.

That was recompiler with the fatal error,but no crashes on running the game,the first run works fine but running the same game again won't even open start it no matter what option I select,leaving me on the menu screen instead of taking me into the boot mode.
I got to locked out games again by deleting the save files in order to do the fresh log on Super Mario 64.
[Project64.log.zip](https://github.com/project64/project64/files/412064/Project64.log.zip)

**Comment by retrobenny** [comment]
Just "played" Smash Bros. with Kirby on Very Easy mode with an infinite timer.
I don't know how,but **I managed to get all the way to Metal Mario before losing the last of my 5 stocks without proper access to the touch input!**
And I almost had him with his damage at 350% and if only I had a hammer or exploding capsule spawn.

**Unfrotunately**,polygon sections go missing just like in Mupen64Plus AE.
The other issues are that the magnifier is glitched and then,the common issue of every game,most items will grow to massive size obscuring the screen.

**Comment by project64** [comment]
A massive update to the android build http://forum.pj64-emu.com/showthread.php?p=66014

**Comment by project64** [comment]
Feels like a huge list of things I still need to do, lots of work to get the recompiler faster, the gfx have lots of issue, but I still think it is worth releasing a version soon that people can play with.

**Comment by retrobenny** [comment]
Great! Now end emulation works okay and no longer null when loading to restart the game again.
I am afraid to use the paid option from current stability conditions,I guess it pays $0.00 to an empty location but I don't wanna risk wiping out my Play Store balance before manually choosing to get it.

I tried Recompiler on SM64 and it freezes at first in place until I enter and exit the new settings access,so from loading a savestate via that action lets it contiue,I eventually get to ingame and find it having frequent stutters on the first time I do any action,kinda like the nightmare equivalent of shader stuttering.
Instabilities were to be expected with the recompiler at such an early age.
I saw satan when selecting "sync cores" its a flickering mess of polygons.
Have yet to try recompiler without audio to see if it would help against the issues.

**Comment by retrobenny** [comment]
Nope,stutters the same way without audio checked.
Conker runs really well on Interpreter and continues to run with the pitchfork scene.

I think you should just make people use Interpreter on the free part with native saves usable but no manual savestates,auto saves would still be allowed.
This way after the recompiler is ready,it will give them better reasons to get pro.

**Comment by project64** [comment]
I am not a graphics person but I will end up having to learn it. Sync core is horrible for gfx not sure exactly why. Which is why it is also a hidden option, end users are never meant to see it P

I am sure I could easily spend a long time before a release, but I think better to get something out there. I do not expect people to buy it till it is ready, one of the main reason I did in app purchase instead of buying that way they can see it is not perfect and go I do not pay for that :P

**Comment by retrobenny** [comment]
Okay,why not just make a donation version early beta that you can later rename to a normal version?

So far no SM64 hacks will boot,curious what exactly causes it if not the "bad rom" status of all of them.
Both Peach's Christmas Invitation and Super Donkey Kong 64 refuse to boot and promptly crash the app.

**Comment by retrobenny** [comment]
Hopefully you can eventually apply realtime menu access without hacking around it with savestates.
N64oid already accomplished this long ago and all of the 2d .emu apps "snes.emu" can handle realtime menu access with transparency so you can see the game behind it paused and edit cheats in realtime with new values and easily resume with the changes applied instantly,an example being Donkey Kong Country animation frames that allow you to oddly use enemy and object frames as animation,but further than this on N64 by allowing activator changes with as many as 28 values using all combinations of d-pad making a 56-lined code that can be updated with several other values whenever one wants instead of having to exit every time you want to change any cheats.

I want to say a lot about the memory viewer and possibly memory search for the ability of realtime value changes at any position without making cheats for each specific line,,but that may be stuck in a long waiting list for months.

Also I hit an older cheat issue with a reply if you could check that as well.

**Comment by project64** [comment]
I am not a graphics person, tho I will need to start to study and do work on glide64 soon to try and get rid of the bugs, At the moment i am using java to do the menus but if I actually knew graphics well I could do all the menu system using open gl. But at the moment I am limited to using java UI, 

I am still finding it to slow for my liking, need to work out if that is gfx or cpu the real problem, but I still plan to do an initial release soon and just keep working on it.

**Comment by zminhquanz** [comment]
@project64 Can Project64 supported and implemented Multithreading yet ?

**Comment by retrobenny** [comment]
My thoughts,CEN64 has accomplished the task of multithreading somehow,but not without a handful of issues such as eventual crashes at first.
Maybe its come along even further now and no longer crashes with it.

https://www.youtube.com/watch?v=Jy8IOxcj8r4

Hope nobody minds me linking the CEN64 YT video showing it off.

**Comment by retrobenny** [comment]
Technically the issue has been met now.

https://play.google.com/store/apps/details?id=emu.project64

Do I freshly install it again from the Play Store to get the beta user confirmation in support?
Its not showing up in Shield TV's Play Store list,please try to fix that soon.
I have the balance on Google Play for the Android version,so I can always officially apply the in-app purchase normally,still think its a bit pricey,but if its a one-time permanent purchase,its not that big of a cost.

**Comment by zminhquanz** [comment]
@retrobenny thank you , i'll installed to test

**Comment by zminhquanz** [comment]
@retrobenny thank you sir , i'll tested on my Android devices

**Comment by project64** [comment]
lots still to do with the android version, but a good first step
