### ISSUE TITLE
Paper Mario freezes when you press Start at the title screen.

### ISSUE THREAD

**Issue by Mario0051** [project64/project64#1130]
When I try to load a game file in Paper Mario, it freezes. I use Project64 2.2.

**Comment by LegendOfDragoon** [comment]
I don't see any freezing on my end. Have you tried the latest binary?

**Comment by project64** [comment]
if you install to a clean directory does it work correctly ?

**Comment by Mario3264** [comment]
No, I haven't tried the latest binary yet, maybe that will work.

**Comment by LegendOfDragoon** [comment]
I guess the issue mentioned here is sub-screen delay. I'm guessing I didn't notice before, because I was probably using Angrylion's. The issue is the graphics plugin.

**Comment by oddMLan** [comment]
I noticed if you set the count factor to higher values, the delay increased proportionally.

so a CF=2 is twice as long, whereas CF=6 is six times longer

when you overclock, 2x makes the delay shorter (dunno if it's half of it, but it's certainly faster). at even higher OC values, the delay becomes shorter. I wouldnt just blame the graphics plugin here. I think it's probably because the game checks the RDRAM and since no plugin can reproduce its contents with 100% accuracy except for angrylion's rdp, the function keeps looping, hence the delay. Making the contents of the RDRAM 100% white fixes the delay in some cases (Zelda OOT for example). 
Zelda MM has never had such delay. Proabably because it's better programmed than OOT.

**Comment by LegendOfDragoon** [comment]
I remember that the white trick also worked for Paper Mario. I'd just prefer to do it accurately if possible :smile: .

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
