### ISSUE TITLE
Current Compiler Settings are not optimal

### ISSUE THREAD

**Issue by LegendOfDragoon** [project64/project64#1154]
For example, with Glide64, there are games like Bakuretsu Muteki Bangaioh that have bad performance because it's calling a function for bswap instead of using the native x86 instruction.

Also I think maybe maximize speed might be better than minimize size. Perhaps we should test some of these settings.

**Comment by project64** [comment]
does https://github.com/project64/project64/commit/61accf135402d5c3c45a1da8c931d9697c40d4df work for you?

**Comment by LegendOfDragoon** [comment]
Yes, now I get ~78 VI/s in Bangaioh instead of ~55 VI/s. Other games like SD Hiryuu seem a little faster too.

Before closing, I think we should consider testing other options too, like comparing maximize speed to minimize size.

**Comment by Frank-74** [comment]
@LegendOfDragoon 
Are there any English language games that get a benefit from this?

I had a bit of difficulty trying to test Fushigi no Dungeon - Fuurai no Shiren 2.  Took me a while to just start a game with the Japanese language.  I removed the Flush() commands to disk for sra and it fixed the core issue for that game reported in the rom browser.

**Comment by cxd4** [comment]
Byte swap is an intrinsic language element function and not a function resulting in a procedural sub-call.  The approach in @project64's commit is correct and is more definitive in this fix than changing from minimize size to maximize speed.

Though, `bswap` is more of a messy macro-instruction.  Not to sound like that fallaha dude or anything, but as time goes on with newer CPU processors, the benefit in performance of executing `bswap` instead of 4 8-bit `lea` writes (or 2 8-bit ones and 1 16-bit LEA) becomes less and less than arranging the byte-swap by hand.

>Before closing, I think we should consider testing other options too, like comparing maximize speed to minimize size.

In most cases I think "maximize speed" produces faster programs than "minimize size", but I think this is just important to value for the core and Glide64.  Maybe the RSP interpreter too (not really sure it would help any re-compilers...), but everything else in the entire Project64 package would likely benefit most from size reduction rather than inflation for speed.

**Comment by project64** [comment]
I found before that smaller size could actually be faster, mostly cause it allows more code stored in caches, If you can find a demonstrable performance increase happy to change it.

**Comment by LegendOfDragoon** [comment]
>@LegendOfDragoon 
Are there any English language games that get a benefit from this?

Some games that heavily use 2D graphics. I'm guessing Mischief makers should probably have a noticable improvement.

>In most cases I think "maximize speed" produces faster programs than "minimize size", but I think this is just important to value for the core and Glide64

Yeah, I was just considering using it for core and Glide64.

>I found before that smaller size could actually be faster, mostly cause it allows more code stored in caches, If you can find a demonstrable performance increase happy to change it.

I guess it's worth testing. I'll let you know if I can find a scenario where it's noticeably faster with maximize speed.

**Comment by oddMLan** [comment]
>It might be a good idea to remove all the forced flushing to disk for all save types. I've been using Project64 built with all flushing to disk disabled for a week now, and no problems whatsoever. It's smoother.
Ditto this.

**Comment by project64** [comment]
https://github.com/project64/project64/commit/8422cf708386f529b484a084c4f81802d2b3ba51

**Comment by LegendOfDragoon** [comment]
In my brief testing, I haven't come across a scenario where maximize speed makes a significant difference. So I'll go ahead and close it.

I'm better off optimizing the code itself, if I want to see big performance gains.
