### ISSUE TITLE
[Glide64] Texture screen alignment (Goldeneye portraits)

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1174]
Long standing problem, where the portraits in Goldeneye have a split down the middle.

Closer looking, it appears to be screen position dependant.  As can be seen from the multiplayer character select screen.  The portraits show up a texture alignment problem depending on x position more clearly.
![glide64_goldeneye_01](https://cloud.githubusercontent.com/assets/11056843/17716342/3352199c-6400-11e6-813d-814de5f9827b.png)

But it's also noticeable on some text.  Notice the second 0 of 007.  The bottom right is more cut than the rest.
![glide64_goldeneye_02](https://cloud.githubusercontent.com/assets/11056843/17716543/05e2587c-6401-11e6-9c83-c28e7f5fd425.png)

**Comment by Frank-74** [comment]
Interesting find...

With Glide64Final and using the nGlide wrapper, the smaller portraits are fine.
![glide64_goldeneye_05](https://cloud.githubusercontent.com/assets/11056843/17717604/e0ae2238-6406-11e6-8017-65fec737f7ae.png)

The large bond portrait is still split with nGlide though.

**Comment by cxd4** [comment]
Not really; it's just different filtering mechanisms your card will use when Direct3D is upscaling it vs. some other rendering device.  And in this case the game is instructing bilinear filtering--a thing that the real N64 does in a very particular style of texture upscale that neither fixed-function OpenGL nor Direct3D approximate very well.

Forcing point-sampled (or "nearest-neighbor") filtering fixes the issue by not attempting (almost impossible) real N64 bilinear filtering and just doing blocky pixel upscales.  In RiceVideo this is done by disabling "Accurate Texture Mapping".  In Jabo's 1.5.2 and 1.7 plugins there is usually an RGB software rasterizer option to fix it.  In Glide64 just select point-sampled.

**Comment by Frank-74** [comment]
@cxd4 
Force point-sample in Glide does nothing to fix these screens.
![glide64_goldeneye_01](https://cloud.githubusercontent.com/assets/11056843/17753783/4f571966-64c9-11e6-867a-35d7d62ed8d3.png)
![glide64_goldeneye_02](https://cloud.githubusercontent.com/assets/11056843/17753785/51c4b834-64c9-11e6-9bfc-2c4067464798.png)

But it does fix the multiplayer character screen?
![glide64_goldeneye_03](https://cloud.githubusercontent.com/assets/11056843/17753814/7668ad8a-64c9-11e6-9c6b-ec86c71529dc.png)

There's no problems with Jabo 1.7 or 1.6 in HLE.

**Comment by Frank-74** [comment]
I tried the earliest version of Glide64 here :- https://code.google.com/archive/p/glidehqplusglitch64/downloads

Glide64 'Napalm WX' WIP Date: Nov 17 2010.   Problem still exists.

**Comment by cxd4** [comment]
>Even 320x240 has the problem with force point sample.
Different resolutions alter which portraits are split. Here its the bottom left that is worse.

GoldenEye resolution, in those menus, is not 320x240 pixels.

The native resolution in those cases is 440x330, if I remember correctly from my PixD utility.
Setting 320x240 will just shrink those down and lose precision.

>Force point-sample in Glide does nothing to fix these screens.

They might not even be broken, then.  Actually using a correct three-point bi-linear upscale might be part of hiding the ugliness of a a disproportionate scale coefficient on the real system.

>There's no problems with Jabo 1.7 or 1.6 in HLE.

They, like nGlide, use Direct3D, whereas Glitch64 with Glide64 does not.  Again that is a matter of how your GL Intel drivers chose to implement bi-linear filtering, which may or may not be even further away from the N64's three-point variation of that filter than other cards or when testing with Direct3D.

The comparison using Jabo's 1.7 with Glide set to point-sampled would be to enable "Software rendering" in Jabo's plugin.

>Looking forward to when Angle is tried, as it may fix this issue.

For some people's cards.  At the same time Angle may cause the issue for others, as neither D3D nor GL are pixel-exact specifications.  It's also likely that the fault is just shoddy driver implementation.

In both D3D and GL, shaders (HLSL and GLSL) fix the issue of exactly matching N64 bi-linear.

**Comment by loganmc10** [comment]
Have you guys looked at this:
http://gliden64.blogspot.com/2015/11/improved-2d-and-other-fixes.html

It seems like the same issue, he even mentions:
```
spent many hours on debugging and even wrote my own bilinear filtering shader because standard one causes glitches.
```

In reality who is going to fix issues with Glide64 like this? Probably no one.

**Comment by cxd4** [comment]
The blog is correct exactly, and it is the same issue.  You need to write a custom shader program in GLSL (in an OpenGL Glide64) to use N64's three-point filter instead of the built-in four-point one that's internal to OpenGL and DirectX, and even then the result is correct before hi-res scaling the N64 frame buffer up to common window resolutions like 640x480, if that was not the native frame buffer size.

Somebody run the ROM in my fork of angrylion's plugin, and hit "Dump DRAM" or whatever that button is called in the second tab of the configuration for the plugin.  Upload the resulting `.bin` file for me so I can play with it.  I can't/won't run N64 emulators on these computers, so if someone can upload to me I can extract a real N64 screenshot of what this menu is really supposed to look like, before VI processing and other interference Glide64 never emulates.

**Comment by Frank-74** [comment]
@cxd4 
https://dl.dropboxusercontent.com/u/9498358/n64/RCP_003B5370_00013016.zip
I zipped the bin.

**Comment by Frank-74** [comment]
I ran a test on my OpenGL, here are the results.  OpenGL 4.0 is VERY slow.
OpenGL tests at 1366 x 768, Z24RGB32, 60 Hz
Windows 8.1, Intel(R) HD Graphics

OGL Version	FPS
OpenGL 1.1	203
OpenGL 1.2	476
OpenGL 1.3	455
OpenGL 1.4	395
OpenGL 1.5	449
OpenGL 2.0	419
OpenGL 2.1	388
OpenGL 3.0	382
OpenGL 3.1	396
OpenGL 3.2	396
OpenGL 3.3	397
OpenGL 4.0	39

**Comment by cxd4** [comment]
Yeah sometimes just capturing the window with VI filters disabled at the right resolution is close enough.  In any case, here's the (unnecessarily perfectionist) PNG from the uploaded .bin file:
![ge](https://cloud.githubusercontent.com/assets/1396303/17823405/4ffec50a-662a-11e6-9608-bcb14900cadb.png)

>Looks good but awful slow on my Intel HD Graphics. 6-7 VI's.

I have yet to take advantage of framebuffer rectangle extensions in GL, so it's quite possible that it doesn't run transparently to the way a DirectDraw video blitter would perform in the current releases.  Even so, the choice between GL and DirectDraw is chiefly impertinent so long as the rasterization is software-only.

>z64gl displays the portraits ok at 640x480, 800x600, 1024x768.

z64gl IIRC uses a limited amount of GLSL for better texel scaling.  Well, maybe.  Too lazy to verify.

I recommend setting 440x330 in the z64gl.conf configuration file.
(Actually it's more like ~440x327 or so, due to the active video subset taken after VI_ORIGIN_REG.)

Also, play with toggling `lowres=0` to `lowres=1`.  Erm...except in purplemarshmallow's latest commits this setting got renamed to some other name, which makes setting it in the unofficial z64gl builds confusing.  Nevertheless, if you set lowres=1 (or whatever it's named now) you will get the similar type of thing as Glide64 set to point-sampled, to help notice texture coordinate problems like the ones you captured.

>OpenGL 4.0 is VERY slow.

Absolutely because of beta-quality driver implementation on Intel's part.

That being said, it's worth noting your card is new enough for 4.0 testing to even be available at all.  OpenGL 1.2 appears to be the fastest for your card's tests (based on your results pasted) because a) it supports fixed-function, client-side vertex arrays b) it supports BGRA channel endianness for x86 processors running Windows, for faster server-side memory speed boosts, c) Intel hasn't taken the time to properly implement server-side vertex arrays and shader program optimizations, or clearly OpenGL 2.0 would be way faster than your results with 1.2.

>GDI Generic (No Acceleration). Only 1.1 and 1.2 passed the tests, both with 9 FPS.

That's expected, on any card.

GDI Generic just refers to Microsoft's internal `opengl32.dll` library, with no ICD accelerator loaded from your video hardware's manufacturer.  It's really just pure software-rendering mode by Microsoft's GDI pixel-by-pixel plotter.  In this case opengl is like Glide64:  it needs a wrapper so runs on top of crappy rendering.

And the limit is indeed OpenGL 1.1 without any drivers running on top of opengl32.dll, with one or two extensions from GL 1.2 (chiefly GL_EXT_bgra) which I guess is why it was able to run that test for you.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
