### ISSUE TITLE
[RSP] S.C.A.R.S. incorrect grid

### ISSUE THREAD

**Issue by purplemarshmallow** [project64/project64#1183]
edit: using angrylion's plugin

The blue grid is incorrect and flickering with the default RSP plugin (recompiler). Correct with PJ64's RSP interpreter

incorrect:
![1](https://cloud.githubusercontent.com/assets/7283660/17856968/3c45f472-6880-11e6-9fde-bf3cf71a8578.jpg)

correct:
![2](https://cloud.githubusercontent.com/assets/7283660/17857056/950b12cc-6880-11e6-9f2f-5f93fcec9cfe.jpg)

Savestate:
[S.C.A.R.S. (U).pj.zip](https://github.com/project64/project64/files/430282/S.C.A.R.S.U.pj.zip)

**Comment by Frank-74** [comment]
Using Jabo 1.7 in LLE, is even worse effect.  Setting CPU core to Interpreter does nothing to fix it.  But using cxd4's Static Interpreter RSP with CPU core Interpreter does fix it.

**Comment by cxd4** [comment]
You know dynamic recompilers are purposeless when they persistently find wrong results anyway.

When are we going to stop dicking around with x86 dynarecs and write a clean, static recompiler?
I WANT MY MONEY BACK NOW DADGUMMIT!!

**Comment by Frank-74** [comment]
Actually something went wrong with using the Static Interpreter.  Switching between PJ64 RSP and Static Interpreter.  It appears to have been reading a different rsp_conf.bin in another folder which was set to use HLE graphics.  So when I switched to Static Interpreter, it appeared to be fixed because it was running in HLE.

LLE is broke with both RSP's and Jabo's D3D8 1.7 it seems.

**Comment by Frank-74** [comment]
Still broke with Jabo's LLE here.  The floor is corrupted worse now,
![s c a r s u snap0000](https://cloud.githubusercontent.com/assets/11056843/17956850/be22affc-6a84-11e6-8036-95a4ad67bfb0.jpg)
