### ISSUE TITLE
F4 speed limit off in fullscreen weirdness.

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1203]
Start Goldeneye, go fullscreen, switch off speed limiter with F4.  Nothing appears to happen, speed is still controlled somehow.  Go windowed and VI/s shoot up to 250+.

Music stutters every 3 seconds or so with speed limiter off whilst fullscreen.

Using default plugins and settings except counter factor set to 1.

**Comment by Frank-74** [comment]
Intel 3D vsync setting, is set to application controlled.  The only other option I have is driver setting, which forces it on.

**Comment by Frank-74** [comment]
Closing, nothing to do with PJ64.

**Comment by zpunout** [comment]
I have a similar issue when playing Mario Kart 64 with double temporal resolution enabled in the cheats. (see http://tasvideos.org/GameResources/N64/MarioKart64/Patches.html ) Previously in Windows XP/Vista/7, pressing F4 while in full screen mode would increase the frame rate up from 30fps to 60fps and run smoothly. (In windowed mode, it would run at like some ridiculous speed like 400fps).
Since the update from Windows 7 to Windows 10, the full screen frame rate isn't capped at the screen refresh rate anymore but rather at around the ridiculous  400fps mark. I am aware of controlling the emulator's speed with the plus + and minus - keys but it doesn't quite run smoothly at double emulation speed because the timing is slightly different to the screen's refresh rate. The question I have is: Is there some way to restore the F4 method to work in Windows 10 like it used to in previous versions of Windows?
