### ISSUE TITLE
Black Screen On Android

### ISSUE THREAD

**Issue by VirtuaroidPilot** [project64/project64#1225]
When loading up a game, the digital control pad pops up like normal, but the screen is black with only very laggy audio in the background. Running on a Matsunichi M97 which I believe is dual core which should be enough to run Super Mario 64 at the very least.

**Comment by project64** [comment]
the current speed should be better with the version in source .. I assume you have installed the version on the app store instead of a compiled version from the source?

Why you just get a black screen I am not sure and that needs to be worked out.

Glide64 is very similar to the ones used by the other n64 emus on android, the actually java gl window is very different.

If you use glide64 on a different emu does it work correctly for you?

**Comment by VirtuaroidPilot** [comment]
Glide 64 works fine on other emus with varying degrees of graphical glitchyness. On other emus whether or not I get a black screen depends on the frame buffer settings I choose.

**Comment by VirtuaroidPilot** [comment]
Where can I find the version compiled from source? Is it an apk file? I'm sorry for the double post, I can't seem to find the edit post button.

**Comment by Frank-74** [comment]
> Where can I find the version compiled from source? Is it an apk file? I'm sorry for the double post, I can't seem to find the edit post button.

The current playstore version is up to date with the source.  Just update or download from playstore.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
