### ISSUE TITLE
Make the donation request dialog more intuitive

### ISSUE THREAD

**Issue by Fanatic-64** [project64/project64#1244]
There are a few things that I think can be improved in this dialog:

(Note: I am _NOT_ asking to remove it.)

-1. The wording is rather ambiguous. The text only talks about "supporting" Project64 without specifying what type of support is being requested. Some people may believe you're asking for Facebook likes or something like that. Also, nowhere does it mention that you can remove the dialog by donating. It only says "Enter notification code" without explaining what this does (shouldn't it at least be called a "verification code" or "product key"?).

(Also, have all PJ64 1.7 donors been emailed a code?)

IMO, the dialog should preface by saying that it takes time and money to develop PJ64, etc, and clearly state that you can support the project and remove the dialog by donating $20 USD (or is it AUD?) to the developer.

-2. Once 10 uses have been exceeded and the emulator starts making you wait, it is unclear how long you have to wait or if you will be able to even use the emulator at all, specially since the wait is rather long. When I first encountered the Continue button greyed out and it didn't enable after about 30 seconds, I figured I wouldn't be able to use the emulator anymore without entering a donation code, so I opened the Project64.cfg file suspecting the lockout to be simple setting, and sure enough, it was. It was only when I went back to close the emu that I noticed the Continue button had been enabled, so I closed and reopened the emu and counted how long it took for the Continue button to be enabled, and it was about 40 seconds.

You should add a countdown to the Continue button to make it clear that, and how long, you have to wait to continue. A text on the greyed out button that says "Please Wait 40... 39... 38... 37... 36..." and so on before "Continue" appears.

(Also, to make it harder to bypass the dialog by modifying Project64.cfg, I would recommend storing the Run Count= setting somewhere deep in the registry and with an ambiguous name.)

Finally, as minor suggestions I would recommend adding a Cancel button to the donation dialog to be able to close the emu instead of waiting, and adding a "Donate... (Alt+D)" option to the Help menu for easy access to the donation page in case the user decides they want to donate during gameplay (say, if they were impressed by how well the emulator works).

**Comment by loganmc10** [comment]
> Also, to make it harder to bypass the dialog by modifying Project64.cfg, I would recommend storing the Run Count= setting somewhere deep in the registry and with an ambiguous name.

Don't play game like this, if you start doing stuff like that with an open source project like this, somebody is just going to fork the project, remove that crap, and start releasing the "unofficial version that everyone uses" somewhere else.

If people don't want to donate, you can't force them, you've got to live with that.

**Comment by oddMLan** [comment]
Don't quote me on this, but I think Zilmar is well aware that is easy to get around the donation nag by modifying the cfg file. End users normally wouldn't be bothered to mess around with cfg files, and advanced users who don't want to donate can just modify the run count. I agree with Logan, you can't force users to donate, that's why the option to modify the run count it's there.

**Comment by project64** [comment]
I am happy to improve it, my focus has been trying to get android to work better at the moment. I modeled it after how mirc works.

I tried to make it that it was effective, but if any one with some tech skills did not want to pay then it was easy to get around. Always seem to be comments in reddit mentioning it.

There is no code generation, it is just a fixed code which is in clear text in the source code to.

**Comment by Frank-74** [comment]
If you want a more secure option, I did make something that uses an email address to encrypt the 'thank you blah blah message', to get a unique code based on an email address.  It uses the thank you message (or any message you decide) to encrypt the email address.  I hacked something from when I was working on the game Uplink by Introversion.  I made some Redshirt decryption/encryption console apps to edit the save files.

**Comment by project64** [comment]
it is insecure on purpose

**Comment by LegendOfDragoon** [comment]
I think Fanatic made some good points. I agree that there should be a timer displayed so that the user knows how long they have to wait. I also agree that it's too easy to bypass. Imo, it almost defeats the purpose of the nag screen, if it's that easy to bypass. I'd much rather make it harder to bypass while shortening the wait time. I've honestly never encountered a 30 second nag screen before.

>if you start doing stuff like that with an open source project like this, somebody is just going to fork the project, remove that crap, and start releasing the "unofficial version that everyone uses" somewhere else.

Weren't you already planning on forking it anyway :smile: ?

**Comment by loganmc10** [comment]
> Weren't you already planning on forking it anyway :smile: ?

I looked into it but I lost the motivation lol. The differences in compatibility between this and mupen64plus are small enough that I can live with it.

**Comment by cxd4** [comment]
>I've honestly never encountered a 30 second nag screen before.

I was probably supposed to, but WINE seems to not implement whatever part of the Windows API Project64 is using to nag so I guess I never get nagged.

**Comment by Fanatic-64** [comment]
My suggestion would be making it hard to bypass on the released build, but easy if you download the source and/or build it yourself (maybe make it so that the dialog is enabled only in Release builds but not in Debug builds?).

And as another suggestion, maybe you could offer donors to have their name engraved in their copy of PJ64 (title bar, Help menu and maybe About dialog) as an additional perk, like in the 1.7 betas.

**Comment by project64** [comment]
the thing with the 1.7 beta version meant I need to modify the binary on the fly ... it is not so easy to do ..

**Comment by SigmaVirus** [comment]
I'm just gonna get this out of my system and leave quietly afterwards.

First of all I'm surprised if Project64 still have a user base left since all Adware scandals and now there's Ransomware like nag screens in Project64 popping up (yeah I'm late to the party, been using GLupeN64)

I have been gone for quite some time here and have not used Project64 since then and when I finally want to give it a honest chance again after all these months I just can't.

Project64 is open source, nobody have to pay for this software but with everything that's going on and have been going on it feels like it's all about money and greed.
"Pay up bitch or else we take your computer as hostage"
Gangsters, mobsters and thugs do these kind of things and here I thought Project64 were honest...

What you are doing is a dick move, either remove this altogether or make it closed source again so people are forced to buy it instead.

And seriously, way to go to make the Notification code public in the source code and a way around it with the Run count.
Even end users with IQ over 30 could figure that out eventually.

**Comment by oddMLan** [comment]
http://cdn3.gurl.com/wp-content/uploads/2017/02/white-guy-blinking-gif.gif

**Comment by cxd4** [comment]
>What you are doing is a dick move, either remove this altogether or make it closed source again so people are forced to buy it instead.

>And seriously, way to go to make the Notification code public in the source code and a way around it with the Run count.  Even end users with IQ over 30 could figure that out eventually.

LOL.  That really was a dick move.  Way to go zilmar on not forcing everyone to pay.

**Comment by crazyboy92** [comment]
Here's a better idea......some one should make a fork of this PJ64 based on 1.7.0.50 but keep windows XP support

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
