### ISSUE TITLE
Ability to hide Project64 window

### ISSUE THREAD

**Issue by bboydj** [project64/project64#1279]
Great work folks, and this since ages - loads of appreciation!

Is there a way to hide the UI window when launching roms by a script? I believe another user asked whether specific bars could be hidden but I am really talking about the whole dialog?

In my use case, PJ64 is embedded into a full-screen cabinet and is supposed to not expose that it is running on known operating systems.

Thank you!
bboydj

**Comment by project64** [comment]
there is an option to launch in to full screen on starting a game, does that do what you want?

**Comment by bboydj** [comment]
Not exactly - it does start the game in fullscreen, but only after it showed the project64 window visible.
I want the game to run as if there was no window.

**Comment by cxd4** [comment]
You would probably have to script launching Project64 in full-screen from the command line, which I think isn't implemented yet.  Some other emulators do support this.

There's also the `-nogui` argument when launching Mupen64.

**Comment by project64** [comment]
so it does what you want, except it temporary shows a screen first?

if that is the case I may be able to reduce the amount of time it is there for .. I am not sure if I can get rid of it completely tho

**Comment by bboydj** [comment]
Thanks for your answers!

@project64: yes that might be an option. But even when running a very small game like monopoly and from an SSD it shows quite some time. could it be minimized or skinned/covered/go to background?

@cxd4: I had a look at mupen64 and the precompiled version from 2005 seems to require to be compiled with that option. And then there is a 2016 x64 codebase not sure it even supports that.

**Comment by cxd4** [comment]
No, you just pass `-nogui` to mupen64.exe.  No need to compile from source.

It may be different on Linux.  I've never tried passing `-nogui` to the Linux port before--primarily because there are two separate modules that get built:  `mupen64` and `mupen64_nogui`.  So it would be `mupen64_nogui -g path/to/gfx-plugin -a path/to/sound-plugin [...] --fullscreen path/to/ROM`.

In fact you could run this without any windowing framework launched, unlike Windows which can't run without loading the graphical windowing framework (because using an operating system isn't possible without having...WINDOWS!).  So if, as you say, "not expose that it is running on known operating systems" is your goal, you could gain a lot of flexibility into setting up a kiosk that hides any details of what OS is running just by switching away from Windows.

**Comment by bboydj** [comment]
Thanks again @cxd4: your comments led me now to following findings:
- mupen64.exe accepts -nogui, but doesnt do more than showing a small window. I might have been missing something else.
- found mupen64plus-ui-console which is exactly what I've been looking for: a cmdline tool that accepts various options like --fullscreen and --noosd and even specifying --resolution XbyY
- however, mupen64plus-ui-console is a bit cryptic to configure in terms of inputs, so used m64py which is a GUI frontend to do just this. 
- plus, I was lucky enough to find that there is even a rocket launcher module available, so further abstraction into a multi-console system is possible if needed (there's also a module for project64 of course).

Anyway, in the above combination it does exactly what I wanted, although I regret it kinda moved me away from project64. But then, maybe less work for @project64 ;o)

Thanks again for your kind support!

**Comment by cxd4** [comment]
No problem.

I have no idea about Mupen64Plus, as I've never really used it or had any reason to.  You should be able to pull it off with the actual Mupen64.  Yes, `-nogui` all by its lonely self still shows a (minimalist) window, but if you add `-fullscreen` it should go to full screen without showing the window.

It is also theoretically possible to construct a borderless window, showing the emulation screen with no Win32 or X11 elements around it...but, that's kind of...should I say annoying to work with?  It would hide the operating-system-specific windowing elements like you requested, but you would still see Windows Explorer, the Start menu or whatever you have open in the background, so it would still not be a convincing kiosk and would still have OS-specific elements visible.  I'm not really sure how you could solve that issue without going full-screen, at least on Windows anyway.

>Anyway, in the above combination it does exactly what I wanted, although I regret it kinda moved me away from project64. But then, maybe less work for @project64 ;o)

It should be implemented in Project64, too.

I'm mostly referring to Mupen64 as an example of what any emulator can do.  In time, you should be able to do the same with Project64.  It would probably not be implemented by zilmar though since he's working on the Android interface while I was supposed to do the command-line, Unix and other primitive style platform-agnostic interfaces.

**Comment by bboydj** [comment]
Thanks @cxd4 and sorry for me assuming that zilmar is the one to implement, your clarifications helped a lot. Also, thank you for following up on this thread and use case - fullscreen is perfectly fine by me if this is the feasible solution.

So today I tried the combo of -nogui and -fullscreen (and also the documented -f) with the 2005 v0.5.1 Windows version of mupen64 but the window would not go away.

Anyway, I am happy to hear that you are planning to implement this functionality and cannot await to try and validate should you want someone to review.

Cheers!

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
