### ISSUE TITLE
Save Files *Internal Name* Bad Idea

### ISSUE THREAD

**Issue by CanadianJeff** [project64/project64#1304]
using the internal name as a save file OH MY GOD PLEASE!!!!!!!!!!

![](http://i.imgur.com/trfEP5x.png)

if I have 4 copy of zelda OOT I want a unique save file for each

![](http://i.imgur.com/b1SJxk9.png)

**Comment by project64** [comment]
yes, but can not change with out lots of issues with backward compatibility ...

there is an option to have saves separated in to a folder, but it is off by default.

**Comment by colejohnson66** [comment]
What do you propose? There's not really much that can be done. Dolphin uses the 6 character ID of a game because that avoids naming conflicts. I guess you could add a hash of the ROM to the filename. Do the ROMS contain anything unique?

**Comment by cxd4** [comment]
>Also, On some ROMS (at least for Zelda: Majora's Mask (both the original and the one inside the GC Collector's Edition GCM/ISO) and DK64), there appears to be a 4 character identifier at 0x3B. For DK64, it's NDOE, and on both Zelda's it's NZSE.

And, there is a 5th byte after that, at header[0x3F], indicating part of the mask ROM version, which GoodN64 inaccurately uses as "V1.0", etc.  I wouldn't bother with GoodN64 "friendly" names honestly.

So there is more than one issue here.

* Do I want my save file to be universal to all ROM versions (at the risk of save structure breakage)?
* Do I want my save file to be universal to all USA versions of the ROM (v1.0, v1.1 etc.) but not PAL?
* Do I want my save file to be universal to non-modded and non-hacked ROMs with different CRCs?
* Do I want to have a unique save file for every single hacked or good version of the game and have to go through the trouble of copying, pasting and renaming to duplicate file names in Windows Explorer every time I want to test out my saved progress on an alternate version of the ROM?

One could implement flexibility to all of those things by having support for dynamic save file names.

Something like...
```
if (ROM is Mario USA v1.1) {
    if exist (save/NSME1.eep) {
        load (U) v1.1 EEP settings
    } else if exist (save/NSME.eep) {
        load default USA settings
    } else if exist (save/NSM.eep) {
        load default Mario64 settings, region-independent defaults
    } else if exist (save/SM.eep) {
        load default settings for Mario, independent of manufacturer code
}
```

**Comment by cxd4** [comment]
Yes, though, Internal Name is a bad idea.  That much I know for sure.

But not so much for the reason in the OP, imo.  I personally like having the same save file being recycled by different ROM versions since it makes cross-region testing with features in other versions of the ROM more convenient, and renaming files in Windows Explorer to "copy" new saved changes to a save file is a PITA.

That part of the ROM header doesn't exist except in commercial images branded by Nintendo.  Many ROMs don't even have an "internal ROM name" in the header.  In fact, usually the second 16-byte half of the 32-byte ROM header is just a bunch of null bytes.  They are also not necessarily composed of ASCII bytes and can have characters within the kana set of the Japanese alphabet--not wise choices for file names.

**Comment by wfowler1** [comment]
> I guess you could add a hash of the ROM to the filename.

This is actually exactly what the "Unique Game Save Directory" option does. Personally I use it and I have no problems. The save file naming is incompatible with other emulators anyway (or at least Mupen, which uses the GoodName for some really bad reason), though the files themselves are compatible.
[image](https://user-images.githubusercontent.com/5846565/29493403-32eb30dc-8552-11e7-8e3e-ef349abe45e7.png)

**Comment by AmbientMalice** [comment]
>I personally like having the same save file being recycled by different ROM versions since it makes cross-region testing with features in other versions of the ROM more convenient.

Which is a great idea on paper except a number of N64 games wipe the save file if you do that. I mean, seriously. You should NEVER boot different regions of the same game in Project 64. Ever. Especially with Factor 5 games.

**Comment by cxd4** [comment]
It seems to work quite often more than you seem to expect.

Almost every game that I've reversed the save chip/mempak formats for--or even just transferring the save to test on features in a different region of the game--has worked just fine.  One exception is commonly the Japanese versions of games, since the save file format is more likely to change due to storing names and text with added support for the kana character sets (which the English and PAL versions usually like to delete).  Especially Zelda Majora's Mask, what with owl statues not being supported and File 3 being deleted upon adding them to USA/PAL.

But otherwise you can pretty much always count on renaming the save file to get it to load in other game regions.  This makes everything way more convenient because I need to test other versions of games, sometimes--they will tend to have newer or changed features or just more things to test actually.

The only way that a N64 game will "wipe the save file if you do that" is if the EEPROM version inside of the mask ROM version (stored partly in the ROM header, at header[0x3F]) were to change.  Again, this is why the header makes a far better standard for recognizing save files to import than the internal ROM name.

You could even use the CRC in the ROM header like 1964 does to save the file names if you want to be totally specific and eliminate the possibility of reusing the save file for any other ROM versions, but that's stupid to be honest.  So somebody does a ROM hack to make Mario's left ear purple, and I have to hit F2 in Windows Explorer, rename the old file then rename the new file around all because I want my save data to work for stupid ROM hacks that don't even change the EEPROM file format?  Same thing with other ROM regions/translations to be honest.

**Comment by colejohnson66** [comment]
What about a CRC of the header? Then changing the code, sprites, etc. wouldn't change the filename.

**Comment by project64** [comment]
the crc of the first X number of bytes is stored in the header and used during boot. We use those values directly to save time to not have to crc and there is still collisions.  MD5 the whole file is the safest, but it is slow cause you have to load the whole file to memory. Not a problem for the running game as that is going to happen any way, but for the rest like in the games listing.

There is already an option to have each save in its own md5 dir, just not on by default for backwards compatibility ... tho maybe I should have it on for default going forward

**Comment by cxd4** [comment]
@project64 I read him as talking about a solution that would cause the same save file to be reused in another version of the ROM that changed only sprites, graphics, minor code changes etc. (instead of anything EEPROM-related).  Naming the save files after an MD5 hash of the whole file is the opposite of what we want.

>What about a CRC of the header? Then changing the code, sprites, etc. wouldn't change the filename.

Doing a CRC or checksum of some kind of the 32-byte header seems kind of unnecessary.

For one thing, the header contains a checksum of the first part of ROM (like @project64 said), so doing a CRC on the entire header could easily change the file name if only code, sprites, etc. were changed.

For another, I think the only part of the entire ROM header that is relevant to indicate whether save structure may have changed (regardless of insignificant changes to ROM outside of that which also would change the CRC stored in the header, or the internal ROM name) would be the 5-byte string of bytes at header[0x3B] to header[0x3F].

**Comment by cxd4** [comment]
I like the idea of naming save files NSMEXX.eep (where `XX` is the hexadecimal for header[0x3F] or the ROM version e.g. 1.0, 1.1 in Good Tools misinterpretations...).  Project64 could default to that for maximized global prevention of the case where games can erase/invalidate the entire save file due to loading it on a different region or version of the ROM, while people like myself who personally prefer to reuse the same save file in other ROM versions can just rename it from NSME00.eep to NSM.eep and Project64 would load that for all versions of Mario (in the absence of more specific, localized file names using the full NSM???.eep specification existing in simultaneity to the global file name).

One problem left unattended is demos or homebrew ROMs.  Commonly these won't set the ROM header beyond basic things like the checksum and maybe (but not necessarily) some made-up internal ROM name (a field used by Nintendo's registration process and not just to have a secret cool "inside name" for demos).  So a lot of NULL bytes...might have to use the CRC or something to name the file then.  But that's only if a N64 homebrew/demo actually has some implementation of the save chip for some reason which I haven't noticed yet.
