### ISSUE TITLE
WDC/Stunr Racer runnning in HLE

### ISSUE THREAD

**Issue by olivieryuyu** [project64/project64#1322]
Heya

I would like to get those games running in HLE.

The issue is that I could try to do the reverse engineering of the game (I already did such a task successfully for some games) but for that I would need to get sure that at least the emulator can run in HLE the game.

Till today only LLE support was implemented.

Can it be done for HLE?

Thanks

Olivieryuyu

**Comment by LegendOfDragoon** [comment]
Only possible issue is that PJ64's RSP doesn't support yielding for HLE. Other than that, it should work.

**Comment by AmbientMalice** [comment]
Would it be difficult to work around that problem?

**Comment by loganmc10** [comment]
A good test for this would be Gauntlet Legends, it can be run using HLE graphics, but needs RSP yielding, so if you can get Gauntlet Legends to work in HLE, you would be able to get WDC/Stunt Racer working as well if you had a working microcode implementation.

I can't speak for Project64's RSP, but in HatCat's RSP, the magic happens here:

https://github.com/cxd4/rsp/blob/master/su.c#L65-L68

Basically it increments ```MFC0_count[rt]``` every time that code block happens, and if it gets to 16 (I think Project64 uses 10 by settting ```RSP-Mfc0Count=10``` in the RDB), then it exits the RSP loop with SP_STATUS_HALT set to 0. This gives control back to the CPU, and having SP_STATUS_HALT set to 0 is a sort of "special signal" to the CPU that the RSP task needs to be resumed.

This only seems to happen in LLE mode, I'm don't know much about how the RSP works, but in HLE mode, a lot of the RSP work is handed over to the graphics plugin, so it's possible that this is something that may have to be done in the graphics plugin, although I don't know how the graphics plugin would set SP_STATUS_HALT to 0, since it is typically the RSP plugin that sets the value of SP_STATUS_HALT

**Comment by LegendOfDragoon** [comment]
To be honest WDC should be the easiest game to HLE, aside from maybe random Demos or something. There's only 1 set of Ucode data which all fits in IMEM. Good luck though :smile: . I'm on vacation so I do finally have some free time, if you need help :smile: .

>Would it be difficult to work around that problem? Even temporarily?

Not at all. It might be difficult to do so with the current spec (assuming it's possible, it requires some creativity), but it's easy to modify and improve the plugin spec. I'm sure zilmar doesn't really care about backwards compatibility in the plugin spec, so it shouldn't be a problem.

>A good test for this would be Gauntlet Legends, it can be run using HLE graphics, but needs RSP yielding, so 

Actually Gauntlet is a bit trickier to implement for yielding. In WDC, it has a specific microcode function that infinite loops while waiting to receive a yield signal from cpu, while Gauntlet uses standard F3DEX2 iirc. I'd much rather just HLE that yielding function, since you only need to yield during that infinite loop. I don't even bother with the mfc0 count variable anymore, except for gauntlet.

When HLEing the yield function, you can play WDC on older versions of PJ64 (that's how Angrylion got it to work).

**Comment by loganmc10** [comment]
> I don't even bother with the mfc0 count variable anymore, except for gauntlet.

I'm not really sure what you mean by that, if you remove ```RSP-Mfc0Count=10``` from the RDB file then WDC no longer boots, that's what makes the yielding happen.

**Comment by LegendOfDragoon** [comment]
>I'm not really sure what you mean by that, if you remove RSP-Mfc0Count=10 from the RDB file then WDC no longer boots, that's what makes the yielding happen.

I HLE'd the specific function to get a performance boost. Less yielding resulted in better performance. No one seemed interested so I never made a PR.

**Comment by olivieryuyu** [comment]
Ucode can set parameters in COP0 so potentially it can halt the cpu till further notice from rsp. Current plugin specs doesn t allow the emulation of thisI thin.

**Comment by cxd4** [comment]
The yield debate is pretty moot since it's not relevant to HLE.  You should sync with the CPU in LLE.

Let's try to be logical though.  The "issue" here is that the microcodes for those games are based entirely on custom functions.  There isn't really anything else keeping them from HLE that didn't stop several other plugins for a game like _Gauntlet Legends_ from getting playability, which is even more complicated and dynamic in its checking for CPU synchronicity than the entirely custom microcode games by Boss Game Studios.  (Although the latter generate an RSP interrupt from within the plugin, unlike _Gauntlet Legends_, which adds interference.)

It was only a matter of time before angrylion also got _Gauntlet Legends_ to wrest its way out of the sync loop in his RSP plugin, even though that was not in the version he released with source.  It's actually easier because you don't have to emulate the interrupt that the other games do, but it's harder because of the jungle of IMEM offsets you have to check for.

As long as we're not Shunyuan though I wouldn't call that "HLE" since that's just evading the fixation of trying to get the games to work in LLE with a limited plugin architecture.  As has been proven by several plugins, this "yield" is not necessary to be done to get the games work in HLE, only to keep the machine state accurate during LLE.

**Comment by olivieryuyu** [comment]
Please understand my point: I cannot start doing the reverse engineering if I am not even sure that the game will run in HLE. What I mean here that there should be sounds even if we skip the display list. This is not the case

**Comment by Frank-74** [comment]
WDC sends two buffers to the AI prior to starting the audio loop.  Audio works correctly in Azimer's new audio code since around February.

**Comment by olivieryuyu** [comment]
ok but do you have audio when you send the display list to a HLE graphics plugin? You can use for instance Rice, there will be around no gfx but I should have sound. Is it the case?

**Comment by loganmc10** [comment]
>  What's weird about these BOSS games is the Alist is always at 0%.

The audio is processed by the CPU, not the RSP, so HLE or LLE audio won't make a difference, it's never felt with by the RSP

**Comment by Frank-74** [comment]
WDC doesn't get past the first splash screen with RiceVideo6.1.1.beta10 when enabling HLE here.

**Comment by LegendOfDragoon** [comment]
>Please understand my point: I cannot start doing the reverse engineering if I am not even sure that the game will run in HLE. What I mean here that there should be sounds even if we skip the display list. This is not the case

If you can successfully skip/handle yielding and interrupts, I don't see any other problems. I remember when I had a regression in RSP, it messed the sound up. So maybe it's true that you'd get no sound if you skip dlist. Why is that an issue though? Just implement the code in HLE and it should work :smile: .

**Comment by olivieryuyu** [comment]
handle yielding and interrupts? in which way? You keep insisting it will work and I don't see how.

**Comment by LegendOfDragoon** [comment]
>handle yielding and interrupts? in which way?

My idea is to yield and do interrupts similar to how LLE RSP handles that. Basically yield to the cpu, then resume after the emulator calls runRSP again. This would likely require a modified RSP since current ones don't give HLE plugins the option to yield.

Other people here suggest that yielding is not necessary at all. Maybe they are right, but idk :smile: . If i were to do this myself, I'd try implementing yielding first, then later try to find a way to skip it.

Anyway man, no pressure. If you feel that you should wait until someone has figured out how to solve some of these potential issues, then you should wait. There are other games that need work on HLE, so you should probably do the ones you know you're capable of improving/implementing first.

**Comment by cxd4** [comment]
No, other people did not suggest that.  They suggested that it's a part of LLE, so it would be necessary for hardware emulation, not software simulation.

**Comment by LegendOfDragoon** [comment]
I guess i should have clarified :smile: . I knew y'all were referring to HLE with the yield skippin. Anyway, I edited previous comment to clarify :smile: .

**Comment by cxd4** [comment]
Maybe with something like HLE graphics inside the RSP plugin you could still need to emulate yielding in cases due to the plugin system (because the RDP might be waiting on the CPU before the RSP breaks the sync loop), but entirely doing an actual HLE plugin like with graphics should not even involve caring about that.

Although it is true that _Gauntlet Legends_ works in most HLE plugins only because they hacked around the yield, but then again the point of HLE was never to emulate the system, only the software.

**Comment by cxd4** [comment]
...and it is easier to hack around the yield in a functional HLE of the micro-code in games like those, rather than instruction-by-instruction layout from RSP IMEM (which is like Shunyuan HLE and would need yield).

Which was the original starting point of this issue to begin with:

The issue is HLE'ing the ucodes so that you can examine the HLE yield, not worrying about HLE yields.

**Comment by LegendOfDragoon** [comment]
I decided to debug WDC to refresh my memory. The only functions I currently yield in are at 0x1AC and 0xFBC. 0xFBC is where it does the interrupt too, I wonder what happens if you just skip that function :smile: . Both functions contain infinite loops.

**Comment by olivieryuyu** [comment]
I checked 0x1AC. Yes it can lead to an infinite loop. The code is waiting that the SP status changes from 0x840 to something else. The microcode will not change this value by itself I think. So would it be the CPU? (osSpSetStatus)

I do not think that the plugin can solve the issue by itself at current stage (or please explain me how). Skipping the function will not help, this is what a dummy plugin like CFB does and it get stuck.

The only manner to get out of this is either to get the CPU changing the SP status, which does not seems to happen nowadays neither in LLE (current fix seems a hack) or HLE or to allow the plugin to change the SP status when getting to this infinite loop (command would be able to force the sp status).

**Comment by LegendOfDragoon** [comment]
> So would it be the CPU? 

Yes. I assume the developers' intention was to allow the CPU to catch up to the RSP if it's behind, since RSP and CPU run in parallel on the console. Whether yielding is necessary or not for HLE, who knows :smile: . You'd have to do some analysis on whether yielding makes any significant difference on the results. I think it might, because when i made the RSP yield more often, I ended up reaching code that previously didn't execute. Then again, i didn't really check to see if that code actually did anything significant.

One odd thing I noticed was that it was often calling the function 0x7F4 repeatedly. Seems like a complete waste of cycles lol. It makes me think something might be wrong. Although I will need to double check to make sure there's absolutely no point in consecutively calling that function. If it's a waste, I wonder how much of a speedup I'll get from skipping consecutive calls :smile: .

>which does not seems to happen nowadays neither in LLE (current fix seems a hack)

The current method allows the cpu to resume until it modifies the SP status register to the desired value.

Anyway, I think it's better to handle yielding last. Once the other code is done, you will have more opportunity to figure out how yielding works.

>Skipping the function will not help, this is what a dummy plugin like CFB does and it get stuck.

How can you tell it's getting stuck? Anyway, WDC is one of those games that don't always end the DList with syncFull command. That's why opening the  configure graphics menu crashes (without the pausing workaround). This means that you shouldn't always fire a DP interrupt after the end of every DList. Instead it should be conditionally done.

**Comment by cxd4** [comment]
The dummy CFB plugin merely takes responsibility for drawing what the CPU (and, if running in LLE, the RSP) draws to the frame buffer.  It's not able to skip the function if the RSP runs in LLE because the RSP plugin is supposed to handle the function in that mode and not the graphics plugin.

>0xFBC is where it does the interrupt too, I wonder what happens if you just skip that function 😄 .

Well I never said the interrupt should be skipped, but when it comes to HLE:  If you go far enough, you could skip just about anything.  Most of these N64 games are so poorly optimized (not just coded for a different SIMD processor but compiled with an ancient version of GCC used by Nintendo) that the amount of skipping of unoptimized code we do on the emulator's side seems pretty moot anyway when you could just port the games from N64 to PC.

**Comment by olivieryuyu** [comment]
@project64 

Zilmar, please can you help out?

**Comment by LegendOfDragoon** [comment]
@olivieryuyu don't worry about yielding :smile: . Once the other functions are implemented, someone else can take care of it for you :smile: .

>Most of these N64 games are so poorly optimized 

I know right! It honestly hurts my brain sometimes, when I try to analyze some of the code in various games :smile: .

**Comment by cxd4** [comment]
Rename Shunyuan's audio.dll to Shunyuan's Audio (J) [!].z64 and write an open-source emulator for it.

>don't worry about yielding 😄 . Once the other functions are implemented, someone else can take care of it for you 😄 .

That's basically the main thing I was trying to convey.  The yield issue shouldn't affect the issue of getting the microcode's HLE'd although it will need to be analyzed as a final step probably, but I meant to say it shouldn't be a distraction.

**Comment by olivieryuyu** [comment]
Deeply sorry but even if we do reverse the ucode, we won't be able to run it. Doing a HLE implementation means that you can do tests and see if your code works or not.

**Comment by LegendOfDragoon** [comment]
>Deeply sorry but even if we do reverse the ucode, we won't be able to run it.

Why not? We already know how to get the game working in LLE, which means HLE should be no problem :smile: .

**Comment by olivieryuyu** [comment]
closing ticket. I guess it won't be ever emulated in HLE then.

**Comment by AmbientMalice** [comment]
>closing ticket. I guess it won't be ever emulated in HLE then.

I think you might be misunderstanding what he's saying.

**Comment by loganmc10** [comment]
You guys say "don't worry about it, someone will figure it out later", but look at Gauntlet Legends. It has a similar problem and can run in HLE, yet no one has figured it out in all these years. I think it's fair to want to know that the yielding problem can be solved before he spends all that time working on the microcode

**Comment by LegendOfDragoon** [comment]
>It has a similar problem and can run in HLE, yet no one has figured it out in all these years.

What problem? Seems fine in Glide64. 

>I think it's fair to want to know that the yielding problem can be solved before he spends all that time working on the microcode

Yielding has already been explained. Getting it to work is not an issue. The only thing to solve, is figuring out the best way to handle it in HLE.

Anyway, it's up to him what he wants to do with his time. If yielding is his only concern, then he should trust that others will help him with that and continue to HLE the rest of the code :smile: . Anyone with a good understanding of the RSP and some HLE experience, could HLE this game within 1 day, if they don't obsess over optimizations. Nothing to worry about :smile: .

**Comment by loganmc10** [comment]
> What problem? Seems fine in Glide64.

I can't even get the game to go past the title screen in PJ64 2.3 and the included Glide64 version. With Jabo the game flickers, I'm guessing Glide64 would do the same thing if it worked, because yielding isn't properly implemented...

**Comment by olivieryuyu** [comment]
@LegendOfDragoon : 1 day to reverse engineering a ucode? Well I guess that compared to your outstanding skills, I cannot compete then. 

Issue closed once and for all, I did raise this issue for a debate but for support.

**Comment by LegendOfDragoon** [comment]
My intention was to encourage by pointing out how simple it is to get an HLE implementation of WDC working. Generally speaking, most of the time spent on implementing HLE will go to optimizations. Simply getting a working implementation, does not take very long.

WDC only has about 1000 assembly instructions, which is why I say it's relatively quick & easy to implement.

>I can't even get the game to go past the title screen in PJ64 2.3 and the included Glide64 version.

That's odd, it seems to work on my end. There does appear to be some flickering though. I'm not sure if it's because of yielding though, because LLE had its own set of problems. Seems like the RDP needs some work on these hardware rendering plugins. Which is one of the main reasons I haven't bothered HLEing graphics much at this point. I'd rather focus on improving RDP at this point. Anyway, I might experiment with yielding to see if that fixes the flickering in Gauntlet with Glide64 in HLE.

How does the game look in GLideN64 LLE? I can't test GLideN64 for a while.

**Comment by oddMLan** [comment]
ITT
Q: "How can I implement the game's yield in HLE or what can I do to skip it altogether"
A: "Try implementing the game in HLE then figure out how to skip it"

**Comment by LegendOfDragoon** [comment]
>Q: "How can I implement the game's yield in HLE or what can I do to skip it altogether"
A: "Try implementing the game in HLE then figure out how to skip it"

I did explain that you could update the plugin spec to support yielding in HLE...

**Comment by LegendOfDragoon** [comment]
I wonder if it's because people don't trust me, or if they just didn't see my post :smile: .
>When you cross out the common factors out of this, the result is:
A: "Try implementing the game in HLE then figure [it] out how to skip it"
Very helpful guise

His main question was "_will it work in HLE?_". I answered how to get it working in my second post.. It is already known how to get the game running in HLE, there's no mystery. I even came up with the great suggestion of letting someone else **take care of yielding**. I have no clue how y'all came to the conclusion that I'm just telling people to just "_figure it out_".
