### ISSUE TITLE
vrcp & others

### ISSUE THREAD

**Issue by olivieryuyu** [project64/project64#1334]
Hello!

Please need help!

Can someone explain me in the simplest way possible the VRCP and VRSQ RSP instructions?

I cannot figure out how it works :(

How for instance can you have the reciprocal of 0x0035 = 0x4200

I am lost :(

Please explain me very plainly the matter, I am not very good in maths I am afraid ...

**Comment by theboy181** [comment]
I asked about these functions with the developer I know. He has an invested his interests in the RSP. He was uncertain about these functions on that level of emulation though. 

I assume this is something to do with Gauntlet?

Have you reached out to CDX4, I'm sure he has some knowledge on these. Angrylion might know have some knowledge as well, but is harder to reach than CDX4.

**Comment by cxd4** [comment]
As integers, 0x4200 is not the reciprocal of 0x0035.

All divides and fractional multiplies operate in floating-point values.  The thing that I do not remember (because of the fact that a small ROM chip caches the results, instead of relying on algorithm) however is whether they are 14.2 etc. format.  If you're confused, well, don't be surprised...looking at C types for `float` and `double` in a hex editor showed you integers, right?  Even though they're FP.

Conceptually, you just need to know that VRCP yields the multiplicative inverse, while VRSQ takes the square root of the multiplicative inverse.  sqrt(1 / x) = 1 / sqrt(x) ... although the function is actually more detailed than that.

The algorithm is not how the hardware literally operates, though, like I said, because of the ROM chip on the RCP filtering the scalar divides.  Conceptually, though, if you ARE interested in how the algorithm works mathematically, I can get back to you on that!  I do not have access to the Linux partition on my computer where I stored my notes and cannot access the files at this time, but you do not need to know it for bit-perfect emulation of the scalar divides.

As far as appending L/H (VRCPL vs. VRCPH and VRSQL vs. VRSQH), it is the same as your question about multiplies you asked me in my RSP repository with VMUDL vs. VMUDH and VMADL vs. VMADH.  Specifying Low/High in two instructions lets you operate in double-precision in single-precision; that's all there is to it.

**Comment by cxd4** [comment]
I would reply to the issue you started on my `rsp` repo, but like I said the mathematical, functional details of the inverse square root are outside the scope of the hardware's actual operation and I will respond to your issue on my repo once I've re-obtained my notes on that.

**Comment by olivieryuyu** [comment]
I have now more or less an idea on how it works now but honestly the maths behind is still a bit obscure.

Let's see we have 

VRCPH 0x0000
VRCPL 0x3F01

How do you compute the sqrt of 0x0000? I get a result of 0x102, which is somehow correct but conceptually it is hard to apprehend for a novice like me.

**Comment by cxd4** [comment]
It would be the square root of the inverse but not the square root its self.

VRSQ(x) is based on the function of sqrt(1 / x) = 1 / sqrt(x).
So VRSQ(0) = sqrt(1 / 0) = 1 / sqrt(0), which by the way happens to be one of the differences between the functional algorithm and what the RCP division ROM chip actually yields due to not actually using the algorithm but a scalar index table.
