### ISSUE TITLE
x64 build doesn't run.

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1349]
I get this error when trying to run the x64 build, I added the x64 build of AziAudio to the Plugin64\Audio folder:

> The application was unable to start correctly (0xc000007b)

I thought the x64 build used to work.  I'm running Windows 8.1 x64.

**Comment by ksio89** [comment]
Having the same problem. I read at http://forum.pj64-emu.com/showthread.php?t=7884 that Project64 Git version needs Visual C++ 2015 runtime libraries. I have installed both x86 and x64 versions, but the error persists. I have even installed Visual C++ 2017 redistributables, which is an upgraded version of Visual C++ 2015, but no luck. Project64 Git x86 works, though.

**Comment by JunielKatarn** [comment]
What ROM are you using?

**Comment by JunielKatarn** [comment]
Try this build. It uses a 'no audio' plugin, but might help narrow the error:
http://hyvart.com/download/project64/ci/0.0.0.586/Win64.zip

**Comment by Frank-74** [comment]
@JunielKatarn Same error with your build.  The Project64.exe application doesn't run.  So cannot try a ROM.
The application was unable to start correctly (0xc000007b).

**Comment by cxd4** [comment]
...Yeah, if applications are unable to start correctly, that error is usually common enough to indicate that the EXE can't even be launched, let alone run a ROM or try switching to my plugins.

C000007B is the kernel signal for an invalid executable image format.  Your Windows basically believes you are trying to launch an unknown executable format (like 64-bit) within a 32-bit environment.

The fact that people can have this error on a 64-bit Windows narrows the troubleshooting a bit, since several other 64-bit programs may tell you that they think you're on a 32-bit Windows when you're not.

* Run a dependency walker scan on the EXE, if you can, and look for 32- and 64-bit DLL mismatches and criss-crosses.  Possibly a while back you may have mistakenly installed the 64-bit version of some DLL to the 32-bit SysWOW64 folder or the 32-bit version of some DLL to the 64-bit System32 one.
* Try linking the C run-time statically with /MT in the linker options instead of /MD.
* See if the Debug x64 build acts up the same way as the Release x64 one does, as the libraries linked by both are different.
* Try "Run as Administrator".  This can change the start-up routine used with the image.
* Play with the Windows version environment setting in the Compatibility tab.
* Try to run other 64-bit executables.  I can guarantee Project64 isn't the only one that will give you this error, but it may be part of a small group that does, say if other EXEs share the same CRT version.

**Comment by Frank-74** [comment]
Dependency walker found a few problems.  Here are the highlighted red ones.

[ ? ]  API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL            Error opening file. The system cannot find the file specified (2).
[ ? ]  API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL              Error opening file. The system cannot find the file specified (2).
[D? ]  API-MS-WIN-CORE-SHUTDOWN-L1-1-1.DLL                    Error opening file. The system cannot find the file specified (2).
[D? ]  API-MS-WIN-SERVICE-PRIVATE-L1-1-1.DLL                  Error opening file. The system cannot find the file specified (2).
[D? ]  EXT-MS-WIN-NTUSER-UICONTEXT-EXT-L1-1-0.DLL             Error opening file. The system cannot find the file specified (2).
[D? ]  IESHIMS.DLL                                            Error opening file. The system cannot find the file specified (2).
[   ]  COMCTL32.DLL                                           06/08/2015 18:20  06/08/2015 18:20   2,105,856  A      0x00204D9C     0x00204D9C     x86  GUI        CV          0x--------71A00000  Unknown      0x00206000    Not Loaded  6.10.9600.18006  6.3.9600.18006   6.3          11.0        6.3     6.3

Tried several other x64 exe's.  All work fine.  Only have problem with PJ64.

**Comment by cxd4** [comment]
COMCTL32 is the common controls library.  The 32 is only for backwards compatibility in their naming convention; it does not indicate that it should be a 32-bit DLL.

In fact, if you ran the 64-bit version of Dependency Walker, and it said that Project64 64-bit is loading a 32-bit COMCTL32.DLL from C:\Windows\System32 (the 64-bit directory), I can guarantee that this will be a part of the problem.  The API-MS-WIN* stuff I remember missing as well; I'm not sure I needed those.

**Comment by Frank-74** [comment]
Everything is already set to /MT in x64 configuration.
I changed it to /MD and still same error.

**Comment by Frank-74** [comment]
I have a comctl32.dll in Windows\System32.
File version: 5.82.9600.17810
Product version: 6.3.9600.17810
Size: 638 KB

But 64-bit Project64 is loading comctl32.dll in C:\windows\winsxs\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.9600.18006_none_a9ec6aab013aafee
File version: 6.10.9600.18006
Product version: 6.3.9600.18006
Size: 2.00 MB

**Comment by Frank-74** [comment]
@ksio89 What OS are you running?

I'm on Windows 8.1 64-bit.

**Comment by ksio89** [comment]
@Frank-74 Windows 10 Home Single Language x64 build 15063.501.

**Comment by cxd4** [comment]
>Opening the COMCTL32 tree, and everything has a 64 next to it.

Only the COMCTL32.dll by itself needs to have a 64 next to it.

Whether all the DLL dependencies underneath COMCTL32 have a 64 next to it or not is merely reflective of whether you are running the 32- or 64-bit version of Dependency Walker (which forces whether to load the dependencies from System32 or syswow64 rather than basing it on whether comctl32 itself is 64-bit or not).

That winsxs shit is uncharted territory to me.  I've seen it before but rarely delved into it.  I think the comctl32 there may be a hard link to the one in syswow64 (or was it the other way around...), but from everything you've said it sounds like both the 32- and 64-bit version of Project64 are loading the 32-bit version of comctl32.

Though I'm skeptical of even drawing that conclusion.

Don't forget to try the Compatibility Mode options for Project64.exe.  Try running it in compatibility mode for Windows 7 and Windows XP.

**Comment by cxd4** [comment]
As for the others you mentioned, I doubt this ties in to your issue, but:
```
[ ? ] API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL Error opening file. The system cannot find the file specified (2).
[ ? ] API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL Error opening file. The system cannot find the file specified (2).
[D? ] API-MS-WIN-CORE-SHUTDOWN-L1-1-1.DLL Error opening file. The system cannot find the file specified (2).
[D? ] API-MS-WIN-SERVICE-PRIVATE-L1-1-1.DLL Error opening file. The system cannot find the file specified (2).
[D? ] EXT-MS-WIN-NTUSER-UICONTEXT-EXT-L1-1-0.DLL Error opening file. The system cannot find the file specified (2).
[D? ] IESHIMS.DLL Error opening file. The system cannot find the file specified (2).
```

As a sanity check, I would run the same scan on the 32-bit Project64.exe using the 32-bit version of depends.exe (not the 64-bit Dependency Walker) to see if those are consistent with the 32-bit version of Project64 as well.  I do not think missing DLL files could cause an invalid image format issue though.

**Comment by Frank-74** [comment]
32-bit Project64.exe has the same missing dll's.  So they're not a problem.

32-bit Project64.exe has compatibility options for win95, 98/me, xp, vista, 7 and 8.
64-bit Project64.exe only has options for vista, 7 and 8.  None of which make any difference.

The winsxs folder holds all versions of dll's for compatibility.  It's the biggest folder on any windows 7, 8 or 10 install.

**Comment by cxd4** [comment]
Well, yeah.  Win95, 98 and ME didn't have 64-bit editions, so there would be no compatibility mode for those when running a 64-bit program.

The confusing thing about winsxs is that a lot of the stuff in there is links with the real DLL file located elsewhere in syswow64 or system32 (or I have that backwards).  I don't even know that much about hard and soft links.

Is 32-bit exe also loading comctl32 from the winsxs location or from syswow64?  Don't forget to use the 32-bit version of Dependency Walker and not the 64-bit version to run the scan.

I would also run Dependency Walker on a few other of the "files" in syswow64 to see if all of those are also 32-bit or if it's just comctl32 that's the odd one out.  I want to say replace or remove the comctl32 in winsxs except again that could be a really bad idea if it's a link.

**Comment by cxd4** [comment]
Well OK, I'm a risk taker but here's what I would do.

Use 32-bit depends.exe to scan C:\Windows\syswow64\comctl32.dll.
Use 64-bit depends.exe to scan C:\Windows\system32\comctl32.dll.

If both of them correctly check out as 32- and 64-bit versions respectively, then I would just adventurously delete the winsxs one.  Even if it really is linked to the 64-bit OS's comctl32 in some way I think the primary functions of Windows would continue to function, as it's not really a frequent dependency outside of applications heavy in form usage I think.  But if you can scan the other DLL "files" in winsxs and they say 64-bit, and only the winsxs/comctl32.dll by itself says 32-bit, I think you're 100% safe to just delete it or replace it with the 64-bit copy better yet.

**Comment by Frank-74** [comment]
@cxd4 I don't really want to start deleting anything yet.

I've just had an idea of changing the platform toolset, I think it's set to v120_xp.  I might need to get rid of XP support.

**Comment by cxd4** [comment]
You could do that, but primarily that only changes the version of the CRT linked to the EXE.

It does also modify which version of MSVC compiles the C sources (and the version of link.exe etc.), but that's negligible to the invalid image error Windows would be giving you.

It's a good idea, but unlikely to actually fix anything since we've already tried Debug x64 like I suggested which would have already changed the CRT and other libraries being linked against.  And since you ran Juniel Katarn's build of the EXE, we know it's not related to bad static library files from the Microsoft Linker directory in your own installation.

**Comment by cxd4** [comment]
I don't think WINE is enough for me to test any of this stuff anymore.  Haven't ran Windows in months. :P 

Most of what I'm telling is from memory.  Also I only have time in mornings and late nights to even check GitHub at this point in my life.

**Comment by Frank-74** [comment]
Dependency Walker shows System32 has 64-bit version, SysWoW64 has 32-bit version.
Version in C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.9600.18006_none_a9ec6aab013aafee, is 32-bit (x86 folders).

Found a similar issue here: https://social.msdn.microsoft.com/Forums/en-US/c0bc5e8e-1b17-40e2-9476-c1900b5b04ea/comctl32dll-64-bit-version?forum=netfx64bit

Apparently I need to set manifest dependency for Microsoft.Windows.Common-Controls.  There are 64-bit versions of comctl32.dll in WinSxS\amd64_ folders.

**Comment by Frank-74** [comment]
Hooray, I got it to work!

I changed Project64.exe.manifest file from processorArchitecture='x86' to processorArchitecture='amd64'.

**Comment by Frank-74** [comment]
Got it to work without editing manifest file.

Changed x64 configuration, linker manifest file option, Allow Isolation to No (/ALLOWISOLATION:NO).

**Comment by oddMLan** [comment]
Now that we ditched VS2008, the manifest file will attach Common Controls (themed window controls) correctly, which was the issue some people were complaining about in the forums with the official builds from the buildbot (which were using VS2008, which had unthemed window controls)

#720  Is it okay to reverse the reversion of this commit now? This would also fix the 64-bit builds because the manifest would get generated during compilation time with the appropriate parameters.

**Comment by cxd4** [comment]
Manifest, huh?  I'm rather glad you didn't bother with my strategy if the issue was in that dimension.

I remember needing a manifest file to get the VS2005 64-bit C run-time (msvcr80.dll) to even import properly with stuff I built in 64-bit using Visual Studio 2005.

**Comment by Lithium64** [comment]
It's the same issue
https://github.com/project64/project64/issues/1298
