### ISSUE TITLE
x64 - Default save type blank

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1350]
![x64dst](https://user-images.githubusercontent.com/11056843/28934818-3a59fe0a-787a-11e7-871a-3691fb951b5a.JPG)

**Comment by cxd4** [comment]
There is something of a paradox:

1.  [/Project64-core/Settings/SettingType/SettingsType-RDBSaveChip.cpp, line 47](https://github.com/project64/project64/blob/2cb00d34112c49c816ec96eb4fa851df09035fd7/Source/Project64-core/Settings/SettingType/SettingsType-RDBSaveChip.cpp#L47)
2.  [/Project64-core/Settings/SettingType/SettingsType-RDBSaveChip.cpp, line 103](https://github.com/project64/project64/blob/2cb00d34112c49c816ec96eb4fa851df09035fd7/Source/Project64-core/Settings/SettingType/SettingsType-RDBSaveChip.cpp#L103)
3.  [/Project64/UserInterface/Settings/SettingsPage-Game-General.cpp, line 62](https://github.com/project64/project64/blob/master/Source/Project64/UserInterface/Settings/SettingsPage-Game-General.cpp#L62)

The second instance is bad because `SaveChip_Auto` is just a C++ enumeration for -1, but the uint32_t `Value` being switched on cannot ever reach -1LL in a 64-bit preprocessor.

The third instance is bad because--in the event that the second instance was not problematic--in this case `(WPARAM)SaveChip_Auto` would then under the alternate interpretation (which is not immediately obvious as valid or invalid) be zero-extending the integer (__int32)(-1) to 0x00000000FFFFFFFF instead of 0xFFFFFFFFFFFFFFFF, once again resulting in unreachable conditions.

The first instance actually proves that the 32-bit value being stored into memory is just a 2's complement truncation of negative one.

Now I'm not on Windows so can't build and test (and the new UI doesn't load up any of the forums properly under WINE anyway, so if I'm going to use Project64 on Linux under WINE it will have to be through editing the Config files manually), but there is obviously a fatal problem with at least one of those conflicting instances, just by looking at the code.

**Comment by cxd4** [comment]
@Frank-74 try changing from
```c
//case SaveChip_Auto:  m_SettingsIniFile->SaveString(m_SectionIdent->c_str(), m_KeyName.c_str(), "First Save Type");
case 0xFFFFFFFFul:  m_SettingsIniFile->SaveString(m_SectionIdent->c_str(), m_KeyName.c_str(), "First Save Type");
```
and/or (don't do both changes unless necessary)
```c
//ComboBox->AddItemW(wGS(SAVE_FIRST_USED).c_str(), (WPARAM)SaveChip_Auto);
ComboBox->AddItemW(wGS(SAVE_FIRST_USED).c_str(), (uint64_t)(int64_t)SaveChip_Auto);
```

In the latter revision (as my understanding of type-conversion is relatively shallow), you should possibly instead try `(uint32_t)(int64_t)SaveChip_Auto` as well.

**Comment by cxd4** [comment]
Alternatively, instead of doing any of that, you can probably just change [N64Types.h](https://github.com/project64/project64/blob/b19277223bf26da3769564d0d2b182d2f4fd3b37/Source/Project64-core/N64System/N64Types.h#L49-L52).

Change the enumeration for `SaveChip_Auto` from -1 to 9999, 63, 0xFFFFFFFFul or something intangible.

If nothing else, that should surely fix this issue.

It's a shame zilmar didn't just make Auto 0 and EEPROM/SRAM/flash 1/2/3 abrasively against the intuitive C specification that enumerations should start at 0 instead of sloppy values like -1 anyway.

**Comment by Frank-74** [comment]
I changed SaveChip_Auto from -1 to 0 in N64Types.h.

It works now.

**Comment by cxd4** [comment]
If possible (or at least when submitting a PR), you should try to avoid doing that.

It's a quick fix, but it's not backwards compatible because maybe older EXEs use Project64.cfg to store save type = -1 Auto, = 0 EEPROM, = 1 16 Kbit EEPROM, = 2 SRAM or whatever...and now it's type = 0 auto, = 1 EEPROM etc. with everything bumped up.  So copying archived CFG files might be broken because the things Project64 writes to and reads from the CFG might not be consistent.

I agree auto should have been 0 and not -1 though.  -1 should have been more like an error thing for an enum value to be; 0 (auto) makes more sense since detecting the save type should be what an accurate emulator should do by default when possible anyway and 0 is a standard value for defaults.

It would be ideal to submit a fix using one of the methods in the earlier post I did, but I can't test.

**Comment by Frank-74** [comment]
Seeing as only a 0,1,2,3 is written to the cfg, just make the default value Auto = 4.  Shouldn't break anything then.

'''cpp
enum SAVE_CHIP_TYPE
{
    SaveChip_Auto = 4, SaveChip_Eeprom_4K = 0, SaveChip_Eeprom_16K = 1, SaveChip_Sram = 2, SaveChip_FlashRam = 3
};
'''

**Comment by cxd4** [comment]
0 is better than -1, but I think -1 is better than 4. :P 

Besides which, maybe setting the save type to SRAM and back to auto again would actually write -1.  Or at the very least, if somebody did write -1 there they would be facing a regression now if auto was 4.

Then again, I just checked the RDB from 1.6 and the RDB from 2.3 and don't see any =[0123] anywhere for the save type, just stuff like `Save Type=FlashRam` and `Save Type=First Save Type`.  I can't actually use 2.3 in WINE though so can't speak for the CFG file.  Maybe you really can just make Auto = 0 and fix it to the way it should have been without breaking any backwards compatibility then, but only @project64 would know for sure.
