### ISSUE TITLE
Save files not from the same emulator/PJ version are not compatible now.

### ISSUE THREAD

**Issue by retrobenny** [project64/project64#1364]
When I try to copy my save from an old PJ build to 2.4.0-444 (441 folder) it will appear wiped regardless of the TLB setting I mentioned in the previous issue.
A slightly less new build allowed it to load the save one time but then only became wiped when disabling TLB but now in the latest builds it never loads.

I don't have emulators in a program files folder as I have my stuff in a new folder created above that directory which has full access so files don't have any trouble with red/write access like they would in Windows program folders.

So this probably really needs to be fixed or nobody will be able to use newer builds without starting over with fresh saves every time if its a problem with exact versions.

**Comment by oddMLan** [comment]
I doubt this will ever be addressed. You can get around it by using a savestate, and loading that savestate on a newer version, then saving in-game. Unless it is Donkey Kong 64, then you're screwed because that unholy game only saves the changed bytes from the last save point to the chip instead of the whole save data at once.
