### ISSUE TITLE
[Glide64] Banjo Tooie exit fullscreen video size problem

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1376]
Just noticed in latest build.

Entering then exiting fullscreen in Banjo Tooie, I get this.
![glide64__04](https://user-images.githubusercontent.com/11056843/30617242-10949d86-9d8d-11e7-8fa0-a8686cbb163e.png)

Current world/level is displayed in smaller screen bottom left.  The rest is from when I left fullscreen.
My fullscreen setting is 1366x768, windowed at 640x480.
![glide64__02](https://user-images.githubusercontent.com/11056843/30617376-affc19ee-9d8d-11e7-8745-2ccd9e6b4a2a.png)

Kazooie and other games seem fine.

**Comment by Frank-74** [comment]
I've tested Project64 builds back to 2.3.1.  It's the same.  So I tested Glide64 Final, and it's the same issue there as well!

Why wasn't this noticed before now?

**Comment by cxd4** [comment]
Since it happens specifically in full screen mode, I think it sounds like a viewport offset issue.  Something with glScissor or glViewport maybe is receiving data from the C code that isn't maintained properly when in full screen.

**Comment by Frank-74** [comment]
It only happens to Tooie.  Tried a couple of dozen games and no problems.

In Tooie, windowed mode is fine starting the game, fullscreen mode is fine.  It only happens when exiting fullscreen back to the windowed mode.

**Comment by retrobenny** [comment]
Can you find anyone with Windows 7 that can test it if you are on Windows 10?
I can't do fullscreen on Windows 10 because it might break something or trash my monitor setup on my laptop,so all I can do is give suggestions for this scenario.
Using fullscreen is impractical in my common use case.

**Comment by Frank-74** [comment]
@retrobenny I'm on Windows 8.  I refused the 'free' update.

**Comment by retrobenny** [comment]
No wonder you are running into issues.

If you have more than one GPU,which one is being used?
Crazy to know that even Glide64 Final also has this issue,but it may be in other plugins as well.

Too bad/good thing Windows 8 is no longer supported. 😁 (may have snuck in that telemetry crap that Win7 also got in an update alongside the Windows 10 "adware" too.
This issue has a 50/50 chance of being fixed for Windows 8 since no updates will be made to fix it on Windows' end,this would mean you'd need to uninstall updates to attempt to find a working condition for Windows 8 if it can't be fixed on PJ64's side

Anyone in your position should have a DX12/etc. mod created for Windows 8 if anyone can figure out how to make it work,of course pulling out DX12 from the "free" edition of Windows 10 so they can't say anything,plus installing a mod for DX12 support (if it can be done) on an older Windows iteration would further be untouchable,as you would be taking something from Windows and adding it to Windows.
Though Vulkan and DX12 won't matter for PJ64 unless someone ports plugins to those backends.
Vulkan may variably fail to run better much like it acts in Dolphin.

Not that DX12 is needed for much if people push for Vulkan support in modern gaming and say screw DX12 because only Windows 10 has it and its detrimental to sales of games that can be multi-platform and multi-OS capable.
I wanted Sonic Mania to come out on Android but it would've probably lacked mapping for keyboard input remapping like the Sonic 2 app.

Sorry for any offtopic parts.

**Comment by Frank-74** [comment]
I found a solution.

I need to enable 'Use frame buffer objects' in Project64-Video basic settings.
Funny how only Banjo Tooie needs this option for me.
