### ISSUE TITLE
Project64.cfg created outside program directory

### ISSUE THREAD

**Issue by bryc** [project64/project64#138]
Should the config file really be stored two folders behind the root directory? This creates a lot of havoc if moving the directory around, because it won't find the config file.

[/Bin/Release/Config/Project64.cfg](https://github.com/project64/project64/blob/master/Bin/Release/Config/Project64.cfg)
```ini
[default]
ConfigFile=..\..\Config\Project64.cfg
```

If this line is removed, it will default to the _normal_ folder at $AppPath/Config/Project64.cfg.

**Comment by Lithium64** [comment]
Just delete project64.cfg ant let the the emulator create a new one

**Comment by project64** [comment]
the cfg file really is just in the bin dir ... but a config file can redirect to another directory and because I want to share the config file between release and debug I reference things in the root\config directory.

when I clone, I have a base config file there which I just copy and rename to Project64.cfg

**Comment by Frank-74** [comment]
Can the Innosetup create a Project64.cfg file based on options in the install?

I was thinking of updating the setup to a Wise installer, as I have Wise Installation Studio that is a lot more powerful than innosetup.  I could read/write the registry for a rom directory and write it to the Project64.cfg for example.  Or read the location of the last installed .exe from the registry and read the rom directory from the last install .cfg file.  Write the correct directory path for OS's to the Project64.cfg that choose to install plugins or the config files to a different folder.  Or only allow installation to a folder with admin access.  Anything is possible with Wise.

**Comment by project64** [comment]
I am sure I can do any of that with inno as well .. may have to do more work programming it .. but I can do basically anything I want there .. 

maybe getting setting from a previous version may have some value, but I do like that it is reset and that I know it is clean when I install.

**Comment by project64** [comment]
is this actually an issue ?

**Comment by AmbientMalice** [comment]
Because PJ64 stores changed per-game settings data in the cfg file, if the cfg file is shared by every PJ64, it means that RDB fixes may not be applied when installing a new version because the user's cfg file overrides them. Yes, it's possible to reset a game's settings to default, but not all users may know to do this if they've simply clumsily tinkered with per-game settings.

**Comment by project64** [comment]
installing a new version it will be self contained and will not go out, the config file in the debug/release dir go down two dirs because it expects the tree layout of checking out the source.

**Comment by AmbientMalice** [comment]
@project64 I see.

**Comment by project64** [comment]
I do not think this is an issue, if so then please reopen it.
