### ISSUE TITLE
Register 0 isn't a constant 

### ISSUE THREAD

**Issue by gamemasterplc** [project64/project64#1421]
Any operation that attempts to modify r0 changes the value of r0 instead of locking the value of the register on both interpreter and JIT mode. The hardware treats it as 0 at all times. A GS Code for US Super Mario 64 that tests it is below. It should not crash PJ64 or the game as soon as the PRESS START text shows up. If it does its inaccurate emulation

Hide START Text in PRESS START:
8127A91C 2400

**Comment by project64** [comment]
it generates a "crash" cause it hitting a break point. I have lots of these in the code, when things should not happen instead of trying t o implement them I have break points as they should not occur and then I can work out why something is trying to do something. Writing to r0 is not going to do anything, so it should not hit this breakpoint.

**Comment by gamemasterplc** [comment]
i can tell you that the caller code thinks r0 is 0x59B0 instead of 0x0 after the code executes

**Comment by project64** [comment]
Yes you should not be able to change register 0

I had stuff originally in some of it can still be seen here.
https://github.com/project64/project64/blob/master/Source/Project64-core/N64System/Interpreter/InterpreterCPU.cpp#L406

now that line probably should be at 316 as well.
https://github.com/project64/project64/blob/master/Source/Project64-core/N64System/Interpreter/InterpreterCPU.cpp#L316

The re compiler has to be done in about 100 different places.  well basically every time for every op.

I was paranoid about this at the start of the emu, but it is extra overhead that I have never seen happen in any real game.

**Comment by gamemasterplc** [comment]
a bunch of cheat codes rely on the fact that r0 stays 0 in an ADDIU opcode for a shorter NOP

**Comment by project64** [comment]
well I can add that line above easy enough which should fix the interpreter .. can also add a check in addiu is that all you need?

**Comment by gamemasterplc** [comment]
yes

**Comment by project64** [comment]
I will try to add that tonight (like 8 hours from now)

**Comment by theboy181** [comment]
:)l

**Comment by project64** [comment]
https://github.com/project64/project64/commit/4b7fafbdedc20023870f3e40e07012f7f503385e that does it for the interpter, recompiler already handles addiu

**Comment by cxd4** [comment]
>I was paranoid about this at the start of the emu, but it is extra overhead that I have never seen happen in any real game.

You have, just not on the R4300 because that code is generated from a C compiler.

On the RSP, both _Donkey Kong 64_ and _Banjo-Tooie_ try to overwrite $zero as the destination register via `ADDU` and `AND` op-codes.  The debug ROM of Zelda Majora's Mask also boots up using an `ADDIU` instruction with register 0 as the destination.

Not something I ever had to tell you because PJ64 RSP had register 0 protected since before the 1.4 sources (except for 3 instructions that no game exploited, which after PRs from me are handled now in 2.x RSP).

**Comment by retrobenny** [comment]
My take on it is that by attempting to change r0 to a non-zero value like 1 then continuing,you would have any and every,for example `ADDIU A1 , R0 0x012C` change the value in register A1 into 012D which if used to add into an offset address destination for a Jump to another register would cause an error or glitches/memory leaking overload because of being a misaligned address offset.

**Comment by cxd4** [comment]
Everybody knows this.  That's why games can't attempt a change to $zero (why does everybody call it R0 anyway) in R4300 code, without self-modifying code or using asm.  A C compiler will never generate instructions to modify $zero.  Even if $zero could be modified, the SLL $zero, $zero, 0 doesn't repair anything on its own.

If anything, I should use signals and write-protect &(SR[0]) and &(GPR[0]) instead of setting SR[0] = 0x00000000; at the end of every RSP instruction that exposes an attempt to use $zero as the destination operand.  I could remove all the extra steps of constantly enforcing GPR 0 is 0 by using a C exception that, when caught, repairs the value and ignores the instruction, continuing on.  Except it's not really efficient cause either you set the CPU register restores point every iteration of the interpreter CPU or at the beginning of every RSP task, by rewinding to which you restart the entire task in the rare case a game attempts writing to it.

**Comment by gamemasterplc** [comment]
close this iissue
