### ISSUE TITLE
FPS bit Slow when loading Project64 on Windows 10

### ISSUE THREAD

**Issue by TradeDraft** [project64/project64#1450]
When I load PJ64 up and then a Game the FPS is around 53fps instead of around 60fps.

Go into settings then Exiting out seems to fix the Problem but I don't think it should be doing that. Nothing Major but can be Annoying.

**Comment by theboy181** [comment]
probably using sync to audio?

**Comment by TradeDraft** [comment]
I just have it set as Default.

Yeah, the sound when doing that at 53fps is bit off

Do I need to change something?

**Comment by theboy181** [comment]
turn off sync audio

**Comment by TradeDraft** [comment]
That Works but have to do it for Each Game

or

Is there a Way you can set it for all Games?

**Comment by theboy181** [comment]
Zilmar is working on a global function to turn them all off. But it’s best you toggle options as you test and play them each game has Different best settings. Because of the different plugins it’s hard to maintain a solid list of best settings.

**Comment by TradeDraft** [comment]
Okay.

Yeah, Not all games work with same Settings. Need to Change a Few for Certain games to work

**Comment by LegendOfDragoon** [comment]
@TradeDraft have you tried latest build? I believe your issue may have been fixed. Also are you on Windows 8?

**Comment by project64** [comment]
try v2.4.0-728-g355be14 (from: https://www.pj64-emu.com/nightly-builds) and see if it is happening

**Comment by TradeDraft** [comment]
Yes I have tried the latest Build.

Interesting IF you have Project64 Video Plugin it still does it but when I set it to the Jabso Video Plug In it's not there and I can then change per-game IF needed to Gliden64 and as long as main video plug in is Jabso it will run at Normal Speed.

Though have to turn of Syncing/Fixing with Audio to make it run with 60fps

**Comment by oddMLan** [comment]
@project64  You should probably change the Timer to 1ms, that's what Jabo does, and what seems to work for everybody.

**Comment by LegendOfDragoon** [comment]
@TradeDraft you need to use latest audio plugin. If using Jabo's Video fixes your issue, then you must not be using latest version of audio plugin. @oddMLan  0.5ms is going to work even better than 1ms, I just don't recommend it because it slows down the CPU performance of your machine, when you raise the timer resolution. Also because of the fact that PJ64 doesn't utilize NtDelayExecution, I see less of a point in using 0.5ms.

If i were to make my own emulator or  fork an existing one, I'd use NtDelayExecution instead of Sleep and make an option to set the timer resolution. I like using these low level Windows API functions :smile: . I started using MessageBoxTimeout instead of Messagebox, because I think it's cool to have a timer lol.

**Comment by cxd4** [comment]
NtDelayExecution() is not exposed as callable function....  You'd have an easier time copying the SYSCALL interrupt number from which version of Windows your version of NTDLL.DLL implements NtDelayExecution() with and writing inline assembly that breaks all versions of Windows other than the ones using the SYSCALL number you copied in.

**Comment by cxd4** [comment]
If I made a suggestion to call `NtDelayExecution` directly for either x86 or x64, I sure don't remember it.

I **do** remember documenting the code profile differences of executing kernel32::Sleep vs. ntdll::NtDelayExecution somewhere on EmuTalk a while back, but I can't remember saying to ever actually use the latter.  I may have indeed though.  That does sound like something I would say. :) If so I'm pretty sure I was wrong.

>I don't like how these use all these weird types.

Well, it's not like Microsoft wanted _us_ to have access to those undocumented types and functions.

>I recently found out that even including Windows.h, slows down compilation,

Be careful with the word _"even"_ in this instance.

In fact, `windows.h` (or `Windows.h` with the capital `W` in newer versions of VS which are backwards-compatible with the case-insensitive design of previous versions using the lowercase `w` so you may as well just say `windows.h` with the lowercase spelling) is probably the only header I can think of offhand that does slow down compilation conspicuously.  Most standard header files are pretty clean compared to that.

>so now I just make my own header file that only includes the stuff I'm actually going to use.

That used to be how I did all my projects in my first year or two of C coding.

Would make my own header file including the relevant typedef's from the Windows API or C stdlib....

You gotta admit it doesn't look very elegant, though.  Your source code becomes larger and harder for other contributors to have the confidence to read when there are extra files not absolutely needed by the project (e.g. copy pastes from windows.h instead of `#include <windows.h>`).  People will give up and think it's something much more complicated than it actually is.  That's why most people don't build from source.

You also run the lesser risk of breaking forward-compatibility with upgrades to the Windows API.  If a new version of Windows modifies NtDelayExecution's calling procedure, function parameters or types and adjusts their lib accordingly, their ntdll.dll will be up-to-date while the code you copied from an older version of a Windows header will be immortal, old and ever-unchanging.

>Doing this also gets rid of tons of warnings too, when enabling wall.

Yeah no shit.  Any time I did projects in Visual Studio I always compiled with /Wall, but I had to give up doing that if I made any Windows-specific programs including the standard header.

You know, in all seriousness, if you really do like coding in asm or working around the limitations of C, that would actually add to your advantage to focusing on UNIX-based systems.  The Windows interrupt numbers and syscall's are undocumented, volatile and can change at any time.  The kernel Linux's low-level asm interface is completely documented and intends to stay fixed and constant, which makes it more reliable to program in asm in an open environment.

And if you've ever done those main(int argc, char* argv[]) kinds of programs instead of just int main(void), you'll notice that Visual Studio or whatever you use to do a Win32 build always generates function calls to set up those kinds of command-line programs.  If you do it on Linux, the stack pointer register immediately points to argv[] without you having to call any functions to get argc or argv.  So the assembly source code to most command-line programs built on Linux is actually substantially smaller than what you'd have to write to do the same thing on Windows.  Just sayin'....

Oh what am I doing!  I'm supposed to keep on topic.  Shutting up now...

**Comment by TradeDraft** [comment]
@LegendOfDragoon Which one is the Latest Audio Plugin? (Bit out of Loop)

I don't know a ton about Programming

**Comment by LegendOfDragoon** [comment]
By suggestion, I meant getting the interrupt number and using inline assembly. I do recall you introducing me to NtDelayExecution and I was so excited thinking you could actually sleep for 100ns :smile: . Dunno why they even give you such a big range of input values lol. But I'm happy to be able to sleep for half a millisecond though. It helps for frame-limiting, or just simply having a faster response time. So I appreciate you introducing it to me :smiley: .

>Well, it's not like Microsoft wanted us to have access to those undocumented types and functions.

Yeah that's a real shame. Iirc, I had to link an extra directory path or something, because Visual Studio didn't come with ntdll.lib. Good thing I had already installed Windows SDK. If they do end up modifying their procedures for Winapi, I don't mind doing the extra work. Imo the benefits of using these low level functions, outweigh the extra work required to implement/use it.

>You gotta admit it doesn't look very elegant, though. Your source code becomes larger and harder for other contributors to have the confidence to read when there are extra files not absolutely needed by the project 

Do people really read header files lol? I honestly rarely look at them. My biggest issue is simply the time investment required to set it up :smile: . I learned the hard way that it's likely not worth the effort to do this for some projects. Something simple like an RSP plugin where you don't need too many API functions, it's totally worth it for me. I added a few dozen lines to a header and everything is set. Then again, I wasn't using intrinsics :disappointed: . Directsound8 was a major pain. I stopped about 1/10th way through it and realized that I'm better off just writing in assembly to achieve my goals. I couldn't even be bothered to replace emmintrin.h . 

>You know, in all seriousness, if you really do like coding in asm or working around the limitations of C, that would actually add to your advantage to focusing on UNIX-based systems. The Windows interrupt numbers and syscall's are undocumented, volatile and can change at any time. The kernel Linux's low-level asm interface is completely documented and intends to stay fixed and constant, which makes it more reliable to program in asm in an open environment.

That does sound appealing :smiley: . I did always appreciate certain aspects of UNIX. Like iirc, I liked the x64 calling convention better in Linux than Windows. My main reason for preferring windows was because of all the software currently available on it. Also the fact that Intel IGP's don't have good OpenGL support. 
Next year, I do plan on developing on Linux. I'll have to find a good alternative to MASM.

@TradeDraft did you do any recent testing?

**Comment by cxd4** [comment]
>Imo the benefits of using these low level functions, outweigh the extra work required to implement/use it.

I think it was either ReactOS and/or WINE that document NtDelayExecution, just not Microsoft.

IIRC I only learned about it by stepping through the x86 for `printf` on Windows 7.

>My main reason for preferring windows was because of all the software currently available on it.

The video game and PC gaming industry I believe is the only solid entity to thank for that.

I can't think of any software I miss having that was on Windows but not here, though that's not very telling.  I'm not very collective or picky.

>Next year, I do plan on developing on Linux. I'll have to find a good alternative to MASM.

I believe GAS has the widest availability outside of both Linux and Windows.

If you only care about Linux and/or Windows and a few others, then NASM is another one I hear a lot about.  I believe there was another one...can't remember.  NASM isn't too MASM-friendly.

To reduce the amount of work converting your MASM assemblies to GAS, include the `.intel_syntax noprefix` directive at the top to use Intel's operand-ordering and the like instead of AT&T's.

Actually, for doing the release of my RSP I was considering compiling on Linux, then taking the asm files on Windows and assembling them and linking them for the DLL, since the version of GCC on Linux is always newer and more native than what MinGW will give you, which means newer optimizations.

>Do people really read header files lol?

Yeah not really.  I do, but never mind me.

I meant that the more files in a source code repository, the larger people will think the source code is.  And the larger people think the source code is, the less subtle the impact of the exotic, complicated appearance to working from source is on users.

I may not even be correct necessarily, but if you can think of a way to delete code from your project, you should delete your code.  Much easier than trying to clean it up or simplify it.  Re-inventions of header files or copy pastes from standard header files already provided by the compiler would tend to fall under that category.  As much as I've hated distros for having dependency hell, it is nice that code recycling is optimized.  Much better than static-linking msvcrt inside every single Windows DLL and EXE file on your computer, eh? :)  Don't forget to optimize for small files sizes as well from time to time, not just perf.

>Something simple like an RSP plugin where you don't need too many API functions, it's totally worth it for me. I added a few dozen lines to a header and everything is set.

I don't imagine that the speed of compilation is so much faster with your own custom lines taken out of a header vs. directly including the header that you would not just simply include the header.

For `windows.h` and friends then yes, that I can understand.  But for simple, universal header files that are required by the C language implementation to always exist (like stddef.h, stdlib.h, limits.h ...) I cannot imagine any genuine advantage to not just `#include`ing them.

**Comment by TradeDraft** [comment]
@LegendOfDragoon I did a test few days ago.

Tried Jabso Audio Plug-In but I still found you had to turn them Audio Syncing Off to get it Run Perfectly as have it on now makes it run to fast and Crackles in the Audio when 1st Loading Project64 Up

**Comment by LegendOfDragoon** [comment]
>I think it was either ReactOS and/or WINE that document NtDelayExecution, just not Microsoft.

Yeah I think ReactOS does document these functions.

>I can't think of any software I miss having that was on Windows but not here, though that's not very telling. 

I use a lot of stuff like cheat engine.

>I believe GAS has the widest availability outside of both Linux and Windows.

I guess I'll try using GAS, when on Linux. I'll definitely use intel syntax, so thanks for that tip :smile: .

>Actually, for doing the release of my RSP I was considering compiling on Linux, then taking the asm files on Windows and assembling them and linking them for the DLL, since the version of GCC on Linux is always newer and more native than what MinGW will give you, which means newer optimizations.

That would be interesting to see. That reminds me of when I compiled your plugin years ago and compared each vector instruction, after compiling with Mingw and Intel, so that I could pick the best implementation out of the 2.

>I meant that the more files in a source code repository, the larger people will think the source code is. And the larger people think the source code is, the less subtle the impact of the exotic, complicated appearance to working from source is on users.

I get what you're saying. Part of it is me not ever wanting to end up maintaining a project that takes minutes to compile lol. Hated doing that. It's also just a fun experiment for me, to see how much of a difference it makes. Nothing I work on is popular, so I don't really expect any contributors :smile: . People even tease me for that, since I'm into stuff no one else really cares about. After seeing how messy it would be to replace dsound.h and ddraw.h, I doubt I'll ever finish this experiment, since I'd rather just start coding in assembly more. So I'll probably only replace windows.h for basic software like RSP, or some tools I make.

I'm just being extra picky, but I kinda don't like how a lot of these header files include other headers in it. That was one of the reasons I wanted to try replacing these includes. You're probably right that many of these standard ones will hardly impact compilation time, though.

I'm tempted to try using NtDelayExecution in Project64. I think I'll test it during vacation :smile: .

@TradeDraft please try Project64 Audio, as that is now the default audio plugin for Project64.

**Comment by cxd4** [comment]
If you're concerned about projects that take minutes to compile, I would really just focus on obeying the laws of the C specifications.  Anything outside that (such as POSIX headers, Macintosh stuff or `windows.h`) should not be a requirement to compile those projects, as they are not under the jurisdiction of the C language anyway.  They can wait as optional fancy per-OS features to add in with optional compile switches.

Otherwise, perhaps you must have seen by now `stdafx.h`?  zilmar uses this method as well; it is compiled one time as just a header file and referenced as a static binary to accelerate the processing of all translation units which would depend on that header.  I personally do not practice compiled headers, but if you don't want to simplify your code down to just the standard C headers then you could speed things up with `stdafx.h`.

Here's a tip most people don't get:  If you write a program that doesn't call any standard library functions, but your code uses `size_t` or the `NULL` macro in it, you don't need to include `stdio.h` OR make your own copy paste from those headers to declare `NULL` or `size_t`.  They're both defined in `stddef.h`, which stdio/stdlib both include anyway.  So you can speed up compilation just by including stddef, which is so small enough of a universal C header file you really shouldn't care to copy paste from it.

>I kinda don't like how a lot of these header files include other headers in it.

Nothing on the scale of SIMD intrinsic headers, standard C headers or any of that should ever include `windows.h` or other gigantic messes like that.  If you find yourself with a compiler that does an `#include <windows.h>` inside of a header like `stdio.h` then you definitely need to ban that program.

>I use a lot of stuff like cheat engine.

Cheat Engine is just a memory editor, correct?  I'm certain there are alternatives to it.

One I just found is `scanmem`.

**Comment by LegendOfDragoon** [comment]
>Otherwise, perhaps you must have seen by now stdafx.h

I've seen it before, but never used it. While thinking of how to improve compilation speed, I did consider it at one point. I'll leave that into consideration for when I start larger projects.

>Here's a tip most people don't get: If you write a program that doesn't call any standard library functions, but your code uses size_t or the NULL macro in it, you don't need to include stdio.h OR make your own copy paste from those headers to declare NULL or size_t.

I started doing stuff like that, ever since I had trouble compiling some intrinsics with clang. For some reason that compiler had an issue with me using `intrin.h` , so i looked inside that header and tried to look for headers included inside of it, so that I could use that instead. After digging through some of those headers, I found that `emmintrin.h` was all I needed. Lol I thought you needed some other header for size_t :smile: . Good to know.

>Nothing on the scale of SIMD intrinsic headers, standard C headers or any of that should ever include windows.h or other gigantic messes like that.

You're right. I'm just nitpicking :smile: .

>Cheat Engine is just a memory editor, correct?

Yeah, also a debugger. Seems like scanmem might be a good enough alternative :smile_cat: . Nice find man

@TradeDraft Does project64 audio sound fine with audio sync enabled when using Jabo's Video?

**Comment by cxd4** [comment]
I always shed a tear of pride whenever I encounter yet another one of GitHub's cat emotes. T_T

>Yeah, also a debugger.

I haven't established myself with a good debugger on Linux yet, but then again I never really found a debugger while on Windows either since I didn't actively look for one.  `gdb` is the traditional debugger on GNU operating systems and generally all other operating systems to which GCC was ported.  Didn't try it.

>After digging through some of those headers, I found that emmintrin.h was all I needed.

Nah I've never used `intrin.h`.  Barely even saw it be referenced anyplace.

It's just `emmintrin.h` for SSE2 (or the SIMD subset of x86-64), `xmmintrin.h` for SSE1 (needed for the added PSHUFW operation on MMX registers, which was not present in the original MMX), `tmmintrin.h` for was it SSSE3 or SSE4, forgot which.

>Lol I thought you needed some other header for size_t 

Nope and that's the thing.

On 32-bit Windows size_t is `unsigned int`.
On 64-bit Windows size_t is `unsigned __int64` or `unsigned long long`.
On 32-bit LP64 ABIs, size_t is `unsigned int`.
On 64-bit LP64 ABIs, size_t is `unsigned long`.

So why bother copy pasting the definition of `size_t`?  I would generally make the same argument for the `NULL` macro.  Most people blindly include `stdio.h` or `stdlib.h` just to have NULL and size_t defined, even if it's in individual .c or .cpp files that use no standard library functions, just NULL and the types.

Always try to find ways to delete your code.  The less code you have, the less you have to worry about compile times, or whether to _add_ code pasted from headers to make up for code that's already large, or any of that.  If a widely available C header file defines most of what you would have otherwise needed to define yourself then I would definitely take advantage of that.

**Comment by TradeDraft** [comment]
@LegendOfDragoon I tried with the Sync on with Jabso.

It Runs bit Slow and the Sound/Music is Choppy

**Comment by project64** [comment]
I have build v2.4.0-735-g8838660 (https://www.pj64-emu.com/nightly-builds) disable Sync to audio setting in the emu for plugins not pj64-audio

**Comment by oddMLan** [comment]
Described issue same as #1472 and was fixed with https://github.com/project64/project64/commit/2ca97f0b377a13d969856a1d653b7c4fe42099b4
