### ISSUE TITLE
Project building errors

### ISSUE THREAD

**Issue by Legiaoday** [project64/project64#1454]
I'm using Visual Studio 2015 and I'm getting several errors when building Project 64. A year ago or so I was able to build Project 64 on this exact machine without any problems, but the latest snapshot of this repo gives me these errors:

![untitled](https://user-images.githubusercontent.com/25484098/39400061-551e65a2-4aff-11e8-88ad-33dc5a0368e0.png)

I also tried building on another machine with Visual Studio 2017 installed and I got the same errors. Before, I always followed the instructions [here](https://github.com/project64/project64/wiki/Building) and I was able to build without issues.

**Comment by project64** [comment]
Did you download the source or clone it?

try cloning the source

**Comment by Legiaoday** [comment]
Even after cloning it I still can't build the solution. And again, I tried on both VS2015 and VS2017.

**Comment by wfowler1** [comment]
Having the same problem here, except the error code is 1. Why does this script keep breaking the build?

**Comment by Legiaoday** [comment]
[This is the commit that broke the building for me.](https://github.com/project64/project64/commit/1178b5c73fa054c329c11d769374e5d50928eaea)
I can build pretty much everything that came before it. But apparently you guys are already aware of that. Is there fix or workaround for this?

**Comment by wfowler1** [comment]
Looking at the list of errors, the first problem that comes up for me is "lib\Common.lib" isn't being generated in the bin folder by the build process. A few other things depend on this and it causes all kinds of issues.

**Comment by Jj0YzL5nvJ** [comment]
I can build just fine (Visual Studio Community 2015.3).

http://0x0.st/s1js.txt
http://0x0.st/s1ji.txt

PS: I only use CLI =P

**Comment by project64** [comment]
basically the update version script is failing (https://github.com/project64/project64/blob/master/Source/Script/UpdateVersion.cmd)

if you run:
git describe --tags --long --dirty

what do you get?

**Comment by wfowler1** [comment]
> [snip]\Documents\Visual Studio 2017\Projects\project64> git describe --tags --long --dirty
> v2.3.2-691-g5d7dc12f

**Comment by project64** [comment]
can you show me the build output where it is failing

**Comment by project64** [comment]
Does https://github.com/project64/project64/commit/f20dca31fdc43e71fd50c4c0888352e4c78a36c2 fix it?

it is possible the issue was that version.h.in had unix line endings instead of windows line endings and the update version was crashing on that

**Comment by wfowler1** [comment]
Nope, still fails.

Here's the full build output from the x64 in Release configuration
https://cl1p.net/pj64_1454

**Comment by project64** [comment]
try win32

**Comment by wfowler1** [comment]
Ok, so I've been fighting with this thing all night. I tried Win32 and was getting the same errors about UpdateVersion.exe not being found, but I noticed a few errors that came up before them saying there was some problem with a .lib file in my VS install. I ended up uninstalling VS altogether and then it wouldn't reinstall because the directory wasn't empty. I tried manually deleting "C:\Program Files (x86)\Microsoft Visual Studio\2017" from my filesystem and it wouldn't do it, even with administrator privileges. Turns out there were some random errors in my filesystem and running chkdsk got it sorted, and I was able to delete the folder.

So from there, I was able to do a full clean reinstall of VS2017 Community edition, and started fighting with the compiler trying to figure out what components I needed to install. After several hours (and reinstalling the "Windows XP support for C++" component several times thanks to a nasty bug in VS2017) I finally got the damn thing to build at five in the morning. Let it be known how much I utterly loathe C++ and its bloody compilers.

Anyway, it looks to me that this issue is fixed, at least for Win32, x64 gives several "error C2504: 'CDebugSettings': base class undefined" but I doubt a 64-bit port is a huge priority for you right now anyway. It is strange, though, since I was getting this same problem on two different machines...

**Comment by Legiaoday** [comment]
Nope, the compiler still complains about the Version.h.

![untitled](https://user-images.githubusercontent.com/25484098/42074277-a6a22c16-7b41-11e8-9829-6a6211485cd0.png)

I honestly don't know what this script is or what it's trying to do, but it's messing everything up for me.
Anyway, I looked inside each project folder to be sure Version.h wasn't there, and it actually wasn't inside any project I looked. But I did find a file named "Version.h.in" inside several project folders. I opened this file and saw that it looked like an average header file, full of macros, etc.
I tried renaming these files to "Version.h", but as soon as I build the projects the script wiped out every version file and the errors repeated themselves.
I restored the files and so not to mess with this script, I tried instead renaming these file to "Version2.h" and changing every single _#include "Version.h"_ to _#include "Version2.h"_.

After I did that everything compiled as it should, but it's obvious that this isn't how things were supposed to work. Can anyone tell me what is this script is and why it needs to generate this Version.h right before the compile runs?

**Comment by oddMLan** [comment]
I don't know what's wrong on your end, project compiles just fine for me. I use VS Studio 2017 Community
At install I checked C++ toolset, ATL and MFC and Windows XP C++ toolset. I think that's all it needs.

**Comment by Jj0YzL5nvJ** [comment]
If he can't generate 'Version.h', it's clear that he doesn't have git installed or it isn't configured in the "Path" environment variable.

**Comment by Legiaoday** [comment]
I already said it before, GitHub is installed and configured, but even if it wasn't the wiki [here](https://github.com/project64/project64/wiki/Building) never stated anything about needing the github application or the configuration of something else. Maybe you should try updating your wiki when making such major changes that impact in the building of the project.

**Comment by Jj0YzL5nvJ** [comment]
Other possible scenario is be downloading the code from "Download ZIP" instead of using `git clone https://github.com/project64/project64.git`. That prevent the generation of the library even if you have 'git CLI' properly configured.

**Comment by project64** [comment]
closing for now

**Comment by cxd4** [comment]
>GitHub is installed and configured, but even if it wasn't the wiki here never stated anything about needing the github application

Because it isn't needed. :)

They said "git".  You misread as "GitHub", which is either this website or some desktop GUI candy.
