### ISSUE TITLE
Project64-Video (v2.2.0.706).dll, memory leak report on exit

### ISSUE THREAD

**Issue by MelchiorGaspar** [project64/project64#1495]
I just grabbed today's latest build on exit of program a memory leak is reported regardless if a ROM is loaded or not...

Order, Source File, Line Number, Mem Size
55,Unknown, 0, 64
45,Unknown, 0, 32
21,Unknown, 0, 440
23,Unknown, 0, 84
24,Unknown, 0, 19
25,Unknown, 0, 19
26,Unknown, 0, 19
27,Unknown, 0, 19
28,Unknown, 0, 19
29,Unknown, 0, 19
22,Unknown, 0, 844
30,Unknown, 0, 19
31,Unknown, 0, 19
32,Unknown, 0, 20
33,Unknown, 0, 20
34,Unknown, 0, 20
35,Unknown, 0, 20
36,Unknown, 0, 20
37,Unknown, 0, 20
38,Unknown, 0, 20
39,Unknown, 0, 20
40,Unknown, 0, 20
41,Unknown, 0, 20
42,Unknown, 0, 20
43,Unknown, 0, 21
44,Unknown, 0, 21
57,Unknown, 0, 48

**Comment by project64** [comment]
https://github.com/project64/project64/commit/58305edc8b62b3de0a75955e413bfc8136570805 might fix it.

where did you grab the build from, cause it should only be in the debug build

**Comment by MelchiorGaspar** [comment]
I grabbed it from the main build-bot download page 
[https://www.pj64-emu.com/nightly-builds](url)
I just grabbed build 710 and will check it out..

**Comment by Frank-74** [comment]
Just tried 710 myself, my last version was 573.

No problem starting and running here.  But I get memory leaks in Project64-Video and Project64-Audio after using those plugins and closing Project64.  With Debugger off.

Also Goldeneye doesn't start anymore.  After turning on Debugger to get a log, Goldeneye's error is, 2018/11/25 18:39:28.075 04264,Error,User Interface,CNotificationImp::DisplayError,Break point found at
N64System\Recompiler\RecompilerClass.cpp
168

**Comment by Frank-74** [comment]
No memory leaks on 697, memory leaks on next nightly build 704.
Goldeneye is fine upto last 710 build.

**Comment by Frank-74** [comment]
712 fixes the memory leak reports for me here.  Goldeneye still crashes on startup.

**Comment by project64** [comment]
Golden eye is a completely different issue, but I will try to look at it today. 

there still might be leaks in the video plugin, but it should not be tested in release (https://github.com/project64/project64/commit/bb29e788069db7b7bc29d63bba2b7d357d351727 fixes that). 

Closing this issue now

**Comment by cxd4** [comment]
>I think leaks must've therefore started being shown with this commit: e7f93f2

Nothing there controls the actual decision to trace a memory leak or ignore it, but you do have me curious about the commit because `struct` is a more generalized representation of `__interface` that I actually do not know if it may trigger a different memory size.

Did you try seeing if including `objbase.h` back in (and removing the #define directive for __interface) fixed the memory leak?  Wouldn't think it should...would have thought some other commit caused it, just curious.

**Comment by Frank-74** [comment]
> Golden eye is a completely different issue, but I will try to look at it today.

It's problem with Virtual Lookup.  Every game that uses it crashes with same error.  CBFD and Perfect Dark as well.

**Comment by MelchiorGaspar** [comment]
I'm not getting the memory leak error now.. but I can't startup PJ64 without getting that main.cpp line 89 exception

**Comment by Frank-74** [comment]
> What does that option do?

Recompiler's function lookup method.  Virtual lookup table instead of physical.  It's faster.  CBFD, Goldeneye and Perfect Dark currently use it.
CBFD and Perfect Dark work with Physical lookup, but Goldeneye is not starting with Physical lookup table either.

@MelchiorGaspar Have you tried moving 712 to a different directory?  One with full user permissions.  Mine is in my downloads folder and I'm not getting error in main.cpp.

**Comment by MelchiorGaspar** [comment]
@Frank-74  I keep all my emulation related stuff on sub-driectory of a gaming/storage HDD.. so there is no permission issues...

**Comment by project64** [comment]
golden eye should be fixed with https://github.com/project64/project64/commit/5f39f3d12248066b9b0aa1b4373e033116479ded
