### ISSUE TITLE
Error on screen capture, cannot escape without crashing program

### ISSUE THREAD

**Issue by khionu** [project64/project64#1497]
I hit F3 by accident, and now every frame triggers this error, and I cannot escape it.

**Suggested Fix:** Auto Pause on engine errors that report to the user

![](https://files.khionu.net/ss/20181124_29e03b.png)

**Comment by CrashOveride95** [comment]
What video plugin are you using?

**Comment by khionu** [comment]
Jabo

Also, to note, my default settings are for FXAA are off, so, the program

**Comment by CrashOveride95** [comment]
Jabo does not support it, try using a different video plugin. it works fine with other plugins

**Comment by khionu** [comment]
> Hit F3 **by accident**

Note that the issue here isn't related to the functionality, but the handling of the error.

Hitting "Ok" allows the game to proceed a singular frame, then it shows the error again. To get to a save point, I created a macro to spam enter, so I could get through the cutscene I was trying to skip through by hitting F4 (toggling Framerate Limiting).

**Comment by project64** [comment]
closing issue due to an in ability to be able to change jabo's video plugin

**Comment by khionu** [comment]
Please clarify if I'm wrong, but is it not within Project64's ability to make a change in the error-handling flow?

And for the record, I have since changed the plugin. I feel this issue transcends a specific plugin's shortcomings.

**Comment by Frank-74** [comment]
@khionu Jabo's saving of screenshots broke when I disabled logging errors.
You can download the original Jabo GFX here: https://github.com/project64/project64/raw/98f87e31d11f3c335661801c475d0a10c994d921/Plugin/GFX/Jabo_Direct3D8.dll

Error handling is done within the plugin which is closed source.

**Comment by khionu** [comment]
So, there is no way Project64 could detect that the engine is throwing an error, and then pause the emulation?

**Comment by cxd4** [comment]
>To get to a save point, I created a macro to spam enter,

... or just hold down the Enter key thru the error boxes instead of creating a macro to repeatedly press a key you can hold down?

>And for the record, I have since changed the plugin. I feel this issue transcends a specific plugin's shortcomings.

The error message you provided is not a Project64 error message.  It's a Jabo plugin error message.

If you continue receiving that exact error then you have not actually changed the plugin.  You may have changed global plugin assignments; the local or per-ROM plugin is still Jabo's.

>So, there is no way Project64 could detect that the engine is throwing an error, and then pause the emulation?

By "the engine" of course you mean the plugin's engine, not Project64's.  Sure it's possible for Project64 to catch an external module's error-catching, but not before said external module catches the error itself first.

**Comment by khionu** [comment]
> If you continue receiving that exact error
I'm not. My issue is not with the error, but with the fact that a plugin can behave this way.

>  Sure it's possible for Project64 to catch an external module's error-catching
If it can do that much, then it can pause the emulation on such an occurrence.

> ... or just hold down the Enter key thru the error boxes
It was a notoriously long cut scene, hence I was attempting to hit F4 in the first place.

**Comment by cxd4** [comment]
>I'm not.

Goodie, no issue then.

>My issue is not with the error, but with the fact that a plugin can behave this way.

Software can behave literally in any way you allow it to behave by running it.  That's not a Project64 issue; that's a Microsoft Windows issue you'd need to take up with them.  The operating system controls what a child or image process or plugin inside of a parent process or emulator is allowed to send interrupts with, not the parent process.

>If it can do that much, then it can pause the emulation on such an occurrence.

And here we are with an example.

I'm the emulator.  As the parent process responsible for core operations, I am aware that I can only catch plugin errors after the plugin sees them first.  If the plugin doesn't react to something as a plugin error, I cannot detect a plugin error _reaction_.

I try to communicate this message to the plugin.

You're the plugin.  You react to the "error" first before I have a chance to explain the problem to you because you cut off the rest of what I say and reply to the first, less significant part of my post and dismiss the rest. :)

**Comment by khionu** [comment]
If this is not technically possible, you could say so, instead of being an ass.

And no, a plugin's behaviour can and should be curtailed by the program it's plugging into. It's called designing an API.

Thank you, though, for taking the time to respond to my complaint, however inefficiently.

**Comment by cxd4** [comment]
>If this is not technically possible, you could say so,

Well, that would be inefficient, now wouldn't it?

You said that it is possible.  Me replying simply that it isn't would just be acting argumentatively.  True, though, childishly going back and forth without explaining **why** you're wrong would be much more efficient than "inefficiently" explaining everything.  That's a given.

>It's called designing an API.

On the contrary, it's called designing an operating system.  Somehow coming from the perspective of designing an operating-system-compliant API instead of an actual OS, though, you know more than they do, so I'd probably do best to back off before you get even more argumentative over it.
