### ISSUE TITLE
unable to build using VS2019 GUI

### ISSUE THREAD

**Issue by belegdol** [project64/project64#1633]
It does not seem to be possible to build project64 from git in VS2019 gui. It throws a ton of errors like

> The build tools for v142_xp (Platform Toolset = 'v142_xp') cannot be found. To build using the v142_xp build tools, please install v142_xp build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".

Unfortunately, the said "Retarget solution" option is not available. Building with MSBuild works fine.

**Comment by Azimer** [comment]
Please see my solution in #1635

**Comment by JunielKatarn** [comment]
XP support is dropped in the latest MSVC toolset (14.2).
While VS2019 supports installing both 14.1 and 14.2, `DefaultPlatformToolset` evaluates to the latter.

I've submitted #1642 to solve this the following way:
If `DefaultPlatformToolset` evaluates to `v142`, then don't prefix `_xp`. Otherwise, prefix `_xp`.

You can also build from the command line using `MSBuild.exe` with the following switch: `/p:PlatformToolset=v142`, or any other value your Visual Studio installation supports.

**Comment by bonimy** [comment]
Suggest closing since #1642 has merged.
