### ISSUE TITLE
Reopening Scripts menu hangs if you use the JS API to open a Server

### ISSUE THREAD

**Issue by snoozbuster** [project64/project64#1712]
Steps to reproduce:
--------

1. Save the following file in `Scripts/server.js` (or wherever)
```javascript
// server-hang.js
const server = new Server({ port: 8001 });

server.on('connection', function() {});
```
2. Load the script in the Debugger>Scripts... menu
3. Right click and stop the script
4. Close the scripts menu
5. Re-open the scripts menu

Instead of reopening the scripts menu, the whole emulator hangs. I'm pretty sure this is because the [file descriptor opened in Server](https://github.com/project64/project64/blob/master/Source/Project64/UserInterface/API.js#L920) isn't closed properly - I can see in `ScriptInstance.cpp` and `ScriptSystem.cpp` that it looks like there's some code intended to clean up open files, but I'm not really familiar enough with how everything fits together to see why it's not working.

With the following function added to `Server` (since the file descriptor is not exposed):

```javascript
this.close = function() {
  _native.close(_fd);
}
```

Then running this script is fine - you can open and close the scripts menu after running it and there's no hang.

```javascript
// server-ok.js
const server = new Server({ port: 8001 });

server.on('connection', function() {});

server.close();
```

If I can sort out why this is happening, happy to raise a PR - otherwise I hope this helps someone else track down the issue!

**Comment by m000z0rz** [comment]
Part of the problem with cleaning up file descriptors appears to be erasing the files after closing [inside a loop](https://github.com/project64/project64/blob/0462f637c4794eb99d81d98b569806f0ff107e89/Source/Project64/UserInterface/Debugger/ScriptInstance.cpp#L530), but that doesn't appear to be the entire problem; replacing that with m_Files.clear() after the closing loop prevented one error but still hung.

**Comment by m000z0rz** [comment]
The rest of the problem appears to involve killing a thread that holds a CGuard lock. When a running script with an event loop is stopped, the following occurs:
# ScriptSystem->StopScript is called
## That calls scriptInstance->ForceStop()
*** And that deletes listeners via CleanUp. With listeners gone, ScriptInstance's event loop thread exits the while and continues to CleanUp and SetState, which is like ForceStop but without the CGuard
## The EventLoop's thread goes on to enter a CGuard within the Debugger-System for the UI (maybe just the script list?)
## The original ScriptSystem->StopScript thread goes on to call DeleteStoppedInstances, where it frees the ScriptInstance while it still holds the UI lock

Now, when you click the script list again, it freezes waiting to get the UI lock

I think I was able to fix this by:
* Changing StartEventLoop to call ForceStop (with the CGuard) instead of just calling CleanUp and SetState directly
* Having ForceStop quit early if the state is already stopped

Not sure if that's the best way to fix it. I'll try to put a pull request together this week for it
