### ISSUE TITLE
"Default" UI has wrong value for "Memory Size"

### ISSUE THREAD

**Issue by Nicholas-Steel** [project64/project64#1747]
Currently unidentified ROM's will utilize 8MB of Memory even though the Default is set to 4MB by default.

Tested with the 15th of May 2020 release under Windows 10 x64 v1909.

**Comment by oddMLan** [comment]
This is intended. The reason is that many people wanted to make 8MB RDRAM the default for all ROMs, but it is a waste of resources if the game is not going to use it. With unknown ROMs, chances are it is a Romhack that requires the extra memory, otherwise it fails to boot. This is just saves some extra steps to change the RDRAM size for that ROM.

**Comment by oddMLan** [comment]
Now I see this could create confusion so I want to split the Defaults category in two categories: For known ROMs and for Unknown ROMs sometime in the future

**Comment by Nicholas-Steel** [comment]
Could a note be added to the Defaults UI that says 8MB Memory is forced for Unidentified ROM's?

**Comment by oddMLan** [comment]
In the meantime before more precise default options are implemented, yes that sounds like a good idea.
