### ISSUE TITLE
(JavaScript API) socket.write problems

### ISSUE THREAD

**Issue by jonathan25** [project64/project64#1787]
I found two problems working with sockets with the JavaScript API

**``socket.write`` requires two arguments**
The [documentation](http://shygoo.net/pj64d/apidoc.php#Socket) describes that the argument ``callback`` is optional (it has square brackets):

``socket.write(data[, callback])``

But when I try to pass only ``data`` a warning box appears with the title:
"Script error"
and the message:
"TypeError: Cannot read property 'apply' of undefined"

This only goes away when passing a callback function.
Also, if the warning message box is not closed and ``socket.write`` is called again it will pause the emulation and can only be resumed when all message boxes are closed.

**``socket.write`` converts numbers to strings**
I don't know if this was the intended behavior but when I try to send data like this:
``socket.write(gpr.v1, console.log);``
the data received in the other end is a string.
I checked the data type of that register or variable before sending it and it shows as "number".

**Comment by Kenix3** [comment]
I encountered this error as well.

Here is a simple script to replicate.

`var debugServer = new Server({port:3666});

debugServer.on('connection', function(newSocket) {
	newSocket.on('data', function(data){
		console.log("Socket Received: " + data);
	});
});

socketTestCon = new Socket();
socketTestCon.connect({ port: 3666, family: 'IPv4', address: '127.0.0.1' });
socketTestCon.write('BLAH!');`

**Comment by m000z0rz** [comment]
Assuming write didn't require a callback before, I think this may have been caused by my commit 4d546ee36bdad7b1929adc18dcf7e8b51d61d6dc. I'll try having singleUseCallback in API.js immediately return undefined if an undefined callback was given.

I do expect numbers will be transformed to strings here. If you want to send binary data, you'll need to use [Typed Arrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays#:~:text=JavaScript%20typed%20arrays%20are%20array,that%20these%20arrays%20are%20fast.); you can look at [Shygoo's sm64 collisions code](https://github.com/shygoo/project64/commit/48a5e1357515302f40e0287bd6c99c18bd90bf2e) for an example.

**Comment by m000z0rz** [comment]
I still have some debugging to do to find the best solution for the issue, but I did want to mention that it appears there's a similar existing issue that socket.**connect** requires a callback but documentation says it's optional. While it appears that you can get away with writing to a socket before the connect callback,

So @Kenix3  to make your script above work currently, you also need to specify a callback for connect.  I'll try to fix both the .connect and .write callbacks to be optional this week.
