### ISSUE TITLE
fullscreen shows menubar

### ISSUE THREAD

**Issue by fastrizwaan** [project64/project64#1889]
using GLideN64 for fullscreen
Bug: fullscreen is showing menubar in wine-stable (5.0.3) and wine-staging (6.0-rc4)
![Screenshot from 2020-12-28 20-38-41](https://user-images.githubusercontent.com/1161682/103223735-d5e79c00-494c-11eb-883e-f0819f732242.png)

**Comment by dftf-stu** [comment]
@fastrizwaan: as WINE means running _Windows_ apps on _Linux_, can you confirm if you run the same-version of _Project64_ on a _Windows_ system, with the same settings and plug-ins, does the same issue occur?

I'm not sure if alternatives to _Windows_, such as _WINE_ and _ReactOS_, would officially be supported -- @project64 may be able to confirm?

**Comment by AriaHiro64** [comment]
why are you using an old version of wine in the first place?

**Comment by dftf-stu** [comment]
> @AriaHiro64 wrote:
> why are you using an old version of wine in the first place?

They weren't when this ticket was first raised... 5.0.3 [was released](https://www.winehq.org/news/75) 10 Nov 2020, and 6.0-rc4 [was released](https://www.winehq.org/news/50) on 26 Dec 2020, just 2 days before the user originally raised this ticket.

Not really their fault that no-one has replied in the just-over 1 year and 7 months since they first logged it!

**Comment by project64** [comment]
sounds like a wine bug

**Comment by ariahiro64** [comment]
no its an old wine bug not a pj64 bug. proton fixes it 
![image](https://user-images.githubusercontent.com/45049787/183824940-91f6d48d-d0f2-488c-b6b8-20ee0bbb198b.png)

**Comment by fastrizwaan** [comment]
> no its an old wine bug not a pj64 bug. proton fixes it !

proton ge ? which version?

**Comment by ariahiro64** [comment]
i used 7-3 so latest stable
