### ISSUE TITLE
RSP Interpreter lle graphics issue(s) in SD Hiryuu No Ken Densetsu

### ISSUE THREAD

**Issue by LegendOfDragoon** [project64/project64#2]
Here's a screenshot of the intro  with RSP interpreter, using HatCat's fork of Angrylion's plugin for graphics.
![sd hiryuu intro](https://cloud.githubusercontent.com/assets/10492645/5850658/8b0437bc-a1ae-11e4-89da-679432d8547d.png)

Here's what it looks like in a match, also using zilmar's RSP interpreter.
![sd hiryuu match](https://cloud.githubusercontent.com/assets/10492645/5850662/a0288dc8-a1ae-11e4-96cf-800358b998e2.png)

**Comment by cxd4** [comment]
I have also file a RSP pj64 interpreter bug here:
https://dl.dropboxusercontent.com/u/16494013/n64/Quake%2064%20%28U%29.pj.zip

I will look at this issue and mine in the next few days to see if they might be coinciding, thanks.

Also feel free to edit your message to use GitHub's native image uploading feature so that they show directly in the post--do you mean that the second one "what it looks like in a match" is with PJ64's RSP, while the first one is with mine?

**Comment by LegendOfDragoon** [comment]
Both previous screenshots were taken with zilmar's RSP interpreter. I had trouble with save states, so i didn't post a comparison picture. it turns out, zilmar's RSP was also responsible for the save state problem. I'll go ahead and edit 1st post to use native image uploading feature.
Here's a decent comparison picture. I didn't take the pictures at the exact same in-game time frame.
This is with zilmar's RSP
![sd hiryuu bad](https://cloud.githubusercontent.com/assets/10492645/5850632/121d7778-a1ae-11e4-8a0b-49b3d8f48ca2.png)

This is with HatCat's RSP
![sd hiryuu good](https://cloud.githubusercontent.com/assets/10492645/5850639/2681cba6-a1ae-11e4-98da-3267b32dc8f1.png)

**Comment by cxd4** [comment]
Okay.
Now try with this commit:
https://github.com/cxd4/project64/commit/5b346077ef536a42f79ffb1b914f9dcf62f1bd6f

Your issue here looks pretty similar.
Tell me if my commit to RSP 1.7.0.9 has fixed it.

**Comment by LegendOfDragoon** [comment]
Ya that fixed the gfx issues. Nice job!

**Comment by cxd4** [comment]
The issue is fixed now in the master branch:
https://github.com/project64/project64/commit/2dd4e99ed692be9fc207c02072af432189ca833d

With this commit project64 upstream should have the issue fixed in the RSP interpreter now.

You can close this issue / mark as solved now if you like.
Unless the game still has same gfx bugs in recompiler...mine does, so I am leaving mine open.

**Comment by LegendOfDragoon** [comment]
The main issue is fixed. There's one other problem (probably related to your as well). I guess I will close mine and report another issue I forgot about.
