### ISSUE TITLE
Project64 Input Plugin

### ISSUE THREAD

**Issue by CCrashCup** [project64/project64#2019]
## Expected behavior
Select Rumble Pak in the Options from the Configure screen for the controller. Should save the setting between Project64 launches.

## Actual behavior
It resets to Mem Pak upon exit.

## Steps to reproduce the problem

  1. Go to the Options window.
  2. Select Rumble Pak from the drop down.
  3. Click OK.
  4. Click OK.
  5. Close/Exit Project64.
  6. Run Project64 again.
  7. Go to the Options window.
  8. In the drop down, it shows Mem Pak.
 

## Specifications

  - Windows version: 10
  - Project64 version: All 2.4.0
  - Plugins used: Project64 Input Plugin

**Comment by vgturtle127** [comment]
Did you try the latest development version from https://www.pj64-emu.com/nightly-builds ?

**Comment by CCrashCup** [comment]
I said "All 2.4.0".
Unless a nightly build comes out that has this issue specifically addressed, then I will only try the latest one every month or so.
As of the date of my first post, the latest nightly build had the same issue.

**Comment by vgturtle127** [comment]
I didn't know what you meant by "2.4.0" since all commits after 2.3 are 2.4, so I couldn't tell if you were on a really old build or something from a few days ago. Sorry.

**Comment by legend800** [comment]
I can confirm this issue is still active. Been present for a long time from what I can tell. Everything else in Controller settings and this window save fine. 

![2021-03-27 14_29_35-Options - Player 1](https://user-images.githubusercontent.com/20983844/112735394-de7a4f00-8f08-11eb-9cf8-5f19eed9bc33.png)

**Comment by CCrashCup** [comment]
Bump this.

**Comment by IronYoshi64** [comment]
Yes, lets see if we can get this fixed.

**Comment by ssylvester87** [comment]
Confirming problem still exists in 3.0.1
(can't use stone of agony in OoT randomizer)

**Comment by legend800** [comment]
I can verify this issue is fixed. Ty! 
But I'm still getting no rumble on my Xbox pad. Does it not support xinput rumble? Is there an issue tracking this? 

I know nrage does, but there's some limitations to that plugin which is why I want to use the internal plugin (need to adjust the c-stick input).

![2021-07-11 00_52_01-Window](https://user-images.githubusercontent.com/20983844/125187151-01dcb780-e1e3-11eb-874a-8ab6cbd113b0.png)

**Comment by Squall-Leonhart** [comment]
its a DirectInput plugin, that much is obvious from the naming of the stick axes

**Comment by legend800** [comment]
So nrage is the only way to get rumble on xbox pads on PJ64 and using a 3rd party app (xinput+) is the only way to adjust the stick mappings? Hopefully some kind of invert or full u/d/l//r adjustments can be added like other emus. 

![2021-07-11 09_49_22-Window](https://user-images.githubusercontent.com/20983844/125203461-4ab95e00-e22d-11eb-94c0-f7c3dbdfc627.png)

**Comment by Squall-Leonhart** [comment]
No, there is a way using the Mori Force Feedback Driver for XInput, and customizing the registry

[Xbox_Vibration.zip](https://github.com/project64/project64/files/6797299/Xbox_Vibration.zip)

duplicate any of the reg files and do a search replace of the VID and PID with that of your controllers

**Comment by dezraj** [comment]
> 

Hello Squall! Do you know if the drivers in this page have the same effect as yours?
http://lavendy.net/special/driver/xi/index.html

Yours has a more recent date of modification (2019), but the sizes are the same.

Thank you so much!

**Comment by CCrashCup** [comment]
dezraj, they are the same, written by Masahiko Morii.
