### ISSUE TITLE
3.0.1.5664-df3434 Regression #566 Win10 BSOD (even with Win7 compatibility mode)

### ISSUE THREAD

**Issue by Bogged** [project64/project64#2163]
X570 mobo with Ryzen 5950x and nvidia GTX 1650 with latest drivers.

Occasional PC reboot while playing Rocket Robot On Wheel. I tried win7 compatibility mode and even XP without success.
It's playable as it sometimes can take a couple of hours before crashing.

**Comment by Squall-Leonhart** [comment]
fix your computer.

**Comment by dftf-stu** [comment]
@Bogged: don't use the compatibility modes, they're likely to cause issues and are unnecessary, given the latest versions of _Project64_ support _Windows 7_ and later anyway!

Are you using either the most-recent stable version 3.0.1.5668 (there is a 5669 release, but it only updates the Japanese translation, so unless that's what you use, you don't need it), or the most-recent unstable version, 4.0.0.5871?

If not, download the ZIP files of those from [here](https://www.pj64-emu.com/public-releases) and [here](https://www.pj64-emu.com/nightly-builds) and test _Rocket: Robot on Wheels_ in both and confirm if you still have an issue, along with what version of _Windows_ is installed on your PC.

**Comment by Squall-Leonhart** [comment]
this isn't a software issue, its a hardware issue.

**Comment by dftf-stu** [comment]
@Squall-Leonhart: maybe so, but still best not to be passive-aggressive with someone asking for help... many open-source or non-commercial projects thesedays are increasingly getting a bad-rep in the tech community for being unwelcoming

**Comment by Squall-Leonhart** [comment]
Good, can't let end users think this is a service society where the customer is always right.

**Comment by dftf-stu** [comment]
@Bogged: as I can see you've visited this post recently, to upvote and downvote, and you able to share any further information -- have you tried the game in the most recent 3.0.1 and 4.0.0 versions?

**Comment by Bogged** [comment]
@dftf-stu : No, I finished the game and moved on.  The c*nt response I got initially didn't put me in the mood to help investigate any further. Especially that my broken computer worked like a charm before and never crashed after I quit using 3.0.1.5664-df3434. Thanks for asking, I appreciate.

**Comment by Squall-Leonhart** [comment]
Cool story bro, fix your computer.

User mode software can't bsod your computer.

**Comment by flagrama** [comment]
Github really isn't a valid place to look for or provide support. It's meant for reporting something that seems like a bug or a feature request. If it can be confirmed to be a bug with the software or a feature request it is fine. The Discord is the clearly defined location to go to for support in the readme. More synchronous communication than comments which most people won't even have notifications for responses anyway.

It's really annoying to have the github notifications and channels dedicated to reporting github updates on Discord filled with support questions. I think there were like 50 today. Makes it impossible to see if any new work or bugs or feature requests have been posted. I can understand why Squall would be annoyed.

---

Of course there doesn't seem likely to be a software bug on PJ64's side. You're the first person in years I've seen mention getting a BSOD just from running PJ64, so it does seem more likely to be a hardware or software configuration issue on your computer. Just because a single version of PJ64 somehow hits something your computer doesn't like doesn't necessarily mean it's a PJ64 issue.

If you have any friends who have a similar setup to yours, or that have other hardware you can test with by swapping out I recommend doing that. If you can prove it happens on multiple hardware configs it makes more sense to take a look at it as a PJ64 issue. At the same time you may narrow it down to a piece of hardware you own being partially faulty.

For example, I have a couple graphics cards that were used in mining rigs for a while. They have very subtle VRAM issues that never show up on Windows, but you can see a massive issue with them on Linux when the compositor starts freaking out after fullscreening a video. Clearly a hardware issue, not a software one. It feels like this might be a similar issue.

**Comment by dftf-stu** [comment]
@flagrama: "The Discord is the clearly defined location to go to for support"

But WHY?  Why must seemingly EVERY open-source or non-commercial project thesedays force people to have to use selective social-media?  Just like how big-companies seemingly now only offer you support via Twitter or Facebook.

This just discriminates against people who don't wish to use such social-media...

**Comment by flagrama** [comment]
Because nobody ever used the forums :laughing:

**Comment by dftf-stu** [comment]
@flagrama: many Forums or Message Boards back-in-the-day where a pain-in-the-backside to use: slow, clunky designs, awful search functionality, nuisance to format your text properly, often didn't allow attachments (in some cases, unless you'd reached some sort-of "approved" status by the admins).  Oh, and not to mention the "good-old-days" of the browser wars when it wasn't guaranteed sites would work properly in all web-browsers.  So... not surprising why!

But I highly doubt that many people thesedays equally join _Discord_ immediately after encountering an issue either.  They'll just try and play a game, and if they get constant errors, _Google_ it, find some old _Reddit_ posts dating-back to something like the mid-2000s with advice that no-longer applies to the current versions of _Project64_, get frustrated when nothing seems to work, and move on.

**Comment by flagrama** [comment]
Weird how people use Discord instead because it does most of that stuff better. Plenty of people do join the Discord just because they need help. The majority of people would prefer to use Discord because they're already on it with their friends. The ones who don't can create a temporary account which they can either set up to be a full account later, or leave to rot (or to accidentally create even though they already have an account but weren't logged in on the device they are using)

Github Issues is not intended to be a support or general discussion medium. You're looking for https://github.com/project64/project64/discussions but most of us forget it's even there.

**Comment by dftf-stu** [comment]
Yeah, have to say I'd never-even noticed that the "Discussions" was a thing.  (And given on the default "View all" filter there are only 18 chats in-total, I'd say neither do most-other people!)

I guess if that's just the way things are I'll have to look at joining _Discord_, though I still find it mad that despite _Project64_ being-around now for over 20 years, it's still necessary to have to go somewhere to ask people what settings need to be altered just to get certain games to work.  Needless to say, that sure sucks the fun out of spontaneously wanting to just play a game!

**Comment by Bogged** [comment]
To be clear I never came here for support. Felt like a known bug returning. Thus the regression reference. I just wanted to report. But the God of Software has stated that it's a Hardware problem. Cauz you know... No bad programming can BSOD a computer. (So he says). BTW Compatibility mode was a workaround suggested back on the initial bug known to BSOD Windows as well. Other than that I couldn't care less.

**Comment by Squall-Leonhart** [comment]
If there was a known bug returning it would be up to microsoft to fix because all Luigiblood did was worked around a security vulnerability in a windows kernel driver.

https://www.exploit-db.com/exploits/41880

**Comment by project64** [comment]
likely a windows issue not a project64 one
