### ISSUE TITLE
CD64 Memory Test (PD) way too slow on recompiler

### ISSUE THREAD

**Issue by cxd4** [project64/project64#219]
_CD64 Memory Test_ (PD) is fast enough on the interpreter.
If you set "CPU core style" in RDB to "Interpreter", it runs at 34 VI/s.

If it's kept at the "Recompiler" setting, it never exceeds 2 VI/s, even with the Virtual Lookup Table and no self-modifying code methods.  (Execution does seem to continue normally though; it's just that you have to wait a while to confirm that with a measly 2 VI/s.)
![cd64_mem](https://cloud.githubusercontent.com/assets/1396303/6511332/1bc54870-c33a-11e4-97e6-0519236f4d3a.png)

RDB settings:
![cd64_rdb](https://cloud.githubusercontent.com/assets/1396303/6511358/5627effe-c33a-11e4-8109-0ff03b54c74c.png)

Again, if you change to use the interpreter, the ROM runs at like at least 30 VI/s, instead of just 2.

**Comment by project64** [comment]
One of my original ideas that it would be quicker to generate an exception if you read out side of memory instead of checking if the address is valid on every read/write. 

something that is continually generating exceptions because it is reading non valid memory is going to be extremely slow. 

the interpreter because it can not cache and pre-detect if it would be to memory or not would be even worse normally so it actually does checks for if it is valid memory or not and able to detect so that is why it is a lot faster in the interpter.

**Comment by cxd4** [comment]
You could also probably add an extra check to the recompiler that happens outside of the scope of compiling a block perhaps.  If this memory range checking is implemented with enough prediction ahead of time you would lose no performance from doing this check in the recompiler.

Otherwise, I'll send a pull request changing this game to use the Interpreter RDB setting, and if that is merged I can close this issue if you don't want to add the check to compiler.

**Comment by cxd4** [comment]
>the interpreter because it can not cache and pre-detect if it would be to memory or not would be even worse normally so it actually does checks for if it is valid memory or not and able to detect so that is why it is a lot faster in the interpter.

More accurate that way.

**Comment by cxd4** [comment]
Fixed in https://github.com/project64/project64/pull/231.
