### ISSUE TITLE
Should SP Hack be enabled for EVERY SINGLE game?

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#222]
I discovered that SP Hack was making Infernal Machine crash. And then I discovered that the setting is enabled by default for all games in 2.x, while it was disabled by default for PJ64 1.6 Do you think this could be causing problems?

I quote:
"This option was added in v1.5 simply as a performance feature - enabling it gives typically 5% more speed from the core, however a large numbe of games will not be stable with it enabled, therefore it's not set often. Try it if you are desperate for speed, but for most people most of the time it's recommended you leave it off."

**Comment by project64** [comment]
in theory it should not cause any problems with giving a 5% speed increase .. but that does not mean it actually 100% bug free .. it detects most of the common cases of using the SP register, but there could be something in that game that is not covered and needs to be.

**Comment by cxd4** [comment]
It's about the same question as, "Should Advanced Block Linking be enabled for every single game," and, "Should Register Caching be enabled for every single game?"  Like using the re-compiler in the first place instead of the interpreter, it's enabled for every game by default tested to work with it.

**Comment by AmbientMalice** [comment]
Fair enough.
