### ISSUE TITLE
Strange Audio Judder during Factor 5 Star Wars Opening Crawls.

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#228]
When beginning a new game in either Rogue Squadron or Battle for Naboo, the game displays the classic Star Wars crawling text. And the sound proceeds to shit itself. Imagine the Star Wars theme being sung by Porky Pig. Saving the game and then loading a save state has no effect... UNLESS you quit PJ64, restart the game, and then load the save state. Viola, perfect music.

**Comment by LegendOfDragoon** [comment]
I think fixed audio timing is the problem. It sounds fine without it.

**Comment by AmbientMalice** [comment]
@LegendofDragoon Maybe I'm doing something wrong, but it sounds terrible without FAT with a variety of VI/AI values.

Just so we're clear, this issue only affects the SW text crawls. With 2200/785 & FAT the rest of the game's audio is fine-ish. And the game behaves entirely differently if you save during the crawl and reboot PJ64, compared to just loading the save state. I have seen something similar with RE2 - if you boot the game and immediately load a save state, the music can be juddery.

**Comment by LegendOfDragoon** [comment]
Pretty sure the AI setting only effects audio when fixed audio timing is enabled.

The reason these games generally sound better in Mupen is because Mupen does more of the audio work, rather than letting the audio plugin do it.

The problem with fixed audio timing is that certain parts of a game may need a different number, so fixed audio isn't ideal, except for netplay or debugging.

Not to say that there aren't improvements in the core that could be done. Sometimes when I load a save state in Rogue, i lose audio. But when i enable fixed audio timing, I never lose audio.

What audio plugin are you using for these games?

I will say though, that sounds weird if loading a save state fixes the issue. So perhaps the core may need some fixing.

**Comment by AmbientMalice** [comment]
I'm primarily using Jabo 1.7 for sound. But fortunately, Azimer's seems quite happy with the new 2200/785/FAT settings most of the time.

But yea... this juddery audio business is very strange. If you get load a save state from a normac part of the game while the text crawl is running, it will carry the bad audio across.

After quitting and loading a save state where the judder was present, the audio will be running too slowly.

On a related note, WDC and Stunt Racer both have constantly juddering sound for me. I've been unable to fix it.

**Comment by LegendOfDragoon** [comment]
Generally, I'd recommend Azimer's for Factor 5 games. With fixed audio timing enabled in Rogue Squadron, you're probably better off enabling "Old sync" in Azimer's plugin.

As for WDC, I can tell you, a significant source of the problem is the audio plugin. So far, Zilmar's audio, 1964 Audio, Azimer 0.70 DS8 WIP 4, and shunyuan's have good audio for that game. Too bad Azimer's 0.70 DS8 uses an extra full core of cpu ;/ . Too bad 1964 Audio doesn't work well with PJ64.

**Comment by AmbientMalice** [comment]
Has anyone been in touch with Azimer about updating his plugin? I recall him intending to support MusyX in HLE, likely using Bobby Smiles's work from mupen64plus. Plus a bunch of other improvements.

TBH, it's a little annoying how so many N64 plugins are closed source. I don't begrudge people wanting to protect their work, but it throws a spanner in the works when it comes to obscure bugs.

Also, the trouble with PJ64's audio is that Jabo, clunk and closed source and alll, is a darn good plugin. It just... works for most games. Wheras the other plugins, with rare exceptions, tend to have mixed compatibility. If Azimer's could be cleaned up and improved, and preferably open sourced, it could be a good replacement for Jabo as the default PJ64 audio plugin.

**Comment by Frank-74** [comment]
Azimer 0.70 DS8 WIP 4 has Bobby Smiles's work in it.  That's why its recommended to use it for musyx in HLE.

**Comment by LegendOfDragoon** [comment]
Lol ya, it's a shame a lot of good plugins are closed source. Not like anyone would even do something with the source though xD. I wish I could figure out how to get proper audio in games like WDC and Rogue Squadron, without relying on closed source plugins.

Iirc, 0.70 WIP2 and up have bsmiles' HLE musyx. Azimer said he would eventually make it open source after fixing things up.

I like Jabo's audio, but I hate how the audio sync is messed up in games like Quest64. it's all game specific as to what audio plugin to use. For instance, I use Jabo's for Last Legion, Super Smash Bros, F-Zero, etc. I use Azimer's for Rogue Squadron, Quest64, etc. Sadly for WDC, I'll have to either use 1964 Audio or Shunyuan's ;/ . I like 1964 Audio, but it doesn't work well with PJ64.

**Comment by AmbientMalice** [comment]
Azimer's WIP4 crashes for me with a lot of games including WDC. This is apparently caused by PJ64 fixing a bug that was fixed in WIP4 and the fixes conflict?

**Comment by LegendOfDragoon** [comment]
>Azimer's WIP4 crashes for me with a lot of games including WDC. This is apparently caused by PJ64 fixing a bug that was fixed in WIP4 and the fixes conflict?

The WDC crash is a different issue. It's a regression in his WIP4 XA2. The crashes regarding WIP4, after the plugin spec fixes was for loading save states.

That's another issue ;/ . I personally like 0.70 WIP2, but it's a shame it has a threading problem. Fortunately, it's easy to fix, via ollydbg. Odd thing is, different versions work better for different games. For instance, the audio quality in 0.70 DS8 WIP4 is much better than any other version of his plugin, for WDC.

**Comment by LegendOfDragoon** [comment]
After tweaking 1964 Audio a bit, I get very good audio for Rogue Squadron. Best plugin for the game actually. So I don't even need FAT anymore for this game. Only issue I'm currently aware of is loading save states are bugged, but I got more work to do, for stabilizing the plugin.

**Comment by AmbientMalice** [comment]
Do the opening crawls judder still, or is that fixed?

Also, what about Resident Evil 2? Being able to get smooth SFX and voices that are timed correctly without FAT fiddling would be ideal. (And a lot trickier than most games. Mupen64plus falls flat on its face trying to run RE2's audio.)

Do you think a modded 1964 sound plugin could be a good default once it is fixed up?

**Comment by LegendOfDragoon** [comment]
>Do the opening crawls judder still, or is that fixed?

Fixed when set up correctly. It seems that buffer size makes a huge difference in the audio, for that game. Most audio plugins don't let you configure the buffer size (1964 audio included), so that's a reason why some games have poor audio.

>Also, what about Resident Evil 2?

Good question, I haven't really tested audio for that game. I should try and see.

>Do you think a modded 1964 sound plugin could be a good default once it is fixed up?

I wouldn't recommend it as a default. It just happens to do well on some troublesome games. For instance, Nuclear Strike, WDC, and Rogue Squadron all sound good with this plugin, yet most other plugins have issues in these 3 games.

For most games, I've had much better luck with experimenting with Azimer's 0.55. Ironically, I spent quite a bit of time trying to fix WDC, musyx games, and Nuclear Strike. Not much luck, other than improving WDC (still not as good as Azimer's DS8 WIP 4). I figure I'm better off just alternating between like 2 plugins, than to spend countless hours getting perfect audio in every game for 1 plugin. Maybe eventually I could overcome some more obstacles.

**Comment by AmbientMalice** [comment]
2 plugins seems like a fine compromise. Do you think it would be acceptable to use PJ64's per-rom settings to define specific plugins as defaults once everything is in order?

I must warn you, though, that one reason I was resigned to using FAT in the first place is that without it, certain games jam up if the framerate dips for extended periods. An example would be Indiana Jones. (It's ALWAYS this bleeding game.) At the pyramids, Indy will walk over to a sign, say a line, and then his second line comes out as garbage, followed by random speech samples. I'm not sure whether this will prove easy to fix with 1964 audio since Azimer's seemed affected, too. And of course RE2 is prone to losing its sound effects without FAT, leading for freezes.

But on the topic of save states - it'd be nice to cure the bug that affects games such as Turok 3. Loading a save state immediately after booting will result in no sound, followed at some point by a freeze.

**Comment by LegendOfDragoon** [comment]
>2 plugins seems like a fine compromise. Do you think it would be acceptable to use PJ64's per-rom settings to define specific plugins as defaults once everything is in order?

I agree that 2 plugins is a fine compromise. Yes, it would be acceptable to use PJ64's per-rom seetings. Per rom settings are also very nice. One thing that holds developers back, is dealing with backwards compatibility. For instance, most other emulators don't even use RomOpen for audio plugins ;/ . I'm considering just modifying the source of older emulators, rofl. Just to make things simpler. I know Shunyuan already did this with PJ64 1.6. In fact, these sort of differences are a reason for certain bugs in plugins.

Alright, I'll try experimenting with some of these games you mentioned, this week. In RE2, what do I do, for testing? Do i just start a new game and play a bit? I don't really play the game, so I'd like to know what parts have serious issues.

**Comment by AmbientMalice** [comment]
There are a few things to look for.

Opening FMV. (This is the one after you start a New Game.) I was testing with Claire's version, here is Leon's recorded from a real N64 for reference. http://youtube.com/watch?v=AfsxcnEhVQk

Check for missing sounds, missing voice acting. Bad settings will result in the SFX disappearing towards the end of the video, when the truck appears, hits a car, and then crashes. Also compare with YT video to see whether audio timings are off. (Watching that FMV over and over again can be rather exhausting, mind you.)

Ingame, run up the street, enter the alley, then enter the gun store. Abuse quicksave during the cutscene if you want to test save state stability. This cutscene is a good test of the MORT speech codec.

**Comment by AmbientMalice** [comment]
Also, @LegendOfDragoon how soon do you think the 1964 plugin will be available for testing? Not trying to put pressure on you or anything.

**Comment by LegendOfDragoon** [comment]
Ok, I did some testing in RE2. Looks like the only decent plugin w/o FAT is Azimer's XA2. I say decent because there didn't appear to be any voices missing in the FMV. I need to review that video you linked, so I can figure out what needs to improve. I haven't seen Azimer's XA2 lose sound yet either (during the FMV). Haven't tested save states yet.

As for Rogue Squadron, I'm at a loss as to why loading a save state is bugged. Sound is still running, but it's just broken. One interesting thing you can do is load a save state with 1964 Audio, and switch to Azimer's at runtime (if you like using Azimer's). That proves that the issue is the plugin spec (either plugins did implemented certain functions wrong, or pj64 2.2 needs to refine the plugin spec). That's somewhat good news, because I'm sure the Turok3 problem is related. One interesting thing about Rogue Squadron with 1964 Audio, is that it needs CF=1. The audio was messed up during the opening credits with CF=2.

>Also, @LegendOfDragoon how soon do you think the 1964 plugin will be available for testing? Not trying to put pressure on you or anything.

No worries. Fortunately I have enough time and interest to get things done :) . It depends on how soon I reach success. Right now, there's too much experimental code, so I want to figure out certain things first. I also need to decide a few things, after stabilizing it. Such as the name, whether to have a configurable buffer size, and what to do with the HLE code (i think I want to discard it for now). The HLE code makes it take a long time to compile, and the performance is slower than PJ64's RSP recompiler. This week, hopefully I'll learn more about the Dsound API so that I can fix some of these issues. Again i need to mention that this plugin isn't suitable for most games. It just works well with certain games.

**Comment by AmbientMalice** [comment]
>One interesting thing about Rogue Squadron with 1964 Audio, is that it needs CF=1. The audio was messed up during the opening credits with CF=2.

I personally think all the Factor 5 games likely need CF=1 for best operation. (Plus it gives a lovely framerate boost for Ep 1 Racer.)

>what to do with the HLE code (i think I want to discard it for now).
I'm of the view that LLE audio emulation is generally better, particularly for N64 emulation.

>Again i need to mention that this plugin isn't suitable for most games. It just works well with certain games.
I understand that, but it fills a valuable hole.

**Comment by LegendOfDragoon** [comment]
>I personally think all the Factor 5 games likely need CF=1 for best operation. (Especially since Indiana Jones goes weird with CF=2+) (Plus it gives a lovely framerate boost for Ep 1 Racer.)

Ah, good to know. Especially about Ep1 Racer. I started switching to CF=1 for many games after figuring out how to get good audio :) .

>I'm of the view that LLE audio emulation is generally better, particularly for N64 emulation.

Good to see other people on board. I guess I will strip out the HLE code. As for the name, I'll prolly just call it 1964 Audio 2.8 I guess xD.

I really need to find a good way to deal with the plugin spec issue(s).

>I understand that, but it fills a valuable hole.

Ya, just didn't want to get anyone's hopes up, xD.

**Comment by Frank-74** [comment]
I wish an audio plugin would support ASIO.  Its miles better than any directsound or XAudio2.
If you don't have an ASIO driver for your soundcard or onboard sound.  There is ASIO4ALL which is a Universal ASIO Driver For WDM Audio.  I use it on an old 1Ghz laptop, and get latency of 10ms at 48khz, instead of 384ms with default drivers.  Soundcard in my PC is an old M-Audio Delta 1010, which has ASIO drivers.  Out of dozens of emulators, there is only one zx spectrum emulator that lets me select my ASIO drivers.

**Comment by LegendOfDragoon** [comment]
>I wish an audio plugin would support ASIO. Its miles better than any directsound or XAudio2.
If you don't have an ASIO driver for your soundcard or onboard sound. There is ASIO4ALL which is a Universal ASIO Driver For WDM Audio. I use it on an old 1Ghz laptop, and get latency of 10ms at 48khz, instead of 384ms with default drivers. Soundcard in my PC is an old M-Audio Delta 1010, which has ASIO drivers.

Hmm. Well I think the issue is compatibility. DirectSound just works with a lot of hardware, so it's kinda convenient. I don't even know if I have an ASIO driver (probably not). I'm all for using the best API's for my hardware. I just need to figure out what works best for me.

**Comment by Frank-74** [comment]
ASIO is by Steinberg, originally a Mac driver and used by music software like Cubase.  Luckily there is http://www.asio4all.com , a universal driver for software that supports ASIO, for PC's/Laptops that don't have ASIO native drivers.

In terms of performance/latency with audio.  A modern 4Ghz Quad Core desktop PC with XAudio2 might come close to the performance of a 10 year old 1GHz Celeron Laptop with ASIO4All driver.

**Comment by LegendOfDragoon** [comment]
Is there an audio plugin that never loses sound with FAT disabled in Rogue Squadron? Unfortunately, in rare ocassions, I lose audio with 1964 Audio in Rogue. Not often, but it does happen ;/ . Interesting thing is that loading save state worked fine with 1964 Audio (for audio anyway) in 1964 1.1. Of course the game is broken in that emulator unfortunately ;/ . I'm thinking that the plugin spec might need some modications. I reckon other games, like WDC's load state problem are also related.. I may try testing 1964 0.85 and see if  the audio ever disappears there, for Rogue.

>ASIO is by Steinberg, originally a Mac driver and used by music software like Cubase. Luckily there is http://www.asio4all.com , a universal driver for software that supports ASIO, for PC's/Laptops that don't have ASIO native drivers.
In terms of performance/latency with audio. A modern 4Ghz Quad Core desktop PC with XAudio2 might come close to the performance of a 10 year old 1GHz Celeron Laptop with ASIO4All driver.

I've heard of ASIO before, but never heard about ASIO4ALL. Sounds interesting. From what I've read today, I hear a lot of praise, but also some complaints. If I were to consider WinXp support, I'd probably choose asio4all. I'm kinda leaning towards WASAPI. They say it's easier xD. First, I have to fix issues with DSound plugins though, before I start trying out other API's.

**Comment by LegendOfDragoon** [comment]
Is this still an issue with the new FAT code?

**Comment by AmbientMalice** [comment]
@LegendOfDragoon Haven't tested yet. Partially because PJ64 is now refusing to boot any games. I think a recent commit broke something.

**Comment by LegendOfDragoon** [comment]
I believe the problem was that the frequency is set to 32khz during that Opening. Most of the game is at 22khz I believe. So you'll have to use AI = 0, if you want to use FAT, because none of the others are dynamic.

@AmbientMalice , I believe the crackling might be caused by the audio plugin. I think this issue can be closed now :smiley: .

**Comment by AmbientMalice** [comment]
Not sure when it happened, but this issue seem to be back. Juddering audio during scroll regardless of FAT being enabled.

**Comment by LegendOfDragoon** [comment]
Not going to entirely blame Jabo's plugin, since FAT isn't perfect, but other plugins seem to be fine for this game. 1964 audio and Shunyuan's seem fine.

Also, Rogue Squadron is another game that requires really good performance in order to get good audio.

**Comment by AmbientMalice** [comment]
@LegendOfDragoon It runs at about 140VIs during the text crawl for me. It's a rather odd little issue. Rest of game sounds fine. This one section has stuttering audio.

**Comment by LegendOfDragoon** [comment]
What I find odd is that you say the rest of the game sounds fine :smile: . Only thing you can do really is tweak the buffer settings if you insist on using Jabo's. Other plugins sound much better on my end.

The FAT code can be tweaked, but it could cause regressions in other games. As I said earlier, that part of the game changes the frequency from 22khz to 32khz. Maybe his plugin doesn't handle mid-game frequency changing properly. I don't think too many games do that, other than the very beginning.

**Comment by LegendOfDragoon** [comment]
I'm convinced Jabo's plugin isn't ideal for musyx games, just like Boss studios games, based on current FAT code. I tried Tarzan and it's pretty bad. Even Azimer's DS8 sounds better in Tarzan, based on brief testing.

**Comment by LegendOfDragoon** [comment]
@AmbientMalice does this happen with other audio plugins?

**Comment by AmbientMalice** [comment]
It happened with Azimer's DirectSound in my recent testing. Haven't tried XAudio build in quite some time.

**Comment by vgturtle127** [comment]
@LegendOfDragoon Uh, Jabo's is definitely not good for MusyX audio. :laughing: 

MusyX is fairly hard to emulate comparatively speaking. You should use Azimer's for MusyX audio in games that use it.

I have only tried Azimer's and Jabo's for MusyX, and they both seem to handle it somewhat poorly.

**Comment by LegendOfDragoon** [comment]
You're right that it happens with Azimer's DS8. Doesn't seem to happen with the XA2 version though. Seems like no matter what I do, I cannot get perfect audio for this game.

>You should use Azimer's for MusyX audio in games that use it.

Why would you recommend I use Azimer's if you said it handles it somewhat poorly?

**Comment by vgturtle127** [comment]
@LegendOfDragoon I meant as opposed to Jabo's, which doesn't handle it well at all. Azimer's at least tries...The XA2 version seems OK, but sometimes the audio clips slightly before it is supposed to.

There was a project that documented all the MusyX stuff, right? I mean even the GameCube and other systems version of it?

**Comment by LegendOfDragoon** [comment]
>There was a project that documented all the MusyX stuff, right? I mean even the GameCube and other systems version of it?

Don't know what you're talking about, but I did find this https://archive.org/details/MusyXAudioToolsForNintendo64AndGameBoy . It's an interesting read so far.

**Comment by vgturtle127** [comment]
@LegendOfDragoon Thanks, I will read the whole thing cover to cover. :smile:

**Comment by Nyerguds** [comment]
Is there any real converter for the MORT format? In the N64 ROM of Command & Conquer I found actual .mrt files with a file header starting with "MORT". I'd love to convert them to plain WAV somehow.

**Comment by vgturtle127** [comment]
@Nyerguds Have you tried N64 Sound Tool?

**Comment by Nyerguds** [comment]
@vgturtle127 I did. It extracts midi music and sound fonts from ROMs,  But MORT is an audio _sample_ format, and I got extracted files. The author of that tool is in fact also looking for ways into the MORT format.

**Comment by vgturtle127** [comment]
@Nyerguds 
Ok, just curious if maybe it supported it. Thanks for being way more proactive then most people. Haha.

**Comment by Nyerguds** [comment]
@vgturtle127  I'm making a tool to edit and convert all file formats inside the N64 Command & Conquer ROM, so yea, this one's a bit of a missing link.
https://forums.cncnet.org/topic/6694-cnc64-file-converter-released/

**Comment by vgturtle127** [comment]
@Nyerguds Cool! I will definitely keep an eye on it.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
