### ISSUE TITLE
Killer Instinct LLE resolution is not correct while using LLE plugins

### ISSUE THREAD

**Issue by theboy181** [project64/project64#23]
While testing Killer Instinct in Mupen 0.5 I noticed that the exact same LLE plugins I was using in PJ64 were outputting a lower resolution (320x240). Should be 640x480, and I believe its interlaced. This is odd that it happens in this game and think this issue might be larger than this particular game.

**Comment by LegendOfDragoon** [comment]
Mupen64 0.5 forces expansion pack to be enabled. So keep that in mind.

**Comment by theboy181** [comment]
This game came out before the expansion RAM did and has no impact on the output in PJ64

**Comment by LegendOfDragoon** [comment]
I see. Had to make sure you knew though.

**Comment by cxd4** [comment]
Yes that is an issue with Project64.

Project64 does not administrate the VI_V_CURRENT_LINE_REG or other video interface registers for handling interlacing of raster scanlines sent thru the VI.

Currently only Mupen64 0.5 seems to have that implemented.

**Comment by cxd4** [comment]
Just noticed something about this issue report.
It says "while using LLE plugins".

This is only an issue with Project64, if you are using pixel-accurate plugins (either LLE or HLE, or zilmar's Basic CFB Plugin, either way really).  It's not a visible issue with Project64 if you're using a hardware-accelerated triangle-rendering graphics plugin, such as z64gl, Jabo's Direct3D or Glide64, no matter whether it is HLE or LLE.

So while it's Project64's fault for maintaining a couple VI registers, it's generally a moot point as most graphics plugins don't emulate the VI on a scanline-accurate basis.  So the issue could be put off for quite some time...I'm not even sure how to emulate that thing myself.  I have a clue about how to do it from my conversations with angrylion, but I would have to examine Mupen64 more to see the comparison.

**Comment by theboy181** [comment]
Thanks for the update. Could this missing function be causing some the the Gfx issues that spear while using those other plugins and pj64?

**Comment by LegendOfDragoon** [comment]
theboy181 only considers AL's plugin to be LLE lol ;/ .

I'd love to learn from Mupen64 0.5's source, but have no clue how to compile it with MSVC. I know there's a makefile for Mingw, but I like using MSVC for debugging. If someone could help me out with that, I'd be very happy. I may try learning from MAME and CEN64 as well, in order to fix these kind of issues.

**Comment by cxd4** [comment]
>Thanks for the update. Could this missing function be causing some the the Gfx issues that spear while using those other plugins and pj64?

No it's pretty insignificant by comparison.  Other graphics issues like triangles on the RDP aren't controlled by any DMA writes to the VI registers, just microcode.

>theboy181 only considers AL's plugin to be LLE lol ;/ .

Oh I thought SoftGraphic by suanyuan was LLE? :D

**Comment by project64** [comment]
@cxd4 what in particular should change to handle VI_V_CURRENT_LINE_REG correctly?

**Comment by cxd4** [comment]
That unfortunately is a hard question to answer.  I was kinda afraid I'd be asked that.

Neither angrylion nor myself are aware of where in Mupen64 VI_V_CURRENT_LINE_REG is being estimated.  It's one of the reasons I was playing with trying to get Mupen64 0.5 to compile as a 64-bit app, work on a 64-bit plugin system, experiment with how the R4300 interacts with the RCP registers and how it maintains them...because I really don't know much about the main CPU or core-side of things really.

Even in Mupen64, the implementation only allows neat interlacing to sometimes happen.  In my contact with angrylion we could just agree that it seemed virtually impossible to properly regulate the correct timing in the plugin specs as we know them for this value.  His current heuristic for deducing the interpretation of Mupen64's feedback for VI_V_CURRENT_LINE_REG is to determine whether the "upper field" or "lower field" of every 2 alternating scanlines is currently being DAC'd to the television screen, based on the LSB of this reg (as rcp.h should tell you).

The Killer Instinct issue here coincides with other games using interlaced mode--Virtual Chess 64, which has a 640x480 frame buffer, not 320x240 like most games we know of, and the Bombers' Notebook in Zelda Majora's Mask, which uses 576x448, with the rest of the game operating in 320x240 typical N64 native resolution.

The VI native resolution is 640x240 scanlines.  If we play Mario 64, the native frame buffer size is 320x240...the VI reads from the frame buffer and does basic analog filters until it is sending a 640x240 image to the DAC, in non-interlaced mode (so this doubles into a 640x480 image).  Conversely, Virtual Chess 64 uses a 640x480 frame buffer.  The VI cannot write 480 scanlines non-interlaced:  It uses interlacing and the least-significant bit of VI_V_CURRENT_LINE_REG, currently defined by the emulator's current stage of the RCP timing, to determine whether it is alternating every even or odd scanlines.  It does 240 alternating scanlines, then 240 alternating scanlines on the next vertical interrupt calling UpdateScreen until both updates construct a 640x480 image.

Screenshots next...

**Comment by cxd4** [comment]
Virtual Chess 64 on Mupen64, with partial attempts to emulate current line timing:
http://ft.trillian.im/785abe041074fd64135ab3318aff1ec8767ab03d/6w4VMejq51w3REB70M3AQw887kqHb.jpg

Virtual Chess 64 on Project64, with no attempts to emulate current line timing:
http://ft.trillian.im/785abe041074fd64135ab3318aff1ec8767ab03d/6w4W2NihVJCJFQT6auhflwC8WZA4J.jpg

In the first screenshot, we see that Mupen64 isn't perfect either.  The odd/even scanline timing in interlaced mode appears to give a solid 640x480 image, but with animation and moving objects constantly in motion around the game, it has this jagged effect, because the scanlines alternation is not really properly timed.

In the second screenshot, Project64 doesn't have this artifact, but that's because it makes no attempt to emulate the register.  It comes out looking like a 640x240 image, point-sampled up to a x480 image, rather than a genuine 640x480 image in high resolution.

But what happens if we have NO animation on the screen, with no moving objects?
Then it starts to look better on Mupen64's attempt to emulate it and Project64's non-attempt.

Mario no Photopie is another example of a game with a 640x480 native FB resolution.

Mario no Photopie on Mupen64:
http://ft.trillian.im/785abe041074fd64135ab3318aff1ec8767ab03d/6w4WhfQXRXV6vo7nRsHUinuGo9Izt.jpg

Mario no Photopie on Project64:
http://ft.trillian.im/785abe041074fd64135ab3318aff1ec8767ab03d/6w4WlzK6gZeA1UYSFrd4EuZXJf7bV.jpg

Same as before with the VC64 comparison.  It comes out as a 640x480 native frame buffer sent to the television screen through the VI's register's control over the DAC, while on Project64 it comes out as a 640x240 image with only half the resolution and detail.  Again, once motion or animation happens on the screen, it looks worse in Mupen64 and better in Project64, since what attempt there is to time the scanlines balancing is still imperfect and jittery/jagged.  I hope that this explanation has cleared a thing or two for your personal understanding on that situation.

**Comment by cxd4** [comment]
> @cxd4 what in particular should change to handle VI_V_CURRENT_LINE_REG correctly?

What _exactly_ should change to handle it...I can now answer that once you have processed my current PR.

I had about 80% of the solution...spent the past few hours analyzing Mupen64 emulator for the other 20%.  Now Star Wars:  Rogue Squadron is playable in angrylion's plugin when used with Project64, rather than just a black screen, and _Killer Instinct_, _Mario no Photopie_, _Virtual Chess 64_, _Lode Runner 3D_, _Legend of Zelda:  Majora's Mask_, all have interlaced video support once I am able to send you my next pull request.

**Comment by cxd4** [comment]
If you're still around @theboy181 you might want to look at closing this issue pretty soon, as it has been fixed within the core executable side.

But I understand that you probably won't want to close it now, because you may have to compile the source code to see for yourself until there is a release.

**Comment by theboy181** [comment]
I trust you know what your doing.  Is the source as simple as hitting compile now? 

Has this request been pulled to the master?

**Comment by cxd4** [comment]
Yes it's part of master.

You could compile Project64 or you could wait for EmuCR, but pretty sure it seems to be fixed.

**Comment by cxd4** [comment]
oh, and if you have problems compiling project64, you can join #project64 on irc.freenode.net and one of us can help walk you through it.

**Comment by theboy181** [comment]
I am unsure if the output resolution is correct for this. Killer Instinct looks OK, but RS looks horrible. If you test Mupen64 with doncdoon.n64 you will see how the resolution in this mode should look. I believe its 640x480. I thought that was the resolution for RS. but maybe I am mistaken.?

**Comment by cxd4** [comment]
RS comes out the same way on Mupen64Plus libretro.  It's slightly worse on Project64 but that's because the Counter Factor timer clock needs to be slightly adjusted...should fix some of the jittering.

But I would just close this issue, start a new one for Rogue Squadron unless KI Gold still wasn't fixed?

**Comment by theboy181** [comment]
Will do. Thanks
