### ISSUE TITLE
Sync to audio RDB parameter doesn't seem to do anything

### ISSUE THREAD

**Issue by oddMLan** [project64/project64#237]
As the title says.

Steps to reproduce:
-First, be sure that you're using Jabo's DirectSound.
-Right click any game in the ROM Browser
-Go to "Edit Game Settings"
-Verify that the game has "Sync using Audio" checked
-Open the game

You'll hear some audio popping. 
If you go to Options > Configure Audio Plugin... you'll see that "Sync game to Audio" is unchecked (unless you checked it there previously for that game).

If I check "Sync game to Audio" in Jabo's and open the Project64.cfg file, I see that the parameter _Dsound-SyncAudio=1_ is being written. 

Jabo's plugin seems to be happy with _Dsound-SyncAudio=1_ but the parameter _Sync Audio=1_ seems to be ignored.

I'd expect Jabo's to use _Sync Audio=1_ instead of using the other parameter.

**Comment by project64** [comment]
there is sync to audio in the core where I tried to reproduce what is jabo's audio plugin. What is happening in the audio plugin with settings, no idea and I can not change anything there, not with out getting a new open source audio plugin.

**Comment by oddMLan** [comment]
Are you saying that the _Sync using Audio_ core option was implemented sometime when you tried to recreate Jabo's Audio plugin from scratch? So at the moment, this option is not actually doing anything?

**Comment by project64** [comment]
the option was in the audio plugin and it worked well for a lot of games to sound better, but was not on by default. So I tried to recreate the functionality in the core where i had more control. 

In theory the core should make this option redundant in jabos plugin but I do not know that 100%. It would be nice at some stage to replace the audio plugin completely. Maybe if azimer either releases his plugin under open source we can look at using that.

**Comment by LegendOfDragoon** [comment]
@project64, I think it's better to leave audio sync to the audio plugin. However, if you decide to do more AI emulation in the core, instead of letting the audio plugin handle that, then would make sense to have the sync audio option in the core.

I think i get better results using sync audio from the audio plugin, rather than from the emu core.

**Comment by project64** [comment]
@LegendOfDragoon  I can not remove it from the plugin even if I wanted to since I do not have the code for it :)

**Comment by LegendOfDragoon** [comment]
What I mean is, emulators like Mupen64 don't call AiReadLength, (at least when "no audio delay" is unchecked) , because it does the emulation internally. I imagine it would be easier to handle timing for musyx games, at the very least. I still have no luck fixing audio for those games, from the plugin side. Not that Mupen64's audio timing is perfect though. So in a way, I'm kinda glad Project64 leaves it to the audio plugin to handle timing.

I know that PJ64 doesn't call AiReadLength, when fixed audio timing is enabled. I'll have to see exactly what Fixed Audio timing is doing, because without it, Musyx games have issues in PJ64.

**Comment by oddMLan** [comment]
Most of the games right now have minor audio popping in which the Sync to Audio emu option doesn't help but Jabo's Sync to Audio fixes on almost all the cases... personally I think about replacing _Sync Audio=1_ with _Dsound-SyncAudio=1_ in the RDB, (in the meantime PJ64 gets better core audio timing or an open source audio plugin).

Haven't you considered 1964 Audio as one of the possible candidates? Sure it might need some modifications in the code in order to make it work with PJ64, but if Shunyuan could make it work with PJ64, why couldn't anyone else?

Advantages:
-Open source (comes with 1964's code)
-Fast and high compatibility
-High Level Emulation thru on-the-fly uCode translation to C code
-Recent added support for MusyX uCodes HLE

**Comment by LegendOfDragoon** [comment]
> Most of the games right now have minor audio popping in which the Sync to Audio emu option doesn't help but Jabo's Sync to Audio fixes on almost all the cases...

His audio sync is good, but needs some work. For instance, Quest64, Mario Party, Nuclear Strike 64, etc cannot run 60 fps, with sync audio enabled. But yes, the crackling is significantly less with sync audio.
>Haven't you considered 1964 Audio as one of the possible candidates? Sure it might need some modifications in the code in order to make it work with PJ64

1964 audio is a good plugin, but it needs serious modifications done to it. It was designed specifically for 1964, so it's a hassle trying to fix emulator specific issues. I will say this though, it's one of the best plugins for WDC :) . I'd be surprised if anyone was willing to work with that source. It's not a totally bad idea, since I've actually experimented with 1964 Audio and I do like the plugin, but I just doubt anyone would actually work on it.
>but if Shunyuan could make it work with PJ64, why couldn't anyone else?

Shunyuan's plugin is actually significantly different (at least the important parts are). I don't even know if the threaded version of 1964 Audio works out of the box. I'd like to know how he was able to solve problems that no open source plugin was able to do, like emulating Musyx audio properly (I don't mean the microcode).

**Comment by oddMLan** [comment]
>In theory the core should make this option redundant in jabos plugin but I do not know that 100%. It would be nice at some stage to replace the audio plugin completely. Maybe if azimer either releases his plugin under open source we can look at using that.

So, now that Azimer's audio plugin is open sourced (I know that at the time you made that comment it wasn't open sourced yet) is there still a way to improve the Sync to Audio core option to makes Jabo's "Sync to Audio" redundant?

Dynamic AI (AI=0) with FAT enabled seems to work fantastically producing smooth continuous audio with next to no audio popping. Although this does not work for some specific games according to other people. Jabo's Audio "Sync using audio" on the other hand seems to help all games (I don't know if there's still some games with it that still produce incorrect audio).

By the way @ all testers, are there any negative consequences of enabling the three audio/timing options (Dynamic AI, FAT and Sync to Audio (core))? Currently I only enable Dynamic AI and FAT to get good audio, since the Sync to Audio core option seems redundant/not to do anything.

Also, Force Old-school Audio sync seems to do the same thing as Jabo's "Sync using audio". @Azimer did an amazing job improving FAT using the method he used for Project64 1.4 Audio Fix version.
If moving the audio/timing handling completely from the Audio plugin to the Core is the expected goal, can't Force Old-school Audio sync be ported from Azimer's to Project64? Unless I'm mistaken and it doesn't achieve the same as the current Sync to Audio core option and Jabo's "Sync using audio".

**Comment by LegendOfDragoon** [comment]
>If moving the audio/timing handling completely from the Audio plugin to the Core is the ultimate goal, can't Force Old-school Audio sync be ported from Azimer's to Project64?

I doubt that is the ultimate goal. In order to port the audio sync, the spec would need to be modified.

**Comment by Frank-74** [comment]
Sync using audio does nothing if Fixed audio timing is off.

And when both FAT and Sync using audio are checked, the video stutters.  Noticeable on the Goldeneye intro, when the eye moves onto the screen.  With Sync using audio off, it's as smooth as silk.
