### ISSUE TITLE
Factor 5 game saves are not compatible across regions.

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#241]
I've discovered that saves created by (U) Factor 5 titles such as Rogue Squadron\Naboo\Infernal Machine do not seem to be compatible with (E) versions and vice versa. The game simply overwrites them upon boot. Which is kind of a really, really bad thing. (Most N64 games are quite happy to accept cross-region save files.)

What we need is some flag or something that will tell a game to only use save files from its own region, while still allowing compatibility between cartridge revisions, which work fine.

**Comment by AmbientMalice** [comment]
Using "Internal Name" for save files and save states is tidy, but it causes problems.

Pros:
Rom revisions share save files.
Certain games can share save data across regions.

Cons:
Save states are incompatible between roms.
Some games delete saves if from other regions.

Perhaps Good Name should be used for save files, with Internal Name used for memory card files?

**Comment by cxd4** [comment]
This is all too technical on the level of what games and software do individually to really be an emulation issue to me.

Saved states of course never work when the region or revision is modified, so the good name works when naming them.  (Isn't that what's already being used when pj64 1.7+ creates saved states?)

Save chips might or might not work between different regions or different revisions of the game.  All the game developer has to do is modify the SRAM structure or offsets certain reserved/unused data in the eeprom to take up more space and throw off the bit positions of other data.  Most games won't, but some will.  Whether or not a developer is willing to break backwards-compatibility of someone's own EEPROM format doesn't feel like it has anything to do with N64 emulation.

**Comment by AmbientMalice** [comment]
This is something that mupen64plus doesn't encounter because it doesn't use Internal Name for save files. It just seems to me that it's a really bad trait for PJ64 to erase people's save files if they boot a rom from another region.

**Comment by AmbientMalice** [comment]
Even if Mem Pak saves are for whatever reason incompatible across regions, it's unlikely the game will erase your saves without asking if you boot the same game from a different region.

**Comment by cxd4** [comment]
Mupen64 0.5 uses the GoodN64 name for save files.  (I assume Mupen64Plus probably made no changes.)

1964 uses the CRC32-CRC32:C?? INI code method of naming save files.

Nemu64 uses the same method as Project64 1.6 I think.

If I were in charge of my own project, I doubt that I would be using any of those 3 methods.
But that doesn't mean that I see any issues with Project64's current method either.  Most people who are simply trying to play a game just pick an NTSC version (sometimes PAL) and play it.  In your case you're alternating between (U) and (E) to test things.  But the general trend is:  If the internal ROM name never changes, the save formatting is most likely backward-compatible.  (For example, Zelda Majora's Mask (J) uses a different FLASHRAM offset, while MM (E) and (U) are both compatible with each other and have the same internal ROM name in English.)

**Comment by cxd4** [comment]
>Even if Mem Pak saves are for whatever reason incompatible across regions,

They are incompatible at the same times and for the same conditions as any other save type.  There is no difference, other than where the save data is stored (on the SI controller RAM or through the PI on the save chip in the cartridge).  It affects nothing.

> it's unlikely the game will erase your saves without asking if you boot the same game from a different region.

That's a personal design choice on Nintendo's part.  Nintendo knows that the user can administrate the contents of the controller pak, but not the contents of the save chip.  Therefore, _with some exceptions_, you usually are not prompted that your EEPROM or SRAM is corrupt because Nintendo knows you are not in control over those things (at least legally, so far as they're concerned).  And even if it was corrupt, you could do nothing outside of an emulated environment, so it may as well get erased.  Moral of the story:  If you're purposely trying to test multiple regions, and about to make a region switch after making tons of progress in your save file first, backup your save data.

**Comment by AmbientMalice** [comment]
I think this doesn't really change the fact that wiping people's saves is really, really bad. Using Internal Name does have the benefit of keeping things somewhat neat and tidy, but if someone merely booting another region's rom will wipe their saves, I don't think it's acceptable behavior.

Scenario:
Person downloads Indiana Jones (U).
Discover (E) is better and download it.
Play (E) for 5 hours. Much whip-cracking fun is had.
Next day, accidentally click on (U) when trying to start game.
*Poof* Five hours of saves gone.

From a design standpoint, I find this mind-bogglingly bad. As for accuracy to a real N64, there is no way games from other regions/revisions would be seeing each other's save files since they're on individual carts.

**Comment by AmbientMalice** [comment]
I'm not kick and scream over this, or anything like that. PJ64 has been like this for years, and this trait only affects certain titles, it would seem. But I certainly think it's very bad design since and can and will cause heartache for users who don't understand how PJ64 handles saves.

**Comment by cxd4** [comment]
>I think this doesn't really change the fact that wiping people's saves is really, really bad.

Maybe it is, but that is the game designer's choice.  If something other than the save files being wiped had happened, it would be a bug within Project64, because that is what the game does on actual hardware.

As a matter of principle, however, I agree that an emulator is probably safest keeping one save file per exact ROM loaded (since each ROM from a different cart which has its own save chip).  So your idea seems logical enough, but then we also have to weigh that against people backing up all their saves from Project64 1.6, 1.7, or 2.0 and loading that in 2.3 or whatever if your idea is implemented, only to see that none of the save file names are relevant anymore.  So when naming conventions like this are changed it fixes one potential curse in exchange for another, at least as equally potential curse.

**Comment by project64** [comment]
I agree it is very bad, but I would like to keep backward compatibility since I doubt most people would try to use multiple version of the same game, so I do not think it will be changed any time soon. 

one idea that I did have which maybe for something for 2.3 is have an auto backup of saves, as well as having the native saves backed up/restored with instant saves. For example I save before a chest, open the chest, restore game .. the save in the eeprom/sram will have it recorded that the chest is open and then things are broken for me. This would be a bigger issues if some of the games keep tho whole save state in memory and write it back to the eerpom on saving.

**Comment by AmbientMalice** [comment]
>Maybe it is, but that is the game designer's choice. If something other than the save files being wiped had happened, it would be a bug within Project64, because that is what the game does on actual hardware.

I don't see it as the game designer's choice since they had (generally speaking) no way of anticipating that their games would be run on emulators that shared a single save file between multiple revisions and regions. Not just that, there is no way for this to happen on a real N64. (Excluding games that use Mem Paks - but that's a whole other kettle of fish.)

I do agree, however, that changing save formatting will upset people who wish to import their saves from older versions of PJ64.

**Comment by cxd4** [comment]
> I don't see it as the game designer's choice since they had (generally speaking) no way of anticipating that their games would be run on emulators that shared a single save file between multiple revisions and regions.

Whether they anticipate it or not doesn't change the fact that it is the game designer's choice.  They chose to wipe the save file if anything about the formatting seems off, and I'm sure that Nintendo **did** anticipate that somebody would try to have their games running on emulators someday.  Doesn't mean they welcomed it, or that they would have been willing to demand companies like the maker of Indy Jones to not wipe the entire EEPROM just in case their game was being emulated and not run on the real hardware.

> Not just that, there is no way for this to happen on a real N64.

It can happen on a real N64.  EEPROM save chips are more volatile than ROM and can give out after enough electrical content--I'm not good with hardware or the specifics, but after a certain amount of sector writes, the save data will have to be corrupted eventually.  Also, some people could use special tools to write to their cartridge's save chip and test a save from a different region, which is also not something ninty cares about.

**Comment by AmbientMalice** [comment]
I'll close this issue. I think it would be a good idea to have some sort of warning about this in PJ64 2.2's documentation so that unwary users aren't caught out.

**Comment by oddMLan** [comment]
>one idea that I did have which maybe for something for 2.3 is have an auto backup of saves, as well as having the native saves backed up/restored with instant saves. For example I save before a chest, open the chest, restore game .. the save in the eeprom/sram will have it recorded that the chest is open and then things are broken for me. **This would be a bigger issues if some of the games keep tho whole save state in memory and write it back to the eerpom on saving.**

That sounds like a killer feature! Games such as Donkey Kong 64 especially have this issue. It is very, very easy to corrupt the native save if you use save states... so all of a sudden your progress gets erased which is angering considering that DK64 is a gigantic collect-a-thon.
