### ISSUE TITLE
What is "RSP-JumpTableSize"?

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#242]
I noticed that (U) versions of Rogue Squadron had "RSP-JumpTableSize=3584", but the (E) versions didn't. Since I have no clue what the setting does, I didn't touch it.

**Comment by project64** [comment]
when a rsp task is sent to the rsp, the whole code is compiled. Now there is an issue when the ucode is smaller than the whole buffer and you get random code in the end, so it keeps compiling rsp tasks even if it does not need to, so we do not use the whole buffer to determine if the code has changed.

Now with rogue squardran it needs more code to be checked so that value is passed in to the rdb to be able to override the default behaviour

**Comment by AmbientMalice** [comment]
So should it be enabled for the (E) version for consistency?

**Comment by project64** [comment]
most likely

**Comment by AmbientMalice** [comment]
Okay. I'll close this and handle that later.

**Comment by LegendOfDragoon** [comment]
@project64 , What's a good way to figure out the correct RSP JumpTable size for each game?

**Comment by project64** [comment]
the default is usually fine, just in this particular case when I was debugging it I found it needed to be bigger, I can not remember now how exactly I worked it out, maybe removing it and see what the side effect is. I did not want to play with the default so I gave the ability to override the default.
