### ISSUE TITLE
[Bug]: Whenever i open a rom, pj64 just goes on a black screen for a second, then closes

### ISSUE THREAD

**Issue by avereyishere** [project64/project64#2439]
### Expected behavior?

pj64 opens the danm rom

### Actual behavior?

pj64 just dies

### Steps to reproduce the problem

1. open a rom

### Error messages?

none, just dies

### What game were you playing?

Title:

(Sell Name) Super Mario 64
(Rom Name) SUPERMARIO64

ROM information: normal mario64 rom
 
Save type: what do you think.

Original or modified ROM?:OG

### Specifications and build details

Project64: (include commit version number and whether you are using the
32-bit or 64-bit version)

Note: PC Is Mobile (A.K.A Laptop)

OS: Windows 10 22H2 19045.2965

CPU: AMD Ryzen 5 2500U

RAM: Installed (8.00 GB), Usable (6.90)

Graphics: Primary (one in use for the issue) Radeon RX 560, Discrete AMD Radeon(TM) Vega 8 Graphics

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

Graphics plugin (and HLE or LLE): Angle Gliden (LLE Mode)
Audio plugin: Normal
Input plugin: Normal
RSP plugin: Normal

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by DerekTurtleRoe** [comment]
@ThePerfectMario64 Please properly fill out the bug report, otherwise we cannot help you.

Some things that need changed, filled out, or updated:

- Did you try with the latest development build? Which build did this occur with?
- Did you try GLideN64 as well as Project64-video? We don't support Angle GlideN64, that is a separate project.
- Have you tried updating Windows, your graphics card drivers, and rebooting?
- Did you try with the CPU interpreter enabled?
- How many games did you try that didn't work?

**Comment by avereyishere** [comment]
nvm, i just set up windows, and got the wrong drivers for my gpu resulting in no opengl support.
