### ISSUE TITLE
audio gaps/pops with a bunch of games

### ISSUE THREAD

**Issue by dsx-** [project64/project64#252]
this is a big problem with 2.x, which didnt happen in 1.7

cruis'n world, cruis'n usa, sf rush, rush 2, are some of the games with this issue (using either jabo or azimer's plugins)

games like ocarina of time and super mario 64 have sound pops not present when using pj64 1.7 (using either jabo or azimer's plugins)

**Comment by LegendOfDragoon** [comment]
Which version of 1.7, and what are your setings for SM64 and OOT? I can try testing those 2 games.

**Comment by dsx-** [comment]
all settings default, 1.7.0.50

**Comment by oddMLan** [comment]
Which are the default settings in PJ 1.7.0.50? Can you provide a screenshot of the settings?
Can you provide audio samples comparing PJ64 1.7.0.50 vs 2.2.0.1? Is Jabo's DirectSound using _Sync game to Audio_ in any of those versions?

**Comment by dsx-** [comment]
http://dsxcorner.com/emulation/rush2.m4a - example of the gaps on 2.x with some games (1.7 is 100% smooth and creamy)

the gaps are there because these games want to play at 63VI/s for some reason (fixed audio + sync using audio -OR- sync game to audio + frame limiter off), but on 1.7 they are perfectly happy providing gapless audio at 60.00VI/s

http://dsxcorner.com/emulation/oot.m4a  - example of the popping on 2.x with some games (1.7 has no popping)

these problems occur with both azimer's plugin and jabo's plugin (havent tried other plugins, but the point is that the problems aren't present in 1.7 with any audio plugin)

sync game to audio is never enabled in jabo's plugin for these tests (doesnt fix anything in 2.x when i turn it on anyway, unless i disable frame limiter as well, which like i said is the equivalent of enabling both fixed audio timing and sync using audio in the rom settings, causing 63VI/s)

ROM SETTINGS: http://puu.sh/gsQ9M/3721fe25b2.png
Plugins: Jabo gfx/Jabo or azimer audio/zilmar rsp, HLE GFX

if anyone else can confirm this behaviour on 1.7, then we need to bring back the way the 1.7 core handles audio. this affects more games than only the ones ive listed

**Comment by AmbientMalice** [comment]
What we *really* need is a *new* way of handling audio that doesn't make me want to STAB MYSELF IN THE FACE.

But yea, checking 1.7's source may prove worthwhile.

**Comment by LegendOfDragoon** [comment]
I used to blame PJ64 for audio issues, but now I can see that it's mostly the audio plugin's fault.

>cruis'n world

Neither Azimer's nor Jabo's emulates this game perfectly. Shunyuan's does a better job than both, unfortunately.

When I tested OOT, I didn't really hear any crackling with Jabo 1.7.0.7. Where did you hear crackling in OOT?

I haven't tested many games with 1.7, but I tested Smash Bros, and if anything, it was worse on 1.7.

So far, the only real issues I have with the emulator core, as far as sound goes, is the stuttering, caused by the cpu recompiler. Maybe certain games like Top Gear Rally, could have core issues, but   not too many games are effected by the core, for audio. I was able to solve most of my issues, by picking the right plugin and settings.

**Comment by dsx-** [comment]
cruisn world and super smash bros both sound perfect on 1.7 with any audio plugin for me, 60.00VI/s

crackling in oot was in the audio sample i linked earlier

possibly this is related to the audio hardware in my computers? ive tested on several computers to come to these conclusions but they all use realtek integrated audio

**Comment by LegendOfDragoon** [comment]
Ahh, I see why now. As I suspected, you had fixed audio timing on, with 1.7. I guess 2.x just requires tweaking the aicount per byte. I was gonna say, there's no way the emulator could fix audio plugin issues, without something like FAT.

Another difference is that 1.7 has advanced block linking off, by default I think. At least that's what I'm seeing.

**Comment by dsx-** [comment]
yeah FAT works differently in 1.7 as well, doesnt break any games that i know of

**Comment by LegendOfDragoon** [comment]
I used to just think FAT sucked xD. Guess it was actually good in 1.7, somehow. Although it's still bad in games like Top Gear Rally. Hopefully, it's just a matter of finding the right AI count setting. I was impressed with the audio in Cruisin world. Certainly better than w/o FAT, since only shun's is good for that game otherwise.

**Comment by AmbientMalice** [comment]
>Neither Azimer's nor Jabo's emulates this game perfectly. Shunyuan's does a better job than both, unfortunately.

Ah, Shunyuan's :( A few games work beautifully with that plugin. Quest 64, for example.

Has anyone been in touch with Azimer about possibly fixing his plugin?

**Comment by LegendOfDragoon** [comment]
I did more testing. Fixed Audio timing certainly isn't perfect in 1.7. It works good in games like Nuclear Strike and Cruisin world, but not games like Top Gear Rally or Rogue Squadron. It's still worth seeing what the code for Fixed Audio timing was like. I'd rather fix things from the plugin side though ;/ .

I've only gotten good audio in Nuclear Strike with Azimer 0.56 and 1964 Audio ;/ .

**Comment by dsx-** [comment]
yeah fixed audio timing in 1.7 can't fix audio in games that need the orbits of all the planets aligned

**Comment by LegendOfDragoon** [comment]
Really though, I don't think fixed audio timing is good, except for netplay. In the meantime, I bet it wouldn't be too difficult to see what 1.7 did with FAT.

I think I've got very good audio in most games now, after tweaking and testing. There's enough good plugins out there too. You'll just have to do a per game plugin setup.

Actually... I just tested smash bros intro, it actually synced good to the intro. Now I'm wondering why zilmar changed FAT. Maybe it wasn't accurate for netplay?

**Comment by cxd4** [comment]
>audio in games that need the orbits of all the planets aligned

That caused me to space out for a little while.
Suddenly I can't stop laughing.  "What do astrologers think about how I should configure this game?"

**Comment by AmbientMalice** [comment]
I see a lot of praise for mupen64plus's audio code. I tried to get Resident Evil 2's sound working correctly earlier, and it was ridiculous. I eventually got it working, but with wonky FMV framerates. Sure, it doesn't crackle and pop, and sure it's neat and tidy... but it's not all peaches and cream.

Not to mention how poorly configured everything is by default. :(

**Comment by LegendOfDragoon** [comment]
Last time I remember trying m64p with smash bros, the audio was poor ;/ . Is the audio for Top Gear Rally good in M64p?

**Comment by dsx-** [comment]
no

**Comment by AmbientMalice** [comment]
Nope, it's TGR sounds terrible in M64p.

**Comment by LegendOfDragoon** [comment]
Ok, pj64 ftw :) . That's why I prefer letting the plugin handle AI timing.

**Comment by cxd4** [comment]
> I wish Shunyuan's audio plugin weren't effectively dead as a viable per-game plugin thanks to infighting and tantrums.

Don't really care what anyone wishes, or what anyone thinks is the reason that plugin is discontinued.

I have at least some extent of ethical viewpoint much like any decent and upstanding human being should.  It shouldn't take having any programming experiences to understand that stealing, purposely violating licenses, taking credit for everything inobvious without doing half the actual work is bad.  Anyone who doesn't understand at least that much has no legitimate wish for that plugin or any scope of N64 progress for that matter.

**Comment by AmbientMalice** [comment]
@cxd4 When I say "tantrums", I'm largely referring to Shunyuan being a crappy developer who took other people's work and closed sourced it and then ran away when people called him out on his bad practices. This doesn't change my regret at the fact that despite its roots being shit, the plugin got decent results in certain scenarios. If Shunyuan hadn't been such a sneak, maybe good things could have come from his work.

**Comment by cxd4** [comment]
Okay.  Never mind part of why I made my post then, sorry.
I figured it could have also meant me calling him out and having my own lashes at him.

And yeah, at first I remember he asked for some help on configuring an AI register or two, but ultimately I guess he was able to collage the best of several worlds.  His is the only XAudio plugin after all besides Azimer's, which IIRC is trying more for an experiment on accurate audio timing than immediately trying to sound perfect off the bat.

**Comment by AmbientMalice** [comment]
@cxd4 Am I correct in my understanding that XAudio is the major reason why his plugin doesn't have noticable popping and crackling?

**Comment by LegendOfDragoon** [comment]
>Am I correct in my understanding that XAudio is the major reason why his plugin doesn't have noticable popping and crackling?

No. DS8 is just fine. Major reason for less crackling is because of the techniques he used + emulated certain games better. The problem is, nobody is using an accurate formula, so hacks are needed. Yet everyone hates hacks, sooo ya...

The thing is though, no open source plugin is able to do some of the things shun's did. Musyx is one example. So I'm wondering how he fixed that. Although his has crackling in Rogue, so Azimer's is better.

For WDC, 1964 Audio sounds just as good as Azimer's DS8 WIP4 (provided you adjust the buffer size a bit). The main issue is Musyx. 2nd issue would be Boss Studios. Most other games have at least 1 plugin that do a good enough job.

**Comment by dsx-** [comment]
so i guess the issue i initially raised is that FAT is a dream in 1.7 (all games run at perfect speed, audio is perfect no matter what plugin), and in 2.x it sucks

**Comment by Frank-74** [comment]
>Although his has crackling in Rogue, so Azimer's is better.

Have you tried adding settings for Rogue Squadron in the lua script?
Maybe try this:
```
	if RomName == "Rogue Squadron" then
		SetPlaybackSetting(K_HighQualityAudio, K_TRUE);
		SetPlaybackSetting(K_SyncGameToAudioMode, K_SyncMode_2);
		SetPlaybackSetting(K_BigAudioChunk, K_TRUE);
		SetPlaybackSetting(K_SmallAiLen, K_FALSE);
		SetPlaybackSetting(K_UpdateAiLenReg, K_TRUE);
	end
```

**Comment by cxd4** [comment]
DS8 is better than DS7 anyway, with DS7 definintely just the choice of API enough to make any game keep crackling.  So XAudio2 likely has some extra effect on it, but as stated, it's not everything that's for sure.

> The thing is though, no open source plugin is able to do some of the things shun's did. Musyx is one example. So I'm wondering how he fixed that. Although his has crackling in Rogue, so Azimer's is better.

Come on.  Really?

You're wondering how a plugin that copied an entire RSP interpreter into ProcessALists and called it "HLE" supports MusyX? :D

**Comment by cxd4** [comment]
About the fixed audio timing in 2.x being broken compared to 1.7 (trying not to throw off the topic here) I'll try compiling all the 1.7.0.50's off this GitHub and isolating what commit began the regression and broke it, unless @project64 already has some memory of when where or why the fixed audio timing got worse since the way it was in 1.7 but otherwise if it helps I can try pinpointing where it began when I wake up.

**Comment by LegendOfDragoon** [comment]
>Come on. Really?
You're wondering how a plugin that copied an entire RSP interpreter into ProcessALists and called it "HLE" supports MusyX? :D

I don't mean RSP / microcode. I'm talking about the AI interrupts. If you try zilmar's audio, or azimers (if u comment out the audio sync code and add basic interrupts) the audio is really messed up, unless you use an option in the emulator to internally handle the AI emulation.

@Frank-74, I'll test it out.

**Comment by project64** [comment]
I have no idea where it went bad ... I focused on how well things work consistently not how it sounded. It was not until a lot latter that I even knew about sound problems. I always ran with sound off in essence, most because I never play the games

**Comment by LegendOfDragoon** [comment]
Lol I just tried FAT in 1.7 for Quest64 and WDC. Both had terrible audio.

@Frank-74 , I tested with those settings and still heard cracking. Azimer's seems to handle these kind of games better.

**Comment by dsx-** [comment]
FAT in 1.7 with quest 64 sounds perfect...

**Comment by project64** [comment]
with out fixed audio on which is what 1.7 added, an interrupt would fire when the audio finished playing on a real machine, which means every time you run and on different machines when the interrupt fires will likely be different, my aim was to try to get it to the core could do net play with out desyncing since you could fire the interrupts at a constant timing. 

So it made things more constant and reproducible in 1.7 which was great for sync core, and in theory net play/recording key strokes. Which is why I turned it off by default for 2.2 it does not help when people are playing by them self so better to let the plugin control how much data is left in the buffer and when the interrupts fire.

**Comment by dsx-** [comment]
why does fixed audio in 1.7 and 2.x provide different results though

**Comment by project64** [comment]
early versions of 1.7 might not have fixed audio, but fixed audio off should work the same as 1.6 did. With 1.7 there are many versions so not sure something might have changed something for the worse along the way

**Comment by LegendOfDragoon** [comment]
@dsx- My bad, must have been random lag. Still not perfect though.

>so better to let the plugin control how much data is left in the buffer and when the interrupts fire.

Indeed! I'm truly glad you did it this way.

**Comment by dsx-** [comment]
sf rush, rush 2, cruis'n world, cruis'n usa, goldeneye, etc
- fixed audio ON in 1.7 - perfect audio, 60.00VI/s
- fixed audio ON in 2.x - perfect audio, 63VI/s (too fast)
- fixed audio OFF in 2.x - audio gaps and crackling with jabo's and azimer's plugins, 60.00VI/s

this is the problem i am having

**Comment by AmbientMalice** [comment]
I've got a 1.7 build from that big emulator bundle with all the plugins and such. Tested it with Goldeneyed, and yep, as @dsx- says, no crackle at all. 1.7 lacked adjustable VI and AI, though. Dunno how it behaves with problematic titles such as RE2.

It would be a massive benefit if the crackling could be resolved. Even if it meant including a "Legacy FAT" option for games or something.

**Comment by LegendOfDragoon** [comment]
Good thing there's more audio plugins than just Jabo's and Azimer's :) . Also different versions of Azimer's plays certain games better than other versions.

>Dunno how it behaves with problematic titles such as RE2.

Probably bad.

**Comment by Frank-74** [comment]
I found GoldenEye to be best in Azimer's 0.60 if you have Fixed Audio off, Sync using Audio on in PJ64, and in Azimer's options disable Emulate Audio Interface and enable Dynamic Audio Sync.  No gaps, pauses, stutters, clicks, pops at all.

Its just a pain that the options don't save.  Maybe it could be patched to enable Dynamic Audio Sync as default, and disable Emulate Audio Interface as default.

**Comment by LegendOfDragoon** [comment]
@Frank-74, I can help you with that patch if you need.

I haven't tested Goldeneye much, but I should look into it and see which plugin's the best. That's a shame you had to disable Emulate Audio interface, since that generally improves the audio timing.

**Comment by Frank-74** [comment]
@LegendOfDragoon Yes please about the patch.

The intro in GoldenEye for example, has a gap in sound before the big eye appearing.  But with those settings in Azimers, there are no gaps or stutters, just smooth music.

**Comment by LegendOfDragoon** [comment]
@Frank-74 ,at 0x6BCC, change 10010088 to 10000188

I tested Goldeneye with PJ64 2.2, and the audio seemed good to me.

**Comment by AmbientMalice** [comment]
>@Frank-74 The intro in GoldenEye for example, has a gap in sound before the big eye appearing. But with those settings in Azimers, there are no gaps or stutters, just smooth music.

I'd be wary of the sound dropping out unexpectedly during the game. That said, if it gets smooth audio, it's a decent compromise - at least until Azimer releases an improved plugin.

**Comment by Frank-74** [comment]
@LegendOfDragoon Thanks for that, I found all the options except Force Old Audio Sync.
>Option				Offset
Emulate Audio Interface		6bcd
Dynamic Audio Sync		6bce
Enable HLE Audio		6bdd
Enable RSP Emulation		6be4
Force Old Audio Sync		????

@AmbientMalice I'll play through the whole game now, only takes about 50 minutes on Agent.

**Comment by AmbientMalice** [comment]
@LegendOfDragoon @Frank-74 I've been testing with Azimer's 0.60 WIP2, and overall I am extremely impressed. Dynamic Audio Sync seems to cure any minor crackle in games like TWINE and Resident Evil 2.

**Comment by Frank-74** [comment]
@AmbientMalice Well you can by hex editing the options you want and saving as a different filename, also hex edit the internal plugin name, so you know which options you select.  I've just done that.  To turn on Dynamic Audio Sync, goto offset 0x6bce and change the 00 to a 01.

**Comment by cxd4** [comment]
lel u nubs and ur audio plugins

Fixed audio timing sounds perfect when I change the graphics plugin!  Because then emulation sounds the exact same at that speed regardless of the audio plugin. :P

But seriously, if at all possible I think the more optimistic approach is to figure where the internal support for it got broken, not try to cover up for it by changing plugins.

**Comment by cxd4** [comment]
> I always ran with sound off in essence, most because I never play the games

If you always play with sound off @project64 why not include the No Sound plugin with project64 source?  Wouldn't exactly take up a lot of space + fill in a hole quickly for easier compiling of the whole package as 64-bit as a no-sound audio plugin is unlikely to have issues porting to a 64-bit plugin spec.

**Comment by LegendOfDragoon** [comment]
A good audio plugin > FAT ;/ . Maybe other people have a different definition of perfect, since I ain't hearin perfect audio with FAT in 1.7! Only some games are good.

@Frank-74 , I'm glad to help.

Has anyone tried Azimer's 0.56 WIP2 for Goldeneye?

**Comment by cxd4** [comment]
> good audio plugin > FAT

Different way of defining the issue.

Some people are saying the issue is that it sounds terrible compared to how it did in 1.7; other people are saying it sounds worse without plugins doing it.  It's just a different description really; how it sounded in 1.7 or how it sounds in plugins isn't really a factor.  The factor is that it's imperfect and even worse now.

And it is an issue because you need to have fixed audio timing for several things.

**Comment by LegendOfDragoon** [comment]
I wouldn't call it completely worse, if it sounds better for games that actually need it (like Rogue Squadron). FAT in 1.7 just didn't live up to the hype :) .

>Different way of defining the issue.

I only said that because I am not hearing perfect audio. I already suggested to look at 1.7's source to see the difference. If nobody is willing to do that, then they just have to deal with it for the time being. I merely suggested a superior alternative in many cases.

**Comment by cxd4** [comment]
Never said anything about 1.7, just FAT.  Just talking about correct fixed audio timing, not Project64, not versions of PJ64.

The 1.7 source on this Git/SVN is too new.  According to dsx FAT only sounded correct before any of the 1.7.51.* which is all that there is here.

**Comment by Frank-74** [comment]
I had a brief look at all the developments to audio from early 1.7 versions to the present a few days back.  Overall, the developments made have been to increase accuracy.  Individual instruction timings were added to try to make the timing more accurate to the real hardware.  I think the ideal approach is to be accurate compared to the real hardware.  Just emulate how the real N64 does it, and sync shouldn't be an issue.

**Comment by LegendOfDragoon** [comment]
>Never said 1.7, just FAT. Just talking about correct fixed audio timing, not Project64, not versions of pj.

FAT is better in 2.x for games like Rogue Squadron. So it's not completely worse.

>The 1.7 source on this Git/SVN is too new. According to dsx FAT only sounded correct before any of the 1.7.51.* which is all that there is here.

I'll take a quick look and check.

**Comment by cxd4** [comment]
>If you mean audio quality, I still disagree.

Never said anything about audio quality either.  When I say audio timing I'm referring to audio timing.

>Agreed. FAT should be used just for netplay, recording input, or debugging.

Actually it's used for accuracy.

>Using an accurate audio plugin gives better results than FAT.

Are you trying to look at this from an end user's point of view, or from an emulation contribution point of view?

Because from an end user's point of view, the inferior audio quality resulting from using fixed audio timing is the very ISSUE reported so that it can get FIXED.

**Comment by LegendOfDragoon** [comment]
>Actually it's used for accuracy.

How is it more accurate?

>Are you trying to look at this from an end user's POV, or from emulation contribution point of view?

Mostly end user's POV. I was also speaking based on current implementations in N64 emulation.  I'm not against FAT, but the way it's currently implemented (I'm talking about various emulators), its timing is not the most accurate. From a theoretical standpoint, I wouldn't know what has the most potential. I just know what's better as of current implementations.

Basically, my whole point is that 1.7's FAT is not perfect and that the change in the way FAT works in 2.x isn't a big deal. Some games actually sound better in 2.x with FAT, so not even a total loss.

>What about LLE? Should that only be used for netplay, recording input, or debugging?

I only said it, based on current implementations. Maybe in the future, FAT will be good to use in normal gameplay.

**Comment by cxd4** [comment]
>How is it more accurate?

Any reason to propose it isn't more accurate?  Uh sorry but I thought the purpose of audio timing being set correctly (either because of automatic detection or some hardcoded value in the RDB value or whatever) was supposed to be a good thing last I checked.  Or is true accuracy only found by moving as much of the core emulator's job as possible into plugins?

And the fact that the N64 state machine can be constantly reproduced and repeat behavior every time is a hack too eh?

So actually this "fixed audio timing" is really all just some HLE hack then, and that's why it does all those things you mentioned (improved debugging, NetPlay, recording input)?

>I'm not against FAT, but the way it's currently implemented (I'm talking about various emulators),

What are we measuring which shows fixed audio timing is used in other emulators besides pj64 1.7+?

How do we know they aren't just using a better auto-detection than what Project64 does when fixed audio timing is turned off?

**Comment by LegendOfDragoon** [comment]
>Any reason to propose it isn't more accurate?

I was interested in hearing about why it would theoretically be the most accurate.

>Or is true accuracy only found by moving as much of the core emulator's job as possible into plugins?

I obviously don't believe that ;/.. I just think that based on the current design, it's better to let the plugin do the audio timing, for regular game play.

>So actually this "fixed audio timing" is really all just some HLE hack then, and that's why it does all those things you mentioned (improved debugging, NetPlay, recording input)?

I don't think being deterministic automatically means it's more accurate. Sure ideally, it's better to be deterministic, but current implementations of FAT are not the most accurate.

>What are we measuring which shows fixed audio timing is used in other emulators besides pj64 1.7+?

Mupen 64's audio is fixed I believe. I know that I was able to get AQZ netplay working on it without desyncing. I may try debugging with Mupen, later on, to see if it's perfectly deterministic. For certain I know that audio is fixed in 1964 1.1 when using kaillera.

**Comment by cxd4** [comment]
> Sure ideally, it's better to be deterministic,

Only if it's more accurate, which obviously in this case it is.

Being deterministic is only less accurate if a game relies on registers with undefined values or something like that, and not when it's caused by discrepancies resulting from a non-cycle-accurate emulator.  But I guess you believe in hacks anyway, so why should accurate timing automatically mean it's more accurate.

> , but current implementations of FAT are not the most accurate.

Huh?  I thought you just got done admitting to talking only about "current implementations"?

Now you're using it as a retort in an argument over whether the principle itself is more accurate.  Again, it's easy for HLE to be more accurate than LLE.  Take cen64 for example.

**Comment by LegendOfDragoon** [comment]
>But IIRC you like hacks anyway

Not as much as you think xD.

>Huh? I thought you just got done admitting to talking only about "current implementations"?
Now you're using it as a retort in an argument I started over whether the principle itself is more accurate. Again, it's easy for HLE to be more accurate than LLE. Take cen64 for example.

More like I admit idk what's the theoretically most accurate way to implement audio. I just had to point out that my suggestion is based on current implementations.

**Comment by cxd4** [comment]
>Not as much as you think xD.

Where did that come from?  All I said was that you like them, not how much you like them.

I just said once that HLE gets berated and bashed too often on the forums, and you agreed with it all devoutly and such, and kept saying, in your own words, how hacks were worthwhile if it meant gaining performance.  Now you're acting as though you're ashamed about it or whatever or like I meant what I said as an insult.

>More like I admit idk what's the theoretically most accurate way to implement audio. I just had to point out that my suggestion is based on current implementations.

Isn't that what I just said?  "Got done admitting to talking only about 'current implementations'"  If you want to admit to additional criteria _besides_ that then that's fine, but that wasn't the scope of the point.  But with the current state of emulation for X or Y, anything goes, so there's no genuine base for comparison, so, I don't see why keep bringing it up really.

**Comment by LegendOfDragoon** [comment]
>Where did that come from? All I said was that you like them, not how much you like them.
I just said once that HLE gets berated and bashed too often on the forums, and you agreed with it all devoutly and such, and kept saying, in your own words, how hacks were worthwhile if it meant gaining performance. Now you're acting as though you're ashamed about it or whatever or like I meant what I said as an insult.

I think your opinion of me is a bit skewed. I can't tell if you're purposely exaggerating or if you genuinely believe it.

**Comment by Frank-74** [comment]
The only issue with FAT is that it breaks VI/AI sync.  It might fix the audio timing, and keep it accurate, but the display (VI's) doesn't get fixed to the audio in sync.  Think I said that ok, I've had a few beers/:)

**Comment by cxd4** [comment]
...and now you're taking a public quote of what you said openly on the forum and interpreting it as some sort of opinion about you, ooookay then, never mind.

All I know is, I pointed out a quote where you said that you were just fine with the idea hacks, publicly on the forum, and you reacted by saying "not as much as you think xD", even though I never stated how much you're fine with them.  I can't tell if you're purposely exaggerating my intentions or if you genuinely believe they're something they're not. :P

**Comment by LegendOfDragoon** [comment]
>The only issue with FAT is that it breaks VI/AI sync. It might fix the audio timing, and keep it accurate, but the display (VI's) doesn't get fixed to the audio in sync. Think I said that ok, I've had a few beers/:)

This is true, + the fact that there's more crackling and stuttering. This is why I prefer it off, for the time being, during normal game play. PJ64 1.7's FAT even has missing voices in RE2. That's probably one of the reasons why zilmar changed it in the first place.

>...and now you're taking a public quote of what you said openly on the forum and interpreting it as some sort of opinion about you, ooookay then, never mind.
All I know is, I pointed out a quote where you said that you were just fine with the idea hacks, publicly on the forum, and you reacted by saying "not as much as you think xD", even though I never stated how much you're fine with them

It's just the vibe I get from you, sometimes. Saying things like "Now you're acting as though you're ashamed", is what gives me that vibe :) . Anyway, I originally misunderstood your post, but I understand what you're saying now, about accuracy.

**Comment by project64** [comment]
mostly I created it in response to project64k i felt that 1.6 was fundamentally flawed in that it could never play with out desyncing since when the interrupt would be non deterministic and would never be the same on all machines, since the firing of the audio interpter would be determined by what was going on the host machine, not in regards to what was happening in the emulation.

Since I basically only ever use pj64 for testing, I do not have audio on, so I did not know what the effect would be on the actual playability or that it would cause gaps/pops. I originally did not even image it would have made any difference there.

**Comment by AmbientMalice** [comment]
@LegendOfDragoon 2.x's FAT needs specific AI values for the voices to work. Since 1.7 lacked AI adjustment, that's likely the reason.

**Comment by cxd4** [comment]
>Saying things like "Now you're acting as though you're ashamed", is what gives me that vibe :) .

Well no, that wasn't the part you reacted to.
This was:
>>But IIRC you like hacks anyway

>Not as much as you think xD.

Which was before I even started guessing that you were feeling ashamed about something.  All I could do was give the benefit of the doubt that it wasn't something weird...unlike shame, which is perfectly normal.

>i felt that 1.6 was fundamentally flawed in that it could never play with out desyncing since when the interrupt would be non deterministic and would never be the same on all machines, since the firing of the audio interpter would be determined by what was going on the host machine, not in regards to what was happening in the emulation.

Sounds like a substantial gain in accuracy to me.

>2.x's FAT needs specific AI values for the voices to work.

On 1.6 I had to change counter factor to fix the voices, and that was it.  I didn't think to try playing with the AI values since I almost never touch those.

**Comment by SatanNintendo** [comment]
A similar problem in California Speed games, Rush 2 sound is interrupted and clicks.

**Comment by theboy181** [comment]
Please review if this issue needs to be closed or not.

**Comment by AmbientMalice** [comment]
This will be fixed when dynamic Fixed Audio Timing is enabled for all appropriate games. (Which is a vast majority of them, IMO.) Azimer has fixed the broken FAT behavior of 2.x, but a few games crackle with Jabo now. Azimer seems to work much better. So once Azimer is the default plugin and FAT is configured correctly, this issue should be resolved.

**Comment by oddMLan** [comment]
@dsx- Is this still an issue in the games you listed with the current global settings?
For the record, they currently are

FAT ON, dynamic AICount calculation and Sync Using Audio off.

#429 and #882 #881 might be of interest

especially PR 429 since the date of this bug is older than the merge of the improvements Azimer made to the Fixed Audio Timing algorithm, which made a substantially big improvement to the audio

**Comment by dsx-** [comment]
nah all fixed

**Comment by oddMLan** [comment]
Ok, could you close the issue then?

**Comment by dsx-** [comment]
OH right sorry
