### ISSUE TITLE
Project64 2.2.0.2 (from github) is not working with Socket A CPUs (AMD Athlon XP or AMD Sempron)

### ISSUE THREAD

**Issue by MELERIX** [project64/project64#263]
you will see this error window when execute Project64...

![Text](http://i.imgur.com/tU40dMq.png)

**Comment by project64** [comment]
that is with 2.2.0.2 downloaded from the pj64 forum? Or what version?

**Comment by MELERIX** [comment]
yes, with current version 2.2.0.2 from github.

**Comment by project64** [comment]
was a previous version working, did you compile it your self ?

**Comment by MELERIX** [comment]
I have no idea about previous versions, because I just tested now with the computer of a friend in order to check if I can run Project64 in Windows XP, and only then I noticed this bug.

**Comment by project64** [comment]
how did you get the binary file your testing?

**Comment by MELERIX** [comment]
was compiled by me in Visual Studio 2013 Community Edition.

**Comment by project64** [comment]
for xp it needs to be compiled in 2008 or you get that issue

**Comment by project64** [comment]
if you use the one on the pj64 forum that is compiled in visual studio 2008

**Comment by MELERIX** [comment]
I don't see any builds in the forum, may be is an area where I don't have access :(

anyway for me it seems to be more likely a CPU feature being forced in PJ64, because the CPUs I've mentioned above does not have SSE2 instructions, and if you open RCP Main.cpp at line 267 you will see the following code:

void DetectCpuSpecs(void) {
	DWORD Intel_Features = 0;
	DWORD AMD_Features = 0;

	__try {
		_asm {
			/* Intel features */
			mov eax, 1
			cpuid
			mov [Intel_Features], edx

			/* AMD features */
			mov eax, 80000001h
			cpuid
			or [AMD_Features], edx
		}
    } __except ( EXCEPTION_EXECUTE_HANDLER) {
		AMD_Features = Intel_Features = 0;
    }

	if (Intel_Features & 0x02000000) {
		Compiler.mmx2 = TRUE;
		Compiler.sse = TRUE;
	}
	if (Intel_Features & 0x00800000) {
		Compiler.mmx = TRUE;
	}
	if (AMD_Features & 0x40000000) {
		Compiler.mmx2 = TRUE;
	}
	if (Intel_Features & 0x00008000) {
		ConditionalMove = TRUE;
	} else {
		ConditionalMove = FALSE;
	}
}

and probably this is causing the issue.

its SSE2 being forced in PJ64 ?

**Comment by project64** [comment]
what do you see if you click on the link above

**Comment by LegendOfDragoon** [comment]
>its SSE2 being forced in PJ64 ?

Yes, the way it's currently set up, it compiles with SSE2 code for MSVC 2013. You have to manually disable sse2 code, in project settings. I don't see why it would crash there though.

**Comment by MELERIX** [comment]
oh lol, I'm blind xD

well, I'm going to download and I'll test if this forum build works in this CPUs.

**Comment by MELERIX** [comment]
ok tested, and the forum build opens normally in XP.

this means VS2008 does not force SSE2 ?

**Comment by LegendOfDragoon** [comment]
>this means VS2008 does not force SSE2 ?

Yes, by default, SSE is disabled in 2008. For some reason, with 2013, for Enable Enhanced Instruction Set, "not set" = SSE2 lol ;/ . You have to set it to "No Enhanced Instructions".

**Comment by cxd4** [comment]
Does anything in Project64 benefit from SSE or SSE2?

**Comment by LegendOfDragoon** [comment]
>Does anything in Project64 benefit from SSE or SSE2?

I imagine the cpu interpreter & RSP would benefit. Actually I'm certain it does, just not sure how much.

**Comment by cxd4** [comment]
I'm sure the RSP recompiler does, but that's a separate project and should have its own setting for that.

I was mostly just talking about Project64 core...I imagine the CPU interpreter wasn't meant to be fast compared to the compiler, so probably wasn't meant to generate much in the way of SSE bytecode?

Basically what I'm getting at is maybe the VS2013 project files should be updated to force "No Enhanced Instructions".

**Comment by MELERIX** [comment]
> Basically what I'm getting at is maybe the VS2013 project files should be updated to force "No Enhanced Instructions".

you mean using /arch:IA32 like this ?

```vcxproj
<AdditionalOptions Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">/arch:IA32 %(AdditionalOptions)</AdditionalOptions>
<AdditionalOptions Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">/arch:IA32 %(AdditionalOptions)</AdditionalOptions>
```

**Comment by LegendOfDragoon** [comment]
>Basically what I'm getting at is maybe the VS2013 project files should be updated to force "No Enhanced Instructions".

I figured that's why you asked xD.

>I was mostly just talking about Project64 core...I imagine the CPU interpreter wasn't meant to be fast compared to the compiler, so probably wasn't meant to generate much in the way of SSE bytecode?

If even you don't care about the speed, then perhaps it should be disabled :) . Honestly though, without SSE generation, there's less of a point in using 2013 imo. I think the main difference is floating point math. I don't mind either way, because I already use different settings than the current default anyway. Of course for testing problems, i use w/e the default settings were.

For instance, I don't like using "minimize size", and prefer max speed instead.

**Comment by cxd4** [comment]
> I think the main difference is floating point math.

kthx that was the info I was looking for.

Never said I don't care about making the interpreter fast, just trying to figure what it was you were seeing that made the interpreter dependent on SSE generation.  With CP1 floating-point operations it will probably have to generate x87 op-codes instead of SSE1 or SSE2 for floats and doubles in MIPS, but on the bright side Project64 needs 64-bit portability to improve the accuracy of the interpreter and speed of the recompiler anyway.  So anyone with a 64-bit CPU would be able to emulate MIPS accurately there, plus be able to get the SSE2 support for the extra speed as well.

But this guy is talking about some old AMD CPU that doesn't even have SSE on it, so I don't think using x87 instead of SSE on a 32-bit machine incapable of accurate 64-bit register storage/operations is really that important anyway especially since most people here only care to optimize the re-compiler not the interpreter anyway.

**Comment by MELERIX** [comment]
> But this guy is talking about some old AMD CPU that doesn't even have SSE on it

this CPUs have SSE, MMX and 3DNow!, only SSE2 is not present on them.

**Comment by LegendOfDragoon** [comment]
It's totally understandable to disable SSE for the emulator. I just figured, if there's going to be 2 different builds, might as well have 1 on. Either way, I don't mind just compiling myself.

Now that I realize there's enough 64 bit plugins available, I'm eager to move onto 64 bit!

**Comment by cxd4** [comment]
And with 64-bit we have the real storage opportunities of reading/writing 64-bit all the time and can use SSE2 to optimize the CP1 floating-point stuff you mentioned.  No reason to use the 32-bit build unless you had to in which case using x87 ops instead of SSE is probably the least of our worries...

**Comment by project64** [comment]
ok made some changes to the project settings (https://github.com/project64/project64/commit/1e0efb670e747ad0db1e434a5c69c84e61e0a9e0) need to test if that actually helps

**Comment by MELERIX** [comment]
now it show a new error...

Project64.exe is not a valid win32 app

![error](https://cloud.githubusercontent.com/assets/1040116/6630141/57c0d078-c8f4-11e4-9013-b18861fe1397.png)

**Comment by LegendOfDragoon** [comment]
Is this still an issue?

**Comment by MELERIX** [comment]
>Is this still an issue?

yes, the issue/bug is still present.

**Comment by JunielKatarn** [comment]
Yes, still there :(

![image](https://cloud.githubusercontent.com/assets/4507319/8567590/844e99e4-251b-11e5-848a-9f2498750cee.png)

**Comment by cxd4** [comment]
OS subsystem version needs to be set to 5.1 or less in the linker build settings.

**Comment by JunielKatarn** [comment]
> OS subsystem version needs to be set to 5.1 or less in the linker build settings.

Verified this fixes the issue. PR on the way...

**Comment by oddMLan** [comment]
@MELERIX 

After @JunielKatarn submited some PRs to address this ~~(I think, #817 being one of them).~~ some changes in the core seemingly fixed it

is this still an issue?

**Comment by MELERIX** [comment]
probably is already fixed, but I can't test it anymore, I don't have a machine with that CPU in my hands now to check :/

**Comment by JunielKatarn** [comment]
This is not an issue anymore. It was fixed a while ago.
It can b closed.
