### ISSUE TITLE
Move "Use High Level GFX/Audio" options to Advanced settings

### ISSUE THREAD

**Issue by toehead2001** [project64/project64#306]
I know these two options are directly related to the plugins, but the average Joe shouldn't need to change these. Perhaps they could be moved the Advanced pane in the settings.

**Comment by cxd4** [comment]
I don't see this as an issue (much like many of the other issues we've had filed lately).
This is a design suggestion revolving around how advanced, useful or necessary LLE vs. HLE may or may not be.

Besides which, in theory Project64 could be designed to be totally inconvenient, advanced and/or unfamiliar to beginner users due to not newbing up the design or whatever--doesn't mean the emulator itself has any issues or that this would be one of them.

LLE isn't something you use just when you "need" to use it or if you're an advanced user.  It's just there for people who prefer hardware accuracy over software accuracy + more direct RCP testing.  Only fundamental problem is it's slower--I think it's more than enough that zilmar already puts up a warning message when toggling these settings saying that they're not for general use, so why put extra emphasis on it by also moving the plugin HLE/LLE settings away from the plugins pane to advanced/hidden pane settings?

**Comment by LegendOfDragoon** [comment]
>I know these two options are directly related to the plugins, but the average Joe shouldn't need to change these. Perhaps they could be moved the Advanced pane in the settings.

I really don't see a point in moving them. I think it's convenient to have it in the plugins section. What benefit is there to moving it to somewhere else?

**Comment by project64** [comment]
If I really wanted to go that far, more likely I would actually hide all things related to plugins in basic mode.

**Comment by toehead2001** [comment]
@project64 Fair enough

@cxd4 Those are very valid points. The same things could be said about some of the options already in the Advanced pane, but that's beside the point :p

@LegendOfDragoon Personally I also think it's convenient to have them in the plugin pane. I was trying to think of the first-run UX from a objective point of view, and it seemed like a good fit to put them in the existing Advanced pane.
However, you all provide good arguments for keeping it the way it is, so I can just close the issue if needs be.
