### ISSUE TITLE
Mario Kart 64 MP speed issues

### ISSUE THREAD

**Issue by theboy181** [project64/project64#32]
Not sure if this can be emulated correctly, but MK64 has issues with emulating the correct speed while playing Mario Kart multiplayer. Most noticeable in DK jungle with 3 or more players. I think that Nintendo has coded the game to increase some multiplier to achieve reasonable results in frame rate when playing MP on the real HW.  This is only emulated correctly on the Wii VC.

**Comment by cxd4** [comment]
I got that working fairly well by tweaking the VI refresh rate setting in the RDB, but I have no idea what I set it to anymore.  The last time I played with it to get it working, was when some guy said he offered $500 to whoever got it working, so I felt like getting it working to see what his reaction was, then when I finished answering all his PMs about how to install the fix he just ran off and never came back. :D

But yeah try lowering it from 1500 to something like, 1100 maybe 600, it'll make a lot of other things slower as well but DK Jungle 3-player won't be on crack either.

**Comment by theboy181** [comment]
This creates only a work around and has other effects during other pets of the gameplay. 

I think the real fix is going to be finding out what nintendo has actually done and emulate those features. I have tested this on many emulators and no change. The real HW seems to be ok though. 

Tbh I Havnt checked CEN64 since the core updates.   I wonder.

**Comment by Predator82Germany** [comment]
My N64 had this problem too but don´t know which pal version of the game it was

**Comment by cxd4** [comment]
Typically non-cycle-accurate has to rely on said workarounds, but whatever, technically it is an issue.

It definitely has been asked about a lot, for all the emulators, no matter what timing they do.

**Comment by Predator82Germany** [comment]
That means it´s fixable anyhow in face of the big-n issue?

**Comment by cxd4** [comment]
wut

**Comment by cxd4** [comment]
> I think the real fix will be finding out what Nintendo has actually done with this game,

No I think the real fix will be what I said.
Set VI refresh rate manually when not automatic, because non-cycle-accurate emulators have no "real fix", and "finding out what Nintendo has actually done with this game" is more of a stereotype on your end for something that's rather self-explanatory:  Nintendo had timer issues on the actual system so needed to adjust to it in this particular course.  What they did is clear; doesn't mean they'd know how to fix this issue from an emulator's perspective.

**Comment by theboy181** [comment]
:(  

Sounds like there is very little hope then. I don't see how fixing the timing is going to help here. The game acts similar to OOT regarding Links movement speed frame rate. 

Can you explain any further?

**Comment by theboy181** [comment]
are we sure this isn't a frame-skip setting. Can we verify that Nintendo had some dynamic CF abilities?

I was doing some testing the other night, and between 2p vs and 4p vs on DK jungle there seemed to be missing frames of animation speeding the game up.  Lakutu also is on crack and counts really fast.

**Comment by LegendOfDragoon** [comment]
@theboy181 Nobody here has RE'd MK64. Feel free to debug the game.

**Comment by Frank-74** [comment]
Its because the real N64's processor was a cap for speed.  In emulation it runs much faster if you have a fast processor.  Or on real overclocked N64's, these levels run too fast too.

**Comment by theboy181** [comment]
> Its because the real N64's processor was a cap for speed. In emulation it runs much faster if you >have a fast processor. Or on real overclocked N64's, these levels run too fast too.

Using 1964 and under clocking didn't seem to correct the frame skipping that I reported.

I'm getting closer to the same conclusion that the big N had used FS to get a desired result in 4p MP.

**Comment by MatthewHunter1983** [comment]
hiya folks!~ just thought I would add some empirical input form forums on this topic I have read as well as personal input since I can't find the other 2 posts on this precise topic that I've seen before. I have read a lot about this issue with this game / these courses. here are some things I have read on multiple forums:

this issue happens in multiplayer battle mode and in certain courses like dk jungle parkway and a few others (presumably "graphics heavy"--by n64 standards/compared to other tracks within the same game--courses... always in multiplayer mode single player mode is fine).

this issue happened sometimes on the n64 hardware itself.

this issue happened more severely on the wii virtual store re release on the wii hardware (as it is happening with modern pc's now). this was the actual wii hardware, not a wii emulator (although the virtual store itself on the actual wii is like emulation).

wherever this issue was present (n64 hardware, wii hardware/virtual store, pc emulation), people had ranging opinions on weather they could notice it all, being certain that it is happening, and being certain that it's not happening. on the n64, not many people had the issue. on the wii virtual store, most people seemed to have the issue, on pc emulation it seems to vary... possibly depending on hardware specs and versions of software. but always the same courses and always in multiplayer mode, across platforms.

the prevailing theory on the internet seems to be that Nintendo implemented some weird hack on these graphically heavy courses/modes that lowered the framerate, or something weird so that the  certain affected courses in a few (always the same few races) 2 player race mode, and the battle mode ran full speed. the theory is that whatever the fix is, it's not translating well to modern hardware with more cpu/gpu power.

now for my personal experience:

on my best computer with 3 different operating systems each (windows 7, 8.1, and 10 technical preview) this issue is present on any emulator with any plugin. yes altering region and VI settings can fix things but then the other 90% of the game (the courses where this issue is not present and single player mode) becomes too slow.

and I guess that's it! I never had this on the n64. and it sucks that Nintendo charged people for a broken emulation on wii virtual store. I hope a solution can be found that doesn't require us interrupting the flow of gameplay while in 2 player mode to tweak some setting. that is just intolerable in my opinion. my friends would just be like this is dumb and not want to play anymore lol.

on one of the other threads I read about this on here you guys talked about implementing some type of virtual VI settings that could vary on the affected courses (if I understood correctly)

**Comment by theboy181** [comment]
I would like to point out that REAL HW would mean N64 only. I can tell you that I have tested this on real HW and this issue doesn't occur the same way as it does on the emulators.

You can tell from Lakitu count down if the game is going to run too fast.  

@cxd4  had an explanation/solution, where he thinks that the emulator needs to support dynamic VI/s. I'm uncertain if this is how the real HW did this, but this type of a hack allow MK64 to keep the FPS at 30 and run at the correct speed I would think.

**Comment by oddMLan** [comment]
No "real" fix given the non-cycle accurate nature of Project64. But ~~#605~~ #607 has been merged, so I'll highly advice to close this issue.

**Comment by cxd4** [comment]
Based on title of issue I would agree.  Though @theboy181 usually too inactive to probably notice this.

**Comment by theboy181** [comment]
There is the cheat code, but does this qualify as the fix?  I think that this issue could be closed because a workaround was discovered, but I don't think the core (real) issue issue is fixed.

Have been inactive lately. :( been working on my rental house..
