### ISSUE TITLE
Save States Kill Sound in Turok Games. (Possibly Others)

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#329]
Loading save states with certain titles - Turok ones in particular, has a tendency to make the sound disappear. All plugins are affected as far as I know. Using Fixed Audio Timing can partially cure the problem (at the cost of crackling) except sometimes loading the save state will simply freeze the emulator instead.

**Comment by jjjustinleblanc** [comment]
Also happens in Paper Mario, but not always. Sometimes loading a save state is fine, sometimes there is no audio and can't be corrected until using in-game saving and then restarting the emulator and playing from an in-game save.

**Comment by LegendOfDragoon** [comment]
Well, I just tried Turok Dinosaur Hunter and loading a save state had working sound. Turok 2 seemed to have problems with certain audio plugins. I'd say some of the blame goes to the audio plugin, but the emulator core isn't making it easy ;/ . As I thought, the problem is similar to Rogue Squadron's load state issue. I must say, it seems like 1964 Audio is pretty good for Turok 1 & 2. I'm glad that there's usually at least 1 audio plugin that works great for a particular game.

**Comment by AmbientMalice** [comment]
@LegendOfDragoon Bear in mind Turok 2/3 can SEEM fixed with certain plugins, such as Shunyuan's, but aggressive saving and loading will still stop the sound. Sometimes the game will save and load a few times without incident before glitching.

**Comment by LegendOfDragoon** [comment]
Briefly tested with Shunyuan's. His loaded, but after quickly loading again, sound broke. With a modified 1964 Audio, I could keep loading a save state and it wouldn't break. Only issue I'm aware of so far is that if you load as soon as the game boots, there's no sound. But if you wait a few seconds, it works fine from then on. I wouldn't call it an ideal solution yet since it has load state issues in other games. But it's a good temporary solution.

I may try doing more aggressive saving and loading, later on. But I need to try and solve some other issues first.

**Comment by project64** [comment]
I will have a look tonight and see if I can work out what is going on

**Comment by LegendOfDragoon** [comment]
@project64 it's going to be tough to debug since current open source plugins are not really suitable for those games.

Basically, the problem occurs if there's deinitialization code in RomClose. Plugins that do any sort of significant deinitialization will have issues in Turok2, Rogue Squadron, etc, when loading a save state. On 1964, this isn't the case. Either 1964 did some weird work around and the fault is the audio plugin, or Project64 needs to do something different, for handling loading save states.

**Comment by AmbientMalice** [comment]
When using Jabo's, Turok 2 has no sound without CF=1. Other plugins work fine with CF=2.

**Comment by LegendOfDragoon** [comment]
>When using Jabo's, Turok 2 has no sound without CF=1. Other plugins work fine with CF=2.

Nice find. I generally use CF=1 anyway, now that I've figured out a good setup for most games I play.

Did more experimenting today, and it seems the turok save state issue isn't the same as Rogue Squadron's issue. It seems like the problem is mostly from the plugin side. 

Weird thing is that if you load a save state with an audio plugin that works, you can swap the plugin at run time to switch to w/e plugin you want.

**Comment by project64** [comment]
I only use the default plugins/settings I thought I saw the issue this morning and have not been able to reproduce it since

**Comment by LegendOfDragoon** [comment]
@project64 In Turok 2, the audio only works after loading save state if FAT is enabled, with Jabo's audio.

**Comment by AmbientMalice** [comment]
There's a side effect of using FAT with Turok 2. Sometimes the game will freeze when loading. Pressing the load button again will load the state correctly. But leaving it instead will crash the emulator after a few seconds.

**Comment by LegendOfDragoon** [comment]
I heard a ton of crackling with Turok 2 with FAT enabled anyway ;/ . Although I didn't bother tweaking the AI count.

I'm guessing the problem has to do with AI interrupts for Turok 2. Fixing that, seems to fix the problem with plugin's like Azimer's. Sadly I don't really know too much about AI emulation. Best I can do is experiment or look at source code of emulators & a few audio plugins.

For Rogue Squadron, deinitialization in RomClose the main problem.

**Comment by AmbientMalice** [comment]
Yea, the crackling in Turok games with FAT deterred me from enabling it - plus it doesn't really fix the odd save state behavior.

**Comment by LegendOfDragoon** [comment]
>Pressing the load button again will load the state correctly. But leaving it instead will crash the emulator after a few seconds.

I get this issue with FAT disabled too, so that must be a different issue. I'm losing motivation unfortunately, since most of the audio plugins I need to learn from are closed source. I'll try studying AI emulation by reading the source code in various emulators ;/ . Other than that, all I can do is guesstimate and hope something happens.

Another issue is that I made a save state while using HLE audio and when I load the save state with LLE audio, I hear this awful noise for like 2-3 seconds. I'm guessing it has to do with the fact that the particular HLE audio I used, does not write to DMEM, so its contents aren't stored in the save state. Makes me not want to use HLE audio anymore ;/ . Although I rarely use it these days.

**Comment by LegendOfDragoon** [comment]
I've been experimenting today.  Is there a particular part of the game where you're guaranteed to lose audio when loading a save state? Oddly enough, it seems to be very hard to reproduce on certain plugins. Only time I've seen it be a guaranteed problem is when I press F7 right after booting the game. FWIW it happens in Mupen64 0.5 as well.

I do experience that game freeze issue when loading a save state. I believe that also happens on other emulators, iirc. Most emulators don't have a CPU debugger so it's going to be a hassle to solve.

**Comment by AmbientMalice** [comment]
Ingame tends to be reliable for both Turok 2 and 3, at least for me. You have to endure T2's opening cutscene. T3's is skippable. Hammer F5 and F7 over and over until it breaks.

**Comment by AmbientMalice** [comment]
That issue where the sound craps itself if you press F7 immediately after booting a rom is strange, and affects a wide range of games. Perhaps a delay could be added after rom booting to prevent it.

**Comment by cxd4** [comment]
Does this issue happen with audio HLE, prevent executing audio tasks on the RSP plugin?

Because loading saved states can and will be more difficult with the Project64 RSP plugin, due to some extra timer handling, plus the semaphore which is known to break audio if the sync is mis-timed.

**Comment by LegendOfDragoon** [comment]
>Does this issue happen with audio HLE, prevent executing audio tasks on the RSP plugin?
Because loading saved states can and will be more difficult with the Project64 RSP plugin, due to some extra timer handling, plus the semaphore which is known to break audio if the sync is mis-timed.

I actually don't use pj64's rsp too often, but I tried it just now. Audio still worked, but the graphics were messed up when I loaded a save state, when using LLE for both audio and gfx. Most people generally use HLE gfx for Turok though.

In my experience HLE audio is problematic with save states. At least Azimer's and m64p's.

@AmbientMalice I think spamming F5 and F7 mostly effect plugins like shunyuans. I just tried it and  was never able to break audio after spamming F5 and F7. I did it during the cut scene after starting a new game. So I think the main issue is loading a save state while you're currently in a certain part of the game where there's no audio playing (only seems to happen in this scenario).

>That issue where the sound craps itself if you press F7 immediately after booting a rom is strange, and affects a wide range of games. Perhaps a delay could be added after rom booting to prevent it.

I didn't know that happened in multiple games lol. I never really load a save state quick enough I guess xD.

**Comment by cxd4** [comment]
All I'm meaning is if there is still an issue when using audio HLE.

Which RSP plugin has no significance to that question since the audio would be done elsewhere.

**Comment by LegendOfDragoon** [comment]
Guess it's true I didn't specifically mention that I tried loading a save state with HLE audio for this. Audio HLE has this issue along with additional issues. The sound was more likely to get messed up when l loaded with audio HLE. In fact, I just tried again, and the voices are messed up when I load a save state with audio HLE enabled (Azimer's).

**Comment by cxd4** [comment]
Is it controllable based on whether state was saved from using HLE audio before re-loading it?

**Comment by LegendOfDragoon** [comment]
Well, looks like the problem is even worse when I made a save state with Azimer's HLE audio. It turns out that Turok2's audio microcode is ABI 1, which Azimer never fully fixed. The audio is messed up even without using save states, so can't comment too much on that, other than it being a bad idea to use at all.

Not sure if M64p fully fixed ABI 1 either, but it seems better, and LaC's seems better as well.

**Comment by AmbientMalice** [comment]
This problem has definitely gotten worse since 1.6, and to a degree 1.7, though I couldn't test Turok with 1.7 for some reason.

PJ64 1.6 is extremely resistant to sound dropping out when loading save states with RE2 using Jabo's plugin. (It eventually caved, though. Also, no voices, but 1.6 was always like that.) I couldn't make Turok 3's sound drop out despite hammering F7 for a whole minute.

The related bug where games lose sound if you load a save state just after booting a rom goes way back. But this other issue is a clear regression.

**Comment by LegendOfDragoon** [comment]
For Rogue Squadron at least. I imagine it would help other musyx games too. Seems like the losing audio after loading save state issue is somewhat related to the AI_STATUS register and MI_INTR register. I say somewhat because even though it's one of the reasons, the deinitialization is still a problem with plugins like Azimer's.

>This problem has definitely gotten worse since 1.6, and to a degree 1.7, though I couldn't test Turok with 1.7 for some reason.

I was able to boot Turok 2 with 1.7. The intro had crackling / stuttering with FAT in 1.7. Didn't bother testing save states though.

>So this is another example of 1.6-1.7 having sound code that might be "less accurate" but that works better - as seen with the sound crackle in a variety of games introduced in 2.x

1.6 doesn't handle audio internally. 1.7 was the first version with an option for fixed audio timing. What the core does do, is handle things like initialization, load / save states, etc.

>PJ64 1.6 is extremely resistant to sound dropping out when loading save states with RE2 using Jabo's plugin. (It eventually caved, though. Also, no voices, but 1.6 was always like that.) I couldn't make Turok 3's sound drop out despite hammering F7 for a whole minute.

Interesting point about 1.6. I may try testing that emulator, but that will have to wait until I figure out how to fix RE2's audio. What flaws does 2.2's FAT have with RE2? Seemed decent imo actually.

**Comment by AmbientMalice** [comment]
>I was able to boot Turok 2 with 1.7. The intro had crackling / stuttering with FAT in 1.7.

I was testing without FAT since it would be ideal to be able to run those games without the crackle that FAT brings with it.

>What flaws does 2.2's FAT have with RE2? Seemed decent imo actually.

Very slight popping from time to time. There's no real way to fix it. Jabo's audio sync+FAT or even PJ64's audio sync+FAT causes a lot of problems.

**Comment by LegendOfDragoon** [comment]
Well I think I found a lead. First of all, a bad save state will inevitably have problems. I will need to do more experimenting to see if my idea for a workaround will work reliably and without side effects.

Outside of modifying the way the emulator handles save states, there's really nothing else you can do from the emulator's side, other than using fixed audio timing. It's up to the plugin developers to fix their plugins really.

Now about RE2, I am now interested in testing this game. I was able to spam F7 and didn't lose audio with certain plugins. Is there a particular part where this messes up? Feel free to upload a save state, if you have one that is giving you trouble with audio.

**Comment by project64** [comment]
talking to cxd4 about an RSP issue, one of the things there is that the state of the RSP is not preserved over a save state, well some is, but only the information that is shared with the main CPU things like the RSP vector/gpr registers are not preserved. It may be good to give notification to plugins on save and load so they can keep state information. 

Does not help any closed source ones of course

**Comment by LegendOfDragoon** [comment]
I believe the reason Jabo's and Azimer's worked in 1.6 for loading save states is due to the way the spec was. Changing the plugin spec can have negative effects on older plugins. I'm starting to care less about closed source plugins tbh. No point in holding back, just to use that stuff ;/ .

>talking to cxd4 about an RSP issue, one of the things there is that the state of the RSP is not preserved over a save state, well some is, but only the information that is shared with the main CPU things like the RSP vector/gpr registers are not preserved. It may be good to give notification to plugins on save and load so they can keep state information.

This reminds me of an issue with the RSP recompiler and save states. Sometimes while it is recompiling RSP code, it has the wrong task type, which can affect the recompiler analysis. Fortunately, usually it's harmless since that code is generally never reached anyway. But it's still important to look into. This more likely happens in Musyx games I think. I see it in games like Rogue Squadron and RE2.

**Comment by cxd4** [comment]
Thing is, a saved state is more likely to work without RSP LLE, but it is still possible for it to not work.  Actually with HLE gfx && HLE RSP the CPU can still have some kind of corruption if you re-load the same saved state enough times, so we have multiple issues at play here.  We can just look at making the most out of isolating the individual ones.

**Comment by Frank-74** [comment]
Its not just save states that kill Turok's sound.  Played this today with default plugins/settings, and about 30 minutes in, sound cut out during normal play.  I never made a save state.

So its probably another issue which save states amplify.

**Comment by LegendOfDragoon** [comment]
>Its not just save states that kill Turok's sound. Played this today with default plugins/settings, and about 30 minutes in, sound cut out during normal play. I never made a save state.

Which Turok game were you playing? I'll have to see if it happens on all audio plugins. I believe there are multiple issues.

**Comment by Frank-74** [comment]
Turok - Dinosaur Hunter (U) (V1.1)/(V1.2).  I collected about 4 keys before it cut out.

**Comment by LegendOfDragoon** [comment]
>Also happens in Paper Mario, but not always. Sometimes loading a save state is fine, sometimes there is no audio and can't be corrected until using in-game saving and then restarting the emulator and playing from an in-game save.

I've never really played this game, so if you can upload a save state, I'd appreciate it :) .

>Turok - Dinosaur Hunter (U) (V1.1)/(V1.2). I collected at least 4 keys before it cut out.

Man, playing the game yesterday brought back good memories. I didn't get far enough into the game though. You brought a good point about save states not being the only thing that kills sound. I don't think it's a coincidence that the plugins that have severe issues in 1964 1.1, randomly lose audio in PJ64 in during regular gameplay + save state issues. Rather than relying on FAT (which is hit or miss depending on the game), I just use stable audio plugins for those games. If there's a part where audio consistently breaks, it would be easier to track down ;/ .

If @project64 is willing to take risks or perhaps extensively test save states, one way to reduce the chance of obscure save state issues is to make sure (AI_STATUS_REG & 0x80000000) == 0 upon loading the save state. I noticed my issue with Rogue Squadron loading states a few days ago was cured, when I cleared that bit in status reg and set MI_INTR_REG to 4. This may or may not help closed source plugins, but it certainly helped with open source plugins.

One interesting thing is the fact that CheckInterupts does nothing in PJ64 2.x, yet I think it may do something in other emulators ;/ . I will try to look into this.

**Comment by LegendOfDragoon** [comment]
Ok made a pull request that should "fix" this issue. I still think it's best not to use such plugins for those games since it randomly loses audio in game anyway. Good news is that you can hack it at runtime if you strongly insist on using those plugins. You can either use a memory editor like cheat engine to fix it anytime it stops, or you can make a save state and quickly load it (after the pull request gets accepted).

Now I'm able to load a save state immediately after booting it up :) .

It's interesting how the reason certain audio plugins are unstable on 1964 is because they call CheckInterupts too frequently.

@jjjustinleblanc if my pull request gets accepted, please test Paper Mario.

**Comment by AmbientMalice** [comment]
Good work. Once you've finalised the pull request (RDB settings in particular) I'll compile and get testing. This is a great improvement to PJ64, even if it isn't quite as clean and elegant as one might have hoped.

Darn you, closed source plugins!

**Comment by LegendOfDragoon** [comment]
@AmbientMalice, my PR got merged so feel free to compile and test now :) . It's a per game option so just paste AudioResetOnLoad=Yes for any game you want to test this with.

>Darn you, closed source plugins!

It sure was a pain trying to figure out what was wrong with certain plugins, as well as figuring out how certain plugins were successful with certain games.

**Comment by Frank-74** [comment]
Ok, just tested Turok Dinosaur Hunter.  Added AudioResetOnLoad=Yes to rdb.  Load my game from the .mpk in game.  Now pressing F5 doesn't make a save state.

**Comment by AmbientMalice** [comment]
AudioResetOnLoad fixes Tony Hawk games. Very nice. Turok 3 isn't playing nice. Sound doesn't drop out anymore, but the game freezes on every other load. So you have to press F7 twice to load a game. This is a preexisting problem.

I'm gonna test more titles later and then I'll make a pull request.

**Comment by Frank-74** [comment]
Strange...  Using Turok - Dinosaur Hunter (U) (V1.0), F5 works fine.  But with Turok - Dinosaur Hunter (U) (V1.1)/(V1.2), F5 does nothing, doesn't make a save.

**Comment by oddMLan** [comment]
>I'm guessing the forward slash in the Good Name is causing it not to save.

You're right about that. The forward slash (/) is a forbidden character in a filename.

**Comment by AmbientMalice** [comment]
There are still some problems. Loading save states IMMEDIATELY after booting a game will usually result in slow sound. If all else fails, putting a 3-5 second delay after rom load before save states can be saved\loaded should prevent that problem.

Games that use MORT speech still require FAT with Jabo. Azimer's doesn't require FAT. I'm hoping 1964 audio won't require FAT, either. (Or I hope we can stop the crackling with FAT some other way.)

How does your modded 1964 Audio handle games like RE2 and TWINE without FAT, @LegendOfDragoon? Because Jabo gets garbled voices, but Azimer's 0.60 in LLE doesn't.

**Comment by Frank-74** [comment]
Dinosaur Hunter locks up with a fatal error every now and then with Jabo 1.7.  No lockups at all with Azimer's 0.60 in LLE.

**Comment by LegendOfDragoon** [comment]
>There are still some problems. Loading save states IMMEDIATELY after booting a game will usually result in slow sound. If all else fails, putting a 3-5 second delay after rom load before save states can be saved\loaded should prevent that problem.

Well I'm pretty sure that's audio plugin specific. I only experienced this issue with certain plugins iirc.

>Games that use MORT speech still require FAT with Jabo. Azimer's doesn't require FAT. I'm hoping 1964 audio won't require FAT, either. (Or I hope we can stop the crackling with FAT some other way.)
How does your modded 1964 Audio handle games like RE2 and TWINE without FAT, @LegendOfDragoon? Because Jabo gets garbled voices, but Azimer's 0.60 in LLE doesn't.

Unfortunately 1964 Audio doesn't run those kind of games well. I'm honestly surprised Rogue Squadron works so well, yet other musyx games seem more difficult. I need to test more of a variety of games. I don't feel like hacking around with 1964 Audio tbh, since there are easier ways to get good audio in these games. After doing more testing with different plugins, the only game I can think of, where 1964 Audio outshines other plugins (at least on my end), is Rogue Squadron. The other few games I mentioned that sound good on 1964 Audio also sound good on other plugins too. For instance, Nuclear Strike sounds good in Azimer's 0.70 XA2 and 0.56 WIP2, WDC sounds good in Azimer's DS8 and Shunyuan's, etc.

RE2 is a tough game to get proper audio in. I'll need to test TWINE more. Does Azimer's plugin handle TWINE good enough with FAT disabled?

Once Azimer releases his source, I think there will be a good chance that obscure games like Top Gear will eventually have proper audio.

>That said, FAT causes no issues with Azimer's in RE2 and other MORT speech games, and also seems to have very little crackle. So if PJ64 used Azimer's or a similar plugin for those games, there'd likely be no problem with FAT being enabled.

I did notice that Azimer's somehow was pretty good with FAT compared to Jabo's with FAT in RE2.

>Dinosaur Hunter locks up with a fatal error every now and then with Jabo 1.7. No lockups at all with Azimer's 0.60 in LLE.

I'll have to do more testing in this game. I was gonna say a tweaked 1964 Audio plugin was the most stable, but then I ran into a part where the game crashes. It also happened with Shunyuan's Audio and Zilmar's. So scratch that ;/ .

**Comment by LegendOfDragoon** [comment]
Did anyone test out paper mario? Also are there any new issues?

Turns out the main issue with Azimer's ABI1 code is an unimplemented function. Only some ABI1 games use the function.

**Comment by LegendOfDragoon** [comment]
@AmbientMalice I fixed that load state issue with FAT + AI count=0 recently. Feel free to test and give feedback.

**Comment by AmbientMalice** [comment]
@LegendOfDragoon I'm pleased to report that the FAT errors seem to be fixed. Beautiful, smooth sound after loading save states. I'll close this issue. Good work.

**Comment by LegendOfDragoon** [comment]
>There are still some problems. Loading save states IMMEDIATELY after booting a game will usually result in slow sound. If all else fails, putting a 3-5 second delay after rom load before save states can be saved\loaded should prevent that problem.

I think I fixed this issue a few months ago. I'd like to hear from others whether they can confirm that this is now fixed.
