### ISSUE TITLE
Undefined behavior with CN64System::RunRSP error

### ISSUE THREAD

**Issue by LegendOfDragoon** [project64/project64#415]
When something goes wrong in the RSP, such as the protect memory issue that blocks memory access during SP DMA, depending on the circumstances, it does not always trigger the error message, when something wrong happens.

For instance, when using memcpy for SP DMA, the chance of it happening depends on the computer and compiler. For instance, it did not appear when I compiled an RSP with Intel's compiler. Also, enabling RSP_SAFE_DMA made the error never show up. Yet if I ran it in a debugger with MSVC and stepped through the instructions in SP DMA function, it would expose the issue.

The only reliable way for me to get the error to show ( without using __try{} __except{} ), was to write my own version of memcpy. Somehow that seems to consistently expose the problem in SP DMA. Since this undefined behavior could also fail to expose other problems, I normally just use __try{}__except{} when I really want to check for problems.

**Comment by cxd4** [comment]
Is this a recompiler problem, or it affects interpreter also?

Do the exceptions only happen with 4 MB RDRAM

**Comment by cxd4** [comment]
Also, your terminology isn't straight--memcpy is never _undefined behavior_.  Recompilers however never fall within the domain of the C specifications as far as guarantees.  There's no such thing as undefined behavior in C that "depends on the computer".

**Comment by LegendOfDragoon** [comment]
Basically, the problem is that there's something wrong with the error detection code in the emulator core. That's where the real UB is. I just pointed out that when using memcpy, the error only sometimes gets exposed, and if I enable RSP_SAFE_DMA in dma.c in the RSP, the error never gets exposed which is a bad thing. I need to have Tony try that, the next time he's on.

I just find it odd that the chance of the error getting exposed, depends on your implementation of SP_DMA.

RSP interpreter and RSP recompiler have the same issue, and using 8MB didn't make a noticeable difference.

**Comment by cxd4** [comment]
SP SAFE_DMA is supposed to be safer, so it figures that it would less likely raise an access violation.
So it makes sense that defining RSP_SAFE_DMA  would fix the issue.

The memcpy on the other hand, are you able to illustrate the custom implementation of memcpy you did that fixed the error by replacing the old memcpy?  A link to the old line in original source could come in handy as well since I'm a lazy bastard just energetic enough to scratch his ass.

**Comment by LegendOfDragoon** [comment]
Ok well, I did some debugging since it's been a while. I found an easy way for you to see the problem. I use FAT enabled AI = 0, HLE audio, LLE gfx (jabo's). On the 3rd time SP_DMA_WRITE is called, you'll see some unusual behavior. For convenience you can go ahead and enable RSP_SAFE_DMA.

So on the 3rd call, once you get to https://github.com/project64/project64/blob/master/Source/RSP/dma.c#L141 . Click step into and it will jump to your next breakpoint, rather than going to the next instruction.

As for the custom memcpy, it was nothing fancy, just 32bit writes with an assumption that it's aligned. I'm a bit confused now as I tried it again and doesn't seem to be any different than memcpy. Either some weird compiler wizardry or idk ;/ . Been too long since I debugged this, I guess.

**Comment by cxd4** [comment]
> I found an easy way for you to see the problem. I use FAT enabled AI = 0, HLE audio, LLE gfx (jabo's). On the 3rd time SP_DMA_WRITE is called, you'll see some unusual behavior.

Still can't reproduce it.  Nothing unusual about SP_DMA_WRITE has ever happened for me, just tony971 and I guess you too.  For some reason Project64's re-compiler "protect memory" is generating different SP DMA parameters for you guys than it is for me; otherwise all of us would be getting the error and not just him or you.  That's why I was going to send him the modified pj RSP plugin last night until the router shut me off.

>Click step into and it will jump to your next breakpoint, rather than going to the next instruction.

I wrote my own sprintf/MessageBoxA debugging already and am not going to use Microsoft's debugger.  Stepping into things in Visual Studio is stupid when I can just use C to debug C.

http://ft.trillian.im/785abe041074fd64135ab3318aff1ec8767ab03d/6yFyJCkaRS1zQuEyCLS82ce7p1T3s.jpg

And LLE graphics only confuses the source of the issue.
I want him to continue testing HLE graphics && HLE audio; this leaves the JPEG ucode.

After 76 iterations of the JPEG ucode, the save data finishes loading and the game starts with no more JPEG to execute (meaning no more RSP emulation if HLE graphics and audio).  So sometime before the 76th count, he should see unusual SP DMA write config from my message box right before the crash.  And again Visual Studio debugger can kiss my ass.

>As for the custom memcpy, it was nothing fancy, just 32bit writes with an assumption that it's aligned.

Because of this? ...
https://github.com/project64/project64/blob/master/Source/RSP/dma.c#L116

That's an error on pj64 rsp's side; DMA addresses are always 64-bit aligned, even if the RSP has to ignore the low 3 bits which pj64 isn't doing like it should be.

Otherwise there's nothing else that can cause an unaligned memcpy in that function.
```c
memcpy(Dest, Source, Length);
```

**Comment by LegendOfDragoon** [comment]
I incorrectly thought this issue was caused by a mistake in the Protect Memory code. I didn't know the exception was actually intentional. The reason it only shows up in certain situations, is because the exception handling is incomplete, as zilmar mentioned. I was under the impression that something still goes wrong in the game, even if the error message didn't show. Doesn't seem to be the case.
