### ISSUE TITLE
Nintendo 64 Disk Drive organization

### ISSUE THREAD

**Issue by vgturtle127** [project64/project64#470]
First, I think we should give Nintendo 64 Disk Drive games their own section of the RDB (since it requires an additional system and is separate from the N64's library).

We should also change "Load ROM" to something more universal, such as "Load game" or "Load image" or something. Just to avoid confusion in regards to game support.

These are fairly simple changes, so I don't think anybody would have any issue with them. But just in case. :smile:

**Comment by cxd4** [comment]
"Load game" is no better than "Load ROM" because ROM images are not necessarily games.  It's a bit prejudicial to assume that Nintendo 64 executables are only supposed to be games--I like it when ROMs are not games.

**Comment by vgturtle127** [comment]
Well, alright then maybe "Load image"? "Load catridge"? "Load..."? :laughing:

**Comment by cxd4** [comment]
Just a personal question of mine but what is misleading about calling them ROMs?  Do 64DD cartridges not use ROM chips like standard n64 cartridges do for storing the software?  I don't know.

**Comment by Frank-74** [comment]
Well having never seen a 64DD game or used one.  I do remember from way way back, a Disk Drive attachment that the N64 sat on.  I'm guessing these games run on this.  So its not a ROM its a disk drive with write capability.

What about Load Emulation?

**Comment by vgturtle127** [comment]
It's not misleading, I just think the terminology should be changed to better match the current compatibility.

It is technically a readable and writable magnetic disk. Sort of like a hard drive or ZIP disk.

"Run" would be fine. Anything that sounds good, as long as it isn't "ROM" since that implies that it has to be read-only.

**Comment by death-droid** [comment]
This is kinda completely pointless. Most users will still identify them as a ROM regardless that its not read-only memory. Breaks no functionality keeping it as it is. Also if im not mistaken the dumps would only contain the read-only section of the disc.

**Comment by vgturtle127** [comment]
Yeah, if that is true then I suppose we could keep it the same. How does Project64 handle writing to the disk in LuigiBlood's build (or the main build for that matter)? It obviously doesn't write to the ROM dump...

**Comment by Frank-74** [comment]
AllowROMWrites=Yes, in the RDB.

**Comment by vgturtle127** [comment]
Well, I meant where does it write the data? To a separate ROM file, an SRAM file, or maybe a sort of "save state"? Is it just a temp data file? How does this black magic work? :laughing:

**Comment by death-droid** [comment]
@LuigiBlood

**Comment by LuigiBlood** [comment]
We're dealing with 64DD conversions HACKS and not exactly 64DD disks (which are REWRITABLE).
Conversions writes into the ROM array. I just made a little option that allows writing to its cartridge space so it can "save" temporarily (you lose all changes once you end emulation, because it's not saved).
Really, it's that simple. Flashcarts actually supports that so why not PJ64?

About making 64DD emulation as a whole, we need to think about it:
- We need 64DD IPL, easily can just make a browse button thing in the settings or something.
- Don't forget combos, like F-Zero X cartridge with Expansion Kit together.
- 64DD disks are rewritable. The data is seperated into several areas, like ROM area, which contains the System Data and RAM area, made to be rewritable. We can probably do a save file with just the RAM area.
- 64DD disk dumps aren't really accurate on a physical level. They're only accurate in the libleo (software) order, the conversion needed to make them run on MESS was actually changing the order to be physically "accurate". Not to mention missing C1/C2 data. But that's not a problem overall.

**Comment by vgturtle127** [comment]
Oh alright. So in order for us to be able to emulate development disks won't we need the development IPL? And I didn't think that was dumped yet...

**Comment by LuigiBlood** [comment]
Development IPL ROM? That's already dumped, and it's included in the N64 SDK. So there's no problem about that. There's one ID register that changes as well.

**Comment by vgturtle127** [comment]
Oh, OK. I thought the N64 SDK was impossible to use due to some password protected archive or serial system they had in place?

**Comment by LuigiBlood** [comment]
Considering I got to use it to make a dumper, I highly doubt it was the case.

I know it's a file called "ipl4rom" (no extension).

**Comment by vgturtle127** [comment]
Maybe I just had trouble with it back when I tried it. Couldn't hurt to try again. I suppose there is n64sdk as well, but that doesn't include most of the stuff from the official SDK obviously...

**Comment by oddMLan** [comment]
Is this still an issue?
64DD support is now officially implemented, although write support is still on the way. Isn't that the case @LuigiBlood?

**Comment by LuigiBlood** [comment]
64DD write will come soon. As soon as we finish to decide on a standard for it.
