### ISSUE TITLE
Repo cleanup

### ISSUE THREAD

**Issue by vgturtle127** [project64/project64#472]
- Remove documentation from zlib directory

This is unnecessary, we can just have a license file that contains all of the license stuff.

- Remove Glide64 Help directory

More documentation we don't need in the repo, but we could store on the site or in GitHub releases. Or just not at all, as well.

- Remove GlideHQ readme

Same as above.

- Add a .gitattributes file to tell GitHub what files are what

I will write it, I just need to get permission from you guys.

- Add a license.md and readme.md in the main directory

Again, I can write it as long as I have permission.

- Update 7z and zlib DLL files included in installer

This isn't in the repo, but it fixes a few security issues and bugs, so it should be done if it hasn't already.

Also, add #418 to the above as well.

**Comment by vgturtle127** [comment]
I can do most of this myself, I just need permission to do so. I will also write all of the files above as long as I have permission.

After I get said permission I will make changes one at a time in a pull request.

Thanks for listening to my extreme OCD.

**Comment by AmbientMalice** [comment]
>Remove Plugin directory
>This just contains Jabo's DLL files. We should just package them with released installers.
IMO, it would be wise to wait until Azimer's is integrated into PJ64 before removing the only audio plugin it has.

**Comment by project64** [comment]
I like that I can clone a repository and then you can just build and the solution will compile and be able to run.

This is is why I have the DLL's there so that the project will just work straight out of source code, if it si in a different dir, then it requires some way to be able to pull it in automatically or create more manually steps and the manual steps is what I am trying to avoid

**Comment by vgturtle127** [comment]
@AmbientMalice I think you might have misunderstood. I just mean remove the DLL files from the repository, not from the installer or anything. But I agree, we should definitely wait until we switch to Azimer's plugin (soon, right?).

@project64 Fair enough. Do you also want to keep the binno DLL files and Inno Setup binaries?

I am always OK with manually adding plugins and such since I use my own plugins anyway. But I can understand wanting that for quick testing.

Is everything else OK with you guys? Do you have any additions or suggestions?

**Comment by AmbientMalice** [comment]
@vgturtle127 I meant the repo. Since PJ64 has no official build bot (yet) users are told to compile PJ64 themselves. It's not ideal if the emulator builds with no audio plugin.

>we should definitely wait until we switch to Azimer's plugin (soon, right?).

Should be reasonably soon. Bugs are still being ironed out, but the worst bugs seem to be on PJ64's side, audio-wise.

**Comment by project64** [comment]
@vgturtle127 the binno binaries  InnoCallback.dll and itdownload.dll, or you referring to something else I missed. While they are not needed to run the compiled binary they are needed to compile the installer

**Comment by Frank-74** [comment]
> but the worst bugs seem to be on PJ64's side, audio-wise.

I have to disagree a bit here.  0.56 and 0.60 are miles better than 0.70 at the moment.  DS8 comes relatively close to 0.60, only if you remove the streamdma define in the source.  It still crashes when shutting down PJ64 with a game running.  Serious crash too, as it locks the whole system and have to pull the plug.  XA2 has wxWidgets conflicts causing crashes.  Because PJ64 and XA2 both use wxWidgets CoInitialize, the closing of threads conflict.  And the streaming DMA causes crackles and pops in any game without FAT enabled.  Its a LONG way off being ready to be the default plugin for PJ64.

**Comment by LegendOfDragoon** [comment]
I somewhat agree with @Frank-74. A good portion of the problem is the plugin itself, but the core also has some serious issues too.

At the same time, I wouldn't call 0.56 and 0.60 miles better than 0.70. 0.70 is certainly better for Musyx games, compared to 0.60 and likely also 0.56. Just depends what game you play. As for the crashing, both the core and plugin needs some fixing.

Streaming DMA works good in WDC :smile: .

**Comment by AmbientMalice** [comment]
>It still crashes when shutting down PJ64 with a game running. Serious crash too, as it locks the whole system and have to pull the plug.

I've never had that happen. Must be hardware/OS specific. But you're right - Azimer's has problems. But in my user experience, r4300 usage skyrocketing after loading save states is more alarming since it makes save states useless and save states are the bread and butter of an emulator.

**Comment by Frank-74** [comment]
Well since the new FAT=0 dynamic audio timing, I can run any musyx games with LLE and they work perfectly.  Played through TWINE from beginning to end in 2.2.0.3 using Azimer's 0.60 with FAT enabled.  Never had garbled speech once.

**Comment by vgturtle127** [comment]
@AmbientMalice Alright, thanks for the heads up.

@project64 I mean all the binaries in the Inno Setup and binno directories. There are 8 binaries in the Inno Setup directory (including the default images), and the two binaries you mentioned in the binno directory. If you didn't know about the binaries in the Inno Setup directory, you might not need them. If you want to compile the installer, I would think the only files you would need are the .iss files, but maybe I'm wrong.

I can say with definite certainty that both Project64 and Azimer's plugin have issues that should be fixed (really every N64 emulator and plugin do). However, moving from Jabo's audio plugin to Azimer's makes even more sense knowing that the plugin (Jabo's that is) is closed-source and probably not going to be maintained further (although if Jabo were to come back and open-source them or something that would be cool). So in the end, even if Azimer's plugin had next to no compatibility, it would still be better than Jabo's on the simple fact that we can improve it and we know how it works and what not.

Having said all that, I feel Jabo has better compatibility when running most games that I test when testing N64 emulators and plugins. It even works a bit better with N64DD games, and that was a pretty recent development. Although admittedly, audio crackling and distortion happened no matter what plugin I used in Project64. I need to test more.

Anyway, if you would like to keep every binary, that is fine. Just let me know so I can update the list. :smile:

**Comment by LegendOfDragoon** [comment]
>But in my user experience, r4300 usage skyrocketing after loading save states is more alarming since it makes save states useless and save states are the bread and butter of an emulator.

If only save states even worked with XA2 plugin, without relying on some workaround :smile: .

>Edit: And Jabo's audio is the only one that doesn't have a random delay in audio on rom start. All of Azimer's plugins have a random delay between pressing a button and hearing the sound in LLE. Pausing and unPausing can restore the timing to instant, but timing is random each time you pause/unpause. There probably needs a checkinterrupt somewhere on init.

I cannot reproduce this delay in audio on rom start. My guess is that on your hardware, it takes longer to boot? The only way I've been able to reproduce this issue is if a plugin I'm using has a message box that pops up soon after booting. Forgot to ask, but is this for FAT or non-FAT? If it's FAT, then not much you can do, unless you find a way to improve it. Checkinterrupt does nothing in PJ64 2.x. It's only for other emulators and honestly, Azimer's plugin might be calling it too often, since that's the reason games freeze with certain audio plugins in 1964.

>Well since the new FAT=0 dynamic audio timing, I can run any musyx games with LLE and they work perfectly.

Certainly not Rogue Squadron :disappointed: .

As for switching default audio plugin, I think it's best to wait until a lot of issues are fixed. Being open source doesn't automatically mean it should become default. Problems need to be solved first.

**Comment by cxd4** [comment]
Well vgturtle it's not that binaries need to exist in the Git; it's just that zilmar insists on maintaining his power and control over what other people do by infusing the installer libraries and sources as part of the source to Project64 itself as an emulator.  In other words that can't be helped.

**Comment by Frank-74** [comment]
> I cannot reproduce this delay in audio on rom start. My guess is that on your hardware, it takes longer to boot? The only way I've been able to reproduce this issue is if a plugin I'm using has a message box that pops up soon after booting. Forgot to ask, but is this for FAT or non-FAT? If it's FAT, then not much you can do, unless you find a way to improve it.

Happens with LLE (not HLE), FAT on or off doesn't affect it.  Always random delay between sound fx and video, which pause/unpause changes.  All Azimer plugins do it.  Jabo's plugins are all consistent, but have a slight delay that is not very noticeable.

**Comment by project64** [comment]
> Think about it. Except only for zilmar, who do you think cares about compiling the installer?

I guess I could have a git project just for the installer, it would mean it would have binaries for all the different releases.

**Comment by cxd4** [comment]
Could look at it that way.
Advantage to having its own repo:  more space to having binary/rel. history stored in Git away from src.

The installer is something that you need for distributing Project64 to your users more easily--even without the adware money debate it's still something you use to help people install it.  Nobody compiling Project64 needs it--probably also nobody trying to send it to a friend would choose the installer over making a zip of all the other files they compiled either.  Therefore the installer executable doesn't really benefit anyone other than yourself and a few users who would not interact with GitHub.

**Comment by project64** [comment]
if it did have it's own repository, would we still have default plugins in the source directory I imagine you would have to copy them, also I am guessing languages would live in the installer directory as well.

What about the the RDB .. the main file would be in source or the installer repository.

**Comment by LegendOfDragoon** [comment]
>Happens with LLE (not HLE), FAT on or off doesn't affect it. Always random delay between sound fx and video, which pause/unpause changes. All Azimer plugins do it. Jabo's plugins are all consistent, but have a slight delay that is not very noticeable.

I mostly use LLE. I don't have this random delay on my end. Dunno why HLE would make a difference and not FAT being enabled/disabled.

**Comment by cxd4** [comment]
Well correct me if my memory is foggy but I thought I recalled you having an interest in replacing all closed-source plugins with open-source plugins.  In which case I'm not sure why open-source plugins in compiled form would be sitting in the source directory.  Sure people might be forced to either update the custom plugin folder or copy the plugins over manually to the Plugin subfolder of the EXE...I don't see why you couldn't have just organized the Git repo for Project64 to prevent people having to do this (compiling the EXE to /bin, compiling the plugins separately to /Plugin) but I think when you weigh this problem against people feeling forced to run the installer and/or read whatever, I think they have no comparison to complain about copying plugins of their choice.

The RDB and language files are text files...they're "source code" in the sense that they indirectly program the behavior of Project64 but it's questionable whether they can go in the installer Git or the Project64 source git.

**Comment by cxd4** [comment]
I'm sure that if the installer were moved to its own repo.

There would be little reason why you couldn't have VS compile Project64.exe to /bin/Release/Project64.exe and the plugins to /bin/Release/Plugin/*.dll.

**Comment by MofoMan2000** [comment]
Honestly it seems sloppy to have the source for the installer included in the repo. This repo is for Project64 and its source code, not its installer as well (and whatever mess with binaries it brings with it). Anyone handling the code from the repo will be able to compile it and use the build of the emulator without using an installer.

**Comment by cxd4** [comment]
Not just that but I was thinking this could allow for the easier possibility of having non-Project64 components to their own repository so that people aren't forced to compile every dll and exe when they're just trying to update a certain component after cloning, but I guess that may be too much to ask if it means giving up the control over that behavior for whatever reasons that forcing the dependencies is preferred.

**Comment by vgturtle127** [comment]
@project64 Actually, the language files should probably stay since they are technically text files, and so people don't have to clone the installer repo to get to the language files for the main application.

Anything the emulator requires to run I would keep in the repo. Like the RDB, documentation, etc.

I am all for getting rid of dependencies, especially zlib/miniunzip since we already use 7-Zip.

But anyway, I am just trying to clean things up if we can. :smile:

**Comment by cxd4** [comment]
Neither the RDB, documentation nor language files are required by the emulator to run, nor are they definitively a part of Project64 as an emulator.  They're just INI files unrelated to the emulator, and the RDB is for per-game optimizing the performance of the recompiler core.

**Comment by LegendOfDragoon** [comment]
>They're just INI files unrelated to the emulator, and the RDB is for per-game optimizing the performance of the recompiler core.

32-bit engine helps the interpreter too :smile: .

**Comment by death-droid** [comment]
"we already use 7-Zip."
No we don't. We use LZMA SDK

**Comment by cxd4** [comment]
> 32-bit engine helps the interpreter too :smile: .

No it doesn't.  Use TLB helps the interpreter in terms only of speed if you can assume games never use it, but 32-engine is just another performance tweak for recompilers and other limited builds of Project64, e.g. 32-bit Windows.

**Comment by vgturtle127** [comment]
@cxd4 Well, but the RDB is required for games to load, isn't it? Anyway, languages and documentation might not be necessary for running the emulator, but I think we can all agree having them is certainly nice. :smile:

I'm sure most typical users will want the documentation, as well as language files for all our non-English speaking users.

I suppose you could create a separate repo for the application, the RDB and related stuff, the documentation, the installer, and the language files. I personally don't mind no matter what @project64 and you guys decide, I just like working on this project. :smile: 

@death-droid Oh...Yeah. I mean they are practically the same thing. Anyway, you know what I mean. :smile:

**Comment by cxd4** [comment]
>@cxd4 Well, but the RDB is required for games to load, isn't it?

Why do you think this?

You know that the RDB file is settings.
You know that the RDB file is whether to interpret or recompile, per-game hacks etc.
So why would you think it's required for games to load?  I have loaded plenty of entries from the browser with no RDB entry.

Isn't the most logical conclusion that an emulator should have compatibility defaults, like defaulting to the interpreter for unknown cases?  The only reason Project64 currently doesn't is just as a means of filling in the RDB file faster with contributions, but that can change in the distant future.

>Anyway, languages and documentation might not be necessary for running the emulator, but I think we can all agree having them is certainly nice.

Project64's language is English, so says the C code by itself.  Personally I never needed language files for that; I'd be surprised if anyone who's chatted over the Internet did either.

>I'm sure most typical users will want the documentation,

I suppose that could explain the amount of duplicate threads on the forums.

I'm not even sure if any documentation exists for Project64 apart from the website HTML, maybe some TXT files about plugin credits and authors in the repo etc.?  Not sure really, if there is documentation in this repo then I am unaware of it.

>as well as language files for all our non-English speaking users.

ascii or gtfo

>I suppose you could create a separate repo for the application, the RDB and related stuff, the documentation, the installer, and the language files.

I don't mind keeping it in the current repo as-is like you suggest.  I don't see the language etc. files as so entirely separate that they don't deserve to share the same repo space as the actual source to the emulator or whatever; I just don't think it's that important either way.  They could also be under the installer repo and it would be about the same, with the minor inconvenience of people having to run the installer to make sure they have the config instead of it coming with the pj64 source repo after building.

**Comment by death-droid** [comment]
@vgturtle127 there actually very different. LZMA only support the LZMA compression algorithm. 7zip is an implementation of several different libraries.

**Comment by vgturtle127** [comment]
@cxd4 Well, when I said needed to run, I meant at a decent enough capacity to play. Without the RDB, I assumed most games would crash, have bugs, fail to boot, etc. I guess I just never tried it without because I assumed it would kill compatibility. :confused: 

Yeah, I would rather the installer source was separate, but everything else should be fine. To me, at least. :smile: 

@death-droid I thought the LZMA SDK included .xz and .tar/.gz support. I could be wrong. Regardless, I would like to move to one single library instead of multiple. I would think having zlib, miniunzip, and the LZMA SDK all part of it would be a haunting task to keep updated. I would think. But you know, up to you guys. If it were up to me, I suppose 7z.dll would handle archives and zlib and miniunzip would be removed.

**Comment by cxd4** [comment]
>Without the RDB, I assumed most games would crash, have bugs, fail to boot, etc. I guess I just never tried it without because I assumed it would kill compatibility.

The RDB file exists because of speed hacks, not really compatibility.

Without the possibility of a RDB file or any sort of per-game hacks, Project64 probably would be using either the interpreter or a very cautiously designed compiler.  If you don't know what any of that means.  It means in a nutshell the RDB file has nothing to do with the compatibility of games, only their speed tweaks.

**Comment by AmbientMalice** [comment]
The rom browser is useless without the RDB. Plus the RDB is used for selecting save types and such.

Let's just say you'll have a miserable experience without it.

**Comment by MofoMan2000** [comment]
The RDB is necessary for a good gaming experience. The language files may be necessary for people who don't speak English. The installer does virtually nothing to improve the experience, and does the opposite with the bloat that comes with it.

**Comment by cxd4** [comment]
>The rom browser is useless without the RDB.

No because the good names in the RDB look ugly to me, so to fix that you select the ROM browser to show file name, not "Good Name".  Extension not included, at least as recognizable.

>Plus the RDB is used for selecting save types and such.

Well no, the RDB allows you to force a save type, but I haven't seen any save types get forced because Project64 detects it automatically without issues.

**Comment by vgturtle127** [comment]
@cxd4 Alright, good to know.

@MofoMan2000 Yeah, that is kind of what I was getting at. The ROM browser is kind of silly without the RDB. It is mostly empty. I am going to try using Project64 without it for a few games and see what happens. :confused:

**Comment by cxd4** [comment]
>>The RDB is necessary for a good gaming experience.

>@MofoMan2000 Yeah, that is kind of what I was getting at.

He's not telling you that the ROM browser is more or less meaningful without the RDB file.

He's saying that the RDB is necessary for speed optimizations and hacks.

> I am going to try using Project64 without it for a few games and see what happens. :confused:

If you were listening to what was said earlier then you know that Project64 no longer allows a default configuration for what the RDB does not specify--in other words if you want to use the interpreter core by default for unidentifiable/custom ROMs, you'll have to use something like 1.6 version of pj to set that.

Otherwise your experiment to run Project64 without the RDB file will end in failure because there will be ROMs that require a more stable recompiler without the hacks that the RDB file sets for you.

I'll keep saying it over if I have to.  The only reason Project64 has built-in default settings for speed/hacks instead of compatibility, accuracy and stability is to encourage contributions to the RDB file.  You assume falsely that this means the RDB file has to do with accuracy--in fact quite the opposite.

**Comment by MofoMan2000** [comment]
My point is the rdb and language files are components actually used by the emulator, which is a good reason to keep them in the repo. The installer is used once and then probably deleted, and is not necessary to use the emulator at all.

**Comment by vgturtle127** [comment]
@cxd4 Oh, yeah I got all that. :smile: 

@MofoMan2000 Yeah, totally agree with that. :smiley: 

@project64 Also, if we keep the installer in a separate repo you can make changes to the installer without people complaining about the ads and stuff. :package:

**Comment by cxd4** [comment]
As for the empty ROM browser, that's just because the ROM browser is configured by default to ask the RDB file what the politically correct name for each commercial game should be.  That can easily be modified to show the file name (without the file extension) instead of the "good name".  Otherwise it will just spam the browser with complaints as though all of your ROMs are bad dumps.

That being said, I don't have a personal preference to use Project64 without the RDB file myself, because all the pretty multi-coloring of games with different compatibility comments don't really give me a seizure, so I think they're not harmful. :P Still, while I like to keep the latest RDB file installed, most of what I have the ROM browser set to display, does not reference it--it references the ROM image itself for the information.  (Things like "Good Name" are all matter-of-perspective.)

**Comment by vgturtle127** [comment]
Is everybody OK with the changes in the original post?

Basically it removes some documentation and replaces it with a license.md and readme.md to give proper credit to the libraries we use (and to clearly state the license we use).

Other than that I was planning on having a basic readme for the repo.

I can do all that stuff, and we can still discuss the other stuff and I can just do a pull request for the cosmetic stuff now.

I can also try to add some stuff to the current docs we have in the repo too.

I am working on some of the other files locally and I don't want any to clash when I do the pull request. :smile:

**Comment by JunielKatarn** [comment]
> I like that I can clone a repository and then you can just build and the solution will compile and be able to run

@project64 
Maybe you could use a dependency management mechanism like NuGet.
When you build, it would download any required binary artifacts and store them in a local cache, so they can be fetched each episode time without download (unless you delete them).The build scripts can be configured so these DLLs are properly placed when compiling.

**Comment by cxd4** [comment]
I would seriously be able to contribute much more easily to the non-PJ64 components if they were allocated outside the core PJ64 repository.  (I think especially, PJGlide64, as that wad of C++ seems to be what's causing my RAM overflow crash leaks in VS2013.)

And as for the changes you queried about vgturtle:
>* Add a .gitattributes file to tell GitHub what files are what

I'm familiar with using .gitignore's but not this.  Maybe it would be easier to approve the idea if the changes were in pull-request form, but in the worst case scenario as long as it's just a single Git file I don't imagine zilmar having a problem merging that.
>* Remove Glide64 Help directory
>* Remove GlideHQ readme

Personally I didn't even notice these exist?  (Do they?)  But if they do I don't care.  I presume probably project64 does care since the docs are part of the fork's "integrity" or whatever, but at least having Glide64 to its own repo would be no less clean than just deleting help files.

>* Add a license.md and readme.md in the main directory

The license is a new issue that was just pointed out here:  https://github.com/project64/project64/issues/584

That would probably be the easiest way to solve the mixed, jumbled existence and non-existence of license header comments at the start of only some of the source files.  So yeah your idea would be the best way.

**Comment by vgturtle127** [comment]
Alright, I will make a pull request with some of my smaller changes.

I have learned a few things about Git and GitHub since this issue was originally opened, and I think I can greatly enhance the PJ64 repo with some small changes.

**Comment by oddMLan** [comment]
I think most if not all of the things mentioned here are already done, except by the last two points?
Well now we do have a Licence.md file but we don't have a Readme.md file yet. That should be easy.
I suggest opening separate tickets for the remaining points that need adressing, if there are any besides the creation of a Readme.md.

**Comment by vgturtle127** [comment]
@oddMLan Yeah, but I doubt some of my changes will be merged.
