### ISSUE TITLE
Plugins for 2.2

### ISSUE THREAD

**Issue by project64** [project64/project64#50]
there is a pull request (https://github.com/project64/project64/pull/27) that has updates to jabo's1.6 plugins. 

I am wondering if we even should have the 1.6 plugins, the 1.6.1 plugins are mostly a refactored 1.7 plugins that are there.

What plugins do you think pj64 2.2 should install with ?

**Comment by death-droid** [comment]
Hmmm to be honest, I dont think the 1.6 plugins should be included at all.

We should really refine the plugin list down to a few rather than a plethora of them that can confuse new users. So its best to find which plugin provides the best hastle free support. 
I would personally suggest Nrage as becoming the official controller plugin as it is more feature complete than the alternatives. Though it could do with a good bit of refactoring and cleaning.

Video wise im unsure with, GLiden64 would be nice to bundle with it when that is released, but that is a more modern plugin that may not offer support for older system due to the version of OpenGL its working.

I'm unsure about audio plugins as most seem to run games without many or any hitches.

**Comment by Rukario** [comment]
I agree with death-droid. I also think we should integrate N-Rage plugin into PJ64 AKA plugin-less. We can always salvage some features from other plugins into there.

**Comment by Predator82Germany** [comment]
AQZ Netplay (may get the source from author or work together on a specific one for 2.2), both from gonetz, N-Rage & Jabo´s newest from 1.6/1.7 should be in
I´d like to see more LLE but they seems so incomplete & not very user friendly
Or we take it in the installer & let the user choose which one he wants (needed ones grey out)

**Comment by cxd4** [comment]
This is the kind of confusion that binary files on GitHub can cause.  Git just isn't made to track binaries...and how do you know exactly what the binary file is when somebody sends you a pull request changing them?  Sure they may link to official download for it and say it's legit N-Rage 1.83, but for all we know they could have inconspicuously hacked a porn image into it and you could never know about it.  GitHub should be for tracking code.  The plugins/binaries can just go to the release archives that get posted to the main site / in the installer.  Still plenty of people who are stubborn beyond all repair and would rather get the ads or even donate than build from source, never mind EmuCR.

The most that you could do to accept Fanatic-64's pull request is to find some tool to compare the binary exactly to make sure it's 100% correct, but I wouldn't even use Git for binaries.

**Comment by cxd4** [comment]
I guess I'm not answering the question tho, even though I don't think it's relevant to pj64 source.

I don't think it's that important to decide, at least right now.
Personally, I would get rid of all Jabo 1.6 plugins and include all Jabo **1.6.1** plugins.  Often times the 1.6.1 plugins are >= what you get from the 1.7 ones, as he didn't purposely backport any regressions from 1.7.

I really like that Jabo D3D8 1.7 is flexible to either LLE or HLE gfx though, in case I have constant issues remembering RSP settings and just don't care which one is set.  (Rumor has it that GLideN64 will also support both HLE and LLE.)  For that reason I would like Jabo D3D8 1.7 to continue to remain the default graphics plugin.

Pretty sure Azimer's XAudio2 plugin should also be included, but I know he's not happy with it yet in its present state, and he has a lot of ideas about how to stream the audio more accurately over most plugins, also wants to modify the audio plugin spec...I would like it if he helped you change Audio #1.2 specs with his improvements before they become too permanently established/official.

Lastly, N-Rage 2.3 is stupid.  It should be 2.1.  squall himself confessed to the Project64 fork of 2.3 being "no longer my problem", so I doubt he has any intention to work on it or help with this repository (if he did then I might change my perspective on his attitude).  He had a disagreement with rabiddeity back when he (rab) was the developer of the overhaul on whether N-Rage DirectInput should become a DirectInput + XInput plugin, mixing 2 APIs together in a single DLL.  rabiddeity never agreed with that and neither could I in his shoes.  Sometime after that, I guess rabid vanished off the interwebz, and now squall mood switches from missing him and wanting him back to bashing him as an inept coder who just screwed things up.  The whole attitude behind squalls' 2.2-2.3 continuation is just ridiculous.  2.1 rc3 already has all the improvements, and I've never had any problems with that.  N-Rage 2.3 has XInput support, higher system requirements, larger code size and dependency hell and that's about it.

**Comment by cxd4** [comment]
Now if the XInput code was written by squall himself then I could understand shying away from moving from N-Rage 2.3 to 2.1 and hurting his feelings or something.  What actually happened was squall credited somebody else he hired to add the XInput code for him, along with most of the changes since 2.1 which generally was him crediting other people for as well.  It's kind of like he's doing his own project64 repository except exclusively to N-Rage.  I also don't like that he kissed up to Shunyuan just because he was a developer just for the simple-minded goal of "N64 progress", an event leading to Shunyuan's violation of many open-source plugins and emulators.  He did this with plenty other developers as well.  anyway delete this post if it's too long, it wont bother me tbh

Either way XInput should belong to 1 DLL and DirectInput should belong to a separate DLL...otherwise why even have a controller plugin spec if all the dependencies collide?

Those are all of my thoughts on what could be done for graphics, audio, and input plugins.

**Comment by oddMLan** [comment]
Yeah, Jabo D3D8 1.6.1 doesn't include the regressions created in the 1.7.x plugins, but it also misses some functionality like LLE GFX emulation, Software rendering, texture dumping/loading, etc.

I'd say it would be better overall to just include the 1.7.x Jabo plugins, and drop the 1.6 ones. Also considering that the config of the 1.7 can be moved to a separte file to make the RDB just core config, but the same can't be done with the 1.6 plugins (according to zilmar).

I would also like to include Azimer's Audio plugin but ATM the plugin is in the process of an overhaul.

**Comment by cxd4** [comment]
dsound 1.61 and dsound 1.7 are similar enough I guess so I wouldn't have much to complain, but having d3d8 1.6.1 is still having the latest plugin, not only just d3d8 1.7, so I would tend to keep both.

Maybe when GLideN64 comes out it would replace d3d8 1.6.1 and the only jabo plugin will be 1.7.

**Comment by Fanatic-64** [comment]
1. The files I uploaded are not malware. Zilmar can download them from the links and compare the SHA-1 (for absolute certainty), or even just download them directly and commit them.

2. As for the Jabo plugins, I see no reason to keep the "older" (1.6.1) Audio and Input ones. The latest video plugin (1.7.0.57.5) has several regressions however. I think most of them are not present in 1.7.0.56, so maybe we should ship those 2 versions instead.
Also, is there any reason to keep the RSP 1.6 plugin?

**Comment by cxd4** [comment]
>The files I uploaded are not malware.

Never said they were.  Just speaking fundamentally:  Git is not a reliable solution for binary files.

> As for the Jabo plugins, I see no reason to keep the "older" (1.6.1) Audio and Input ones.

Tell me one thing that's better about Jabo's DirectSound 1.7 or DirectInput 1.7, over 1.6.1 plugins?  Because the version number is higher, which makes them not "older"?  Actually, I always use Jabo's DirectSound 1.6.1.  I never use the 1.7 plugins anymore except Jabo's Direct3D8 1.7.  The 1.7 plugins are the older ones though, not the 1.6.1 plugins.

**Comment by project64** [comment]
Some plugins do not have source, like jabo's plugins, they are going to be in the repository, so we are always going to have binaries in there. So there is no issue with binaries in the pull request, tho I am more likely to look at adding the binaries my self then rely on a pull request.

the question is more which plugins should be in there, hence the nature of this issue.

**Comment by LegendOfDragoon** [comment]
I think both Jabo D3D8 1.7.0.56 and 1.7.0.57.5 should be included. I actually had a problem with Jabo 1.61 input, so I use 1.7. Sometimes the plugin would become uninitialized or something ;/ .

For audio I don't even know the difference.

There's no real point to keeping RSP 1.6 for PJ64 2.x.

**Comment by cxd4** [comment]
Jabo's plugins could be either open-source or closed-source...I fail to see how that question affects whether it's worth including the binary releases on GitHub, just because the Project64 installer also puts the DLLs on everyone's computer doesn't mean the GitHub repo needs them too.

>There's no real point to keeping RSP 1.6 for PJ64 2.x.

eh I forgot about RSP 1.6...wow I last used that a few years ago I think.  It could be either kept, removed, or replaced; it wouldn't affect me probably wouldn't affect anyone else either since RSP is barely even a changeable plugin type / something users pay attention to.  Maybe 1.6 RSP was kept to test RSP recompiler regressions.

**Comment by oddMLan** [comment]
Maybe I'm reapeating myself here, butI  personally think the best would be dropping Jabo's 1.6.x plugins and just include the 1.7.x versions. That way, Jabo's plugin config can be separated from the RDB.

Or at most _just_ Jabo D3D8 1.6.1 and _that's it_ (as said above, there's barely any difference between 1.6.1 and 1.7.x audio and controller plugins, and there's no need to have the 1.6 RSP).  But I personally would prefer to sacrifice support for it just to have a less cluttered RDB/code that handles backwards compatibility.

**Comment by Fanatic-64** [comment]
>Tell me one thing that's better about Jabo's DirectSound 1.7 or DirectInput 1.7, over 1.6.1 plugins?
Jabo's DirectSound 1.7 supports the speech in TWINE, Jabo's DirectInput 1.7 has a picture of the N64 controller, and that's pretty much it. But there's no reason to include the 1.6(.1) plugins instead.

I created this pull request because Zilmar didn't go update the binaries (& CHT/CHM files) on his own.

**Comment by project64** [comment]
a valid pull request and worth doing, it also helps also generate this conversation

**Comment by cxd4** [comment]
Jabo's DirectSound 1.7 is a LLE audio plugin and has no MusyX emulation.  The "RSP Audio Signal" option starting in Project64 1.7 and the private, closed-off plugin spec for audio that the 1.7 plugin uses is what interacts with that kind of fix, not the DirectSound 1.7 plugin itself.

**Comment by cxd4** [comment]
> it also helps also generate this conversation

I prefer minimizing conversation.  Just because I suck miserably at it doesn't mean I hate organization.

And I don't see how this discussion is organized...it's already very long and so far you, project64, haven't talked about anyone's opinions on what plugins should be included with 2.2.  Does that mean you have already made up your mind whose you agree with?  If so, I don't see why this is an issue and hasn't been closed, if you're already sure of what to do.  If you're not sure then I don't get why just generate conversation casually without talking about what you're unsure.

**Comment by LegendOfDragoon** [comment]
What does "RSP Audio Signal"  do?

**Comment by project64** [comment]
I have an idea what I am thinking, but it is not set in stone .. 

my current thought for 2.2 would be:
Audio\Jabo_Dsound.dll
GFX\Jabo_Direct3D8.dll
GFX\PJ64Glide64.dll
RSP\RSP 1.7.dll

I want to look at the compiled version of nrage and see if I can update that and replace Jabo_DInput.dll

I am not sure when GlideN64 will be released, maybe I look at doing a 2.3 with it.

**Comment by Fanatic-64** [comment]
GlideN64 is scheduled for Spring, so anywhere between March 20 and June 21.

**Comment by Predator82Germany** [comment]
But did the old plugins work if I put them in?

**Comment by cxd4** [comment]
The fewer plugins included, I suppose the better.

Technically I'm not even convinced Project64 should be coming with ANY plugins at all.  I don't believe in this notion that plugins are a part of Project64...they're just separate projects by people who don't work on the Project64 CPU.  So yeah, I don't really mind getting rid of even the jabo 1.6.? plugins, or even all of them.

Only issue with getting rid of all plugins is people who do a first-time-ever installation of Project64 when they're brand new to it will see it comes with no plugins, but generally that problem doesn't apply when people are simply upgrading components / extracting the new EXE release to their current folder.

**Comment by project64** [comment]
> But did the old plugins work if I put them in?

they should but I have not tried them

> Only issue with getting rid of all plugins is people who do a first-time-ever installation of Project64 when they're brand new to it will see it comes with no plugins

Not really an issue as most people do not even go looking to change plugins unless something does not work correctly.

If the default plugins work well then it is all good.

**Comment by cxd4** [comment]
What I was just saying is, if it comes with no plugins, they see it comes with no plugins.

That means there are no default plugins, and emulation cannot start.  That was the issue I was referring to.

oddMLan, sorry I'm trying to figure out multiple pull requests / branches still, doesn't seem to be going well

**Comment by MatthewHunter1983** [comment]
wait I am confused as to why there are no longer plugins? sorry for the newb question but how do I get the emulator to run then? I tried putting jabo plugins in the new 'plugins64' folder but they don't work :\ I actually prefer the jabo plugins because directx is the only way I can run project64 in stereoscopic 3d. please do not remove them...

**Comment by LegendOfDragoon** [comment]
Jabo's plugins are 32bit only. 64bit doesn't quite work yet anyway.

**Comment by cxd4** [comment]
Yes it does.

**Comment by cxd4** [comment]
As for default plugin choices (if any at all should exist pre-included), they should be the ones least likely to fail to initialize:  a No Sound plugin, a dummy or keyboard-only plugin, and some shitty GDI plugin for basic VI emulation.  In case all the other more advanced plugins fail to initialize those are the only ones that need to come pre-included with the emulator package.
