### ISSUE TITLE
Replacing Jabo Direct Input with N-rage

### ISSUE THREAD

**Issue by project64** [project64/project64#56]
I have n-rage 2.3 compiling in the current source branch. I would like to look at replacing jabo's input plugin with the n-rage one.

Is there any changes that are needed? What Changes would be good to have in it?

In jabo's one I do like the picture of the controller and the setup button that goes through all the buttons in a row.
There is also a closer linking of the two so it goes through the pj64 settings config similar to what I did for glide so all user settings are in the cfg file.

is there anything else that should/would be good to be done with it?

**Comment by project64** [comment]
It does store its settings in an .ini file which is good, I do not nessarly have to get it to go though the project64 settings system, but it should at least store then in the config folder. Same with the log in to the log folder

I make the logs and conf folder writer to by a non admin that way the files are not subject to redirection by the OS on vista+, where the root directory does not have this so the files will be stored in a redirected folder under the user account.

**Comment by cxd4** [comment]
> It does store its settings in an .ini file which is good, I do not nessarly have to get it to go though the project64 settings system,

Oh my, yes that is a relief.  And here I thought you were decisive on project64-izing N-Rage plugin, in the way that Glide64 was project64-ized (e.g. Glide64.ini becomes an RDB file).  Different folder to move it under /Config ... eh...that's reasonable.  It hardly breaks backward-compatibility with the original N-Rage plugin as long as the INI file isn't even changed at all.

**Comment by cxd4** [comment]
All I ever do is game on my keyboard.  I would not be any more comfortable with any other device.

So I'm not too qualified to opine on this topic.  I know at least a couple people who prefer Jabo's DirectInput over N-Rage DirectInput, for some reason.

Ignoring some more...fundamental issues, what I don't like about N-Rage 2.3 as a DLL in itself is that it is twice the code to maintain as the original N-Rage plugin before squall was left alone to work on it.  N-Rage 2.1 = all of N-Rage and rabiddeity overhaul DirectInput code.  N-Rage 2.3 can double the amount of code we'd have to maintain, because it merges in XInput dependency within a single plugin.  However, it could be reasoned that most people today, who have DirectX installed to support DirectInput8, probably could get N-Rage 2.3 (with its XInput dependencies) to initialize as well.  Bear in mind though that this isn't necessarily true for everyone, and if the assumption breaks, there will be no valid controller plugins installed to Project64 which are usable...meaning no usable input plugins and no way to start emulation without making people figure out plugins and how to change them.

So I like to minimize dependencies not maximize them.  Plugins are already dependencies in order to get Project64 to initialize, and there can be infinitely many plugins, so better to have 1 DirectInput, 1 XInput plugin, than to have 1 merged DLL which requires both to be installed.

**Comment by oddMLan** [comment]
>In jabo's one I do like the picture of the controller and the setup button that goes through all the buttons in a row.

The GUI layout is basically the only thing I like more about Jabo's Input plugin over N-Rage.
Do you plan to make N-Rage's GUI more like Jabo's?

**Comment by LegendOfDragoon** [comment]
I personally prefer using Jabo's input, but it's not a big deal if it's not included. One thing about the newer NRage plugins is that with keyboard, the input for analog controls is different. Instead of instantly doing full range in a particular direction, it starts low and gradually goes higher in range (so it takes a few frames). I can understand why it's implemented, but it's not always good to be that way, imo anyway.

**Comment by cxd4** [comment]
@LegendOfDragoon is that not something controllable with the "Real N64 Range" checkbox option?

Figured I'd ask...guess I never noticed that myself.  I'm usually too tolerant to "feel" those issues.

**Comment by project64** [comment]
> The GUI layout is basically the only thing I like more about Jabo's Input plugin over N-Rage.
Do you plan to make N-Rage's GUI more like Jabo's?

yes that is one of the things I am considering

**Comment by LegendOfDragoon** [comment]
I tried a few options and none of them changed it ;/ . I tested 1.80a and 2.3b. 1.80a took 3 extra frames, 2.3b took 2 extra. It's understandable to implement that sort of functionality, but I generally prefer instant full range for keyboard input, rather than gradually.

**Comment by death-droid** [comment]
"that it is twice the code to maintain as the original N-Rage plugin"
Well thats false, the difference in code size between rabids last source release and the latest available is minimal.
Including the ability to use XInput controllers in NRage is a minimal code increase and is extremely easy to maintain.

I personally think the want to increase the amount of DLL's we use is just bizarre.

**Comment by cxd4** [comment]
> Including the ability to use XInput controllers in NRage is a minimal code increase

Including XInput to go with a pre-existing API solution is never a "minimal code increase".  It's redundant, really.

**Comment by cxd4** [comment]
Unfortunately the issue seems to go further back than alpha 45 of 1.7.0.50.
https://github.com/project64/project64/tree/dae4e73c89ab594783309d58db553d978e1aa186

Anything beyond that, I have to install MSVC 6.0 to compile it...I have not had VC6 on my computer for years now though might be able to try finding it again.

Until then all I can say is that Rat Attack broke SH TLB somewhere after 1.7.0.50 ver 23, and somewhere before 1.7.0.50 ver 45.

**Comment by marhry** [comment]
Something I did not see before and which would be a good thing for the official input plugin:

*Optional* key bindings for system commands.

Let me clarify: Many people use an Xbox360 or similar gamepad, which has more buttons than the N64 original. It is *very* convenient to put "Save state", "Load state" and others (e.g. "Fast forward") on these unused buttons.
So my suggestion is: Add maybe two or three boxes where you can just enter a key and which have a dropdown box that triggers one of the system commands. Or even simpler, just emulates a keypress.

**Comment by project64** [comment]
> It is very convenient to put "Save state", "Load state" and others (e.g. "Fast forward") on these unused buttons.

Yes I would like to do that, at the moment it is not possible since I do not have the source of jabo's plugin, which is the point of looking at replacing it. It will not be in the first version, but probably in the version after that.

**Comment by marhry** [comment]
Sounds promising. The intermediate solution for me is to use something like XPadder to just fire the keyboard key that has been set in PJ64 on controller button presses. Might also be a starting point for the feature implementation, i.e. just let the input plugin fire VK_... codes on button presses.

**Comment by death-droid** [comment]
The UI translation system Nrage is using could do with a good replacement

**Comment by project64** [comment]
>The UI translation system Nrage is using could do with a good replacement

What I did with the settings, it might be worth doing the same thing for language and do al the language strings though the main files, so that way you only have one location your editing. It does produce a higher coupling with the emulator but at this stage I think it is fine
