### ISSUE TITLE
"Predictable Randomness"

### ISSUE THREAD

**Issue by Ownasaurus** [project64/project64#572]
Project64 isn't considered TAS-safe... is it?  Or deterministic I guess?

I'm asking because now that I have kaillera support working in my fork, I am noticing something interesting that has been present since the core 1.4 version: some "random" effects stay synced over netplay, while some do not.

For example, in Super Smash Bros., item "random" spawning (location and item type) is 100% synced over netplay.  However, selecting a "random" stage or a "random CPU" is not synced.  Keeping in mind that kaillera is keeping the inputs synced, I have concluded that Project64's emulation is non-deterministic. (Please correct me if I am wrong.)

What could cause this?  Is this something that can be addressed? Mupen64++ (circa 2005) can handle these random features just fine, so I'm certain P64 can do the same!

I'm not super knowledgeable about the N64 hardware, but I know there is a random register.  Is that truly "random" or should it be consistent (pseudo-random)? 

Thanks,
Owna

**Comment by AmbientMalice** [comment]
Have you tried running with Fixed Audio Timing and AI count per byte = 0?

**Comment by Ownasaurus** [comment]
It seems to work great with Fixed Audio Timing!  Even if AI count per byte is at its default (400). Would you mind giving a quick explanation of why Fixed Audio Timing fixed that problem (was one running slightly faster than the other?)  and what are the AIs?  audio interrupts?

Very grateful,
Owna

**Comment by cxd4** [comment]
It somehow regulates the interval between which _N_ sound data is buffered to the audio interface for an interrupt is fired.  It's at least important because I remember learning that the audio thread has a higher priority in the RCP than the video thread.

It's one of the reasons that NetPlay implementation being done officially was a matter of guided steps to making it a reliable thing first, so options like this were implemented for accuracy on that level.

**Comment by Ownasaurus** [comment]
This is excellent. My only other question is - why isn't this on by default?  Does it have any untoward side-effects?

**Comment by cxd4** [comment]
It historically hasn't been on by default because regulating fixed intervals of audio between interrupts meant that the core CPU timing would be noticeably poorer (like when timing 10 seconds in your head in the Postman's challenge in Zelda Majora's Mask).  So it makes the audio timing up there to about perfect, but essentially forcing the audio timing to be perfect does not guarantee that the CPU timing works in exactly the same intervals.

Sometime back however @Azimer contributed some big improvements, so it is beginning to get more popular to start enabling _Fixed Audio Timing_ by default for several games.  IIRC there are still some games it has issues with, maybe even a regression or two afterwards.

**Comment by Ownasaurus** [comment]
OK, thanks for the info. I will force it for the netplay fork because the benefits greatly outweigh the potential timing discrepancy.
