### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by Buddybenj** [project64/project64#584]
I can't find a license on this software. There are many problems with not having a license: most importantly, it is automatically "All Rights Reserved" with no license, so it is therefore not free and open-source.

http://choosealicense.com/

If you wish to put the software in the public domain, you can use CC0 to do that.

**Comment by JunielKatarn** [comment]
Very good point.
I would suggest @project64 not to choose GPLv3. It is too invasive and ends up being restrictive. It could introduce issues when interacting with non-GPL code.

Any other license mentioned in that link should work perfectly fine.

**Comment by cxd4** [comment]
Alright, first off:
https://github.com/LuigiBlood/64dddump/issues/1
I cite a relatively small history of license trolling.

Second:
https://github.com/project64/project64/blob/master/Source/Project64/N64%20System.h

Most of zilmar's source files/headers to PJ64 have the GPLv2 license in the header.  The immediate exception that I'm seeing is `main.cpp` which ironically has no license in the header.

The other exception could be the RSP sources, but those aren't really "Project64" anyway.

**Comment by Buddybenj** [comment]
@cxd4 There's no need to be rude. I was trying to help since most people don't understand that no license is equivalent to "All Right Reserved". I had a small misunderstanding with LuigiBlood's project, however that doesn't mean I'm trolling. Also, certain files may be free under the GPL, but that doesn't mean the project as a whole is under the GPL. To put the whole project under the GPL, he would need to put a LICENSE file with the GPL in the root directory of the project.

Setting the code free may bring more developers to the project and increase the user base.

**Comment by cxd4** [comment]
Technically it's not really _"All Rights Reserved"_ as partly explained by the link you gave:
```
Even in the absence of a license file, you may grant some rights in cases where you publish your source code to a site that requires accepting terms of service. For example, if you publish your source code in a public repository on GitHub, you have accepted the Terms of Service which do allow other GitHub users some rights. Specifically, you allow others to view and fork your repository.
```
Um I was not intent on being rude when I said that, sorry.

>Also, certain files may be free under the GPL, but that doesn't mean the project as a whole is under the GPL. To put the whole project under the GPL, he would need to put a LICENSE file with the GPL in the root directory of the project.

Well then what should be done about the inconsistent license pastes throughout the source files themselves?  Would it be acceptable to take your advice about covering every file by putting a LICENSE file in the root of the repo but also remove the inconsistent licence bits from the internal files themselves?

**Comment by Watilin** [comment]
Won't there be a sort of conflict between a root LICENCE file and the included 3rd party directory?

**Comment by cxd4** [comment]
Um...I think so.

Most of those are just including includes that don't ship natively with Visual Studio installations to make building Project64 "easier", I guess, but I forgot some of that stuff is licensed 7-zip code etc.

It isn't foolish at all to include a root LICENSE file that reflects the licensing of Project64 and try to please more people, but I guess in this case it has its problems.  And we will need solutions from the creator of this issue if we're not to be left to the conclusion that this "issue" is naive preambling.

My preferred solution:  Get rid of all the 3rd Party stuff because it's irrelevant to Project64, but I know zilmar and friends would never think so.  Fundamentally though, it's simplest this way.

**Comment by Watilin** [comment]
I agree this is simplier, and apparently Zilmar wants things to be like this in order to work out of the box.
Maybe we can put something informal in the LICENCE.md saying that the whole project is under GPL *except* the 3rd party dir, and complement this by adding a licence header in each file belonging to the project, as GPL folks advise to do.

**Comment by Buddybenj** [comment]
You don't need to add an informal statement for that. The license will only apply to the work you have created, not external dependencies. Lots of projects have external applications in their repository. For example, look at [Dolphin's repository](https://github.com/dolphin-emu/dolphin), which is has the GPL in the root of their repository. They have a folder called Externals with 3rd party applications, but that's fine.

AFAIK, the only requirement is that the licenses of the external programs must be GPL compatible (most free licenses are).

**Comment by cxd4** [comment]
Sounds cool.  I am not an expert with root licensing of multiple things so I would be just as happy if someone else took care of that.  (I could PR to add a LICENSE file myself but would rather not risk zilmar merging it and my contributions statistics multiplying for a single repository all because I committed a colossal text file.)

**Comment by Buddybenj** [comment]
Any update on this? This would be such a simple change that would make such a big difference.

**Comment by project64** [comment]
basically everything should GPL2. I would like to clean up the headers to make sure everything reflects that .. the 3rd party are either GPL or mit

feel free to make a pull request to how you think the repository should be set up for showing the license more clearly

**Comment by Buddybenj** [comment]
OK, thanks. I can't make a pull request right now because my computer is broken but when I get it fixed I will make one.

**Comment by oddMLan** [comment]
We have a Licence.md file now.
Please close.

**Comment by LegendOfDragoon** [comment]
Yes, I think this can be closed :smile: .
