### ISSUE TITLE
(x64) Games try to use more than 8mb of memory

### ISSUE THREAD

**Issue by tony971** [project64/project64#638]
Affects the following games:
- Army Men - Sarge's Heroes
- Dazaemon 3D
- F-ZERO X
- Glover 2 (Beta)
- Hybrid Heaven
- Mario no Photopi
- NBA Live 2000
- Roadsters Trophy
- South Park
- Supercross 2000
- Vigilante 8
- War Gods
- Xena Warrior Princess - Talisman of Fate

**Comment by tony971** [comment]
Also affects Dazaemon 3D

**Comment by cxd4** [comment]
I had tested _Army Men:  Sarge's Heroes_ a while back.

The problem is that setting this game to use 16 MB or more of DRAM (even so high as 512 MB of RAM) will leak Project64 into either an infinite loop, TLB status crashes, address error exceptions or other problems, depending on how much RAM you ask for exactly in the CFG file.

I'm thinking it might be because the game only checks a small switch between 4 or 8 MB RDRAM.  If you set it to something higher than 8 it will just have logic like if (size == 8 MB) limit = 0x7FFFFF; else limit = LIMIT_4MB_DRAM;.  At the same time, some leak in the game code is accessing beyond 8 MB of DRAM (either because of Project64 bug or just because the game is badly designed).

Or maybe the RSP plugin and RDP plugin are not both in complete agreement on what the memory limit is.  This is why the plugin specs should have passed MAX_DRAM_ADDR to the plugins, not just a pointer to DRAM.

Otherwise the long and short of it is to check the addressing range in the R4300 ops, or to simply fall back on MemoryFilter working in 64-bit Windows builds of Project64.  Though I think the latter is easier.

**Comment by theboy181** [comment]
Have you tired setting higher memory settings for these games in the per game CFG file?

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
