### ISSUE TITLE
(x64) WWF No Mercy error

### ISSUE THREAD

**Issue by tony971** [project64/project64#644]
```
Writing 3C00000 to flash ram command register
```

**Comment by LegendOfDragoon** [comment]
does this happen in 32bit?

**Comment by tony971** [comment]
Nope. Checked the same plugins and everything.

**Comment by LegendOfDragoon** [comment]
Ok. How do I reproduce this issue?

**Comment by tony971** [comment]
Just try to boot the ROM with @cxd4 's RSP. Using the default RSP will give you the breakpoint saying there isn't enough memory and then an unknown memory action. Changing the memory to 8mb doesn't help this issue.

**Comment by cxd4** [comment]
Finally got a chance to test this one.

@tony971 this is not a x64 error.
It happens on 32-bit Project64 too.  You don't have the error with 32-bit PJ because you have a full `WWF No Mercy.fla` in your SRAM save folder already.  Try copying it to your 64-bit pj save folder.

Also forcing the save type in the RDB settings to SRAM instead of Flash RAM works around it.

**Comment by LegendOfDragoon** [comment]
I guess this issue can be closed?

**Comment by AmbientMalice** [comment]
WWF No Mercy is notorious for its save data erasal problems. http://micro-64.com/features/wwfnomercy.shtml

**Comment by loganmc10** [comment]
FWIW, mupen64plus does this as well

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
