### ISSUE TITLE
(x64) No HLE Video for you!

### ISSUE THREAD

**Issue by tony971** [project64/project64#646]
@death-droid updated Rice Video for x64 so now we have a real HLE plugin to test with.

Testing with release versions of the default RSP or HatCat's gives a break point at Memory Virtual Mem.cpp 2375 and a CN64System::RunRSP Unknown memory action. (While booting any ROM)

Testing with a debug version with the default RSP gives a break point at Memory Virtual Mem.cpp 2361 and an exception caught at N64 Class.cpp 391.

**Comment by LegendOfDragoon** [comment]
I remember when I tested r52's fork of rice video, abs crap worked. I'm pretty sure the problem is the plugin itself. I can debug it later tonight if I'm not busy.

**Comment by cxd4** [comment]
Yeah it would be more appropriate to file this issue under the RiceVideo repository.

**Comment by death-droid** [comment]
Yeah agreed with the guys before, the problem is the plugin itself.
While the code replacements get the plugin to build, there is an awful lot of warnings that look like they need to be dealt with before the plugin would actually be runnable. You have to consider the plugin was never developed with 64bit in mind.
