### ISSUE TITLE
question about building from new `Project64.sln`

### ISSUE THREAD

**Issue by cxd4** [project64/project64#649]
So now I noticed we have an agnostic `Project64.sln` which will be forwards-compatible from VC2010+.

I just try to build with VS2013 and do not have 2015 installed, so I get this error:
```
error MSB8020:
The build tools for v140_xp (Platform Toolset = 'v140_xp') cannot be found. To
build using the v140_xp build tools, please install v140_xp build tools.
Alternatively, you may upgrade to the current Visual Studio tools by selecting the
Project menu or right-click the solution, and then selecting "Upgrade Solution...".
```
When I open the Project menu in 2013 Community it says nothing about "Upgrade Solution...".
When I right-click the solution in the explorer, it still says nothing about "Upgrade Solution...".

So how can I globally set the platform toolset to v120_xp or whatever without manually going through each of the projects inside the solution and setting it every time?

halp4nubplz

**Comment by JunielKatarn** [comment]
That was my bad in terms of documentation.
There has alwas been a "default platform" set. I just put the setting in a single place (instead of each VCXPROJ file).
I chose vc14 because it's the latest stable version, and it can also be obtained for "free" (Community version).

If you don't want to edit the file, the method I use is command line. Something like:
```
msbuild.exe Project64.sln /p:PlatformToolset=v120_xp
```
Sadly, I don't know of a way to do that mixed with Shift+Ctrl+B from within the IDE.

That said, maybe, just maybe, removing the platformtoolset altogether will force Visual Studio to use whichever version of the toolset it "belongs" to.
I'll play with this later today.

**Comment by cxd4** [comment]
Hm.  Yeah I'm mostly alright with editing the file directly (one-time-only thing anyway from the looks of it); I just presumed there would most likely be a GUI way to set it with Visual Studio IDE's GUI that I was missing.

As long as I don't have to re-clone the whole repository from scratch every so often it's not a big deal, though it looks like the linker gives me warnings about toolset version conflicts after finished the exe.  Guess I leave the issue open for you to check.
