### ISSUE TITLE
CBFD crashes in Recompiler 

### ISSUE THREAD

**Issue by project64** [project64/project64#7]
Steps to reproduce:
1. Start the game, get to the Barn Boys chapter; select the Mad Pitchfork one.
2. Get to the cutscene after Frank the pitchfork says is going to "kick your ass".

http://forum.pj64-emu.com/showthread.php?t=3595

**Comment by oddMLan** [comment]
Clearer instructions for those who haven't played the game:

To reproduce the crash, first, start the game, press Ctrl-C, enable the "unlock all chapters" cheat, and once you're inside the tabern, select Chapters > Barn boys > Mad pitchfork. Then talk to the pitchfork; a cutscene will play. After he says he's going to "kick your ass", the error will show up.

If you disable register caching in the recompiler options the crash does not happen. But is a ton slower.

**Comment by oddMLan** [comment]
Retroben @ the PJ64 forums said:

"Just remembered the fix for Conker's "Mad Pitchfork" error,use "Physical Lookup Table" in the game's recompiler settings.
Oh,and make sure Cache,P1 DMA,and Start Changed are checked in the Self Mod Methods list."

So maybe it's a simpler fix than I thought. Can't test right now tho cuz I'm not in my computer. Will confirm later if this fixes the error.

**Comment by project64** [comment]
ok  it should now be fixed in the latest comit

https://github.com/project64/project64/commit/53b86e559c2c69661d6c10b060e561fa0295d4cb

**Comment by oddMLan** [comment]
I can confirm that the bug is indeed fixed. I think the issue can be closed now.

**Comment by project64** [comment]
ok open a new bug with those details.
