### ISSUE TITLE
Regression in Last Legion

### ISSUE THREAD

**Issue by LegendOfDragoon** [project64/project64#70]
When CF is set to 3, I get a black screen after booting the game. It doesn't matter what GFX & RSP plugin I use. For some odd reason, the issue appeared somewhere between http://www.emucr.com/2015/01/project...-20150124.html and http://www.emucr.com/2015/01/project...-20150125.html

It seems to be some undefined behavior, since it works fine on theboy181's computer.

**Comment by cxd4** [comment]
It works fine on my computer as well.  We're still troubleshooting this on IRC channel on Freenode.

**Comment by cxd4** [comment]
>It seems to be some undefined behavior,

There is no such concept when 2 people using the same build system, same operating system etc. are using the same emulator and code.  "Undefined behavior" doesn't make an EXE behave differently on different systems; it makes code **build** differently for different targets and different operating systems.

Rather, the issue is because you've deviated too much off the official RDB; you just need to back up your deviated `Config/Project64.rdb` and replace it with the official one you can find in this Git repository.

**Comment by project64** [comment]
when I edit the rdb, I edit the rdb setting file, go to the settings inside project64, reset the page settings and make sure the settings match what I expect it to be.

**Comment by LegendOfDragoon** [comment]
Sorry, I just keep getting conflicting results for multiple issues ;/ .
>There is no such concept when 2 people using the same build system, same operating system etc. are using the same emulator and code.

I've seen some strange things about Project64, that may happen on 1 computer and not another. One good example of UB, is whether or not the CN64 Error message will even show or not.

Now for this particular problem, I am unsure what's going on, so I will use the official rdb and clear cfg settings. I will also download and compile different builds to track down what caused the change on my end. I just remembered...

From now on, I'll be more thorough and not speak too soon.

**Comment by LegendOfDragoon** [comment]
theboy181 pointed out that the VI refresh rate made the difference. So raising the VI refresh rate allows me to boot the game with CF = 3. I will close this issue for now.
