### ISSUE TITLE
Bug in GFX plugin spec. implementation

### ISSUE THREAD

**Issue by Fanatic-64** [project64/project64#72]
Re-reading Gonetz's GLideN64 blog I noticed this bit:

> Technically, emulation of CPU rendering is easy. Image to display is stored in RDRAM, its address is known. The image is just loaded as texture to video card and rendered as full screen rectangle. The problem is the same as with CPU based fb effects: graphics plugin does not know that CPU started rendering by itself, emulator does not notify the plugin about it. **To be honest, plugin's specification has the function for such notification, but it almost never works.** Thus, plugin can’t rely on emulator’s help.

It would be nice if the function to notify the graphics plugin that the CPU has begun writing to the color framebuffer was fixed. It would allow correct emulation of such instances (which currently relies on a hack), and frankly it's a bit embarrassing that Project64 doesn't have a fully correct implementation of Zilmar's specification.

And by the way, would it be hard to document the 1.7+ plugin specs (Audio 1.2, GFX 1.4, Input, 1.2, RSP 1.2)?

EDIT: It appears this is the function in the spec that needs fixing:

> /******************************************************************
>   Function: ShowCFB
>   Purpose:  Useally once Dlists are started being displayed, cfb is
>             ignored. This function tells the dll to start displaying
>             them again.
>   input:    none
>   output:   none
> *******************************************************************/ 
> EXPORT void CALL ShowCFB (void);

**Comment by death-droid** [comment]
What your interested in is the FrameBufferRead, and FrameBufferWrite functions that are defined in the plugin specifications but are currently disabled. Definitely something thats more up Zilmars alley, as to be honest... I have no idea how it works :P

BTW ShowCFB is unrelated to this, and as far as I know, should work as intended.

@project64

**Comment by cxd4** [comment]
They're not really defined in the plugin specs, but in schibo-Rice extension to them.  Many graphics plugins include them anyway, but the spec itself mandates nothing about supporting them.  zilmar would not have known to implement something like this, so it's an unofficial extension.

It's not really a "bug" so much as it is just not knowing enough about hpw graphics work.  The spec was mostly created to just "work", and it does.  The unfortunate thing about it is that other emulators have to follow the same example or introduce unofficial extensions like this.

**Comment by cxd4** [comment]
> It would be nice if the function to notify the graphics plugin that the CPU has begun writing to the color framebuffer was fixed. It would allow correct emulation of such instances (which currently relies on a hack),

works already in angrylion RDP; I think he's just talking about a hardware-accelerated approach

**Comment by death-droid** [comment]
Look up #ifdef CFB_READ in the core Project 64 code :P
Zilmar had planned the same functionality in the GFX Plugin specs, just from the looks of it never got around to finished implementing it or getting it to work. One of them.

But yeah as CXD4 is right, not a bug.. just there's no actual implementation of it in Project64. (Mupen64plus and 1964 both have implementations of CFB read and write)

**Comment by cxd4** [comment]
Seen the macro, but if it's not defined in the specs, I imagine it's simply not a part of the specs.

Maybe zilmar had second thoughts about introducing it in Gfx v1.4, which isn't really official, though I'm not convinced that was his intention for bumping the specs.  But yeah, if we're going to have an issue report for something like this, it's a little too blind to go hunt for something this abstract--a concrete example of where this needs to be implemented could be useful.  GLideN64 is an accelerated plugin so examples with that plugin don't necessarily mean it's required in general.

**Comment by project64** [comment]
it was in mupen/1964 for rices plugin, I looked at it a little but required a decent amount of changes to memory manager to try and get it working and jabo said it was not worth it cause he could detect it other ways that worked out better.

If it actually helps Gliden64 then I am happy to implement it, but was not one of my extensions, so not in the plugin spec.

now also that project64 is completely open source, I am tempted to remove the specs out of the installer.

**Comment by Fanatic-64** [comment]
Jabo's plugin doesn't work properly with CPU rendering to framebuffer. See the Rayman 2 example from Gonetz blog; After the first gameplay demo, Jabo's doesn't switch back to showing CPU-written framebuffer, so the "Press Start" screen isn't shown again.

It would be a good idea to implement it and notify Gonetz about it. It could also be added to the "official" GFX 1.4 spec, per CXD's "suggestion". I get there's an equivalent to the .h files included in the Plugin Specs folder in the source, right?

**Comment by project64** [comment]
it really only matters if it helps Gliden64 because it is the only one that will make use of it.

**Comment by death-droid** [comment]
May be worth sending a message to Gonetz about it then

**Comment by project64** [comment]
from Gonetz:

>Do you have an option to be writing back to the rdram and what is the penalty
Actually yes. There are options to copy depth buffer and frame buffer from video card to RDRAM. I tried to make these operations as fast as possible and I don't see performance penalty on my PC. You may check how fast they work on your system.

Regarding help from emu side: 1964 introduced set of extension functions
EXPORT void CALL FBRead(wxUint32 addr)
EXPORT void CALL FBWList(FrameBufferModifyEntry *plist, wxUint32 size)
EXPORT void CALL FBWrite(wxUint32 addr, wxUint32 size)
EXPORT void CALL FBGetFrameBufferInfo(void *p)
which should help video plugin to get information when the game is going to read/write to frame buffer area and either render FB to screen or copy video card's frame buffer to RDRAM.
I could not get any use from that extension in 1964. Hacktarux also implemented these functions in Mupen64 and it helped to emulate some effects without speed drop. But it did not always work. Hacktarux explained that it is very hard to track frame buffer access because it can be done from many places. Again, we played with these functions when AGP was in use, because read from AGP was slow. Today I enable both depth and color buffer copy without noticeable speed drop.

**Comment by cxd4** [comment]
I guess it sounds useful in the HLE sense of origin because already you may be able to tell when a game actually needs to know, update or reference the frame buffer in RDRAM.  This way even a pixel-accurate plugin could, in theory, not emulate frame buffer storage every single frame, but only decipher a message from the host r4k CPU when this data even matters / when it is going to be used.  But from an LLE sense, it never occurred to me to care about it.

I know that Rice's plugin made it an option...you could set in the INI whether to write back frame buffer every 1 to 8 frames alternating, or when a certain VI register was detected to have a new pointer value, or "With Emulator" using these plugin spec extensions...but they're all ultimately different speed options of HLE'ing the same basic thing.

**Comment by Fanatic-64** [comment]
Those extensions in Mupen64 are what the option "Get Framebuffer Info" in Glide64 uses. For Glide64 For PJ64, we should either implement those extensions in Project64, or remove that option from the plugin.

**Comment by cxd4** [comment]
I don't know any Windows API/template/resource programming so don't know how to remove the option.

not really much of an "issue" at any rate, more of a suggestion

**Comment by death-droid** [comment]
So essentially from what Gonetz said, it wouldn't be worth the time implementing the functions as its unreliable and can be done in a hacky way in the plugin itself? And that theres no real bottleneck anymore since GPU's use PCIE and not the shitty AGP

@project64 Does this issue still need to be opened?

**Comment by cxd4** [comment]
On the contrary, the hacky way isn't to do it within the plugin itself, but to have these functions implemented for hacking around having to constantly emulate frame buffer every frame like real N64 does.

Bug reports should be about code problems with the emulator, not design suggestions or complaints.

And most of the bottleneck would still go to LLE.  glReadPixels'ing the frame buffer over isn't very fast nor GPU-accelerated either, but I imagine it's far from the top of the bottleneck list.  Sounds like what Gonetz is saying confirmed this.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
