### ISSUE TITLE
Broken ROM Names in ROM Browser ?

### ISSUE THREAD

**Issue by MELERIX** [project64/project64#763]
![roms](https://cloud.githubusercontent.com/assets/1040116/11203402/59ed0676-8cd2-11e5-8cf4-d4355e5e44c9.png)

could be caused by this changeset ? https://github.com/project64/project64/commit/5d0c361b39e7a73b4bb21a61a9bd35485aa3274f

**Comment by Frank-74** [comment]
Works ok for me.

Try deleting Project64.cache3, Project64.rdn, Project64.sc3 and Project64.zcache from Config folder and restart, Refresh ROM List

**Comment by MELERIX** [comment]
I just tested right now with clean build and the issue persist, btw my roms are in 7z format.

**Comment by Frank-74** [comment]
I see.  And I think I see why 7z is broke in that commit you link above.

**Comment by cxd4** [comment]
I should think that's not possible.
I would sooner suspect some other aspect of my commit is responsible for it.

Changing
```c
if (ext2 != ".v64" && ext2 != ".z64"
 && ext2 != ".n64" && ext2 != ".rom"
 && ext2 != ".jap" && ext2 != ".pal"
 && ext2 != ".usa" && ext2 != ".eur"
 && ext2 == ".bin")
```
to
```c
if (ext2 == ".bin") {
```
is not a breaking change.  But in case something else I changed may have affected .7z files in the ROM browser I will check it out.

**Comment by cxd4** [comment]
I've found the commit which caused this issue.

It was not my commit; it's some other commit made 11 days ago.
https://github.com/project64/project64/commit/6a2e88a25cce1c7aedef22882eca9895ebf24fd8

Unfortunately the relevant file changed to have caused this issue, `Rom Browser Class.cpp`, has too many changes for GitHub web interface to show me what changed.  Will have to use the local Git terminal and `git checkout` to see what got changed to break it.

**Comment by cxd4** [comment]
Found the exact change that broke it.

When replacing one of the AsciiToHex() functions with std::strtoul(), there was a failure in accounting for standard library (defined behavior compliance) differences, versus the custom rules the custom function `AsciiToHex` was using.

The standard library function raised an internal `ERANGE` error and returns ULONG_MAX (which is 0xFFFFFFFF on 32-bit Windows, 0xFFFFFFFFFFFFFFFF on 64-bit Linux, ...) while zilmar's AsciiToHex function just did wraparound from unsigned overflow and ignored subsequent characters.

**Comment by vgturtle127** [comment]
So the issue is fixed, right? We can close this?

**Comment by Frank-74** [comment]
@vgturtle127 
No, because the PR that fixes it hasn't been merged yet.  https://github.com/project64/project64/pull/765

**Comment by cxd4** [comment]
I can bet the reason why project64 hasn't merged it yet is because it's almost impossible for zilmar to validate the "legitimacy" of my change.

It basically replicates the old AsciiToHex function behavior by uploading 9-byte null-terminated strings instead of one giant string, but at a price:  It temporarily terminates and un-terminates the sub-strings and assumes that the total overall string is a multiple of 8 digits wide.

There is nothing further I can do about that.  The C++ string algorithm used to generate that huge zip hash is a giant, colossal pre-buffer and I cannot read it.  It would have been way more conservative to just send the RomData hex parses on the intervals of queuing up the string in the first place, but instead it looks like zilmar will have to totally redo the buffer-everything-into-one approach at his C++ strings or, alternatively, risk merging my pull request.  (I say "risk" in the sense that I myself cannot guarantee that my change reflects a correct understanding of all scenarios.)

**Comment by cxd4** [comment]
Okay.  Looks like it's been merged (for better or worse, but I hope for better).

My only fear is that I calculate it may buffer overrun if the ZIP hash string breaks the 32-bit divisibility pattern--in which case I will have to see about complicating my fix further by calling strlen().

@MELERIX if you do a new build from current master, is your issue gone?

**Comment by MELERIX** [comment]
yes, fixed in: https://github.com/project64/project64/commit/8139985ba25c365d12c7bae93a8627986ea2ff98 and now is ok...

![pj64ok](https://cloud.githubusercontent.com/assets/1040116/11316599/52bbd00e-8fec-11e5-8732-569fe6559ff5.png)

thank you ;)
