### ISSUE TITLE
Add save types (EEPROM 4/16 kilobit, FlashRAM, SRAM, controller save) to ROM browser

### ISSUE THREAD

**Issue by vgturtle127** [project64/project64#839]
I'm not sure if this would be hard to implement, but save types would be nice to have in the ROM browser as well. :+1: 

Not much else to say, I am trying to write a list similar to Elitendo's list, except adding NTSC-J and PAL games, and possibly being more accurate as to what games support what kind of saving. So, hopefully, we can use that as a starting point.

**Comment by cxd4** [comment]
I think that's a personal preferential feature request, but not an issue.

Project64 is already complicated enough for even having a ROM browser or any GUI at all, when it really just has to focus on being a clean emulator.  It displays a ton of information already...like number of players, developer, publisher, most ROM header info, and now save types EEPROM/SRAM/etc. as you suggest?  Why not add movie ratings?  List of gfx microcodes used?  Number of ABI microcode command functions used for HLE?  Why only save types?

Those sorts of things suit document projects but I think not emulator projects, which should be capable of auto-detecting which save types to use during emulation instead of HLE'ing them in some INI file.

**Comment by vgturtle127** [comment]
@cxd4 Well, to be honest I don't much care about developer/publisher, players, etc. I agree with your statement on it being a bit of a messy GUI.

However, I usually only display what I want, which is usually name, country, CIC chip, and status (only to check RDB stuff right now). So adding save types seemed like a good idea for me since it would just be another option people could just as easily turn off, and I could turn it on since I am doing some work on Project64's save detection. It doesn't handle FlashRAM that well, I have found. :confounded: 

Anyway, there isn't really anywhere else we can do feature requests, but if there is an official channel besides here, I will post there, as long as it it will actually be seen. :smile:
