### ISSUE TITLE
PJ64 Setup Build will not load

### ISSUE THREAD

**Issue by theboy181** [project64/project64#84]
I compiled the latest Setup build last night and when I tried to open PJ64 the GUI wouldn't load. I moved the older PJ64.exe to the folder and ran it. after that the new build loaded fine.

I think there must be a regression in the new PJ64.exe and it inst crating some config files correctly.

**Comment by cxd4** [comment]
I've never used the installer before up until now but can confirm that this is an issue for people who do.

I tried running `$project64/Bin/Release/Setup Project64 2.1.exe` to install Project64 2.1 to the default location it offers, `C:\Program Files (x86)\Project64 2.1\`, which is not an issue.

But when I install it to a clean, new directory (in my case, `C:\Program Files (x86)\Projectsdfdfgsfdgh`), it asks me what language to select, I choose English, and the main GUI is inaccessible.  The Project64 window never shows up on my desktop, and forcing it to from within Process Hacker seems to also not be able to.

**Comment by cxd4** [comment]
Then again, it looks like if you press Alt+Space (keyboard shortcut I knew of that does the same thing as right-clicking the title bar of a window), pick "Move", and use the arrow keys to move the window coordinates, you can eventually get it within the range of your monitor display's coordinates.

So it looks like it's not a matter of the GUI not loading, just loading way the hell off our screens.

That would be caused by both the CFG file remembering our window position and possibly the recent commit zilmar also did to fix this issue:  https://github.com/project64/project64/issues/68

**Comment by oddMLan** [comment]
I can confirm the recent commit fixes bug #68, but as you I had to move the window because it loaded offscreen for some reason.

**Comment by cxd4** [comment]
Ah that makes sense.  I never paid attention to the setup thing anyway.  Glad it's simple enough to be unrelated to that.  So really all you have to do is wipe the Config data to reproduce the issue.

**Comment by oddMLan** [comment]
Yes, just need to delete Project64.cfg to reproduce the issue.
