### ISSUE TITLE
"Cannot initialize OLE" settings bug

### ISSUE THREAD

**Issue by vgturtle127** [project64/project64#845]
This happens every single time I try to open settings (which is obviously fairly often).

Tested on latest git of Project64 32-bit and 64-bit.

![screenshot 7](https://cloud.githubusercontent.com/assets/3183676/11968400/8de7475a-a8d1-11e5-9a81-2894340638d6.png)

It opens this dialog box twice, then opens the settings.

This doesn't change even with different plugins (not that it should, really).

Any insight would be great.

**Comment by cxd4** [comment]
It's the plugins you have installed.
Mess around with deleting Glide64 and/or Azimer Audio and you should notice a change.

Now there is an upgrade to Wx that does affect this issue, but the true cause within the plugins vs. why they are colliding when loaded to the core has not been investigated.

**Comment by vgturtle127** [comment]
It must have been Azimer's LLE audio, because it stopped once I removed it from the directory.

Glide64 doesn't cause any problems, though.

Do you know why it does this only for Azimer's LLE audio? Does that plugin have some incompatibilities with the newer plugin spec or wxWidgets?

**Comment by cxd4** [comment]
I said **or**, not "only".  Deleting Glide64 without deleting AziAudio fixes the issue here.

**Comment by vgturtle127** [comment]
Huh, that was the first one I tried since I figured a graphics plugin might have older plugin specs and so therefore might cause more issues.

Oh, well. Thanks for the workaround.

Should I keep this open for further investigation? Is there a way I can help further explore the issue?

**Comment by cxd4** [comment]
I'm fairly sure plugin spec version has nothing to do with it.
Even if it did, all gfx plugins >= 0x0102 spec, audio < 0x0102 so that wouldn't make sense.

I don't think you should close the issue necessarily.  When one of us has the time, we need to debug AziAudio/Glide64 and play with emptying out some spec functions' code to isolate what code specifically is triggering the issue, then PR a fix to AziAudio/Glide/PJ64 for whatever is involved.  You could do that to explore the issue if you wanted.

**Comment by vgturtle127** [comment]
@cxd4 Alright, I will look into it after I finish some pull requests.

**Comment by oddMLan** [comment]
No longer an issue after the removal of wxWidgets 68a8ed03696f3365430d8cca14d5084100165cd0
Please close :)
