### ISSUE TITLE
Vigilante 8 timing issues

### ISSUE THREAD

**Issue by purplemarshmallow** [project64/project64#862]
If you disable the frame limiter this game behaves very weird. It skips frames and sometimes hangs. It works correctly if fixed audio timing is enabled.

So there are 2 solutions to this problem. Enable FAT for Vigilante 8 or make FAT the default setting and merge #535. I recommend enabling FAT by default since it will fix other problems with games that can crash with FAT disabled like Turok Dinosaur Hunter or Pokemon Stadium.

**Comment by LegendOfDragoon** [comment]
Interesting. Also using "No Sound" also works. Personally, I'd rather just enable it for specific games.

Also, who knows what would happen on the real hardware, if it could run > 60 VI/s.

**Comment by purplemarshmallow** [comment]
The problem is that if you disable FAT things work asynchronously. Mario Tennis is a good example. If you disable FAT and the frame limiter the game runs too fast but audio still runs at normal speed and audio sounds normal. But if you enable FAT the voices and sounds will speed up too. You can hear a clear difference. If certain events speed up and others don't this creates problems.

>Personally, I'd rather just enable it for specific games.

A large number of games would benefit from FAT. It seems more stable and accurate. If a game does not work with FAT it should be fixed.

>Also, who knows what would happen on the real hardware, if it could run > 60 VI/s.

Emulating hardware at higher speed should not create any problems. If you speed up everything equally results should always be the same. For example you could implement video dumping and dump a 2 minute video in 1 minute. The video should look exactly like a 2 minute video dumped in realtime there should be no difference.

**Comment by LegendOfDragoon** [comment]
>The problem is that if you disable FAT things work asynchronously. Mario Tennis is a good example. If you disable FAT and the frame limiter the game runs too fast but audio still runs at normal speed and audio sounds normal. But if you enable FAT the voices and sounds will speed up too. You can hear a clear difference. If certain events speed up and others don't this creates problems.

If I remember correctly, last time i checked, the results weren't consistent in DK64 even with FAT enabled. But it is true that FAT is more consistent.

>A large number of games would benefit from FAT. It seems more stable and accurate. If a game does not work with FAT it should be fixed.

A lot of games benefit with FAT disabled as well. It's not easy to improve FAT. There's a reason different emulators with fixed audio timing do well in different games. Also I think the priority for audio settings should be for when the game is running at normal speed as intended.

>Emulating hardware at higher speed should not create any problems. If you speed up everything equally results should always be the same. For example you could implement video dumping and dump a 2 minute video in 1 minute. The video should look exactly like a 2 minute video dumped in realtime there should be no difference.

This is not necessarily the case. If you speed up everything, it does change the results. There's a reason counter factor 2 works differently than counter factor 1.

Anyway, I looked into the problem you reported. It appears that this game was apparently coded to do that, when (AI_STATUS_REG & AI_STATUS_FIFO_FULL) != 0 for a significant amount of time. If that is not true, then the emulator core itself is bugged. So this might actually happen on console, if it's not the emulator being buggy. Because based on what's documented, I imagine the status register would be full more often if the N64 ran at a higher speed.

**Comment by purplemarshmallow** [comment]
I disagree here. A good emulator keeps things synchronised and consistent. MAME can record videos. It does not matter how fast (or slow) it runs videos are always realtime. With a good emulator it does not matter how fast you emulate a system. But if you have bugs and inaccuracies like async audio it does matter. If FAT does not work good in a game then it's a bug and it should be fixed.

But it's not easy to emulate things accurately without emulating everything like cen64 I agree here. Research is needed but still it should be the goal. I think in it's current state FAT is already superior and should be the default setting.

dolphin got rid of async audio and now it can record videos in realtime. You can read about it here:
https://de.dolphin-emu.org/blog/2014/11/12/the-rise-of-hle-audio/
http://blog.delroth.net/2013/07/why-dolphin-is-getting-rid-of-asynchronous-audio-processing/

>Also I think the priority for audio settings should be for when the game is running at normal speed as intended.

If someone decides to turn off the frame limiter to skip a cutscene and the emulator crashes can you justify that?

**Comment by LegendOfDragoon** [comment]
So you would rather have increased crackling or latency, just to keep it more synchronized when not running at 60 VI/s?

I'm more concerned about the audio timing when running at proper 60 VI/s. In this scenario, non-FAT is good for most games.

I'm pretty confident that this issue would happen on N64 if it ran > 60 VI/s.

>If someone decides to turn off the frame limiter to skip a cutscene and the emulator crashes can you justify that?

Yes, especially since there's a possibility that this would happen on the real hardware too, if it ran > 60 VI/s. I'd rather implement an option to temporarily force FAT when frame limiter is off, than to set FAT on by default. Too many times I ask myself "why am I hearing crackling?". Then I go and see that I left FAT on..

**Comment by AmbientMalice** [comment]
Different people seem to have different experiences here. On my PC, most games crackle without FAT using Jabo's plugin. FAT fixes most of them, or at least heavily reduces the crackling. Others have an opposite experience.

**Comment by purplemarshmallow** [comment]
I get less crackling with FAT enabled. Never noticed a game where FAT causes crackling.

>I'm pretty confident that this issue would happen on N64 if it ran > 60 VI/s.

You can't run hardware at a higher speed only emulators can do that. In a synchronised emulator it does not affect accuracy. You can run a cycle accurate emulator at 500% and still get the same results.

If you have proper syncronisation time is relative. You can run PJ64 in a virtual machine and speed up the VM. PJ64 will give the same results.

**Comment by LegendOfDragoon** [comment]
>Different people seem to have different experiences here. On my PC, most games crackle without FAT using Jabo's plugin. FAT fixes most of them, or at least heavily reduces the crackling. Others have an opposite experience.

Admittedly, I do not use Jabo's audio plugin much anymore. That may be why I have a different opinion about FAT. I already see Azimer's as more suitable for non-FAT. Not sure about with FAT on.

>You can't run hardware at a higher speed only emulators can do that. In a synchronised emulator it does not affect accuracy. You can run a cycle accurate emulator at 500% and still get the same results.

What I'm saying is that what you're asking for, may be a hack / "enhancement" request, rather than a genuine bug fix. So I wouldn't necessarily call this more accurate, if it's uncertain that this is how the hardware would work. That being said, I think my suggestion is good enough because at normal speed, non-FAT is good for most games.

A serious problem with FAT is pausing.

**Comment by purplemarshmallow** [comment]
It's not uncertain how real hardware would work. On real hardware things happen synchronized so PJ64 must also work synchronized. The ability to speed up is just a side effect. Look at the intro in Clay Fighter - Sculptor's Cut. It's completely out of sync with FAT disabled. It's an accuracy improvement.

**Comment by AmbientMalice** [comment]
Back in the day, I used to crash Vigilante 8 by using the infinite ammo cheat and firing a shitload of rockets. The game would get slower and then finally shit itself. So I wouldn't be surprised if Vigilante 8 isn't particularly well coded.

**Comment by LegendOfDragoon** [comment]
I guess the biggest issue I was having with Fixed audio timing could be plugin related. It's still not perfect like some folks claim, but I guess it's decent enough for your average end user. I'll still stick with non-FAT for most games.

I looked into Turok and it is triggered by the same thing. The status register being full for too long. Although V8 is way more unstable in that regard. It would be nice to know exactly when the status register = full and how soon it becomes not full. Until then, it's all guess work as to what's the most accurate way to emulate it.

Now that FAT is on by default, I guess this issue can be closed?

**Comment by AmbientMalice** [comment]
@LegendOfDragoon On the topic of FAT, I've been thinking that there should be an easy-to-change global variable stored in Project64.cfg so that we can easily disable FAT globally when needed.

**Comment by LegendOfDragoon** [comment]
@AmbientMalice I agree. It would be more convenient that way.
