### ISSUE TITLE
x64 PJ64 RSP won't works

### ISSUE THREAD

**Issue by Lithium64** [project64/project64#868]
What is the current status of both? glide64, nrage and pj64 rsp are working on x64 build?

**Comment by JunielKatarn** [comment]
All three work and can be built from source.
You can find x64 builds here (using no audio plugin, though): http://hyvart.com/download/project64/ci/

**Comment by JunielKatarn** [comment]
Linux port will take longer. Work in progress, as far as I know.

**Comment by Lithium64** [comment]
@JunielKatarn Thanks, aparently x64 rsp doesn't work

**Comment by JunielKatarn** [comment]
> aparently x64 rsp doesn't work

How so? I tried the x64 builds I mentioned, played some games and everything seemed fine.
Do I have to "activate" RSP somehow? Is the RSP build still 32 bits, even in the x64 binaries?

**Comment by Lithium64** [comment]
@JunielKatarn this errors happens and with @cxd4 x64 rsp plugin it works fine.
![pj6401](https://cloud.githubusercontent.com/assets/10705488/12216397/7c050b1c-b6be-11e5-8fe7-89ec2bf9421e.png)
![pj6402](https://cloud.githubusercontent.com/assets/10705488/12216398/7c0a1c24-b6be-11e5-95f1-05254afefded.png)

**Comment by JunielKatarn** [comment]
@Lithium64 You are right.
I had only tested the x64 builds using the Lem's Crap ROM Test.
Trying to load an actual game ROM fails.

@cxd4 Do you know what needs to be done in order to "fix" the RSP in x64?

**Comment by cxd4** [comment]
It could also be that there is a different plugin spec used for pj64 RSP vs. my RSP.

To really know I would have to have working Internet drivers on my Windows machine, which mysteriously seemed to stop being the case.  So either someone would have to pick through the commits to clue me in on the regression or I would have to resume porting the RSP to Linux so that I can compile it at all.

**Comment by LegendOfDragoon** [comment]
I got SM64 to boot in x64. My guess is that you have RSP recompiler enabled instead of interpreter.

**Comment by cxd4** [comment]
@Lithium64 Is Debugger --> RSP --> core set to Recompiler (default) or Interpreter?

I assumed you knew it was interpreter-only but as AIO pointed out it's possible you didn't.  See that it works with the interpreter core and the issue may be closed or edited to care about architecture-specific dynarecs.

**Comment by project64** [comment]
maybe Recompiler should not be default on x64 builds

**Comment by cxd4** [comment]
Can't really say.

it was easy foir me to decide the R4300 core to default to interpreter on x64 since the RDB forces the recompiler setting for a bunch of games, and trying to use the interpreter all the time became tedious.

With RSP it's not so difficult, other than having the Debugger menu enabled.  In principle I would say interpreter should almost always be the default, but with RSP the interpreter is neither clean nor optimized, so maybe keeping it default to non-working x64 RSP recompiler can nag some guy to contribute a x64 port.

**Comment by vgturtle127** [comment]
@cxd4 Who is AIO?

When I was doing some of my initial testing with the sync cores option, I noticed many games don't even boot or only get very early into the main menu. This would make me think there are issues with both the interpreter and the recompiler, so I'm not sure we can make an educated decision until we have more information. The RDB already forces the recompiler for some stuff, so I'm guessing in combination with the fact that the recompiler is the default has probably lead to most of the testing being done in the recompiler. SO, maybe the interpreter has more bugs/regressions now?

Anyway, that's unrelated.

In regards to the RSP, I pretty much always use the default RSP plugin and @cxd4 's RSP plugin because they are really the only ones worth using (at least, in my testing).

I nearly never run into issues with @cxd4 's RSP, but if I use the x64 build and the default RSP plugin, then I do tend to run into problems with memory errors or emulation problems.

I will add some more testing to my TODO list...

**Comment by cxd4** [comment]
His old GitHub account.
After forum announcements of PJ64 moving to GitHub, he created "LegendOfDragoon".

**Comment by vgturtle127** [comment]
@cxd4 Oh, OK. I was confused. :laughing:

**Comment by Lithium64** [comment]
@LegendOfDragoon I tested on interpreter mode and it works
