### ISSUE TITLE
Could we add a "disable mem pak" hack specifically for Chameleon Twist?

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#884]
It's kinda ugly how the emulator currently requests people disable the memory pack, which they really shouldn't be tampering with, and which should be handled by the emulator itself.

**Comment by cxd4** [comment]
Does the game work on a real N64 if you have mempak plugged in?

If not, I don't really see an issue, just a feature request.

**Comment by AmbientMalice** [comment]
>Does the game work on a real N64 if you have mempak plugged in?

I'm not actually sure. As far as I know, it complains if you have a mempak inserted in a real N64. Possibly the game wasn't designed for one, and only expected rumble paks to be inserted.

**Comment by vgturtle127** [comment]
@AmbientMalice This is one reason why I want to get a real N64.

So the game requests you don't have a memory pak in the N64 controller while playing the game? As in, the game requests you at no point in the game have a memory pak inserted in the controller? This must be the only game that does that, because I always have a mempak in my controller...

**Comment by project64** [comment]
sounds like a good idea, feel free to make a pull request if you like and I can look at it. I am busy at the moment so I will not be able to implement it any time soon unfortunately

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
