### ISSUE TITLE
Is the 32 bit engine worth it?

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#896]
32 bit mode creates a minefield where a lot of games crash for no apparent reason and it has to be disabled on a per-game basis, which I've been doing. So I'm wondering whether the mode is actually worth its salt. Looking at Mario 64, it seems to make a difference of about 1% in R4300i load, jumping from around 4.5% to 5.5%. I'm not saying it should be ripped out, and I don't _mind_ testing hundreds of games looking for crashes, but it seems like so much stability risk for so little benefit. Maybe I'm missing something? If the benefits are so small, why not make 64bit mode the default?

**Comment by project64** [comment]
if you want to measure the speed difference, then turn off the fps limiter and record the speed in 64bit vs 32bit.  Then use these two values to determine the speed increase.

**Comment by AmbientMalice** [comment]
Well, I just tested, and Mario 64 seems to be 360fps 64bit and 375fps 32bit. So 4%

**Comment by vgturtle127** [comment]
@AmbientMalice @project64 What exactly is the 32-bit engine? I have never really taken the time to figure out what the code does. I have tried modifying it for games, but I just don't know what it does. It doesn't seem to help or hinder with anything, I have just noticed small improvements or unnoticeable minute differences.

**Comment by project64** [comment]
basically a lot of games lets say 40%-90% .. most likely about 75% just use the n64 as if it was a 32bit processor and never use the full 64bit processor .. so the 32bit engine just use the system as if it was just a 32bit processor.  I do have code in the 64bit to try and detect when the code/register is 32bit .. I probably could do more work there. 

At the time it was it was not hard to implement and I wanted to pj64 to be the fastest emu avaliable

**Comment by LegendOfDragoon** [comment]
I think a good idea would be to make it easier for users to detect it, so that they can put the right setting for each game. I basically usually just debug a game when I see issues, but most people probably do not do that. Perhaps some option that can be added when enable debugger is on, to display a message saying that 64-bit is used.

**Comment by project64** [comment]
well 64bit is always used from an asm point of view so there is no way to know from an Assembly point of view if it should be 32bit or 64bit. Things like thread swap uses LD/SD to store the registers and just using a 64bit function does not mean the majority of the game is still 32bit and will work in 32bit mode. So no way to automatically detect it. 

It is a performance hack like fast SP .. one of the first things to to turn off when something is not working correct. The question really is how many more games actually have a problem with it that have not been already identified.

**Comment by LegendOfDragoon** [comment]
I figured that games that use instructions like DADDU should probably disable 32bit. I guess that's not always the case? I know it's just an assumption, but seems to be true from the limited amount of testing I've done. Can't say I've done extensive testing though. But I do see your point now.

**Comment by vgturtle127** [comment]
@project64 OK, I thought it may have been something like that since most developers ended up not even really using the 64-bit part of the CPU that much (due to increased speed when only using the 32-bit "stuff").

On a somewhat modern system, theoretically you would get a negligible performance improvement though, right? And would there be any reason that this would work better on a 64-bit system? It doesn't seem to be that way in my testing. With some games, anyway. Could be any number of things that are changing in the 64-bit build, though.

**Comment by project64** [comment]
as project64 and recompiler is still 32bit there is some benefit still. If I had the recompiler as pure 64bit then there would probably be no benefit.

**Comment by vgturtle127** [comment]
@project64 OK. Just curious, as always. :smile:

**Comment by LegendOfDragoon** [comment]
Interestingly, I was trying to test the cpu recompiler to see if not using pointers for floating point broke Turok 2. Seems good so far, but I'll need to do more testing.

I found out that Turok 2 has a breakpoint error while playing the intro, if I disable 32-bit. The breakpoint happens at https://github.com/project64/project64/blob/master/Source/Project64-core/N64System/Interpreter/InterpreterOps.cpp#L1129 

Now that I looked at source, it appears that @project64 did not put the message in the 32 bit version.

**Comment by AmbientMalice** [comment]
>I found out that Turok 2 has a breakpoint error while playing the intro

Turok 2 is kind weird because its sound doesn't work without a certain CF setting or FAT enabled. Maybe that's the cause.

**Comment by LegendOfDragoon** [comment]
I use FAT when testing / debugging. To clarify, this breakpoint happens in the intro after starting a new file. Cpu recompiler doesn't have the breakpoint displayed either. Only the interpreter does. I only encountered it because I was testing synchronize cores.

I tried both CF 1 and CF 2.

**Comment by oddMLan** [comment]
Yes. It is worth it.
I think on our currently powerful PCs the difference is not very noticeable, but on lower-end Android devices (which is the current goal to port Project64 over) I think it will definitely yield a bigger speedup.

But I agree auto-detection instead of a Per-RDB setting would be _ideal_. Maybe the issue should be renamed to reflect that accordingly.

**Comment by fallaha56** [comment]
all this just sounds like another good reason to go 64bit and ditch 32bit...sorry but JM2C

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
