### ISSUE TITLE
Glide64's broken mipmapping

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#905]
Currently Glide64 has a rather serious problem with its mipmapped texture handling. For example, in Conker, Perfect Dark, and Turok: Dinosaur Hunter, you have to choose between incorrect tiling (mipmapping enabled) or what appears to be the game rendering the second level mipmap instead of the highest resolution one (mipmapping enabled.)

Glide64 w/no mipmapping:
![glide64_turok_dinosaur_hunte_01](https://cloud.githubusercontent.com/assets/10704701/12409863/0e8a2244-beba-11e5-8f70-2fbd8836c86d.png)

Glide64 w/mipmapping:
![glide64_turok_dinosaur_hunte_03](https://cloud.githubusercontent.com/assets/10704701/12409867/20cacb02-beba-11e5-8613-345d93cf37b4.png)

GlideN64:
![gliden64_turok_dinosaur_hunte_000](https://cloud.githubusercontent.com/assets/10704701/12409882/6d786d9c-beba-11e5-8e14-3953bceab90a.jpg)

GLideN64 used to suffer from a variation of this problem before it was fixed. So I'm wondering whether anything can be done to correct Glide64's textures. It's not a HUGE problem, but it does mean we have to choose between two evils. Maybe @gonetz or @purplemarshmallow could shed some light on the subject?

**Comment by gonetz** [comment]
The problem described in my blog, the solution is in GLideN64 sources. Mip-mapping requires per-pixel LOD calculation, thus shaders are necessary. You may improve per-polygon LOD calculation used by Glide64: calculate not only LOD fraction but also right mip-map level. It still will work incorrect, but may look better. However, you also need to implement mip-mapped textures load.

**Comment by AmbientMalice** [comment]
@gonetz is it possible to fix the wrong texture being loaded when mipmaps are disabled in Glide64?

**Comment by gonetz** [comment]
You may try to always use only one the most detailed tile, without blend. It will be the first tile if detailed texture is off or the second one otherwise.

**Comment by fallaha56** [comment]
sorry but this is a great example why it's silly developing two very similar plugins...'sighs'

**Comment by AmbientMalice** [comment]
@fallaha56 GLideN64 and Glide64 aren't all that similar.

**Comment by cxd4** [comment]
Hell, not even the authors are all that similar, considering the foundation of GlideN64 is Orkin's.

Only thing that's really similar is the name of the plugin.

**Comment by fallaha56** [comment]
@AmbientMalice @cxd4 er no respectfully (but utterly) disagree

i'm well aware of the both plugins' origins

i'm also well aware that @gonetz was the last major author of Glide64 before he bravely went off and started trying to build a plugin on modern principles -how many hardware OpenGL HLE/LLE plugins does one emu need?!?

sorry but i think some folk are so devoted/involved here they can't see the forest for the trees

**Comment by LegendOfDragoon** [comment]
>@AmbientMalice @cxd4 er no respectfully (but utterly) disagree

Have you actually inspected the source code of both plugins? Where are you getting your information from?

>how many hardware OpenGL HLE/LLE plugins does one emu need?!?

Obviously more than one, in order for everyone to be satisfied.

**Comment by fallaha56** [comment]
@LegendOfDragoon you've just proved my point for me

you know more about coding that i ever will but the last thing i need to do is inspect the code. why?

a man @gonetz who devoted years of his life to Glide64 ditched it because in his expert opinion it could never become good enough

and 17(!) years after the release of UltraHLE, N64 emulation is sadly still fragmented and incomplete

working in hospital, i get the concept of blood, sweat and tears. i also know when to let go. Glide64 is an argument for legalised euthanasia

**Comment by LegendOfDragoon** [comment]
>@LegendOfDragoon you've just proved my point for me

Proved what point? I'm not devoted to Glide64 or GLideN64.

> the last thing i need to do is inspect the code. why?

Since you made a questionable claim, I am asking for evidence to prove it. I can tell just by running the 2 plugins that they aren't very similar.

>and 17(!) years after the release of UltraHLE, N64 emulation is sadly still fragmented and incomplete

Emulation will never be complete. Being fragmented doesn't prevent people from enjoying emulation. It just takes a bit more work to get what you want, no bigey :smile: .

**Comment by cxd4** [comment]
Didn't understand a damn word he said.

As far as I can tell he didn't even try to refute what we said about Glide64 and GLideN64 not at all being similar; he just rambled about Gonetz this and forest for the trees that just to cling onto his view by not citing the lack of evidence.

**Comment by gonetz** [comment]
@fallaha56 good trolling, man

**Comment by fallaha56** [comment]
@gonetz 
i'm just sad to a project in this state; it was exciting to see GLideN64 come along because it was clearly a step in the right direction

@LegendOfDragoon 
101: 2 plugins that both are hardware, OpenGL (unless anyone's using their Voodoo2) and HLE/LLE with the same author = identical enough that you should only have one

and er @cxd4 
i've given you plenty evidence, you choose to not "understand a damn word" because you don't like being criticised for being in favour of a protectionist, old-school 'it's mine' approach

**Comment by AmbientMalice** [comment]
@fallaha56 The general plan is to replace Glide64 with GLideN64 as soon as possible. The secondary concern is to make sure Glide64 works as well as it can until it gets replaced.

**Comment by LegendOfDragoon** [comment]
>2 plugins that both are hardware, OpenGL (unless anyone's using their Voodoo2) and HLE/LLE with the same author = identical enough that you should only have one

If they are so similar and should only be one, then can you explain to me why only one of them is usable for me? Besides, that's still not enough evidence. Having the same author doesn't necessarily make it very similar.

**Comment by cxd4** [comment]
>Besides, that's still not enough evidence.

Besides, that's still not **even** evidence, is more like it.

Because that's wrong.  Glide64 isn't OpenGL.  Doesn't take a programmer to see that.  Any end user who has to install this little thing called `glide3x.dll` (sorry if I got the exact name wrong, it's been a while) knows that the plugin really is not at all in OpenGL; that's just what the wrapper is using to emulate the plugin's real design.

Meanwhile he's just going to keep pretending he has evidence in the form of presenting further ad-hominem attacks as a substitute for using stubbornness to hide his insecurity, so it doesn't matter.

**Comment by fallaha56** [comment]
@AmbientMalice 
sounds good, i still feel that time is long past tho, time for some brave forward-looking decisions IMHO 
@LegendOfDragoon 
if you (still) don't have OpenGL3+ hardware then it really is time to upgrade my friend! if i recall rightly, i remember this being your situation and offering to help you do this
@cxd4 
'sigh' **GL**ide was [based on](https://en.wikipedia.org/wiki/Glide_API) Open**GL**, anyway i haven't used my Voodoo2 in 15+ years, still using yours? no, but why let facts get in the way of your ego ;)

**Comment by cxd4** [comment]
It's not based on OpenGL implementations at all.
It's based on Direct3D and OpenGL **specifications**. ;)

Wouldn't really matter even if it really was based on OpenGL software of some kind, because even if it was, why else state that whether you use Voodoo2 in 15+ years has anything to do with 2 plugins being similar to each other if not just for the purpose of letting facts get in the way of your ego? :smile:

**Comment by LegendOfDragoon** [comment]
>Besides, that's still not even evidence, is more like it.

Good point, actually :smile: .

>if you (still) don't have OpenGL3+ hardware then it really is time to upgrade my friend!

It doesn't make sense to me, to advocate that there should only be one plugin (despite the fact that this plugin does not work on older hardware). Why shouldn't there be a graphics plugin for older hardware?

>if i recall rightly, i remember this being your situation and offering to help you do this

There's no convenient way to use a new card on a laptop. I don't think using an external enclosure is feasible for me. The idea of me spending 1k just for N64 emulation is silly to me, when I can just write my own code to get the job done on my current hardware for most of the games I'm interested in playing. Besides, if I had a new computer, I probably would have moved onto something else anyway lol.

**Comment by cxd4** [comment]
I can understand the flack that some people give that plugins shouldn't exist, or that emulators should be plugin-free.  In fact I support the concept of at least one project demonstrating this philosophy (more so for communistic emulation scenes, like GameCube where there's little to no competition).  But then, we have some of those same people saying that plugins cause "plugin wars", competition, arrogant "whose plugin is better than whose" hypes.

And yet, at the same time, they accelerate this by proposing that only 1 single plugin exist.  Um, lol.  As if that doesn't create the "plugin wars" situation at all in the first place.  Deciding on only 1 single plugin is even more controversial than just getting rid of plugins totally, and is the same thing as taking sides in plugin wars and other little imaginary drama hypes these people are hallucinating.

Hell, when I was criticizing Shunyuan for disrespecting the author's GPL wishes, MarathonMan just kept citing that as some example of plugin war arrogance, and only months later took the same end of the mob that I did.

**Comment by fallaha56** [comment]
@LegendOfDragoon 
i jst base my opinions on plugins on those of an expert who said it was time to move on for the sake of making a definitive solution -and watching Dolphin succeed by doing the same

@cxd4 
putting words in my mouth now, 'implementations'? -what a cheap-shot

the simple fact is that you have 'not invented here' syndrome, you hate that Dolphin succeeds through collaboration ('communism'?! lol you) and would rather have your 'plugin wars' OpenGL vs OpenGL

going to leave you down there in the trees

**Comment by cxd4** [comment]
looooooooooooool

So actually I had that wrong, you do admit that they're not software implementations yet, somehow, in that case you for all the more reason _still_ can't even try to refute that OpenGL vs. GLIDE is only a subset of the differences between Glide64 and GLideN64.  That and you'd rather change the subject to more ad hominem attacks and artificial descriptions of me that really only describe how you see yourself.

I'd suggest angry old men who work at hospitals to not work themselves inside of one by getting upset over being wrong in an internet argument.  Anyone can agree to disagree over 2 and 2 giving you 5, but when you put words in their mouth and jump to saying that's what's somehow being done to you then you know it's time for a time-out. :smile:

**Comment by fallaha56** [comment]
forest (me): OpenGL vs OpenGL not much point, we can be stronger as a team, let's collaborate

trees (you): implementations blah...specifications blah blah...Shunyuan disrespecting me blah blah blah...ad hominem ad hominem...refute subset...COMPILE YOUR OWN PLUGINS FALLAHA56 WHAT DO YOU MEAN YOU DON'T UNDERSTAND THE INSTRUCTIONS I GAVE YOU MUST BE STOOPID

@cxd4 just admit you didn't like the idea that Shunyuan was moving the scene forward faster than you wanted -my medical advice: take that energy and put it into working with people young man

**Comment by LegendOfDragoon** [comment]
Having only 1 plugin is silly imo. I agree that they would only accelerate plugin wars. Even though I'm a fan of plugins, I also support the concept of having an emulator be plugin-free.

I can understand someone wanting things to be a certain way. What I don't understand is people expecting everyone else to agree with their idea, especially when it's disadvantageous for some.

>i jst base my opinions on plugins on those of an expert who said it was time to move on for the sake of making a definitive solution

That doesn't sound like something an expert would say. Most reasons I've heard for anti-plugins / only-one-plugin are not good arguments. Some significant cons are never even brought up.

>-and watching Dolphin succeed by doing the same

Mindless copying is not how you truly succeed. I'd rather surpass others instead of copying, which is why "NIH" is actually a good thing.

Do you realize that gamecube / wii emulation is more popular, which means more contributors? That alone has a lot more to do with their so-called success, than arbitrary things like abolishing plugins. Different circumstances lead to different results. Simply imitating successful people is not going to automatically make you successful.

>we can be stronger as a team, let's collaborate

Why collaborate if it's not in my best interest? If I'll be happier and more successful just doing my own thing, what is wrong with doing just that?

**Comment by cxd4** [comment]
He wasn't any less interested in plugin-based development than I was, considering he took advantage of the plugin system to steal MAME's and angrylion's code and violate both of their licenses.

But if a super-plugins fan if the mascot for your honest get-rid-of-plugins dream, be my guest.

**Comment by cxd4** [comment]
>>i jst base my opinions on plugins on those of an expert who said it was time to move on for the sake of making a definitive solution

>That doesn't sound like something an expert would say.

@LegendOfDragoon when he said that, I believe he was probably referring to the blog posts about when Dolphin finally quit the plugin model.  I know, I know--apples vs. oranges--but just clarifying.

**Comment by fallaha56** [comment]
@LegendOfDragoon 
i don't want things 'a certain way' -i merely look to who's succeeding and seek to emulate their approach, that isn't 'mindless copying'!

Dolphin has both DX11 and OpenGL and as I'm sure you know, DX12 now too, co-existing and complimenting one another; DX9 is dead and gone tho

it's your prerogative to work on your own of course but it seems some folk here attempt to demonise and attack others, speaking of which:

@cxd4 
Shunyuan wasn't trying to 'steal' anything, he was just over-enthusiastic and stepped a little out of line trying to move things forward and you bullied him

similar to your pseudo-intellectual snobbery when i struggled with compiling and asked for help

**Comment by cxd4** [comment]
>Shunyuan wasn't trying to 'steal' anything,

Well it wasn't by accident, so what does that leave?

**Comment by fallaha56** [comment]
that wasn't my point

unless i missed the bit where he made millions $$$ and ran off to the Bahamas?

@cxd4 i suggest a heart transplant -it might help you understand when someone does something technically wrong but with good intentions?

**Comment by cxd4** [comment]
Well of course not.  It's never anybody's point that they're wrong; it's just that it's a fact anyway.

Unless you can highlight in the dictionary where "money" or "$$$" shows up in the definition of stealing.  Whether it's money, famewhoring, or whatever else sounds noble to you, it's still taking credit for other people's work, which he never disputed.  He quit because he was guilty and he knew it, not because you bullied him and not because you're pretending like I did.

**Comment by LegendOfDragoon** [comment]
>i don't want things 'a certain way' 

If that's true, then you shouldn't try to discourage others from working on different projects and blame N64 emulation's problems on this behavior.

>i merely look to who's succeeding and seek to emulate their approach, that isn't 'mindless copying'!

It is mindless copying because, their situation is not the same and I'm hoping you misunderstood their reasons (for their own sake). Abolishing plugins is not going to fix any of the major problems in N64 emulation.

>@LegendOfDragoon when he said that, I believe he was probably referring to the blog posts about when Dolphin finally quit the plugin model

I see. I really hope their reasoning was better than "plugins are holding us back, time to get rid of them".

>DX9 is dead and gone tho

So now people who want to use D3D9 have to look elsewhere. This is a prime example of why one-size-fits-all, doesn't always work. The fact that ishiiruka exists and is popular, kind of disproves the notion that Dolphin is super successful and that there should only be 1 emulator.

>Dolphin has both DX11 and OpenGL and as I'm sure you know, DX12 now too, co-existing and complimenting one another

I think it's great that Dolphin has both D3D and OpenGL. Who is willing to code in D3D for N64 emulation? This is proof that different circumstances lead to different results.

>Shunyuan wasn't trying to 'steal' anything

He stole source code.

>he was just over-enthusiastic and stepped a little out of line trying to move things forward and you bullied him

Calling him out on his evil actions is not bullying. He stepped way out of line.

>it might help you understand when someone does something technically wrong but with good intentions?

Please explain to me how he had "good intentions", when he did not contribute back to the people he stole code from? Doesn't sound like good intentions to me.

**Comment by purplemarshmallow** [comment]
Just my 2 cents
Here's the list of dolphin contributors https://github.com/dolphin-emu/dolphin/graphs/contributors
If we want to find out why dolphin is so successful we have to start looking here and not blame the people who work on N64 emulation

**Comment by cxd4** [comment]
>we have to start looking here and not blame the people who work on N64 emulation

>Edit: just to make it clear what I want to say is dolphin has way more active developers

Agreed on both points.

And there are very many reasons for that.  Some of them are circumstantial--factors you can't control, like the fact that the generation for the console is just newer.  Conversely, some of them are not.

For example, it does not weigh for Project64's popularity to open-source contributors that it spent the first 95% of its historical longevity under closed-source philosophy (except for the 1.4 sources).  That, however, doesn't excuse accusing, blaming and yelling at people for trying to change that.

The point like you said--blaming everything on one single type of reason or just blaming a set of people for why things aren't as we personally like them is really only going to achieve missing the picture.

**Comment by fallaha56** [comment]
@purplemarshmallow 
i agree

it's wasn't just code, they built a community and people followed -web designers, testers, sponsors, people keen and willing to contribute what they can

however i'm pretty sure that looking down on people like they don't deserve 'in' because they can't compile source or ask for a buildbot will never lead to this

@cxd4 
wise words, i hope you mean them

**Comment by cxd4** [comment]
No really, there is a huge variety of reasons.
I don't think I could even list them all--why Dolphin is more popular than most other emu projects.

And I'm aware that one of them (out of so many) is their techniques at attracting users to their community (blogs, sponsors, special web design, their own wiki, probably some sort of stuff they do to get funding or payment, ... list goes on quite frankly).  Because more users get attracted to the project, the overall popularity increase causes more open-source collaborators to hear about the project; therefore it attracts more programmers.

I'm well aware of all of this.  For that matter, this isn't my project, so none of those things would be my call anyway.  I don't totally like Project64 anymore than I like trying to change it into something that to me is more likeable--it's just out there, and I'm interested in keeping zilmar's decision to open-source to be not a regrettable thing to him.  That's all I can really concentrate on here with this project.

**Comment by project64** [comment]
closing old issue, if this is still an issue it can be reopened
