### ISSUE TITLE
F12 immediately after boot = Unknown Memory Action.

### ISSUE THREAD

**Issue by AmbientMalice** [project64/project64#921]
As it says on the tin, PJ64 doesn't like being halted immediately after booting a game.

**Comment by LegendOfDragoon** [comment]
Are you spamming F12? I can't reproduce w/o spamming that button. Also what audio plugin are you using?

**Comment by AmbientMalice** [comment]
>Are you spamming F12? I can't reproduce w/o spamming that button.

Of course I'm spamming it. What else would someone do when they realise they booted the wrong game and want to go back and choose another one from the rom browser? If you know what I mean.

>Also what audio plugin are you using?

Jabo's. Still waiting for Azimer's issues to be fixed.

**Comment by LegendOfDragoon** [comment]
>Of course I'm spamming it.

I just wanted to make sure I understood the exact problem. I tried doing a workaround, but it wasn't perfect. Azimer's DS8 had issues. I have some idea of what the problem is, but the fact that the older code did not need such workarounds, made me realize I should try a different approach.

One key issue is that sometimes it takes a long time to end emulation, which is why it can crash if you spam F12.

I think the best way to solve this issue is to pinpoint the commit that introduced the issue and work from there.
