### ISSUE TITLE
Crash on USB flash drive

### ISSUE THREAD

**Issue by Lithium64** [project64/project64#948]
Project64 crash if the user tries to run from a USB flash drive
![crash pendrive](https://cloud.githubusercontent.com/assets/10705488/12635110/961a466c-c55e-11e5-8d84-75987f9b34e8.png)

**Comment by vgturtle127** [comment]
@Lithium64 Well, that's a woefully unhelpful exception. :disappointed: 

I mean, I don't even know how to try and fix this.

What flash drive is it?

**Comment by Lithium64** [comment]
@vgturtle127 It isn't a flash drive fault, you could try run from a USB flash drive and see with your own eyes.

**Comment by vgturtle127** [comment]
@Lithium64 Oh, I know. Are you using FAT32?

**Comment by Lithium64** [comment]
@vgturtle127 yes

**Comment by vgturtle127** [comment]
@Lithium64 How did you put the files on the flash drive? Did you just copy the files over from your hard drive?

**Comment by Lithium64** [comment]
@vgturtle127 I just copied the folder to my flash drive

**Comment by vgturtle127** [comment]
@Lithium64 Did you change all the directories and stuff to be relative for your flash drive? That may be an issue.

**Comment by Lithium64** [comment]
@vgturtle127 This crash isn't related to INI files, because I deleted these files from config folder before copy the emulator folder to USB flash drive. The emulator doesn't quite open up, because the error occurs as soon as you try to open.

**Comment by AmbientMalice** [comment]
This error isn't related to flash drives, as far as I can see. It's caused by placing PJ64 one folder level down from a drive root.

C:/PJ64 -- error.

C:/Spatula Wars/PJ64 --fine.

**Comment by death-droid** [comment]
Fixed the issue, will push a pull request shortly.

**Comment by tony971** [comment]
The placement of the configure folder has always confused me. Why not keep it in the main PJ64 directory or the user's documents or appdata folders?

**Comment by project64** [comment]
@tony971  if you install pj64 at the default location then it is in the program files directory, which can not be directly written to and the data should be in the the user's documents or appdata folders as you said. That is the normal behaviour, if you install it elsewhere say "D:\pj64" then it does not need to appdata. 

I also wanted pj64 to be self contained, so if you have multiple versions in different directories changing the settings of one does not effect the other, which was one of the main reason of going to a config file over using the registry.

Now if every copy has the setting just in appdata, data is shared. Having it in it's own dir each copy is separate. But you can not write to files inside program files dir ... Well actually you can if you change the permission of the dir. So when it is installed it changes the permision of the config folder so it is writable and does not get redirected elsewhere. Which is why config moved out of the root in to a directory so I could change the permission of just the dir, not of whole root folder.

does that make more sense?

**Comment by Lithium64** [comment]
The crash was fixed

**Comment by AmbientMalice** [comment]
@project64 I was wondering -- why not take a PCSX2-esque approach? If there is a file marked portable.ini in the PJ64 directory, store all modified files in the relevant directories. But if it is missing, store the files in Documents/Project64. That way people who upgrade regularly could keep their settings, saves, etc intact with less fuss.

**Comment by vgturtle127** [comment]
@AmbientMalice I really like that idea.

I think we should stop using the registry as well, but maybe everybody is OK with that?

**Comment by project64** [comment]
well it basically always acts as portable, it has not used the registry since 1.6.

I do not see any advantage of storing files in the my documents/app data dir?

**Comment by AmbientMalice** [comment]
>I do not see any advantage of storing files in the my documents/app data dir?

It means you could easily use a single set of save files for multiple versions. Or you could stick all your roms in Documents/PJ64/Roms, and every time you upgrade PJ64, the emulator would pick them up automatically. Personally, Documents is a lot better than AppData because it's easier for people to find.

**Comment by Lithium64** [comment]
@project64 I fully agree

**Comment by Lithium64** [comment]
Portable is always better

**Comment by vgturtle127** [comment]
@AmbientMalice AppData requires admin privileges, right? I don't think the Documents folder does.

**Comment by oddMLan** [comment]
No, it doesn't

**Comment by vgturtle127** [comment]
@oddMLan You mean the documents folder?
