### ISSUE TITLE
Unexpected Transfer Pak error dialog

### ISSUE THREAD

**Issue by JunielKatarn** [project64/project64#980]
There is an issue seemingly related to transfer pack since a few builds ago.
See #965 

![image](https://cloud.githubusercontent.com/assets/4507319/12844664/b451e380-cbb5-11e5-9e6e-d1bd4e01569f.png)

Steps to reproduce:
- Build Project64 at 2ec7a92dfc09d3dae41b86321f06bbd674fd105f (compiled binaries at  http://hyvart.com/download/project64/ci/0.0.0.409/Win32.zip).
- Start any ROM (i.e. Lem's crap test).

**Comment by death-droid** [comment]
Ahhhh, this is being caused due to the code currently initializing the mempak and transferpak at startup of a game regardless of whether a transferpak or mempak has been chosen to be loaded.
Meant to correct it, but had to branch from latest master to deal with it. 

Should be a relatively easy fix, just have to check what paks have been chosen at system startup. That or just remove the error box, but thats just being lazy.
